### ISSUE TITLE
Determine if ceterms:qualityAssuranceTargetType is sufficient and/or if a new class is needed (e.g. ceterms:TargetType)

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#314]
Determine if ceterms:qualityAssuranceTargetType is sufficient and/or if a new class (e.g. ceterms:TargetType) should be created.

Also see related QA Issues:
 #312 concerning whether or not Endorsement needs to be broken out of Recognition.
#315 Add Organization to the range of development, maintenance, and administration process properties, and create new process properties

Quality assurance organizations need to be able to identify the following:

- Types of quality assurance issued
- The quality assurance services provided
- Types of organizations to which they issue quality assurance
- Specific Programs to which they issue quality assurance
- Specific Assessments to which they issue quality assurance
- Specific Credentials  to which they issue quality assurance
- Frequency  of the quality assurance credential renewal cycle
- Jurisdiction where they can issue the quality assurance
- The scope of the quality assurance issued (e.g. ABET only accredits Engineering programs)

**_- Types of quality assurance issued_**:

**_- The quality assurance services provided_**:
http://credreg.net/ctdl/terms#AgentServiceType

serviceType:AccreditService
serviceType:ApproveService
serviceType:OfferService
serviceType:RecognizeService
serviceType:RegulateService
serviceType:RenewService
serviceType:RevokeService

**_- Types of organizations to which they issue quality assurance:_**
http://credreg.net/ctdl/terms#OrganizationType
http://credreg.net/ctdl/terms#AgentSector

ceterms:qualityAssuranceTargetType http://credreg.net/ctdl/terms#qualityAssuranceTargetType

orgType:AssessmentBody
orgType:Business
orgType:BusinessAssociation
orgType:CertificationBody
orgType:FourYear
orgType:Government
orgType:HighSchool
orgType:LaborUnion
orgType:Magnet
orgType:Military
orgType:NonTraditional
orgType:Postsecondary
orgType:PrimarilyOnline
orgType:ProfessionalAssociation
orgType:QualityAssurance
orgType:SecondarySchool
orgType:Technical
orgType:TrainingProvider
orgType:TwoYear
orgType:Vendor

ceterms:AgentSector
http://credreg.net/ctdl/terms#AgentSector

agentSector:PrivateForProfit
agentSector:PrivateNonProfit
agentSector:Public

- **_Types of credentials to which they issue quality assurance:_**
ceterms:ApprenticeshipCertificate
ceterms:AssociateDegree
ceterms:BachelorDegree
ceterms:Badge
ceterms:Certificate
ceterms:Certification
ceterms:Credential
ceterms:Degree
ceterms:DigitalBadge
ceterms:Diploma
ceterms:DoctoralDegree
ceterms:GeneralEducationDevelopment
ceterms:JourneymanCertificate
ceterms:License
ceterms:MasterCertificate
ceterms:MasterDegree
ceterms:MicroCredential
ceterms:OpenBadge
ceterms:ProfessionalDoctorate
ceterms:QualityAssuranceCredential
ceterms:ResearchDoctorate
ceterms:SecondarySchoolDiploma

- **_Specific Programs_**
http://credreg.net/ctdl/terms#LearningOpportunityProfile

**Specific Assessments**
http://credreg.net/ctdl/terms#AssessmentProfile

**Specific Credentials**
http://credreg.net/ctdl/terms#Credential

**_- Frequency  of the quality assurance credential renewal cycle_**
ceterms:estimatedDuration
http://credreg.net/ctdl/terms#estimatedDuration

**_Jurisidiction where they can issue the quality assurance_**

ceterms:JurisdictionProfile
http://credreg.net/ctdl/terms#JurisdictionProfile

**Comment by stuartasutton** [comment]
Do you mean add organization classes? Aren't they already there in pending? Am I missing something?

**Comment by siuc-nate** [comment]
No, I mean the terms within the Organization Type concept scheme: http://credreg.net/ctdl/pending#OrganizationType

We want to enable a QA org to say that it does QA on specific types of organizations.

**Comment by stuartasutton** [comment]
OK, then my sense is that we need to push this out to the next release so we have time to look at it seriously. We made a decision some time ago that the current range of the credential subtypes was how we were handling this. Also, the additional range would be CredentialAlignmentObject. Can we hold on this for the next release?

**Comment by siuc-nate** [comment]
The proposed action:

Add each concept from the OrganizationType concept scheme to the range of ceterms:qualityAssuranceTargetType:

orgType:AssessmentBody
orgType:Business
orgType:BusinessAssociation
orgType:CertificationBody
orgType:FourYear
orgType:Government
orgType:HighSchool
orgType:LaborUnion
orgType:Magnet
orgType:Military
orgType:NonTraditional
orgType:Postsecondary
orgType:PrimarilyOnline
orgType:ProfessionalAssociation
orgType:QualityAssurance
orgType:SecondarySchool
orgType:Technical
orgType:TrainingProvider
orgType:TwoYear
orgType:Vendor

**Comment by siuc-nate** [comment]
Since it seems like it would be easier to discuss/explain this with some visuals, I created a rough diagram based on the (edited) post at the top of this issue:
![image](https://cloud.githubusercontent.com/assets/21346519/23437555/2bdc9f02-fdd4-11e6-8c26-3bfef2b8c9bd.png)

Some things to note:
- TargetType would contain some basic properties to assist in describing itself (namely subjectWebpage)
- It would include some reference to the specific QA credential associated with that type of target (I used "instrument" here, although the definition of instrument constrains it to actions, so it may not be entirely appropriate)
- It also contains jurisdiction and duration properties to express the jurisdiction for which that target type applies (maybe not necessary) and the duration (or frequency) of the associated instrument(al) credential for the target type(s) referenced by the profile
- There is an important distinction between _types_ of targets and _specific_ targets - specific targets being instances of things.  I am concerned that it is mixing apples and oranges to create a profile whose explicit name and purpose is to indicate _types_ of targets only to then include references to _specific_ targets - perhaps those properties belong elsewhere?
- This diagram imagines a reworking of qualityAssuranceTargetType (or some equivalent property) to have a range of CredentialAlignmentObject that can then reference other classes as though they were a vocabulary. qualityAssuranceTargetType as currently spec'd has a range that technically points to _instances_ of those classes.
- Pointing to Competency and CompetencyFramework twice is intentional; on the left, they are used as a vocabulary (e.g., "we accredit competencies"), whereas on the right, they are instances (e.g., "we accredit _this_ competency").
- Note the distinction between pointing to Assessment and LearningOpportunity (as in, the generic classes) on the left (as a vocabulary) and pointing to _instances_ of those things as described by their respective ____Profiles on the right.  We would want to convey "we accredit assessments", not "we accredit assessment profiles"

There would be a fair bit of machining involved in creating TargetType and its associated properties, but I think it's a lot cleaner than trying to overinflate the pseudo-vocabulary we are using with qualityAssuranceTargetType (while also enabling information to be grouped together - e.g., "we accredit diplomas with x credential" and "we endorse competencies with y credential" - something that wouldn't be possible with a single vocabulary).

Note also that the diagram and related points above are in no way intended to be final; they are meant to aid further discussion.

**Comment by stuartasutton** [comment]
First, this is a **very big change**. 

For this to make any sense to me, Nate, I need to see a slightly larger picture of this `TargetType` class. For example, what properties have it as range? I am assuming these properties have a domain of `QACredentialType`. Can you just answer these specific questions first? I have more to say about the rest but want to get this clear first.

Stuart

**Comment by siuc-nate** [comment]
Currently yes, this would be an alternative to combining (nearly) everything in this thread's first post into a single vocabulary for qualityAssuranceTargetType.  qualityAssuranceTargetType would instead point to a TargetType profile, which would in turn contain the various information in a more useful, structured way.

**Comment by stuartasutton** [comment]
I'd like to discuss an alternate path to creating a `TargetType` entity.  All these issues pertain to `QACredentialOrganization`. This whole issue is sourced in the fact that the `QACredentialType` class currently has a single property --`qualityAssuranceTargetType`-- unique to the class that references what is now seen as a bucket of different things. You list the things in that bucket:
1. Types of quality assurance issued (??)
2. The quality assurance services provided (`AgentServiceType`)
3. Types of organizations to which they issue quality assurance (`AgentServiceType` `AgentSector`)
4. Specific Programs to which they issue quality assurance (`LearningOpportunity` `LearningOpportunityProfile`)
5. Specific Assessments to which they issue quality assurance (`Assessment` `AssessmentProfile`)
6. Specific Credentials to which they issue quality assurance (`Credential` subclass or specific credential)
7. Frequency of the quality assurance credential renewal cycle (`DurationProfile`)
8. Jurisdiction where they can issue the quality assurance (`JurisdictionProfile`)

> **INSTEAD, consider additional properties for the QACredentialOrganization entity to cover the above notions instead of a new TargetType entity.**

Nate, the CredentialAlignmentObject should not be used the way you are using it here. With the exception of `AgentServiceType`, `OrganizationType`, and `AgentSector`, none of the things referenced on the left of the diagram are "frameworks". The 6 entities on the bottom left are simply things that can be refernced directly by URL just like the things on the right. 

So, I mean properties such as the following with domain of `QACredentialOrganization` and declared as subproperties of the existing `qualityAssuranceTargetType` [Numbering aligns with the numbers above]:

(1) `???`
(2) `assuranceService`
(3)(a) `assuredOrganizationType`
(3)(b) `assuredSectorType`
(4)(a) `assuredLearningOpportunity`
(4)(b) `assuredLearningOpportunityType`
(5)(a) `assuredAssessment` 
(5)(b) `assuredAssessmentType` 
(6)(a) `assuredCredential`
(6)(b) `assuredCredentialType`
(7) `assuranceRenewalCycle`
(8) `assuranceJurisdiction`

Also, we need to discuss this even further because, at core, the distinction between class and instance of class does not hold up very well in our context. When was the last time we saw a credential that simply required something of the class `LearningOportunity` (any old learning opportunity) or a `Competency` (any old competency or competency framework) will suffice. I've seen none.

We need to talk more...and see some actual example data that makes simply creating appropriate subproperties (such as above) for use with `QACredentialOrganization` the wrong solution.

**Comment by siuc-nate** [comment]
An alternative idea would be a new vocabulary class with some of the other classes as its concepts.  Something like:

URI: ceterms:QualityAssuranceTarget
Label: Quality Assurance Target
Definition: Types of resources that receive quality assurance from some agent.
Terms:
- ceterms:CredentialOrganization
- ceterms:QACredentialOrganization
- ceterms:Credential (and its subclasses)
- ceterms:Assessment
- ceterms:LearningOpportunity
- ceterms:Competency
- ceterms:CompetencyFramework

**Comment by stuartasutton** [comment]
In the end, I am not particularly fond of this. First, you wouldn't have a skos vocabulary with these terms using their `ceterms` namespace prefix. We'd be re-declaring a new vocabulary namespace. So why do that? I still prefer the specificity of a small set of specific properties identifying target classes as noted above .

**Comment by siuc-nate** [comment]
What would that look like in practice though? So far all of the properties we've come up with have been used to point at instances of classes rather than at the classes themselves.  Would it be something like:

```
{
   "ceterms:assuredAssessmentType": { "@id": "ceterms:AssessmentProfile" },
   "ceterms:assuredCredentialType": [
      { "@id": "ceterms:Certificate" },
      { "@id": "ceterms:Certification" }
   ]
}
```

**Comment by siuc-nate** [comment]
Some additional suggestions:

1. Rather than create a TargetType profile, just use a CredentialAlignmentObject (which is what the TargetType profile diagrammed above ultimately uses anyway):
![image](https://cloud.githubusercontent.com/assets/21346519/23761617/11514a5c-04b9-11e7-8710-677384fb643a.png)

Or

2. Extend the range of accredits, regulates, approves, recognizes, endorses, etc. properties to include CredentialAlignmentObject, and use it like this:
![image](https://cloud.githubusercontent.com/assets/21346519/23761677/2d8dd8fc-04b9-11e7-8937-e79d6187a304.png)

Or

3. Extend the range of accredits, regulates, approves, recognizes, endorses, etc. properties to include rdfs:Class, and use it like this:
![image](https://cloud.githubusercontent.com/assets/21346519/23761776/8d281476-04b9-11e7-941d-209b59652ac1.png)

**Comment by stuartasutton** [comment]
Nate, your additional suggestions 1 and 2 are not viable because `CredentialAlignmentObject` **cannot** be used in this manner to reference *general classes*. Our definition states:
> An alignment to a credentialing framework.

With the comment:
> Used to describe the alignment of a resource in the credentialing environment to frameworks such as concept schemes, specialized controlled lists, and competencies.

So `CredentialAlignmentObject` is constrained to values from *credentialing frameworks*--`ceterms:Certificate` is not a member of any framework we have defined. 

Suggestion number 3 serves no purpose since `accredits`, `regulates`, `approves` etc. already have defined ranges that *are* classes.

**But, that said, I am struggling to keep in focus some purpose, some use case we are trying to solve here.** In rereading this thread, I see none explicitly stated. 

**IS THE PURPOSE:**

> A QA target can sometime be a class of resource and sometimes it is an instance of such a class. We need a way to succinctly differentiate between these two cases.

Is that it? If so, we already have `qualityAssuranceTargetType` defined as:

> The class of resource that the agent accredits, endorses, approves, or recognizes.

This handles where the target is a class as opposed to an instance of that class. To handle the latter, we could simply create a new property `qualityAssuranceTarget` defined as:

> An instance of a class of resource that the agent accredits, endorses, approves, or recognizes.

I may be missing the point; but if I am, it stems from lack of clarity around what exact problem we are trying to address.

**Comment by stuartasutton** [comment]
OK, @siuc-nate , I've lost the original goal here. And when I read this issue top to bottom, I see we never explicitly set out the problem (use case(s)) to be solved. Is the problem that in identifying the target of the QA that sometimes it is a class and sometimes it is an instance of a class?  If we look at `ceterms:qualityAssuranceTargetType` we see that it covers the class:

>The class of resource that the agent accredits, endorses, approves, or recognizes.

So, if that's the problem, then

**Comment by siuc-nate** [comment]
We're trying to determine exactly what the range of qualityAssuranceTargetType should be, and in doing so, found the solution to be rather difficult and cumbersome, hence exploring alternatives.  

Anyway I think part of the confusion stems from trying to explain that the range of the property is a _class_ of object rather than an _instance_ of that object since throughout CTDL we reference _instances_ via their respective classes.  The range of qualityAssuranceTargetType may include ceterms:Credential, but if we are consistent with everything else in CTDL, that means that the range of qualityAssuranceTargetType is actually an _instance_ of a generically defined Credential.

In other words:
URI: ceterms:qualityAssuranceTargetType
Range: ceterms:Credential, ceterms:AssessmentProfile, etc

would be interpreted for publishing purposes to cover this situation:
```
{
   "ceterms:qualityAssuranceTargetType": [
      { "@id": "urn:ctid:someUUID" },
      { "@id": "http://credentialregistry.org/resource/someAssessmentGUID" }
   ]
}
```

But that is not the situation we are trying to cover.  We want to cover:
```
{
   "ceterms:qualityAssuranceTargetType": [
      { "@id": "ceterms:Credential" },
      { "@id": "ceterms:Assessment" }
   ]
}
```

So that would appear to imply that the range of ceterms:qualityAssuranceTargetType must be extended to include rdfs:Class, since ceterms:Credential and ceterms:Assessment are instances of rdfs:Class and the way we use range is to point to instances of the classes listed in the range.

Otherwise, are we indicating that anything in CTDL that has a range of a class can point to that class rather than an instance of that class?  I understand that "class of resource" is in the definition, but a computer doesn't understand or care about that.  A computer can interpret the range, but how would we tell the computer that "the range for everything in CTDL is an instance of the indicated class, except for qualityAssuranceTargetType, where the range is actually just the indicated class and not an instance"?

I hope that I'm making sense.

**Comment by siuc-nate** [comment]
Per our 3/14/2017 discussion:
- Regarding qualityAssuranceTargetType, we will need to determine whether or not range is the correct way to convey that it points of classes of objects rather than instances
- We should move forward with constructing properties along the lines of 2, 3a, and 3b in the list Stuart provided above (something like these):
1. assuredServiceProviderType
2. assuredAgentType
3. assuredSectorType

**Comment by siuc-nate** [comment]
It came up in some of our internal meetings that we still need to be able to group QA target information together - e.g., an organization might accredit bachelor's degrees and it might endorse organizations.  These might be applicable to certain regions, or perhaps different credentials are awarded to different targets, or there might be other reasons to group such information together.  This would necessitate a Target Type Profile.

I have constructed a graph to attempt to show our current QA system and its related entities/properties, along with how Target Type Profile would play into it.  In addition, I have added several suggestions in orange to cover what I think are holes we haven't brought up yet - these aren't formal proposals, but I do think we need to discuss them.

In constructing this, I think I may have a solution for the problem we discussed on Tuesday - namely "how do we point to a class rather than an instance of a class".  I think that if we use a range of xsd:anyURI rather than a non-range attribute or a range of rdfs:Class or whatever, that we can accommodate the need to point to a class without having to have a bunch of special workarounds. I'm _relatively_ sure that this would be sufficient.  The data might look something like:

```
{
   "ceterms:targetClass":
   [
      { "@id": "http://purl.org/ctdl/terms/CredentialOrganization" }
   ]
}
```
Though since JSON-LD is supposed to expand to full URLs anyway, it _might_ be acceptable to still use ceterms:CredentialOrganization instead of a full URL in the above example; I'm not sure. It would certainly be a test of the "any" in "anyURI".

Anyway, below is the graph itself:
![image](https://cloud.githubusercontent.com/assets/21346519/24014351/989a4c40-0a52-11e7-85d1-67aa028bbf29.png)

Some things to note: 
- I do not think we should include instances at all within Target Type Profile, as it runs counter to the point of such a profile. It should _only_ point at classes and vocabulary terms.
- I do think we need such a profile, for the reasons outlined above.
- The "targetClass" property in the diagram would have a range of xsd:anyURI as outlined above
- The "isInstanceOfClass" property is perhaps not necessary; it is something we should probably discuss
- The "hasCredentialClaim" property I am not sure of; but it feels like a gap in CTDL
- I deliberately included the serviceType of "AccreditService", the "accredits"/"accreditedBy" properties, and an "AccreditAction" class to illustrate the three "levels" of interaction that an organization can define between itself and other entities
- We can recycle a number of properties within Target Type Profile because their definitions can be read more than one way (the only possible exception to this would be the definition of agentType, but that may be splitting semantic hairs)
- This would negate the need for the new properties in the above post

**Comment by stuartasutton** [comment]
We need to discuss this in a call. Because of the level of complexity of such a `TargetTypeProfile`-a level of complexity well beyond that of ConditionProfile which is already very difficult to explain to people who will be trying to make sense of it, it feels a bit like jumping the shark or a push toward development of a full-blown ontology that we've been advised to not do. Let's talk.

**Comment by siuc-nate** [comment]
So, as it stands currently, I believe the current proposal is:

1. Create ceterms:TargetTypeProfile
URI: ceterms:TargetTypeProfile
Label: Target Type Profile
Definition: A profile that describes the types or classes of resources that are targeted for some purpose or action by some agent or entity.
Properties:
- ceterms:description
- ceterms:instrument
- ceterms:agentType
- ceterms:agentSectorType
- ceterms:serviceType
- ceterms:targetClass

2. Create ceterms:targetClass
URI: ceterms:targetClass
Label: Target Class
Definition: The class of resource that is targeted by the resource being described.
Comment: The target of this property is the indicated class (or a subclass thereof) itself, rather than any specific instance of that class.
Domain: ceterms:TargetTypeProfile
Range: xsd:anyURI

3. Update the range of ceterms:qualityAssuranceTargetType to _only_ point to ceterms:TargetTypeProfile

Notes:
- The definition of TargeTypeProfile probably needs some work
- We may also need an inverse property for qualityAssuranceTargetType (such a property would point to the "some agent or entity" mentioned in the definition), such as:
   - ceterms:targetedBy
   - ceterms:targetOf
   - ceterms:qualityAssuranceAgent
   - ceterms:targetProfileOf
   - etc.

**However:**
Per our 3/21/2017 conversation, we need to review the Quality Assurance documentation to ensure that the proposal above will meet all of the goals that originally led to the initial creation of ceterms:qualityAssuranceTargetType.

**Comment by siuc-nate** [comment]
Per our 4/7/2017 call:

1. Create ceterms:TargetTypeProfile
**URI:** ceterms:TargetTypeProfile
**Label:** Target Type Profile
**Definition:** A profile that describes the types of resources that are targeted for some purpose or action by an agent.
**Properties:**
   - ceterms:description
   - ceterms:agentType
   - ceterms:agentSectorType
   - ceterms:serviceType
   - ceterms:targetClass

---
2. Create ceterms:targetClass
**URI:** ceterms:targetClass
**Label:** Target Class
**Definition:** The class of resource that is targeted by the resource being described.
**Comment:** The target of this property is the indicated class itself, rather than any specific instance of that class.
**Domain:** ceterms:TargetTypeProfile
**Range:** xsd:anyURI

---
3. Update the range of ceterms:qualityAssuranceTargetType to _only_ point to ceterms:TargetTypeProfile

**Comment by stuartasutton** [comment]
While I **do not want to reopen this issue**, I do want to make sure that we understand one thread of this conversation--when the range is an instance of some class (e.g., Bachelor degree from Trump U) and when the range is the class itself. In fact there is _no difference_ and we need to get that straight in our thinking. So, assume the following:

Org==accredits==>TrumpUBachelorDegree
Org==accredits==>BachelorDegree

The first references a specific member of the credentials defining the class and the second references all member credentials defining the class (i.e. no specific member). BOTH are defined by class membership.

**Comment by siuc-nate** [comment]
Recommend we mark this property unstable until we can resolve this, as it will likely involve a definition change.

@stuartasutton @jkitchensSIUC  please reply.

**Comment by siuc-nate** [comment]
Related/recent issue: Higher Learning Commission only does accreditation on other organizations, but a number of credentials have been published that claim to be accredited by HLC.

**Comment by stuartasutton** [comment]
@siuc-nate, this seems to me to be an analytic problem on the part of the credential holders making the assertion...i.e., hanging an accreditedBy off the wrong entity.

**Comment by siuc-nate** [comment]
The goal there would be to allow HLC to say "we only accredit organizations" - this would allow a system that understands CTDL (such as the Publisher) to display a warning or an error when a user tries to publish data that says "my credential is accredited by HLC".  

It would also enable consumers of the data to spot such inconsistencies if that kind of erroneous credential data were published (or found on the web).

**Comment by siuc-nate** [comment]
Considering we already have https://credreg.net/ctdl/terms/qualityAssuranceTargetType, and considering that this issue has lingered for so long without any apparent need to move forward with it, does it make sense to consider this problem as solved?

**Comment by stuartasutton** [comment]
Close it.
