### ISSUE TITLE
Explore Concept Scheme for QA Statuses for Describing the Status of QA Issues, or Not Issued 

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#328]
This Google sheet was used for tracking QA related properties https://docs.google.com/document/d/13td5-K4uYrfInkX2mpxeO-XpN9mFIraoe8NSciv7f58/edit?usp=sharing

Quality assurance organizations,such as accreditors, use statuses to identify if accreditation is current or other statuses.  The Higher Learning Commission provides a good example of statuses found via their online Directory of HLC Institutions.  Below is a listing of the statuses they use and their definitions.

The editor is using two properties that aren't included with CTDL for the purpose of determining if there is a need for a concept scheme.

These are examples of status directly from HLC https://www.hlcommission.org/Directory-of-HLC-Institutions.html 

- Accredited
- Accredited (Probation)
- Inactive-Withdrawn
- Inactive-Resigned
- Inactive-Merged

The statuses used by quality assurance organizations are being compiled via the CTDL editor and/or Google Sheet.  We'll provide the QA advisory the list of statuses and definitions for concept feedback. Look at three test cases:  ANSI, WASC and State of Indiana Higher Ed. 

Statuses are to be tracked here https://docs.google.com/spreadsheets/d/1PrOciCFx4iiuQ7iOqqEHYMdlsn09f5V9mTIxtZhDMwo/edit?usp=sharing

**Comment by siuc-nate** [comment]
We would need to work this into the http://credreg.net/ctdl/terms/CredentialStatus vocabulary. @jkitchensSIUC @stuartasutton any thoughts?

**Comment by siuc-nate** [comment]
There has not been any action on this since 2017.

I think this issue should be closed.

**Comment by jeannekitchens** [comment]
When this ever surfaces as a need, we'll re-open this issue.

**Comment by jeannekitchens** [comment]
This issue is re-opened due to the Equity Council tier 1 use case for QA organizations to provide accreditation status.  This means a status issued to an organization, credential, or learning program.

**Comment by siuc-nate** [comment]
This would be covered by the properties of https://credreg.net/ctdl/terms/AccreditAction
