### ISSUE TITLE
Proposal to support rubrics

### ISSUE THREAD

**Issue by jeff-grann** [CredentialEngine/Schema-Development#530]
There are some usecases in which consumers of credentials would benefit from reviewing additional assessment-related information, such as rubrics.

**Comment by stuartasutton** [comment]
Jeff, rubrics will ultimately be a specification in the CTDL family of specifications. Like competency frameworks and concept schemes, rubrics will be a separate specifications.

**Comment by jkitchensSIUC** [comment]
@jeff-grann @stuartasutton 

The learning opportunity profile http://credreg.net/ctdl/terms#LearningOpportunityProfile includes a property, target learning resource http://credreg.net/ctdl/terms#targetLearningResource

@stuartasutton we might want to add that property to Assessment Profile http://credreg.net/ctdl/terms#AssessmentProfile

I see two completely different aspects here:
1. referring to a rubric as a learning resources.  This should already be covered http://credreg.net/ctdl/terms#LearningResource.  Also see: http://schema.org/CreativeWork and lrmi.dublincore.org/specifications/
2.  Describing the structure of a rubric.  As Stuart noted, this would likely be a new specification just as CTDL ASN is a specification.  

If Credential Engine had an interest in developing a new schema, it would need to start with some viable use cases that intersect with the family of specifications and and modeling that would need to be vetted with stakeholder input. We have multiple classes at this time that have a been vetted and are prioritized as next in line for development.

We can keep this issue open and see what appetite there is to add to the development list.

**Comment by stuartasutton** [comment]
I agree that rubrics may be associated with competency frameworks, perhaps even frequently; but, as a modeling issue, they are not part of, or integrated into competencies or competency frameworks. Rather rubrics are **referenced** by such competencies and frameworks and expressed (by us) as first class RDF resources on the web. For example, courses in semantic metadata might reference the DCMI [Competency Index for Linked Data](http://asn.desire2learn.com/resources/D2695955), but 1-n faculty teaching various course instances in the subject could very likely use 1-n different rubrics. I.e, it's dangerous to hard-wire rubrics directly into frameworks.

**Comment by ottonomy** [comment]
I modeled how a rubric relates to a BadgeClass whose assessment uses it for the recent revision of the Open Badges Assessment Extension. I don't think IMS has yet published the final version, but the merged PR is here: https://github.com/IMSGlobal/openbadges-specification/pull/175

We modeled the relationships like:
A Competency (mastery of it) is a learning objective. A BadgeClass (Credential) that aligns to that competency represents a specific issuer's definition of learning content and assessment that indicate a level of achievement of the competency.

Anyway, I'm happy to provide use cases for how people wanted to use this data in BadgeClasses. We are running it in production right now for a system that allows people to apply for competency badges that are assessed based on rubrics.

**Comment by jkitchensSIUC** [comment]
@jeff-grann @stuartasutton @ottonomy I think for CTDL, the question is whether or not there is interest in a Rubric class. This would entail determining the properties needed to describe rubrics similarly to how we're scoping the pathways class.

**Comment by jeff-grann** [comment]
A Rubric class makes sense to me. Here's an [example](https://www.aacu.org/value-rubrics) of several important rubrics being shared as pdf documents. These could be more easily consumed by assessment tools and referenced by competencies if they were supported.

**Comment by siuc-nate** [comment]
Reference: http://openaccess.uoc.edu/webapps/o2/bitstream/10609/5222/6/Panulla.pdf

**Comment by siuc-nate** [comment]
Per our 4-9-2019 meeting:
ASN has finalized their rubric specification.
http://s3.amazonaws.com/jestaticd2l/purl/schema/standard (ctrl-f "rubric")

We need to review it.

**Comment by siuc-nate** [comment]
Per our 4-30-2019 meeting:
This is suitable for adoption as-is until such time as there is a need to add specific properties.

**Comment by stuartasutton** [comment]
Jeanne, can't the ASN properties/classes be used directly and included in
our documentation without creating a CE namespace. That can be done it we
end up wanting to have terms not included in the ASN schema...but should
first ask them if they would add such properties/classes before creating a
CE namespace.

**Comment by siuc-nate** [comment]
We could also use the properties as-is (in theory) without recreating them, as we did with schema:name and so on.

**Comment by stuartasutton** [comment]
I would think it would depend on the level of in-house documentation we end up needing.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @cwd-mparsons @siuc-nate if we use ASN terms directly how would we communicate this via the tech site and let's develop a list of everything that would need to exist (e.g., API update to publish rubrics, minimum data policy)...

**Comment by siuc-nate** [comment]
If we use the existing terms directly, we'd do it the same way we added the SKOS terms to the CTDL-ASN schema - by adding them to the schema management system and retaining the original URIs and prefixes, while tweaking the domains, ranges, descriptions, etc. to make sense for our schema while retaining the semantic intent/meaning of the properties.

The first step in doing so would be to get the XML rubric schema into something a little more user-friendly so we can make whatever adjustments we need to make.  I can probably write a bit of code to render it out into something we can put into a spreadsheet.

**Comment by stuartasutton** [comment]
I most likely have the encoding...you mean in JSON-LD?

**Comment by stuartasutton** [comment]
The documentation for the ASN Rubric can be found at http://standards.asn.desire2learn.com/rubric.html.

**Comment by siuc-nate** [comment]
The schema management system already supports capturing terms from other/multiple namespaces, so all we would need to do is borrow the existing ASN terms.

**Comment by jeannekitchens** [comment]
@mparsons-ce had added this to the publishing API long ago.  We cannot just have some type of note saying we're using CTDL ASN.  We need to include with CTDL not CTDL ASN and include equivalents per our namespace policy.  We also need to go through the terms and only use what we need.

**Comment by stuartasutton** [comment]
@jeannekitchens, the ASN Rubric spec is already slim. You will not find any properties that are extraneous to gluing a rubric together.

**Comment by philbarker** [comment]
@philbarker to map http://standards.asn.desire2learn.com/rubric.html to CTDL/CTDL-ASN

**Comment by philbarker** [comment]
(Graphical) notes on mapping are here: https://app.diagrams.net/#G1Wm0nLqm_Ny5sbxv8Db_FR58E3q-44MAs

**Comment by jeannekitchens** [comment]
This issue is replaced by #892
