### ISSUE TITLE
Create a way to define organizations that do not play a role in the life cycle of a credential

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#556]
This would be used for organizations that publish, for instance, competency frameworks - but which do not (primarily) have anything to do with owning/creating/managing credentials or with quality assurance.

Examples:
- Organizations (such as employers) which are primarily concerned (in our context) with job descriptions/profiles and job openings
  - Job Data Exchange will publish competency frameworks in the context of job descriptions, profiles, and openings - not in the context of a credentialing organization that offers or owns a credential.
- Organizations that publish and maintain competency frameworks that are not directly related to a credential
  - DQP
  - South African Qualifications Authority (this is likely a QA Organization)
  - Organizations that develop frameworks intended to be used with credentials without targeting any specific credential by assessing the attributes of a credential, the quality of a credential, or benchmark a credential

We will need to do so in a way that avoids a situation where an organization may be described by multiple classes, but must pick one.

Some initial proposals:
- Modify the existing ceterms:Agent class:
  - Adjust the comment to cover more types of organizations
  - Add ceterms:Agent to the domain of all of the properties of ceterms:CredentialOrganization (and possibly ceterms:QACredentialOrganization)

or:
- Create a new generic "Organization" class:
  - Something along the lines of ceterms:Organization
  - Equivalent to schema:Organization
  - Would be a superclass of ceterms:CredentialOrganization and ceterms:QACredentialOrganization
  - Would be a subclass(?) of ceterms:Agent

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate @cwd-mparsons is this handled via the employment and earnings terms?  Do we need to address this?

**Comment by siuc-nate** [comment]
I think the notion of trying to solve this via class, which limits us to one type of organization per entity is going about it the wrong way.

I think, really, we should have a single organization class with some property that is multi-value and allows for selecting **as many as apply** from:
- Credential publisher
- Quality Assurance provider
- Competency Framework publisher
- Statistics data provider (e.g. EETG organizations that provide data about credentials but may or may not serve one of the other functions
- Any other types of interactions we come up with in the future

In other words, have a single organization class with some concept scheme that touches on those areas and allows room for future expansion.  The key part here is the multi-select nature: Rather than inventing an organization class for every possible combination of the above items and/or trying to define classes based on what they **aren't**, just have one class with a multi select vocabulary that allows picking one, two, or all of them.  This provides a more accurate description of the organization in question.

Since we already have our existing organization classes, we're kind of stuck with them, but going forward I think this option gives us the best flexibility with the least chance of coming back to bite us.  I'm open to pushback.

**Comment by siuc-nate** [comment]
Depending on how we define and intend to use such a property, it might even be possible to use the existing Organization Type vocabulary.

**Comment by stuartasutton** [comment]
Nate, I am all for creating a Organization as a superclass for both CredentialOrganization and QACredentialOrganization. But, I'm not for using Organization with a type property that states the actual type...I didn't like it semantically with Credential and I don't like it semantically with Organization. The types of Organization within the domain of Credentials is not large, let alone infinite. We've already instantiated two--CredentialOrganization and QAOrganization. We could consolidate 2nd parties defined as agents that provide resources (data, competency frameworks, concept schemes) as a third class.  The only other category I can think of is one we've discussed repeatedly, agents that provide "soft" quality assurance like employers (hire, recommend). We've not settled on whether this last class is even worthy of inclusion as registered organizations of a type or whether a credential pointing to such agents (or specifically to where such recommendations are stated) is not sufficient. 

This is not a huge intractable problem.

**Comment by siuc-nate** [comment]
the problem with that approach would be how to classify organizations that provide, for instance, both credentials _and_ competency frameworks.

**Comment by siuc-nate** [comment]
In theory, yes, but all of the existing data, code, documentation, presentations, etc. - basically all the work we've done - expects `@type` to be a single value.  Changing all of that would not be trivial, to say nothing of the impact on other publishing/consuming systems.

**Comment by stuartasutton** [comment]
OK, but I want to clearly separate the impossible (bad modeling) from what we might at this point consider the impractical.

**Comment by siuc-nate** [comment]
Since this has come up again, my leaning is to simply create a ceterms:Organization class and use it for anything that doesn't cleanly fall into the buckets of either ceterms:CredentialOrganization or ceterms:QACredentialOrganization.  Agent covers humans as well, so the full hierarchy would look like:

- Agent
  - Person
  - Organization
    - CredentialOrganization
    - QACredentialOrganization

If we had it all to do over again, I would suggest having **only** the Organization class (as this fits much more nicely into the way we document, present, talk about, etc. everything) and using other properties (like organizationType) to indicate when an organization does QA, but it's a little too late for that.

**Comment by jeannekitchens** [comment]
This was handled with issue #765
