### ISSUE TITLE
Harmonize the keyword/subject properties across CTDL and CTDLASN

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#558]
Currently in CTDL we have:
- ceterms:subject
- ceterms:keyword

In CTDLASN, we have:
- ceasn:localSubject
- ceasn:conceptTerm
- ceasn:conceptKeyword

It is somewhat confusing to have related/overlapping notions in the two different schemas.

**Comment by siuc-nate** [comment]
Per our 1/15/2019 meeting:
- This requires discussion, and has been moved to the next release instead of the February release.

**Comment by stuartasutton** [comment]
Nate, I am not for doing anything here. They are two different schemas with the second based on another schema. Change the CTDLASN and lose compatibility with ASN data,

**Comment by jeannekitchens** [comment]
@siuc-nate review and close if no longer applicable.

**Comment by siuc-nate** [comment]
It looks like no pressing need for this has arisen, so we can close this.
