### ISSUE TITLE
Determine appropriate use of blank nodes

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#574]
Referenced from https://github.com/CredentialEngine/vocabularies/issues/557#issuecomment-462793796

One lingering concern. Every time this thing/string need arises, we cannot/should not create "alternative"  properties. This has been solved (perhaps inelegantly) in several large German bibliographic services as well as elsewhere through declaring the property as requiring a thing and using bnodes to handle literals (without declaring any new properties).

### With URI

```
<http://id.meineInstitution.de/12345> 
    dct:creator <http://id.meineInstitution.de/Bergmann_Bertram>.
```

### Without URI

```
<http://id.meineInstitution.de/12345> 
    dct:creator [ rdfs:label "Bertram Bergmann" ].
```

![image](https://user-images.githubusercontent.com/2939046/52644780-4f2e9080-2e94-11e9-9b7e-d5243810c03b.png)

_Originally posted by @stuartasutton in https://github.com/CredentialEngine/vocabularies/issues/557#issuecomment-462793796_

**Comment by cwd-mparsons** [comment]
@stuartasutton 
We would have an issue with URLs for occupations, etc that don't return JSON which is all of SOC, CIP, And NAICS.

NAICS
https://www.naics.com/naics-code-description/?code=5173

ONet
https://www.onetonline.org/link/summary/17-2011.00

CIP
https://nces.ed.gov/ipeds/cipcode/cipdetail.aspx?y=55&cipid=88075

**Comment by stuartasutton** [comment]
We need to clarify whether we are talking about CTDL or CEASN. We have a history of using CredentialAlignmentObject in CTDL and I don't see that actually changing. So, where the concept referenced is from a framework (NAICS, ONet, CIP) we continue as we have. It's with the entry of simple literals that we shift to bnodes per above.

CEASN is a different story. There are few references to frameworks and we've covered those by reference to CETERMS vocabularies. One thing is clear. We are NOT using CredentialAlignmentObject with competency frameworks. Otherwise the pattern would be the same as with credentials. We use plain bNodes where they submit only a literal and a DefinedTerm bnode where they cannot provide a a return of data.

**Comment by siuc-nate** [comment]
The problem, if I'm understanding @cwd-mparsons correctly, is that cases where we would (in CTDL) have both the URI to the term and the name (or some other bit of human-readable text) in the alignment object allow us to consume data and display it regardless of what the URI returns (we don't even have to fetch the URI's data).

For example, if we had:
```
{
  "ceterms:industryType": [
    { 
      "ceterms:targetNodeName": "programming",
      "ceterms:targetNode": "http://some-url-to-a-webpage.html"
    },
    { 
      "ceterms:targetNodeName": "cybersecurity",
      "ceterms:targetNode": "http://some-other-url-to-another-webpage.html"
    },
  ]
}
```
We could display:
**Industry Type:**
- [programming](http://some-url-to-a-webpage.html)
- [cybersecurity](http://some-other-url-to-another-webpage.html)


In cases like the ones Mike outlines above, where the URI returns something other than JSON (such as HTML), we can't display anything to the user if we consume a document that references such URIs (aside from maybe enumerating the links, which I don't think folks will want to see).
So we'd have:
```
{
  "ceterms:industryType": [
    "http://some-url-to-a-webpage.html",
    "http://some-other-url-to-another-webpage.html"
  ]
}
```
We could only display something like:
**Industry Type:**
- [Industry Type 1](http://some-url-to-a-webpage.html)
- [Industry Type 2](http://some-other-url-to-another-webpage.html)

or
**Industry Type:**
- [http://some-url-to-a-webpage.html](http://some-url-to-a-webpage.html)
- [http://some-other-url-to-another-webpage.html](http://some-other-url-to-another-webpage.html)

I'm not sure what a good solution would be. I'm open to suggestions.

**Comment by stuartasutton** [comment]
@siuc-nate, @cwd-mparsons & @jkitchensSIUC , please read https://github.com/CredentialEngine/CatalogingGuidance/issues/2.

**Comment by siuc-nate** [comment]
I reviewed the issue. It does highlight the usefulness of the targetNode property, but I feel I may be missing what you're getting at by directing us to it.

It's a shame we can't make the range of the industryType/occupationType properties be `skos:Concept` - that would (in a perfect world) guarantee the availability of machine-readable data that would give us a URI to point to and a label to display (and a description for cases where that's used, such as tooltips).

**Comment by stuartasutton** [comment]
Did I somehow put this in the wrong issue? I pointed to it in response to a message from Michael about how using the URL in the targetNode as if it were data is dangerous because it frequently points to the kind of stuff I say is bad in the best practice issue.

I pointed you to it, Nate, because it's a cataloging guidance statement about how to use the `targetNode` and how not to do it. We should not be getting links to PDFs and general pages with it.

**Comment by siuc-nate** [comment]
Yes, but we're discussing using blank nodes instead of Credential Alignment Object - which means that there would be no targetNode property in the blank node (presumably).  Or am I misunderstanding?

**Comment by stuartasutton** [comment]
I think I am confused about context. The use of bNodes is only triggered when there is nothing to reference--just a literal. If there is something to reference, then CredentialAlignmentObject is to be used in the context of CTDL.

**Comment by siuc-nate** [comment]
I may be just as confused, then - I thought we were trying to use direct URIs instead of using Credential Alignment Object _at all_ (for the properties in question).  If we're still using Credential Alignment Object anyway, why wouldn't we continue using the targetNodeName property to carry the string value instead of a blank node?

**Comment by stuartasutton** [comment]
Nate, "instead of using Credential Alignment Object *at all*" is apparently not an option when the framework and node referenced (e.g., NAICS) does not return data but a webpage that can't fill in the blank identifying text label.

As for the second part, because there is just a literal and no framework, you **cannot** use the CredentialAlignmentObject...that takes us full circle.

**Comment by siuc-nate** [comment]
I don't recall there ever being a constraint that required a framework to exist in order to use a Credential Alignment Object - if that is the case, then much of our use and some of our past presentations have been incorrect.  One of the major reasons we use Credential Alignment Object to begin with was to handle cases where there was no node to point to (e.g. a value for targetNodeName and no value for targetNode), regardless of framework (which was usually used as more of a "convenience" property).

**Comment by stuartasutton** [comment]
Nate, that is simply not accurate. We have been over this very point countless times over the past several years. Read the definition of `CredentialAlignmentObject` carefully:

>"Entity describing an affiliation or association between an entity such as a credential, learning opportunity or assessment and another entity in a structured framework such as a concept scheme, enumerated list, or competency framework."

**Comment by stuartasutton** [comment]
In addition to an irrefutably clear definition, we also know that in the current state of people's data, many times their structured frameworks (e.g., competency frameworks) are not in machine addressable form--e.g., framework in PDF. In such a case its description quite validly uses the CredentialAlignmentObject without being able to point to specific component nodes.  So, CredentialAlighmentObject makes perfect sense to capture name, a link to the framework if it exist and the node description. But there is an "affiliation or association" between two entities...with plain flat out literals, that is not the case!

**Comment by siuc-nate** [comment]
I understand - however, that is not how we have been using it.  We have been using it as a general purpose container for, essentially, "whatever data is available at the time" - which may be **any** combination of targetNode, targetNodeName, targetNodeDescription, framework, frameworkName, and codedNotation depending on the context (industry/occupation/CIP codes, controlled vocabularies, competencies, etc.).  This flexibility is why we use it.

For instance, I found this graphic from a presentation we gave ages ago:
![competency references](https://user-images.githubusercontent.com/21346519/52751514-41246100-2fb5-11e9-8ec9-068256af56ee.PNG)

Note the bottom example - there is no node to point to, but the object is still used as a container for the name and description.  This is how we have been implementing Credential Alignment Object all along (and why I have always emphasized its use as a structural object over its semantic meaning in terms of alignment).

Getting back to the matter at hand, though, my main concern is that the type of data that shows up as the value for the properties in question is consistent regardless of what is being pointed to.  That is to say, it should always be either an object or a URI, but not something that allows a combination of the two.  And the more consistent the object (either as the value of the property or as the blank(?) node identified by the property) can be, the better.

Hence I would want to avoid something like this:
```
"@graph": [
  {
    "@type": "ceterms:Certificate",
    "ceterms:industryType": [
      "http://url-to-some-source-that-returns-JSON",
      {
        "@type": "ceterms:CredentialAlignmentObject",
        "ceterms:targetNode": "http://url-to-some-source-that-returns-HTML",
        "ceterms:targetNodeName": "Cybersecurity"
      },
      "_:ABC"
    ]
  },
  {
    "@type": "???",
    "rdfs:label": "Programming"
  }
]
```
As that presents an absolute mess to publish or consume.

As I understand it, we originally wanted to do this instead:
```
"@graph": [
  {
    "@type": "ceterms:Certificate",
    "ceterms:industryType": [
      "http://url-to-some-source-that-returns-JSON",
      "http://url-to-some-source-that-returns-HTML",
      "_:ABC"
    ]
  },
  {
    "@type": "???",
    "rdfs:label": "Programming"
  }
]
```
(though I would prefer to use ceterms:name instead of rdfs:label in order to be consistent, we can sort that out later)
Then @cwd-mparsons pointed out that the HTML url would leave us without anything to display, which leads me to prefer something like this:
```
"@graph": [
  {
    "@type": "ceterms:Certificate",
    "ceterms:industryType": [
      "http://url-to-some-source-that-returns-JSON",
      "_:123",
      "_:ABC"
    ]
  },
  {
    "@type": "???",
    "ceterms:subjectWebpage": "http://url-to-some-source-that-returns-HTML",
    "ceterms:name": "Cybersecurity"
  }
  {
    "@type": "???",
    "ceterms:name": "Programming"
  }
]
```
This is where I'm less certain about the best route:
- Option 1: consider the blank nodes to be skos:Concept
  - This feels semantically "close enough", and presents a pattern that would be compatible with CTDL-ASN and other such "it's _sort of_ a controlled vocabulary" situations
  - It would argue for using skos:prefLabel instead of ceterms:name (which is fine)
  - What would you do for ceterms:subjectWebpage?
    - Is there an equivalent skos property?
    - Would it simply be merged in?
      - Would that have any consequences for our documentation (e.g. needing to profile the entirety of skos)?

- Option 2: consider the blank nodes to be ceterms:IndustryClassification (or the other appropriate classes)
  - This feels semantically correct, however:
  - Those classes deliberately have no properties; would such properties need to be added?
    - What properties would be added?

- Option 3: consider the blank nodes to be ceterms:CredentialAlignmentObject
  - This might be easier to work into existing implementations
  - It would mean using ceterms:targetNode instead of ceterms:subjectWebpage
  - It would mean using ceterms:targetNodeName instead of ceterms:name

- Option 4: consider the blank nodes to be different types (within the same array)
  - This allows for greater flexibility in terms of which properties are used, however:
  - It presents nearly the same difficulty in publishing and consuming the data as merging strings and objects in the same array would present

- Option 5: leave the blank nodes untyped
  - This is probably not legal JSON-LD (or at least not a good practice)
  - It would lead to inconsistent implementations

Without having a strict definition of what properties would be in the data returned by URIs that _do_ return JSON (that is to say, "what do you get back when you resolve http://url-to-some-source-that-returns-JSON"?), I don't have a strong basis for what `@type` value to lean towards.  This, in turn, leads me to fall back to Credential Alignment Object (or some functionally identical class), since that has been proven to work thus far.

What ever happened with https://pending.schema.org/DefinedTerm?

**Comment by jkitchensSIUC** [comment]
@cwd-mparsons @siuc-nate is this a Registry publishing issue or a CTDL/CTDL ASN issue?

**Comment by siuc-nate** [comment]
Both.  Depending on how we end up handling vocabularies, if we make any changes, there may be changes to the ranges of some properties (e.g. pointing to skos:Concept instead of ceterms:CredentialAlignmentObject).  But there are also potential changes for the registry side of things (the structure of the data, i.e. blank nodes)

**Comment by siuc-nate** [comment]
I put together this spreadsheet:
https://docs.google.com/spreadsheets/d/1qJkYBz3vHBb8jXZyrC2jE38J8cP1JT99pXLqCT-PrnI/edit#gid=0

It lists properties for Credentials, Assessments, and Learning Opportunities.
- Yellow highlighted properties currently use `ceterms:CredentialAlignmentObject`. Per the above comments, it's worth considering the use of bnodes/skos:Concepts for these instead
- Properties marked as "Describes Other Entity" are suggested candidates for reworking the approach to (see below)
- Properties marked as "Extra Text" are tied to some other property (e.g. ___ and ___Description), and such property sets are worth considering as candidates for the use of bnodes

Reworking properties:
Instead of:
```
{
  "@graph": [
    {
      "@type": "ceterms:Certificate",
      "ceterms:assessmentDeliveryType": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:targetNode": "deliveryType:OnlineOnly",
          "ceterms:targetNodeName": "OnlineOnly"
        }
      ]
    }
  ]
}
```
You'd drop that property, use the normal way of getting from a credential to an assessment (via Condition Profile), and then indicate the delivery type as a property of the AssessmentProfile (since the delivery type is describing the Assessment Profile, not the Credential):
```
{
  "@graph": [
    {
      "@type": "ceterms:Certificate",
      "ceterms:requires": [
        {
          "@type": "ceterms:ConditionProfile",
          "ceterms:targetAssessment": [
            "_abcdefg"
          ]
        }
      ]
    },
    {
      "@id": "_:abcdefg",
      "@type": "ceterms:AssessmentProfile",
      "ceterms:assessmentDeliveryType": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:targetNode": "deliveryType:OnlineOnly",
          "ceterms:targetNodeName": "OnlineOnly"
        }
      ]
    }
  ]
}
```

On the surface, this may look more complex, but consider a case where a credential requires two learning opportunities and recommends a third. If you lean exclusively on the convenience properties, you can't express the number of learning opportunities, letalone what data belongs to which one.

If you did include a condition profile that referenced the learning opportunities, you still lose the context of what data  belongs to which entity (note that this same problem would apply if you used bnodes here instead of URIs):
```
{
  "@graph": [
    {
      "@type": "ceterms:Certificate",
      "ceterms:learningDeliveryType": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:targetNode": "deliveryType:OnlineOnly",
          "ceterms:targetNodeName": "OnlineOnly"
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:targetNode": "deliveryType:InPerson",
          "ceterms:targetNodeName": "InPerson"
        }
      ],
      "ceterms:requires": [
        {
          "@type": "ceterms:ConditionProfile",
          "ceterms:targetLearningOpportunity": [
            "https://credentialengineregistry.org/graph/ce-abcdef",
            "https://credentialengineregistry.org/graph/ce-xyz098"
          ]
        }
      ],
      "ceterms:recommends": [
        {
          "@type": "ceterms:ConditionProfile",
          "ceterms:targetLearningOpportunity": [
            "https://credentialengineregistry.org/graph/ce-12345",
          ]
        }
      ]
    }
  ]
}
```

However, using bnodes that include the delivery type information allows you to correctly indicate the relevant information:
```
{
  "@graph": [
    {
      "@type": "ceterms:Certificate",
      "ceterms:requires": [
        {
          "@type": "ceterms:ConditionProfile",
          "ceterms:targetLearningOpportunity": [
            "_:abcdef",
            "_:xyz098"
          ]
        }
      ],
      "ceterms:recommends": [
        {
          "@type": "ceterms:ConditionProfile",
          "ceterms:targetLearningOpportunity": [
            "_:12345",
          ]
        }
      ]
    },
    {
      "@id": "_:abcdef",
      "@type": "ceterms:LearningOpportunityProfile",
      "ceterms:learningDeliveryType": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:targetNode": "deliveryType:OnlineOnly",
          "ceterms:targetNodeName": "OnlineOnly"
        }
      ]
    },
    {
      "@id": "_:xyz098",
      "@type": "ceterms:LearningOpportunityProfile",
      "ceterms:learningDeliveryType": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:targetNode": "deliveryType:InPerson",
          "ceterms:targetNodeName": "OnlineOnly"
        }
      ]
    },
    {
      "@id": "_:12345",
      "@type": "ceterms:LearningOpportunityProfile",
      "ceterms:learningDeliveryType": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:targetNode": "deliveryType:InPerson",
          "ceterms:targetNodeName": "OnlineOnly"
        }
      ]
    }
  ]
}
```

In the end, it would still be better to properly publish the learning opportunities as standalone entities, but that is beyond the scope of the need for blank nodes.

**Comment by siuc-nate** [comment]
The changes here would basically require doing CTDL over again. Dropping this.
