### ISSUE TITLE
Monitor JDX Schema Development to Identify Additional to the CTDL and CTDL ASN

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#587]
@stuartasutton @philbarker this is as placeholder to begin documenting any additions to the CTDL/CTDL ASN resultant from the JDX pilot.  https://github.com/jobdataexchange

**Comment by stuartasutton** [comment]
ASN has been considering the addition of competency framework-related occupation and industry.

**Comment by siuc-nate** [comment]
Per our 9-3-2019 meeting:
There is nothing at this time to do; this matter is ongoing.

**Comment by jeannekitchens** [comment]
No action needed.
