### ISSUE TITLE
Consider removing ceasn:inLanguage from ceasn:Competency

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#604]
Since all of the properties in a competency that are language-dependent are already language strings, is it redundant to have an inLanguage property on the competency itself?  This property already exists on the Framework.

It may be useful as a way of summarizing the language of all of the fields in the competency.  We need to discuss it.

**Comment by siuc-nate** [comment]
Per our 6-4-2019 meeting:
It makes sense to remove this property from Competencies.  This would also mirror the ASN implementation.

**Comment by stuartasutton** [comment]
No objections...

**Comment by cwd-mparsons** [comment]
What about Concept - wouldn't be the same rational?

**Comment by siuc-nate** [comment]
Changes to be made:

**Remove:**
> **URI:** ceasn:inLanguage
> **Domain:** ceasn:Competency, skos:Concept

**Comment by siuc-nate** [comment]
Per our 7-30-2019 meeting:
We need to consider the impacts on CASS and any other systems before implementing this.

**Comment by siuc-nate** [comment]
Change to be made:

**Remove:**
> **URI:** ceasn:inLanguage
> **Domain:** ceasn:Competency, skos:Concept

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL-ASN and noted in the history tracking.
