### ISSUE TITLE
Operationalizing Relationships - Skill Transferability

### ISSUE THREAD

**Issue by Lomilar** [CredentialEngine/Schema-Development#612]
A point of continuous contention is whether a person who is competent at something in the context of one framework is competent at something in another framework.

An example was: "Make decisions that are objective and reflect the just treatment of others." in a DOL Enterprise Security Framework and the same statement in a DOL Building Blocks Framework.

The phrase "just treatment of others" has a different sense in each framework.

Regardless, if these competencies apply to humans, we have some elasticity that means that we can transfer skills from one context to another and, nearly all of the time, apply them successfully.

Understanding what competencies transfer from one context to another context is a key feature of human learning, otherwise, learning would largely be discarded in favor of experience.

Being able to label what competencies transfer from one context to another is incredibly beneficial. Exact Alignment, Major Alignment, and Minor Alignment are all valid candidates for communicating transfer, but I'm having trouble attempting to use these alignments to operationalize transfer.

Narrow and Broad Alignment make it a bit easier, because if A narrows B, then B implies A, therefore a person who can B can A.

Exact seems to pertains to things like versions of a framework that hold the same context but maybe changes some methods.

What do we do with major and minor? It seems reasonable that *for the most part* those two skills are transferable with each other, but without performing a skill transfer study for each skill, I'm not sure what we can say about the exact same phrase in relatively similar contexts.

**Comment by stuartasutton** [comment]
@Lomilar, I think there is a bit of apples and oranges here. I could not agree more that humans are innately capable of transferring skills from one context to another--whether this occurs in any particular person is a function of a number factors. However whether skills embodied in one competency are transferable to another competency is a human problem that is only tangentially addressed by any of the current ASN (& CTDL-ASN) mapping properties whose sole purpose and capability is identification of the level of overlap in "relevant concepts". 

The current mapping properties alone do not identify which "relevant concepts" (which could be skills but are not necessarily so) are present on both ends of the mapping comparison--that is left to other properties that most competency frameworks in the wild do not cover/identify (e.g.,using conceptTerm). Lack of explicit identification of such "relevant concepts", leaves us with nothing more than rough comparisons of similarity. John Kendall address some aspects of this problem in his [2003 article](http://dcpapers.dublincore.org/pubs/article/download/739/735). But, in the end, even with richer identification of relevant concepts embodied, such mapping do not really touch on the probability of actual skill transfer.

**Comment by siuc-nate** [comment]
>Narrow and Broad Alignment make it a bit easier, because if A narrows B, then B implies A, therefore a person who can B can A.

That depends very heavily on how the broader competency is written.  Consider the difference between:

- Can use a computer
  - Can use Windows
    - Can install and uninstall drivers
    - Can manually update the Windows registry

and

- Can administrate and troubleshoot a computer
  - Can administrate and troubleshoot Windows
    - Can install and uninstall drivers
    - Can manually update the Windows registry

If you ask someone, "can you use a computer?", are you implicitly asking if that person knows every potential thing that can be done with a computer, including diagnosing and fixing problems (in either the digital or physical sense)?  In fact, would the second example above technically fall under the umbrella of "Can use a computer"?  What about "can you use a car?" or "can you use a toaster?".  The broader competency doesn't always imply all of its children if it's not written specifically enough, in my opinion.

**Comment by Lomilar** [comment]
Responding to @siuc-nate first,

Context, context, context. "Can you use a computer" means something much more narrow in this framework's context. In the top framework, it primarily means "Can you use Windows" plus -- at worst -- any implicit additional SKA associated with using a computer in this context, say, turning on the computer, operating the mouse, etc.

In an "all things computer" framework, it may mean a whole world of things as you pointed out.

@stuartasutton:

This brings me to my second point, which is that in a third party mapping, declaring that two competencies have some sort of conceptual relationship or alignment is not necessarily what organizations will want to be defining. 

They may, instead, want to define functional alignments, which are more of an authoritative statement that, for instance: According to us, this skill _covers_ that skill -- it doesn't matter what the conceptual overlap is, according to us, if you can A, you can B.

Other functional relationships could include things like:
* Sequence -- While you can learn multiplication before subtraction, it is awkward to do so. This *should* be learned before that, even though there is not a dependency relationship.
* Transfer/Enables -- This competency, when obtained, makes the acquisition of that competency either much easier (enables) or trivial (transfer). It could be argued that this includes some conceptual elements.

I'm having trouble thinking of additional functional relationships but I'm sure more exist.

**Comment by Lomilar** [comment]
So, an example of _covers_ -- which likely needs renaming.

A barista framework:
* Can make drinks using espresso
  * Can make an americano
    * Can heat water and add it to espresso
    * Can pull an espresso shot
    * Can use an espresso machine
  * Can make a latte
    * Can steam milk and add it to an espresso
    * Can pull an espresso shot
    * Can use an espresso machine

And the much lower class Greasy Spoon worker

* Can make hot drinks
  * Can make coffee
    * Can heat water and pour it over coffee crystals
    * Can use a coffee pot

I would want to make the relationship that an individual who is competent in creating an Americano in the first framework can make coffee in the second framework. Not because there is conceptual overlap, but because of a common sense understanding that an americano is a coffee by another name, and they can figure out the coffee pot.

I think these types of relationships will be far more comfortable for many to make.

People who can ride two wheeled bikes can ride three wheeled bikes, though they may be a bit baffled at first.

People who can dig a trench can dig a hole.

**Comment by stuartasutton** [comment]
OK, did I ever give the impression that conceptual overlap was the only kind of relationship...I don't think so. Long ago, when the current mapping properties were created (i.e., over a decade ago, some nearly 2 decades), we strongly noted that there would mapping predicates would emerge. And that 3rd party mappings taking a wide array of forms would emerge.

Have at it!

**Comment by Lomilar** [comment]
Does this conversation belong here? Is it worth considering (here) a softer vocabulary for mapping between frameworks that are *just* useful, instead of useful *and* descriptive (as conceptual alignments are)? I know there is a great desire to begin mapping frameworks together.

**Comment by stuartasutton** [comment]
Can you be more explicit? Great desire by whom? 3rd parties? If 3rd parties, by what tooling?...CTDL has it's [ceterm:AlignmentMap](https://purl.org/ctdl/terms/AlignmentMap) entity...but no tooling. What mapping predicates?

Note, following image doesn't align exactly with property/class names in CTDL (need to update)

![2017-11-14-maps](https://user-images.githubusercontent.com/2939046/59871107-a1545680-934b-11e9-9adf-a0f97c2649d1.png)

**Comment by siuc-nate** [comment]
What are the schema implications/asks here? This issue is not clear.

**Comment by stuartasutton** [comment]
I can take a stab at stating the issue. @Lomilar asserts that a relationship can exist between competencies where underlying aspects of one are "transferable" to the other supporting an assertion of competence with one is likely competent with the other. @Lomilar summarizes with: 
>"Is it worth considering (here) a softer vocabulary for mapping between frameworks that are just useful, instead of useful and descriptive (as conceptual alignments are)? I know there is a great desire to begin mapping frameworks together.

The current mapping predicates don't enable such assertions. But, no one has said that the current array of mapping relationships were sufficient.  @Lomilar suggests two relationships: 

>**Sequence** -- While you can learn multiplication before subtraction, it is awkward to do so. This should be learned before that, even though there is not a dependency relationship.
**Transfer/Enables** -- This competency, when obtained, makes the acquisition of that competency either much easier (enables) or trivial (transfer). It could be argued that this includes some conceptual elements.

The Transfer/Enables suggest that some notions in one map to the same or similar notions in the other. I'd point out that the current mapping properties identify these notions abstractly in terms of overlap. To say that the notions are coextensive IS TO ASSERT that one can enable/transfer to the other. While I'm OK with some 3rd party doing gut-level transfers/enables mappings but would hope that schema embedded mappings would have some empirical base...e.g., the notions supporting the assertion are explicit in both.   One would be to capture more contextual notions through ceasn:conceptTerm / ceasn:conceptKeyword in all description that could be the base for more justifiable mappings than the gut. Refrain: Read John Kendall address some aspects of this problem in his [2003 article](http://dcpapers.dublincore.org/pubs/article/download/739/735).

**Comment by siuc-nate** [comment]
Thank you for the summary.

I think a "sequence" alignment is sort of redundant with "major alignment" and "minor alignment", though neither of those indicates which one should come first, so I guess I can see a property like that making sense.

Some kind of "enables" or "transfer" alignment definitely seems to cover the same ground as existing major/minor/broad/narrow alignments though.  I can't see how you'd use them differently.

**Comment by stuartasutton** [comment]
From an EdReNe presentation in the Netherlands in 2002:

<img width="917" alt="Sequencing" src="https://user-images.githubusercontent.com/2939046/77459714-60e3a680-6dbd-11ea-920e-42204979e86d.png">

**Comment by siuc-nate** [comment]
Archiving this, as it hasn't seen demand in a few years.
