### ISSUE TITLE
Create “frameworkCategory” property in CompetencyFramework.

### ISSUE THREAD

**Issue by Lomilar** [CredentialEngine/Schema-Development#616]
Alternative to #617

Create “frameworkCategory” property in CompetencyFramework to "type" CompetencyFramework in the same way that “competencyCategory” "types" Competency.

To allow CompetencyFramework to be "retyped" into Work Roles, Duties, Responsibilities, Class Curriculum Frameworks, and other bundles of Competencies.

**Proposal:**
**Add:**
> **URI:** ceasn:frameworkCategory
> **Label:** Framework Category
> **Definition:** The textual label identifying the category of the competency framework as designated by the promulgating body.
> **Comment:** For example, "Work Role Framework", "Performance Objective Framework", "Learning Objective Framework", etc.
> **Domain:** ceasn:CompetencyFramework
> **Range:** xsd:string

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate adding this to the Oct Milestones set for potential inclusion.

**Comment by stuartasutton** [comment]
The reason such a property was not added to ASN was because any given framework may embody multiple types (e.g., Competency, Task, Benchmark). The competencyCategory was assigned to the competency node because that's a single type. Of course, there is nothing that says a framework could not have multiple frameworkCategory instances. If it cannot have multiple, then we shouldn't...

**Comment by Lomilar** [comment]
This is another one of those properties that smoothes the rough edges of the term "Framework".

Use case: Devolving a rigid "work role" object into a "Work Role" describing competency framework in order to align a work role to a cybersecurity degree framework.

Use case: Describing a framework that describes a credential as something other than a framework.

Use case: Describing a curriculum object that outlines the objectives of a course as something other than a framework.

**Comment by siuc-nate** [comment]
Per our 9-17-2019 meeting:
@Lomilar we would need to see examples of those use cases and discuss them further.

**Comment by Lomilar** [comment]
9/18 - Discussed further.

**Comment by siuc-nate** [comment]
@Lomilar Was that discussion documented? I don't recall.

**Comment by Lomilar** [comment]
I don't recall either.

**Comment by siuc-nate** [comment]
I recommend that we drop this (and #617) and start over since the task classes are no longer part of frameworks and our thinking around work roles has changed a lot.

**Comment by stuartasutton** [comment]
I agree...it should be closed and therefore is.
