### ISSUE TITLE
Create a Framework class to accommodate more types of Frameworks

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#617]
Based on our 8-14-2019 meeting:
Alternative to #616

**Proposal:**
Create a generic "Framework" class:
> **URI:** ceasn:Framework
> **Label:** Framework
> **Definition:** Class of structured sets of conceptual resources developed for use as value vocabulary terms for properties in metadata descriptions.

Create a generic "FrameworkStatement" class:
> **URI:** ceasn:FrameworkStatement
> **Label:** Framework Statement
> **Definition:** Class of assertions in a Framework.

Declare CompetencyFramework to be a subclass of Framework:
> **Subject:** ceasn:CompetencyFramework
> **Predicate:** rdf:subclassOf
> **Object:** ceasn:Framework

Create TaskFramework class:
> **URI:** ceasn:TaskFramework
> **Label:** Task Framework
> **Subclass Of:** ceasn:Framework
> **Definition:** TBD

Consider creating the following Framework subclasses:
- WorkRoleFramework (or create a non-framework WorkRole class)
- LearningObjectiveFramework
- PerformanceObjectiveFramework

**Comment by siuc-nate** [comment]
The Framework class would also be a superclass for the TaskFramework classes in the ARTT project, but it is not holding up work in that area.

**Comment by siuc-nate** [comment]
We would also likely need a ceasn:Task superclass.

**Comment by stuartasutton** [comment]
Both #616 and this issue need to consider that an individual competency framework can hold a (sometimes seemingly random) mixed bag of "types" in the sense meant by the current competencyCategory; e.g.,

```
WorkRole
   Standard
      Competency
           Benchmark
               Task
                  Step 
``` 
In such a case, what's the "type" of the framework?

**Comment by siuc-nate** [comment]
Per our 9/17/2019 meeting:
We will leave the Work Role and other proposals alone for now and proceed with the following:

**Proposal:**
Create a generic "Framework" class:
> **URI:** ceasn:Framework
> **Label:** Framework
> **Definition:** Class of structured sets of conceptual resources developed for use as value vocabulary terms for properties in metadata descriptions.

Create a generic "FrameworkNode" class:
> **URI:** ceasn:FrameworkNode
> **Label:** Framework Node
> **Definition:** Class of assertions in a Framework.

Declare CompetencyFramework to be a subclass of Framework:
> **Subject:** ceasn:CompetencyFramework
> **Predicate:** rdf:subclassOf
> **Object:** ceasn:Framework

Declare Competency to be a subclass of Framework Node:
> **Subject:** ceasn:Competency
> **Predicate:** rdf:subclassOf
> **Object:** ceasn:FrameworkNode

Create TaskFramework class:
> **URI:** ceasn:TaskFramework
> **Label:** Task Framework
> **Subclass Of:** ceasn:Framework
> **Definition:** TBD

Create a Task class:
> **URI:** ceasn:Task
> **Label:** Task
> **Subclass Of:** ceasn:FrameworkNode
> **Definition:** TBD

**Comment by siuc-nate** [comment]
It's good that we delayed on this one, because more recent discussions with regard to the navy Task classes seems to indicate that they are indeed **not** in a framework, but rather freestanding entities.

As such, I think adding the "frameworkCategory" property as described in #616 makes more sense at this time, and probably wouldn't hurt even if we did move forward with the generic classes described in this issue.

**Comment by siuc-nate** [comment]
I recommend that we drop this (and #617) and start over since the task classes are no longer part of frameworks and our thinking around work roles has changed a lot.
