### ISSUE TITLE
Additions of ceasn:knowledgeEmbodied and ceasn:taskEmbodied properties

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#618]
We are needing to flesh out some "connections" properties in the CTDL-ASN. We already have [ceasn:skillEmbodied](https://purl.org/ctdlasn/terms/skillEmbodied) and [ceasn:abilityEmbodied](https://purl.org/ctdlasn/terms/sbilityEmbodied). Both of these properties and the two proposed here are 'softer' than the notions of prerequisite or required and should not be used by downstream systems to enforce sequencing etc. 

### Add

> **URI:** ceasn:knowledgeEmbodied
> **Label:** Knowledge Embodied
> **Definition:** Body of information embodied either directly or indirectly in this competency.
> **Domain:** ceasn:Competency
> **Range:** xsd:anyURI

> **URI:** ceasn:taskEmbodied
> **Label:** Task Embodied
> **Definition:** Specifically defined piece of work embodied either directly or indirectly in this competency.
> **Domain:** ceasn:Competency
> **Range:** xsd:anyURI

**Comment by siuc-nate** [comment]
I understand the use of knowledgeEmbodied, but what would some use cases for taskEmbodied be?

**Comment by siuc-nate** [comment]
I would also suggest using "this resource" instead of "this competency" to smooth the reuse of these properties in a task context.  I would apply this to skillEmbodied and abilityEmbodied as well.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate @Lomilar as this progresses.  Need to be sure including these properties with CaSS and with output from the Registry (e.g., the competencies that show with the Finder). If CaSS needs to be updated in tandem with implementing this, it needs to be posted to the CaSS Github issues.

**Comment by cwd-mparsons** [comment]
I have added handling of these properties to the API.

**Comment by Lomilar** [comment]
@woodkri It looks like these are in. Seems like a candidate for closure.

**Comment by woodkri** [comment]
Agreed. I'm not able to close out issues in this repository though.

**Comment by siuc-nate** [comment]
These still need to be added to the schema.

**Comment by siuc-nate** [comment]
Proposal:

**Add:**

> **URI:** ceasn:knowledgeEmbodied
> **Label:** Knowledge Embodied
> **Definition:** Body of information embodied either directly or indirectly in this resource.
> **Domain:** ceasn:Competency
> **Range:** xsd:anyURI

> **URI:** ceasn:taskEmbodied
> **Label:** Task Embodied
> **Definition:** Specifically defined piece of work embodied either directly or indirectly in this resource.
> **Domain:** ceasn:Competency
> **Range:** xsd:anyURI


**Remove:**
> **Subject:** ceasn:abilityEmbodied
> **Predicate:** rdfs:comment
> **Object:** "Enduring attributes of the individual that influence performance are embodied either directly or indirectly in this competency."

> **Subject:** ceasn:skillEmbodied
> **Predicate:** rdfs:comment
> **Object:** "Ability to apply knowledge and use know-how to complete tasks and solve problems including types or categories of developed proficiency or dexterity in mental operations and physical processes is embodied either directly or indirectly in this competency."

**Add:**
> **Subject:** ceasn:abilityEmbodied
> **Predicate:** rdfs:comment
> **Object:** "Enduring attributes of the individual that influence performance are embodied either directly or indirectly in this resource."

> **Subject:** ceasn:skillEmbodied
> **Predicate:** rdfs:comment
> **Object:** "Ability to apply knowledge and use know-how to complete tasks and solve problems including types or categories of developed proficiency or dexterity in mental operations and physical processes is embodied either directly or indirectly in this resource."

**Comment by stuartasutton** [comment]
To sum this up, "competency" > "resource"

Correct?

**Comment by siuc-nate** [comment]
Correct.  Plus the two new properties.

**Comment by stuartasutton** [comment]
I'll sign off. This looks good to me.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL-ASN and noted in the history tracking.
