### ISSUE TITLE
Consider changing the range of ceasn:CompetencyCategory to skos:Concept

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#626]
Currently, the [ceasn:competencyCategory](https://purl.org/ctdlasn/terms/competencyCategory) has a range of rdf:langString. We need to also support URIrefs to concepts in controlled vocabularies. From the inception of this term in ASN nearly 20 years ago, the assumption was always that these terms were "controlled" within the context of the framework where they are used but not formalized in concept schemes. ASN defined the range as "undefined" (i.e., no range assertion). Now, the push is for these schemes to be formalized.

We need to consider either: (1) changing the range to support handling URIrefs to concepts in formal concept schemes, while committing entry of literals in informal schemes of a particular framework or set of frameworks to blank nodes of type skos:Concept; or (2) creating a new property (ceasn:competencyCategoryTerm) to handle such URIrefs.

**Comment by siuc-nate** [comment]
In other cases, we tend to use "type" to point to controlled vocabularies (agentType, directCostType, learningMethodType, and as I so often wish, credentialType, etc.).  It seems like "competencyType" would be a natural fit here, since we are trying to do a sort of soft subclassing of competencies (that could be specific within a framework or set of frameworks) by relating them to a concept.  That would also let us avoid changing the range of competencyCategory.

**Comment by siuc-nate** [comment]
Though taking a step back, it would be nice if we had a more generic name for it, so that it could also be reused in other cases (i.e., avoid eventually having to invent ["taskType" and "nodeType"](https://github.com/CredentialEngine/vocabularies/issues/617#issuecomment-532336016)).  Maybe `nodeType` could kill a few birds with one stone by allowing soft subclassing of FrameworkNode, Competency, Task (and all of its subclasses)?

Something to think about.

**Comment by siuc-nate** [comment]
I think the need to soft-type things may be where generic properties like [schema:additionalType](https://schema.org/additionalType) came from:

"An additional type for the item, typically used for adding more specific types **from external vocabularies**..."

So it wouldn't be that unusual.  But I think the benefits of having `competencyType`, `taskType`, and so on may be worthwhile regardless (vs just having nodeType).

**Comment by Lomilar** [comment]
I think adding URI to the range (it is easy enough to detect) would suffice here.

This is, largely though, a failure of RDF libraries that don't handle "x isa y" queries very well. Type equivalence and subtypes are well recognized concepts in RDF description languages.

One day I will take that sabbatical and create an RDF native javascript. The JS-LD companion to JSON-LD.

**Comment by stuartasutton** [comment]
Breaks a pattern in CTDL. It’s not just a literal, but a langString. How do you handle language map and uriRef in @context?

**Comment by Lomilar** [comment]
Oh, good point. Yeah, I think I may be with Nate then, import/rebrand schema:additionalType.

**Comment by siuc-nate** [comment]
If we did implement this via skos:Concept, can CASS handle creating/managing blank nodes, or would it require generating a concept scheme for each competency framework and converting the framework's language maps for the competencyCategory property over to concepts in the scheme?

**Comment by siuc-nate** [comment]
Per our 10-13-2020 meeting:

**Remove:**
> **Subject:** ceasn:competencyCategory
> **Predicate:** schema:rangeIncludes
> **Object:** rdf:langString

**Add:**
> **Subject:** ceasn:competencyCategory
> **Predicate:** schema:rangeIncludes
> **Object:** skos:Concept

Pinging @Lomilar @woodkri for awareness, as I imagine we'll need to discuss this

**Comment by woodkri** [comment]
In the new interface it will be easy to change the range from langString to Concept. We'll likely need to change our translations too. What's the plan for the existing data?

**Comment by siuc-nate** [comment]
Adding this to the April 2021 milestone so we can evaluate it and determine whether or not to move forward with it.

**Comment by siuc-nate** [comment]
Adding the following from #657 to merge these threads:

@stuartasutton [Mar 11, 2020](https://github.com/CredentialEngine/Schema-Development/issues/657#issue-579318133):
>Some time ago, Jim Goodell asked me whether CTDL-ASN had a companion property to ceasn:competencyCategory for references to categories defined in concept schemes. I have been pondering whether creation of another property with a range of ceterms:CredentialAlignmentObject was necessary or whether we should not simply change the range of ceasn:competencyCategory to ceterms:CredentialAlignmentObject that could be used to handle either case; i.e., using ceterms:targetNode (and perhaps even ceterms:targetNodeName) for referencing a category in a concept scheme AND just ceterms:targetNodeName when all that was present was a literal? Since the underlying assumption is that either way, the values are from some controlled value space (formally declared or not), the fit with CredentialAlignmentObject is appropriate.
>
>The reason that is defined solely as an rdf:langString is purely historical. When the property was defined in ASN nearly 20 years ago, controlled value spaces weren't as prevalent...and, we just didn't see how usage would evolve.
>
>I understand the namespace policy and technical issues of changing the range, but hearing from others on the approach would be appreciated. It is not a new conversation. We've discussed the use of bnodes for handling literals in contexts where the value might also be a a reference to a concept resource. This method has been deployed in other principled contexts.
>
>(+ bloody wish we could use schema:DefinedTerm instead of ceterms:CredentialAlignmentObject...)

@siuc-nate [Mar 11, 2020](https://github.com/CredentialEngine/Schema-Development/issues/657#issuecomment-597694945):
>While I don't know off the top of my head what the technical implications would be for a change like that (they would affect data in CASS quite a bit, for sure), I think a more future-proof approach would be to use `skos:Concept` rather than `ceterms:CredentialAlignmentObject`, since that would allow us to:
>
>1. Reference Concepts where they already exist, and
>2. Use embedded bnodes with a `@type` of `skos:Concept` where they do not
>
>That way we aren't using Credential Alignment Objects as pseudo-Concept nodes.  This is the approach I'm aiming for for cases like ProPath where there is a possibility of needing "Other" values for various use cases.
>
>That said, it might be worth considering whether or not this would be better done with a new property.  I'm not sure there.

@Lomilar [Mar 11, 2020](https://github.com/CredentialEngine/Schema-Development/issues/657#issuecomment-597700674):
>skos:Concepts rigidly (ala 2 object model) identify the scheme they come from, so I'm not seeing the need for alignment object. Is there a need for a verb?
>
>Having a range of schema:URL or schema:Text isn't too much of an ask either.
>
>I'm not sure if we need alignmentObject, unless we need to further annotate the connection with additional information.

**Comment by stuartasutton** [comment]
I obviously would be pleased to not ever use CredentialAlignmentObject for the sole task of identifying a Concept in a ConceptScheme.  CredentialAlignmentObject was created to serve as a kind of reification by **particularizing a relationship** between something and a node in a framework.  In the case at the top of this issue, we already have a  **particularizing a relationship**, ceasn:competencyCategory, so to use  CredentialAlignmentObject for the sole task of identifying a Concept in a ConceptScheme is to push CredentialAlignmentObject into a service it was never intended to fulfill.

**Comment by siuc-nate** [comment]
Reopening this, as I think it was closed by mistake.

**Comment by siuc-nate** [comment]
Per our 7-19-2022 meeting:

**Remove:**
> **Subject:** ceasn:competencyCategory
> **Predicate:** schema:rangeIncludes
> **Object:** rdf:langString

**Add:**
> **Subject:** ceasn:competencyCategory
> **Predicate:** schema:rangeIncludes
> **Object:** skos:Concept

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL-ASN and noted in the history tracking.

**Comment by siuc-nate** [comment]
Per @jeannekitchens this change has been reverted just now.

**Comment by jeannekitchens** [comment]
I still don't agree that categories should have to be concept schemes.  It makes more sense to support both.  We also have frameworks published with categories that are strings so it's still a breaking change even if CaSS updates.

**Comment by siuc-nate** [comment]
Part of the originally-intended approach would likely involve using concept bnodes where a properly-published concept did not exist (or didn't make sense to publish), so that the competencies in a framework would all reference that concept bnode rather than duplicating the string in each competency. It would mean being able to have all of those competencies reference the same bnode (useful for linking) and if the text of the category changes, it wouldn't need to be updated in more than one place. 

But you are right about it being a breaking change, so perhaps it would be more useful to just add [ceterms:classification](https://credreg.net/ctdl/terms/classification) to Competency instead, as that property is already intended for this kind of usage and already directly references a concept.

**Comment by siuc-nate** [comment]
See #949
