### ISSUE TITLE
Employment and Earnings Terms - Final Proposal

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#628]
(Note: Work in Progress)

Replaces #376 and #377 
The following are planned for the November release.

Note: We should examine classes and properties for cases where schema.org terms can be used instead (to avoid needing a middle man mapping process ala EOCred conversion).  For example, we can probably use schema:Place instead of ceterms:Place (but need to investigate its impact on the available properties for the class).

**Classes**
---
**Existing Classes Borrowed As-Is:**

> **URI:** ceterms:Credential
> **Label:** Credential
> **Definition:** Qualification, achievement, personal or organizational quality, or aspect of an identity typically used to indicate suitability.

> **URI:** ceterms:JurisdictionProfile
> **Label:** Jurisdiction Profile
> **Definition:** Geo-political information about applicable geographic areas and their exceptions.

> **URI:** ceterms:Place
> **Label:** Place
> **Definition:** Entity describing a physical location or geospatial area.

**Modifications to Existing/Borrowed Classes:**

> **URI:** ceterms:EarningsProfile
> **Label:** EarningsProfile
> **Definition:** Entity that describes earning and related statistical information for a given credential.
> **Modification:** Addition of properties identified below.

> **URI:** ceterms:EmploymentOutcomeProfile
> **Label:** EmploymentOutcomeProfile
> **Definition:** Entity that describes employment outcomes and related statistical information for a given credential.
> **Modification:** Addition of properties identified below.

> **URI:** schema:MonetaryAmount
> **Label:** MonetaryAmount
> **Definition:** Monetary value or range.
> **Modification:** Simplified definition, use of properties identified below.

> **URI:** schema:MonetaryAmountDistribution
> **Label:** MonetaryAmountDistribution
> **Definition:** Statistical distribution of monetary amounts.
> **Modification:** Use of properties identified below.

> **URI:** ceterms:ProcessProfile
> **Label:** ProcessProfile
> **Definition:** Entity describing the type, nature, and other relevant information about a process related to a resource.
> **Modification:** Use of properties identified below.

> **URI:** schema:QuantitativeValue
> **Label:** QuantitativeValue
> **Definition:** Point value for cohort characteristics and other purposes.
> **Modification:** Use of properties identified below.

**New Classes:**
> **URI:** qdata:DataProfile
> **Label:** DataProfile
> **Definition:** Entity describing the attributes of the data set, its subjects and their values.

> **URI:** qdata:DataSetProfile
> **Label:** DataSetProfile
> **Definition:** Particular characteristics or properties of a data set and its records. 

> **URI:** qdata:DataSetTimeFrame
> **Label:** DataSetTimeFrame
> **Definition:** Time frame including earnings and employment start and end dates of the data set.

> **URI:** qdata:SubjectProfile
> **Label:** SubjectProfile
> **Definition:** Categories of subject in the data set.

**Properties**
---
**Existing Properties Borrowed As-Is:**

> **URI:** ceterms:earnings
> **Label:** earnings
> **Definition:** Entity describing aggregate credential holder earnings data.
> **Domain:** Credential
> **Range:** ceterms:EarningsProfile

> **URI:** ceterms:employmentOutcome
> **Label:** employmentOutcome
> **Definition:** Entity describing aggregate data on jobs obtained with the credential by occupation and industry for a given period of time in a specific region.
> **Domain:** Credential
> **Range:** ceterms:EmploymentOutcomeProfile

> **URI:** schema:maxValue
> **Label:** maxValue
> **Definition:** Upper value of some characteristic or property.
> **Domain:** MonetaryAmount
> **Range:** xsd:float

> **URI:** schema:minValue
> **Label:** minValue
> **Definition:** Lower value of some characteristic or property.
> **Domain:** MonetaryAmount
> **Range:** xsd:float

> **URI:** schema:value
> **Label:** value
> **Definition:** Value of a monetary amount or a quantitative value.
> **Domain:** MonetaryAmount, QuantitativeValue
> **Range:** xsd:float

> **URI:** ceterms:jurisdictionException
> **Label:** jurisdictionException
> **Definition:** Geographic or political region in which the credential is not formally recognized or an organization has no authority to act .
> **Domain:** Jurisdiction Profile
> **Range:** ceterms:Place

> **URI:** ceterms:mainJurisdiction
> **Label:** mainJurisdiction
> **Definition:** Primary geographic or political region in which the credential is recognized as applicable or in which an organization has recognized authority to act.
> **Domain:** Jurisdiction Profile
> **Range:** ceterms:Place

> **URI:** ceterms:geoURI
> **Label:** geoURI
> **Definition:** Referenced entity that describes the longitude, latitude and other location details of a place.
> **Domain:** Place
> **Range:** xsd:anyURI

> **URI:** ceterms:latitude
> **Label:** latitude
> **Definition:** The longitude of a location.
> **Domain:** Place
> **Range:** xsd:float

> **URI:** ceterms:longitude
> **Label:** longitude
> **Definition:** The longitude of a location.
> **Domain:** Place
> **Range:** xsd:float

> **URI:** schema:unitText
> **Label:** unitText
> **Definition:** Word or phrase indicating the unit of measure. 
> **Domain:** QuantitativeValue
> **Range:** skos:Concept

> **URI:** ceterms:externalInputType
> **Label:** externalInputType
> **Definition:** Types of external stakeholders that provide input to an entity's processes or resources; select from an existing enumeration of such types.
> **Domain:** ProcessProfile
**Range:** skos:Concept

> **URI:** ceterms:processFrequency
> **Label:** processFrequency
> **Definition:** Interval of process occurrence.
> **Domain:** ProcessProfile
**Range:** rdf:langString

> **URI:** ceterms:processMethod
> **Label:** processMethod
> **Definition:** Webpage or online document that describes the process methods.
> **Domain:** ProcessProfile
**Range:** xsd:anyURI

> **URI:** ceterms:processMethodDescription
> **Label:** processMethodDescription
> **Definition:** Textual description of the process methods.
> **Domain:** ProcessProfile
**Range:** rdf:langString

> **URI:** ceterms:verificationMethodDescription
> **Label:** verificationMethodDescription
> **Definition:** Textual description of the methods used to evaluate an assessment, learning opportunity, process or verification service for validity or reliability; e.g., data quality audit.
> **Domain:** ProcessProfile
**Range:** rdf:langString

**Modifications to Existing/Borrowed Properties:**

> **URI:** ceterms:administrationProcess
> **Label:** administrationProcess
> **Definition:** Entity describing the process by which a resource, or aspects of it, are administered.
> **Domain:** DataProfile, SubjectProfile
> **Range:** ceterms:ProcessProfile
> **Modification:** Added domains

> **URI:** ceterms:description
> **Label:** description
> **Definition:** Statement, characterization or account of the entity.
> **Domain:** DataProfile, DataSetProfile, DataSetTimeFrame, EarningsProfile, EmploymentOutcomeProfile, Jurisdiction Profile, ProcessProfile, QuantitativeValue, SubjectProfile
> **Range:** rdf:langString
> **Modification:** Added domains

> **URI:** ceterms:jurisdiction
> **Label:** jurisdiction
> **Definition:** Geographic or political region in which the credential is formally applicable, an organization has authority to act, or in which holders of the credential are employed.
> **Domain:** DataSetProfile
> **Range:** ceterms:JurisdictionProfile
> **Modification:** Added domain

> **URI:** ceterms:name
> **Label:** name
> **Definition:** Name or title of the resource.
> **Domain:** DataSetProfile, DataSetTimeFrame, EarningsProfile, EmploymentOutcomeProfile, Place, SubjectProfile
> **Range:** rdf:langString
> **Modification:** Added domains

> **URI:** ceterms:source
> **Label:** source
> **Definition:** Authoritative source of an entity's information.
> **Domain:** DataSetProfile
> **Range:** xsd:anyURI
> **Modification:** Added domain

> **URI:** ceterms:endDate
> **Label:** endDate
> **Definition:** Date some event or activity ends.
> **Domain:** DataSetTimeFrame
> **Range:** xsd:date
> **Modification:** Added domain

> **URI:** ceterms:startDate
> **Label:** startDate
> **Definition:** Date the validity or usefulness of the information in this resource begins.
> **Domain:** DataSetTimeFrame
> **Range:** xsd:date
> **Modification:** Added domain

> **URI:** schema:currency
> **Label:** currency
> **Definition:** Currency abbreviation (e.g., USD).
> **Domain:** MonetaryAmount, MonetaryAmountDistribution
> **Range:** xsd:string
> **Modification:** Simplified definition

> **URI:** ceterms:instructionalProgramType
> **Label:** instructionalProgramType
> **Definition:** Type of instructional program; select from an existing enumeration of such types.
> **Domain:** DataSetProfile
**Range:** skos:Concept
> **Modification:** Added domain

> **URI:** ceterms:processingAgent
> **Label:** processAgent
> **Definition:** Organization or person performing the process.
> **Domain:** ProcessProfile
**Range:** ceterms:Agent
> **Modification:** Change range

**New Properties:**

> **URI:** qdata:adjustment
> **Label:** adjustment
> **Definition:** Describes whether and how the provided earnings have been adjusted for factors such as inflation, participant demographics and economic conditions.
> **Domain:** DataProfile
**Range:** rdf:langString

> **URI:** qdata:administrativeRecordType
> **Label:** administrativeRecordType
> **Definition:** Type of administrative record used; e.g. W2, 1099, and Unemployment Insurance Wage Record.
> **Domain:** DataProfile, ProcessProfile
**Range:** skos:Concept
**Target Concept Scheme:** qdata:AdministrativeRecordType

> **URI:** qdata:earningsAmount
> **Label:** earningsAmount
> **Definition:** Reference to an entity describing aggregate earnings.
> **Domain:** DataProfile
**Range:** schema:MonetaryAmount

> **URI:** qdata:earningsDefinition
> **Label:** earningsDefinition
> **Definition:** Definition of "earnings" used by the data source in the context of the reporting group.
> **Domain:** DataProfile
**Range:** rdf:langString

> **URI:** qdata:earningsDistribution
> **Label:** earningsDistribution
> **Definition:** Reference to an entity describing median earnings as well as earnings at various percentiles.
> **Domain:** DataProfile
**Range:** schema:MonetaryAmountDistribution

> **URI:** qdata:earningsThreshold
> **Label:** earningsThreshold
> **Definition:** Statement of any work time or earnings threshold used in determining whether a sufficient level of workforce attachment has been achieved to qualify as employed during the time period of the data set.
> **Domain:** DataProfile
**Range:** rdf:langString

> **URI:** qdata:employmentDefinition
> **Label:** employmentDefinition
> **Definition:** Statement of criteria used to determine whether sufficient levels of work time and/or earnings have been met to be considered employed during the earning time period.
> **Domain:** DataProfile
**Range:** rdf:langString

> **URI:** qdata:incomeDetermination
> **Label:** incomeDetermination
> **Definition:** Mechanism by which income is determined; i.e., actual or annualized earnings.
> **Domain:** DataProfile
**Range:** skos:Concept
**Target Concept Scheme:** qdata:IncomeDeterminationMethod

> **URI:** qdata:subjectExclusion
> **Label:** subjectExclusion
> **Definition:** Category of subjects excluded from the data.
> **Domain:** DataProfile
> **Range:** skos:Concept

> **URI:** qdata:subjectInclusion
> **Label:** subjectInclusion
> **Definition:** Category of subjects included in the data.
> **Domain:** DataProfile
> **Range:** skos:Concept
**Target Concept Scheme:** qdata:SubjectCategory

> **URI:** qdata:workTimeThreshold
> **Label:** workTimeThreshold
> **Definition:** Statement of earnings thresholds used in determining whether a sufficient level of workforce attachment has been achieved to qualify as employed during the chosen employment and earnings time period.
> **Domain:** DataProfile
**Range:** rdf:langString

> **URI:** qdata:dataProvider
> **Label:** dataProvider
> **Definition:** Credentialing organization or a third party providing the data.
> **Domain:** DataSetProfile
**Range:** ceterms:Agent

> **URI:** qdata:dataSetTimePeriod
> **Label:** dataSetTimePeriod
> **Definition:** Short- and long-term post-award reporting intervals including start and end dates.
> **Domain:** DataSetProfile
**Range:** qdata:DateSetTimeFrame

> **URI:** qdata:dataSuppressionPolicy
> **Label:** dataSuppressionPolicy
> **Definition:** Description of a data suppression policy for earnings and employment data when cell size is below a certain threshold to ensure an individual's privacy and security.
> **Domain:** DataSetProfile
**Range:** rdf:langString

> **URI:** qdata:distributionFile
> **Label:** distributionFile
> **Definition:** Downloadable form of this dataset, at a specific location, in a specific format.
> **Domain:** DataSetProfile
**Range:** xsd:anyURI

> **URI:** qdata:relevantDataSetFor
> **Label:** relevantDataSetFor
> **Definition:** Data set for the entity being referenced.
> **Domain:** DataSetProfile
**Range:** ceterms:EarningsProfile, ceterms:EmploymentOutcomeProfile

> **URI:** qdata:subjectIdentification
> **Label:** subjectIdentification
> **Definition:** Identification of data point(s) in the data set that describe personal subject attribute(s) used to uniquely identify a subject for the purpose of matching records and an indication of level of confidence in the accuracy of the match.
> **Domain:** DataSetProfile
**Range:** rdf:langString

> **URI:** qdata:dataAttributes
> **Label:** dataAttributes
> **Definition:** Attributes of the data set.
> **Domain:** DataSetTimeFrame
**Range:** qdata:DataProfile

> **URI:** qdata:dataAvailable
> **Label:** dataAvailable
> **Definition:** Number of credential holders in the reporting group for which employment and earnings data is included in the data set.
> **Domain:** DataSetTimeFrame
**Range:** schema:QuantitativeValue

> **URI:** qdata:dataNotAvailable
> **Label:** dataNotAvailable
> **Definition:** Number of credential holders in the reporting group for which employment and earnings data has not been included in the data set.
> **Domain:** DataSetTimeFrame
**Range:** schema:QuantitativeValue

> **URI:** qdata:dataSourceCoverage
> **Label:** dataSourceCoverage
> **Definition:** Category of geographic coverage of the subjects.
> **Domain:** DataSetTimeFrame
> **Range:** skos:Concept
> **Target Concept Scheme:** qdata:DataSourceCoverage

> **URI:** qdata:demographicEarningsRate
> **Label:** demographicEarningsRate
> **Definition:** Earnings rate for a demographic category.
> **Domain:** DataSetTimeFrame
**Range:** schema:QuantitativeValue

> **URI:** qdata:demographicEmploymentRate
> **Label:** demographicEmploymentRate
> **Definition:** Employment rate for a demographic category.
> **Domain:** DataSetTimeFrame
**Range:** schema:QuantitativeValue

> **URI:** qdata:employmentRate
> **Label:** employmentRate
> **Definition:** Rate computed by dividing the number of holders or subjects meeting the data set's criteria of employment (meetEmploymentCriteria) by the number of holders or subjects for which data was available (dataAvailable).
> **Domain:** DataSetTimeFrame
**Range:** schema:QuantitativeValue

> **URI:** qdata:holdersInSet
> **Label:** holdersInSet
> **Definition:** Number of credential holders in the final data collection and reporting.
> **Domain:** DataSetTimeFrame
**Range:** schema:QuantitativeValue

> **URI:** qdata:industryRate
> **Label:** industryRate
> **Definition:** Employment rate for an industry category.
> **Domain:** DataSetTimeFrame
**Range:** schema:QuantitativeValue

> **URI:** qdata:insufficientEmploymentCriteria
> **Label:** insufficientEmploymentCriteria
> **Definition:** Number of holders that do not meet the prescribed employment threshold in terms of earnings or time engaged in work as defined for the data set (employmentDefinition).
> **Domain:** DataSetTimeFrame
**Range:** schema:QuantitativeValue

> **URI:** qdata:nonCompleters
> **Label:** nonCompleters
> **Definition:** Non-holders who departed or are likely to depart higher education prematurely.
> **Domain:** DataSetTimeFrame
**Range:** schema:QuantitativeValue

> **URI:** qdata:nonHoldersInSet
> **Label:** nonHoldersInSet
> **Definition:** Non-holder subject actively pursuing the credential through a program or assessment.
> **Domain:** DataSetTimeFrame
**Range:** schema:QuantitativeValue

> **URI:** qdata:occupationRate
> **Label:** occupationRate
> **Definition:** Employment rate for an occupation category.
> **Domain:** DataSetTimeFrame
**Range:** schema:QuantitativeValue

> **URI:** qdata:relatedEmployment
> **Label:** relatedEmployment
> **Definition:** Number of people employed in the area of work (e.g., industry, occupation) in which the credential provided preparation.
> **Domain:** DataSetTimeFrame
**Range:** schema:QuantitativeValue

> **URI:** qdata:subjectsInSet
> **Label:** subjectsInSet
> **Definition:** Total credential holders and non-holders in the final data collection and reporting.
> **Domain:** DataSetTimeFrame
**Range:** schema:QuantitativeValue

> **URI:** qdata:sufficientEmploymentCriteria
> **Label:** sufficientEmploymentCriteria
> **Definition:** Number of holders that meet the prescribed employment threshold in terms of earnings or time engaged in work as defined for the data set (employmentDefinition).
> **Domain:** DataSetTimeFrame
**Range:** schema:QuantitativeValue

> **URI:** qdata:unrelatedEmployment
> **Label:** unrelatedEmployment
> **Definition:** Number of people employed outside the area of work (e.g., industry, occupation) in which the credential provided preparation.
> **Domain:** DataSetTimeFrame
**Range:** schema:QuantitativeValue

> **URI:** qdata:relevantDataSet
> **Label:** relevantDataSet
> **Definition:** Data Set on which earnings or employment data is based.
> **Domain:** EarningsProfile, EmploymentOutcomeProfile
**Range:** schema:QuantitativeValue

> **URI:** qdata:median
> **Label:** median
> **Definition:** Median salary value.
> **Domain:** MonetaryAmountDistribution
**Range:** xsd:float

> **URI:** qdata:percentile10
> **Label:** percentile10
> **Definition:** 10th percentile salary value.
> **Domain:** MonetaryAmountDistribution
**Range:** xsd:float

> **URI:** qdata:percentile25
> **Label:** percentile25
> **Definition:** 25th percentile salary value.
> **Domain:** MonetaryAmountDistribution
**Range:** xsd:float

> **URI:** qdata:percentile75
> **Label:** percentile75
> **Definition:** 75th percentile salary value.
> **Domain:** MonetaryAmountDistribution
**Range:** xsd:float

> **URI:** qdata:percentile90
> **Label:** percentile90
> **Definition:** 90th percentile salary value.
> **Domain:** MonetaryAmountDistribution
**Range:** xsd:float

> **URI:** qdata:dataCollectionMethod
> **Label:** dataCollectionMethod
> **Definition:** Category identifying the method by which the data was collected.
> **Domain:** ProcessProfile
> **Range:** skos:Concept
> **Target Concept Scheme:** qData:CollectionMethod

> **URI:** qdata:percentage
> **Label:** percentage
> **Definition:** Quotient of two values of the data set.
> **Domain:** QuantitativeValue
**Range:** xsd:float

> **URI:** qdata:subjectCategory
> **Label:** subjectCategory
> **Definition:** Categories of subjects included and excluded from the data set.
> **Domain:** SubjectProfile
**Range:** skos:Concept
> **Target Concept Scheme:** qdata:SubjectCategory

> **URI:** qdata:subjectValue
> **Label:** subjectValue
> **Definition:** Quantitative values and percentages for a subject category in the data set.
> **Domain:** SubjectProfile
**Range:** schema:QuantitativeValue

**Concept Schemes**
---
**Modifications to Existing/Borrowed Concept Schemes:**

_None identified_

**New Concept Schemes:**

> **URI:** qdata:SubjectCategory
> **Label:** Subject Category
> **Definition:** Categories of subjects for employment and earnings data.
> **Concept Prefix:** subjectCategory
> **Used By:** qdata:subjectExclusion, qdata:subjectInclusion

> **URI:** qdata:DataSourceCoverage
> **Label:** Data Source Coverage
> **Definition:** Categories of geographic coverage.
> **Concept Prefix:** sourceCoverage
> **Used By:** qdata:dataSourceCoverage

> **URI:** qdata:CollectionMethod
> **Label:** Collection Method
> **Definition:** Categories of methods for collecting data.
> **Concept Prefix:** collectionMethod
> **Used By:** qdata:dataCollectionMethod

> **URI:** qdata:AdministrativeRecordType
> **Label:** Administrative Record Type
> **Definition:** Categories of administrative records.
> **Concept Prefix:** adminRecord
> **Used By:** qdata:administrativeRecordType

> **URI:** qdata:IncomeDeterminationMethod
> **Label:** Income Determination Method
> **Definition:** Methods for determining the actual or anticipated annual earnings of the subjects in the data set.
> **Concept Prefix:** @@@
> **Used By:** qdata:incomeDetermination

**Concepts**
---
**Modifications to Existing/Borrowed Concepts:**

_None identified_

**New Concepts:**

> **URI:** subjectCategory:AssessmentCompleters
> **Label:** Assessment Completers
> **Definition:** Assessment Completers.
> **In Scheme:** qdata:SubjectCategory

> **URI:** subjectCategory:Enrollees
> **Label:** Enrollees
> **Definition:** Enrollees.
> **In Scheme:** qdata:SubjectCategory

> **URI:** subjectCategory:Graduates
> **Label:** Graduates
> **Definition:** Graduates.
> **In Scheme:** qdata:SubjectCategory

> **URI:** subjectCategory:FinancialAidRecipients
> **Label:** Financial Aid Recipients
> **Definition:** Financial Aid Recipients.
> **In Scheme:** qdata:SubjectCategory

> **URI:** subjectCategory:InFurtherEducation
> **Label:** In Further Education
> **Definition:** In Further Education.
> **In Scheme:** qdata:SubjectCategory

> **URI:** subjectCategory:CredentialHolders
> **Label:** Credential Holders
> **Definition:** Credential Holders.
> **In Scheme:** qdata:SubjectCategory

> **URI:** subjectCategory:CredentialSeekers
> **Label:** Credential Seekers
> **Definition:** Credential Seekers.
> **In Scheme:** qdata:SubjectCategory

> **URI:** subjectCategory:HigherLevelCredential
> **Label:** Higher Level Credential
> **Definition:** Higher Level Credential.
> **In Scheme:** qdata:SubjectCategory

> **URI:** subjectCategory:InsufficientData
> **Label:** Insufficient Data
> **Definition:** Insufficient Data.
> **In Scheme:** qdata:SubjectCategory

> **URI:** subjectCategory:PostCredentialEarnings
> **Label:** Post-Credential Earnings
> **Definition:** Post-Credential Earnings.
> **In Scheme:** qdata:SubjectCategory

> **URI:** subjectCategory:PreCredentialEarnings
> **Label:** Pre-Credential Earnings
> **Definition:** Pre-Credential Earnings.
> **In Scheme:** qdata:SubjectCategory

> **URI:** sourceCoverage:Global
> **Label:** Global
> **Definition:** Global.
> **In Scheme:** qdata:DataSourceCoverage

> **URI:** sourceCoverage:UrbanArea
> **Label:** Urban Area
> **Definition:** Urban Area.
> **In Scheme:** qdata:DataSourceCoverage

> **URI:** sourceCoverage:Country
> **Label:** Country
> **Definition:** Country.
> **In Scheme:** qdata:DataSourceCoverage

> **URI:** sourceCoverage:Region
> **Label:** Region
> **Definition:** Region.
> **In Scheme:** qdata:DataSourceCoverage

> **URI:** sourceCoverage:StateOrProvince
> **Label:** State Or Province
> **Definition:** State Or Province.
> **In Scheme:** qdata:DataSourceCoverage

> **URI:** collectionMethod:AdministrativeRecordMatching
> **Label:** Administrative Record Matching
> **Definition:** Administrative Record Matching.
> **In Scheme:** qdata:CollectionMethod

> **URI:** collectionMethod:CredentialHolderReporting
> **Label:** Credential Holder Reporting
> **Definition:** Credential Holder Reporting.
> **In Scheme:** qdata:CollectionMethod

> **URI:** collectionMethod:CredentialHolderSurvey
> **Label:** Credential Holder Survey
> **Definition:** Credential Holder Survey.
> **In Scheme:** qdata:CollectionMethod

> **URI:** collectionMethod:SupplementalMethod
> **Label:** Supplemental Method
> **Definition:** Supplemental Method.
> **In Scheme:** qdata:CollectionMethod

> **URI:** collectionMethod:SupplementalSources
> **Label:** Supplemental Sources
> **Definition:** Supplemental Sources.
> **In Scheme:** qdata:CollectionMethod

> **URI:** adminRecord:TaxW2
> **Label:** United States W-2 Tax Document
> **Definition:** W-2 Tax document used in the United States.
> **In Scheme:** qdata:AdministrativeRecordType

> **URI:** adminRecord:Tax1099
> **Label:** United States 1099 Tax Document
> **Definition:** 1099 Tax document used in the United States.
> **In Scheme:** qdata:AdministrativeRecordType

> **URI:** adminRecord:UnemploymentInsurance
> **Label:** Unemployment Insurance
> **Definition:** Unemployment Insurance.
> **In Scheme:** qdata:AdministrativeRecordType

**Comment by siuc-nate** [comment]
@stuartasutton Some of these properties still need ranges, and not all of them are terribly obvious.  Is there an existing spreadsheet somewhere that lists them?  If not, can you provide ranges for all of the "TBD"s?

Also, we must document some sample data using this schema in order to make sure it makes sense **before** we release it as a schema.  This may mean not having it done in time for the November release cycle, but it will be well worth the quality assurance to not rush it out just to meet a date.

**Comment by siuc-nate** [comment]
Additional changes:

**Remove:**
> **Subject:** ceterms:EmploymentOutcomeProfile
> **Predicate:** vs:term_status
> **Object:** vs:unstable

> **Subject:** ceterms:EarningsProfile
> **Predicate:** vs:term_status
> **Object:** vs:unstable

**Add:**
> **Subject:** ceterms:EmploymentOutcomeProfile
> **Predicate:** vs:term_status
> **Object:** vs:stable

> **Subject:** ceterms:EarningsProfile
> **Predicate:** vs:term_status
> **Object:** vs:stable

**Comment by siuc-nate** [comment]
@stuartasutton I have been using definitions for concepts from https://docs.google.com/spreadsheets/d/1SALLlTh6EsNDvl1gIORboQW1k5-yEiPMEJ2weyTIvHI/edit#gid=1784990949 - however, the following terms are missing definitions:
- subjectCategory:AssessmentCompleters
- subjectCategory:Enrollees
- subjectCategory:Graduates

**Comment by siuc-nate** [comment]
@stuartasutton Additionally, the subject category terms have an inconsistent mix of singular/plural wording in both their labels and definitions.

**Comment by siuc-nate** [comment]
These changes have been made.

**Comment by jkitchensSIUC** [comment]
This is complete; the release  occured on November 29, 2019 https://credreg.net/qdata/release?releaseid=20191129.  This issue is closed.
