### ISSUE TITLE
Indicate that ceterms:Place is equivalent to schema:Place

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#629]
Seems this was overlooked.  It can probably be added to the October release.

**Add:**
> **Subject:** ceterms:Place
> **Predicate:** owl:equivalentClass
> **Object:** schema:Place

**Comment by stuartasutton** [comment]
Nate, I think you mean "owl:equivalentClass", not "owl:equivalentProperty".

**Comment by siuc-nate** [comment]
Oops.  Good catch, I've updated the post.

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton did this get implemented?

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
