### ISSUE TITLE
Property for URL to accredited programs by a QA organization

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/Schema-Development#630]
@stuartasutton 
I noticed on the Navy COOL site, that the links for an accreditation organization go to a page of accredited programs.  Example:
https://www.icacnet.org/membershipprograms/accredited-programs/

Organization doesn't seem t have a specific property for accredited programs.
Should there be a property for a list of programs, or services, etc.

**Comment by siuc-nate** [comment]
Programs, generally speaking, would equate to learning opportunities in our vernacular, unless I'm missing something.

**Comment by cwd-mparsons** [comment]
In this case it would be a page regarding details about programs accredited. 
It is not list of programs (as in accredits). 
It would be similar to availabilityListing - except programs, not locations.

**Comment by siuc-nate** [comment]
Oh, I see. That would indeed be something we don't currently accommodate.

**Comment by jeannekitchens** [comment]
@mparsons-ce @siuc-nate cover this today so it gets resolved.

**Comment by jeannekitchens** [comment]
@siuc-nate please identify if this is an issue. If it is an issue, include the CTDL proposal here.  If it's not an issue, comment here as to why and tag @mparsons-ce

**Comment by jeannekitchens** [comment]
This requires a new property.

**Comment by siuc-nate** [comment]
Archiving this, as it hasn't seen demand in a few years.
