### ISSUE TITLE
Handling of tools as concept schemes or competencies

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#631]
In the navy data, tools are currently (in CASS) atomized as a framework of competencies. @Lomilar did this (correct me if I'm wrong) due to the implied competence with tools when they are applied (which was done in that data by the ceasn:prerequisiteAlignment property) to Maintenance Tasks and Training Tasks (e.g. "this task requires you to be able to use a wrench").

Examining the data for tools, the ceasn:CompetencyText field just has the name of a tool and no other contextualizing information (e.g. "wrench", "hammer", "screwdriver", etc.).

It is therefore my contention that:
- The navy data's tools competency framework should be a concept scheme instead
- The assertion that a task requires a given tool is separate from the assertion that the performer of the task needs to be competent with that tool (even if these two assertions go together in what appears to be all cases)
  - "Completing this task requires a screwdriver" (the data itself) implies "And you have to know how to use a screwdriver", but this is not sufficient reason to call "screwdriver" itself a competency
  - Conceivably there could be a tools framework containing the K/S/As for tools (particularly if a given tool has more than one intended function or usage, such as different attachments for a power tool, or even "put nail in" vs "get nail out", both of which involve different usages a hammer). This framework would reference the tools concept scheme, and this framework's competencies could/would be referenced by Maintenance Tasks and Training Tasks
    - e.g. "Performing this task requires "Competency: K/S/A with a wrench", which in turn references "Concept: Wrench"
    - Perhaps the task references both the concept and the competency? Or is the competency implicit in the reference to the concept (see below)?

That same list of tools could just be a list of concepts in another context:
- A listing of how many of each kind of tool are aboard a ship
- A listing of which tools should go in a toolbox
- A listing of which sailor has which tool in-hand during performance of a task
- etc.

In CTDL, there are some parallels where concepts imply a competency (knowledge/skill/ability) when used in certain ways, but those are not inherent attributes of the concepts themselves:
- [AssessmentMethod](https://credreg.net/ctdl/terms/AssessmentMethod)
  - Example: An assessment with an assessment method of "Performance" implies the K/S/A "And you have to be able to perform the thing being assessed"
- [Delivery](https://credreg.net/ctdl/terms/Delivery)
  - Example: a learning opportunity that is only offered "In Person" implies the Ability "And you have to be able to physically get to the classroom"
- [AudienceLevel](https://credreg.net/ctdl/terms/AudienceLevel)
  - Example: a credential targeted to "Advanced Level" implies the K/S/A "And you must have obtained advanced level K/S/As to pursue this credential"

It is my position that the navy data contains a list of tools as a concept scheme.

Additionally, there may be something worth exploring in the idea of "implied" competencies (where a reference to a concept, by virtue of simply referencing that concept, implies some competency directly related to that concept).

**Comment by Lomilar** [comment]
My argument, which is now further clarified by the introduction of competencyLabel is:

There is a coarse grained competency surrounding the use of a tool that can be derived from the name of the tool. That coarse grained competency outside of any context (as it is in O*NET) encompasses the gambit of uses of that tool. When used in a framework associated with a task, it is specified by the context of the framework and can be treated like any other KSA.

Thus, the "Assembles a computer" competency requires a competency with the label "Phillips Screwdriver".

The context partially defines its use (it isn't being used to dig holes) and the task it is associated with also defines its use. It is defined in the same sense as KSAs, where we know what "Manual Dexterity" means in a task context, and we don't have to define each (task) articulation of a finger.

Of note, this violates the "a competency with only a short label should put that label into competencyText" because I want to refer to or imply the competency called something, without defining it in great detail.

**Comment by stuartasutton** [comment]
Let's freeze this discussion until I can get back to it this evening--in a meeting all day.

Stuart

**Comment by siuc-nate** [comment]
Sure thing.

**Comment by stuartasutton** [comment]
Like most things, there's likely a useful middle ground. I think Nate's analysis is sound, we have the same problems with competency frameworks where a professor, when asked for the learning outcomes for listing in the syllabus of his course, lists the table of contents of the text that he wrote. Of course, one can infer KSAs from that TOC just as one can from the tool "Microsoft Access" but can't do it very usefully without some context. E.g. Esco's "Microsoft Access" entry (see http://data.europa.eu/esco/skill/3d03c40c-1b83-4793-8902-2523f40af59e) leads to job contexts such as "database developer" to which we see attached specific skills and competencies: 

<img width="486" alt="Screenshot 2019-10-26 13 43 45" src="https://user-images.githubusercontent.com/2939046/67625745-d8a1ab00-f7f6-11e9-869b-999f594fc051.png">

So such KSA are perceivable as KSAs only at the intersection of a tool and the uses to which it is put in a particular context. I think that Nate's correct that "Microsoft Access" does not itself portray any particular KSA except as a broad array of latent potential. In that sense, general lists of tools and the TOCs of my professor's text are best modeled as concept schemes that can be referenced by KSA-defining context. 

We are hatching a way to identify context through work role as defined by through sets of KSAs. It's no stretch for me to see enabling tools (as concept) in that work role context.

**Comment by siuc-nate** [comment]
Additional thoughts:
- We have documented the EMSI skills as skos:Concepts because they did not identify any particular competencies
- We are considering documenting ESCO as skos:Concepts for the same reason, but have not decided yet
- We documented ONET Technology Skills as ceasn:Competencies, making them the outlier - I think they should be skos:Concepts because they fit the definition for a concept, even if they are used to help describe competencies.

We will have to come to some kind of (policy?) decision around this for future cases with large lists of terms with no apparent "action" tied to them (ie "shoe laces" is a concept but "can tie shoes" is a competency).

**Comment by stuartasutton** [comment]
What these lack is an active, measurable verb...

**Comment by jeannekitchens** [comment]
Tools are not competencies.  They can be the object or subject of a competency.  If you're writing competencies and need to describe the skills to operate/use a tool, you'd want to be able to select skills and tools from a concept scheme.
