### ISSUE TITLE
Add ceterms:industryType and ceterms:occupationType to ceasn:CompetencyFramework

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#633]
As the Credential Engine Competency Framework repository grows, it will become increasingly difficult to find frameworks in the registry with any display ordering based on framework name or simple text search alone. The ASN-D2L and IMS Global Case registries have the (current) advantage with their corpora being focused primarily in K-12 where jurisdiction plays a dominant role (e.g., math in **Kentucky**). So for ASN-D2L and IMS Global Case registries, colocating by jurisdiction in their context works pretty well (until they decide to expand the domains they cover). 

The Credential Engine's repository scope is much, much broader in domains of applicability and potentially much larger in scale meaning that we are going to have to do more in the future to increase precision so users aren't overcome by recall at the top of their journey to locate or discover applicable frameworks. One way we can do that is by making it possible in terms of the data to colocate on industry and occupation (and perhaps even jurisdiction (see [asn:jurisdiction](http://purl.org/ASN/schema/core/jurisdiction)).

Pushback that credentials to which many frameworks are used identify industry and occupation but having that data in credential records is not guaranteed and in general use in the wild would likely be overlooked. Also, some might say that branding a framework with an occupation code might deter people from using the framework in other, quite appropriate contexts. Perhaps this might happen a bit, but it's a small price to pay for increased balance of recall and precision for everyone else with the common sense to use a framework where ever they see fit.

Stuart

**Comment by siuc-nate** [comment]
Proposal:

**Add:**
> **Subject:** ceterms:industryType
> **Predicate:** schema:domainIncludes
> **Object:** ceasn:CompetencyFramework

> **Subject:** ceterms:occupationType
> **Predicate:** schema:domainIncludes
> **Object:** ceasn:CompetencyFramework

**Comment by stuartasutton** [comment]
Nate, it occurs to me, this should actually be Object: ceasn:Competency not CompetencyFramework.

**Comment by siuc-nate** [comment]
I think Industry/Occupation are high level associations that make more sense at the framework level - you don't want to require the publisher to have to tag every single competency with the same industry or set of industries, for example, if the whole framework applies.

**Comment by stuartasutton** [comment]
OK

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL-ASN and noted in the history tracking.
