### ISSUE TITLE
Description Set data and published URIs

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#634]
I have discovered an issue with the data being published to the Registry compared to the data that returns from Description Set queries.  It's not (exactly) a semantic issue, but it is a practical one.

In essence, the data we publish to the Registry contains URI references that use the `graph` formatted URIs as values for properties like `ceterms:ownedBy` and `ceterms:targetAssessment`

```
"ceterms:ownedBy": [
  "https://credentialengineregistry.org/graph/ce-abcdefg"
]
```

However, data that comes out of the Search API is at the `resources` level, so there are no `graph` URIs in it.  What this means is that any developer using the Description Set queries will not be able to connect data in the result set (which references `graph` URIs) to data in the Description Set (which is all at the `resources` level), at least not out of the box.  

It's possible to do some string manipulation (e.g. convert `graph` URIs to `resources` URIs while crawling references) that solves this, but that's probably not a solution we want to force every developer to implement.

This issue didn't arise with Competency Framework data because Competency Framework data references Competencies at the `resources` level, by design.  So the data in the result set matched up just fine with the data in the related items, at least for the first hop (I did have to do the aforementioned string manipulation to make subsequent hops work for the Competency Framework search in the finder, but I didn't think much of it at the time as I was too focused on getting the system to work).

So, there are some potential solutions I can see:
1. Employ string manipulation to make the connections
  - Pros: 
    - This is guaranteed to work, even if a third party publishes data using graph URIs (which is a very real possibility)
    - Could be encapsulated into a function that handles URI comparison by checking both flavors of a URI (in essence looking for CTID matches since that's the unique part)
  - Cons: 
    - It's extra work that every developer will have to implement for every consuming system that uses Description Set data
2. Update all published data (and future publishing) to use `resources` URIs in all references
  - Pros:
    - It makes the connections possible out of the box
  - Cons:
    - It means we have to figure out how to deal with it when a third party publishes graph URIs
    - There probably are/will be cases where it is appropriate/necessary to publish `graph` URIs and we don't want to effectively disable that functionality
3. Update the Description Set queries to return data at the `graph` level (where relevant)
  - Pros:
    - Returning data at this level should enable connections out of the box
  - Cons:
    - Extra traversal/calculation/code required to get from the graph to the relevant node in the graph (probably safe to assume it's always the first node?)
    - May impact the speed/performance of the queries since the normal search results are also at the `resources` level, so I'm not sure the graph is even indexed at all
    - Would need extra work on the part of the developer to know to go first to the Framework's graph and then look for the relevant `resources` URI inside it
4. Some other means of mapping `graph` URIs to `resources` URIs (to save developers the effort of string manipulation)
  - Pros:
    - Depending on the design, this may be straightforward to use
    - Hopefully would be some additional data injected into the result set negating the need to modify the published data or the queries
  - Cons:
    - Depending on the design, it may be extra work for the developer of the consuming system

I will look into that last one.  Search API requests are all done through CE's server, so it may be possible to crawl the result set, extract the URIs, construct some kind of mapping, and add that in as another property of the same container that currently has the RelatedItems array.  Something like (thinking out loud here):

```
{
  "data": [{...}, {...}, {...}] //An array containing the search results,
  "valid": true,
  "status": "okay",
  "extra": {
    "RelatedItems": [{...}, {...}, {...}, {...}, {...}], //All of the related stuff
    "URIMap": {
      { "reference": "https://.../resources/ce-abcdef", "related": "https://.../graph/ce-abcdef" },
      { "reference": "https://.../resources/ce-ghijkl", "related": "https://.../graph/ce-ghijkl" },
      ...
    }
  }
}
```
Then nodes in the URI map basically get used like any other node in the process of hopping from your starting point to your destination.  However, using this might actually be _more_ complex than string manipulation...hm.

There may be other uses for such injected data based on crawling the result set though, namely to precalculate the inbound references (stuff in the RelatedItems that points to stuff in the search results) but that's beyond the scope of this issue.

**Comment by Lomilar** [comment]
Links to a statement set (@graph), semantically, only make sense when the intent is to link to a contextual group of data.

ceterms:ownedBy and ceterms:targetAssessment -- these referring to graphs is likely a mistake, but there are definitely situations where it would make more sense to refer to a group, such as something like something:foundIn or in an evidentiary chain that justifies a decision that has been made. (we considered the things in this graph but not anything else)

So, a broad solution doesn't seem like it would be appropriate in the long term.

**Comment by science** [comment]
Question @Lomilar @stuartasutton (I already asked @siuc-nate): 

What if graph CTIDs were not the same as resource CTIDs? It seems like if we didn't use the same CTID for both entities, then this problem would kind of be eliminated? This is maybe a baby+bathwater solution..

But, it seems to me, from a semantic data architecture view, graphs are not the same as resources, and therefore re-using CTIDs for both is problematic? I could imagine API services to convert graphs to resources, and vice versa, but at the data layer, these would be distinct CTIDs. Example:

/api/query/graph-to-resource/[ctid123]
=> [list of resource CTIDs and metadata, that are contained within a graph]
/api/query/resource-to-graph/[ctidABC]
=> [list of all graphs and metadata, where resource is contained within]

If we do this, mistakes such as what @Lomilar mentions wouldn't be possible, b/c the CTIDs would be distinct in all cases? 

More generally I'm making an argument that UUIDs (as URNs) should (never?!) be used to describe more than one data entity.

Thoughts?

**Comment by Lomilar** [comment]
Hey, it's another version of the same issue we're having on the CaSS side.

If the CTID is a unique identifier that refers to one thing, it should refer to either a graph or a resource. In the JSON-LD world, the @id is the identifier that only refers to one result on the web, so having /graph/<ctid> different from /resource/<ctid> is fine.

So if we want the CTID to be the unique identifier, we need to probably enforce it, that way if someone pulls down the graph and the resource and puts them in the same cache/database/table, it doesn't behave strangely.

**Comment by siuc-nate** [comment]
I disagree. I don't think it solves anything to give the graph and the resource different CTIDs, and it means you won't be able to figure out one URI based on the other, which is useful in a number of ways.

The problem we have here boils down to "data in the search results references data that does not exist in the related items".  We would have this problem regardless of whether the two types of URI had the same CTID or not.

The only reason it makes it as far as the developer's API response is because the underlying Neo4J database "cheats" by linking the nodes together in its own way that isn't dependent on the URIs matching up.  That's why the description set query will return the data despite the URIs not matching.  In testing with the triples via Neptune, which _are_ URI-dependent, they got the same issue - but they got it at the database level, before the developer would even know anything is wrong.

So, I go back to the three proposals I outlined in my first post, along with sort of a variant of the third one:  When a graph is referenced, return the resources within it along with a generated `@graph` object whose value is an array of URIs that are the `/resources/` URIs of the objects that were in the original, published graph.  This would avoid the possibility of returning both the resources and a graph object that had the same resources inside of it.

In other words, you might get a result response that looks like this:

```
{
  "data": [
    {
      "@id": "https://.../resources/ce-abc123",
      "@type": "ceterms:Certificate",
      "ceterms:ownedBy": [
        "https://.../graph/ce-def456"
      ],
      "ceterms:offeredBy": [
        "https://.../resources/ce-def456"
      ]
    },
    {...},
    {...}
  ],
  "valid": true,
  "status": "okay",
  "extra": {
    "TotalResults": 100,
    "RelatedItems": [
      {
        "@id": "https://.../graph/ce-def456",
        "@type": "@graph",
        "@graph": [
          "https://.../resources/ce-def456",
          "_:blah"
        ]
      },
      {
        "@id": "https://.../resources/ce-def456",
        "@type": "ceterms:CredentialOrganization",
        "ceterms:accreditedBy": [
          "_:blah"
        ]
      },
      {
        "@id": "_:blah",
        "@type": "ceterms:QACredentialOrganization"
      },
      {...},
      {...},
      {...}
    ]
  }
}
```

Alternatively: Just return whatever is **actually** referenced by the data instead of arbitrarily returning either the `/graph/` or the `/resources/` object - which is probably the best solution in the long term.

**Comment by cwd-mparsons** [comment]
One of the issues Nate raised with having different CTIDs for the graph and resource was to 'know' what the related CTID is.
Would using some sort of a qualifier for the main resource for a graph be a solution? The CTIDs would still be unique. The downside is that the pattern for a CTID would then not be consistent.

For a graph CTID:
ce-9fab4187-d8e7-11e9-8250-782bcb5df6ac
The top level resource could be assumed to be one of or variation  of: 
-ce-r-9fab4187-d8e7-11e9-8250-782bcb5df6ac
-cer-9fab4187-d8e7-11e9-8250-782bcb5df6ac
-ce-9fab4187-d8e7-11e9-8250-782bcb5df6ac_r
-etc.

**Comment by siuc-nate** [comment]
I wouldn't go changing around the way CTIDs and URIs work, especially at this stage - we've been very deliberate in our documentation and presentations about the CTID being the same across URI types.  It doesn't solve this issue and I don't see how it wouldn't just create more problems.

**Comment by cwd-mparsons** [comment]
A related question is whether the API should 'normalize' the URIs. 
For example, the API could check for and change any /**graph**/ URIs to /**resources**/.
Would it make sense to implement this check?

**Comment by stuartasutton** [comment]
I am in the middle of meeting and may be misunderstanding. For a graph made up of 3 subgraphs, the number of UNIQUE CTID's should be 4.

**Comment by siuc-nate** [comment]
@cwd-mparsons No, we should stick to the URIs the publishers choose to use.  The description set should return what gets referenced.

@stuartasutton I believe you are missing some of the context of the conversation.  To change the way the URIs work at this stage would be an enormously breaking change and would not solve or help anything.

**Comment by siuc-nate** [comment]
To reiterate: this whole issue is due to the way Neo4J works bypassing the URIs entirely.  If/when we switch from Neo4J to Neptune, the default behavior should be to return whatever was referenced and this issue _should_ disappear.

**Comment by stuartasutton** [comment]
Thanks, Nate. The issue of graph CTIDs (if such beats are needed) as distinct from any subgraph is worth asserting.

**Comment by cwd-mparsons** [comment]
>No, we should stick to the URIs the publishers choose to use. The description set should return what gets referenced.

@siuc-nate 
What if the publisher arbitrarily chose the /graph/ URI without any particular rational?
For example, I checked and saw that NOCTI has been publishing with /graph.

The documentation for the Assistant states to just provide a CTID for a reference and let the API format the URI appropriately. Then if a publisher has a good reason for providing a /graph URI, we could allow it to pass through. 
Are you stating that ultimately the registry search and consumers should be able to handle either?
In which case we would check with partners that are providing graph URIs and provide the necessary guidance.

**Comment by siuc-nate** [comment]
Fair point. If all they provide is the CTID and our system is making the decision, that's one thing. I'm fine with us going with either/or there, but we shouldn't override a deliberate decision if we receive a full URI.

**Comment by philbarker** [comment]
I want to weigh in on just this narrow part of a [point made](#issuecomment-557224177) by @siuc-nate that giving the graph and the resource different CTIDs
> means you won't be able to figure out one URI based on the other, which is useful in a number of ways.

There is standard solution to that:
- Given the resource's CTID URI to resolve, a system should return a HTTP 303 "See other" redirect that yields the Graph describing the resource.
- The graph describing the resource should have a statement saying that it is `about` the resource (identified by its resource CTID URI). 

Another standard pattern is for the Resource URI to be the graph URI with #Resource appended, which is functionally similar.

No comment on whether that's a worthwhile change to make, I'm not sure what the 'worth' or 'while' would be.

**Comment by siuc-nate** [comment]
Thanks for the insight, Phil. It's always good to have a sense of how other systems have solved this kind of problem.  However, given we're over a year into having other organizations use our stuff, and our documentation emphasizes the sameness of the CTID across the types of URIs, I don't think it would be good to change the strategy as far as those go.

To your points about appending additional data to help the entities point at one another, that is something we should probably explore.  I think one of the problems we wrestled with early in the design phase of the `@graph` mechanism was trying to figure out which properties could or couldn't exist at the same layer as the `@graph` property itself and still be JSON-LD compliant.  For example, I think we had tried/wanted to try adding the CTID at that layer, but it didn't work for reasons I can't recall immediately.  

Still, having a property at the same layer as `@graph` that explicitly points at the "main" resource in the graph (e.g. the credential or the competency framework) would be preferable in the long run.

**Comment by siuc-nate** [comment]
We had previously discussed this one in various meetings with the Learning Tapestry team - the overall conclusion is that it's best to reference the `/resources/` URI whenever possible, and only use `/graph/` when you absolutely need to.
