### ISSUE TITLE
Consider changing the range of ceterms:price from xsd:integer to xsd:decimal

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#635]
This would enable more fine-grained descriptions of prices.

**Comment by stuartasutton** [comment]
I've no objections other than affect on existing data.

**Comment by cwd-mparsons** [comment]
Could the type just be xsd:decimal?
http://books.xmlschemata.org/relaxng/ch19-77057.html

It seems that float includes scientific notation, and so on.  
http://books.xmlschemata.org/relaxng/ch19-77095.html

I don't think that we should be trying to handle wide ranges for properties as straightforward as a price.

**Comment by siuc-nate** [comment]
I don't know enough about how numbers like that are handled to really know the difference or which would be best for us.  As far as I know, JSON doesn't distinguish between different kinds of numbers so it really only matters for consuming systems.

Decimal sounds fine; I suggested float because we use that everywhere else that we have a non-integer number.  It might be worth reviewing other xsd:float ranges to see if they are correctly modeled.

**Comment by stuartasutton** [comment]
I've no expertise in how systems treat the distinction.

http://net-informations.com/q/faq/float.html

**Comment by siuc-nate** [comment]
Proposal:

**Remove:**
> **Subject:** ceterms:price
> **Predicate:** schema:rangeIncludes
> **Object:** xsd:integer

**Add:**
> **Subject:** ceterms:price
> **Predicate:** schema:rangeIncludes
> **Object:** xsd:decimal

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
