### ISSUE TITLE
Enable referencing weeks in duration strings

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#636]
The registry team is implementing updates to the graph database and has run into a schema issue where ceterms:exactDuration, ceterms:minimumDuration, ceterms:maximumDuration, and ceterms:renewalFrequency have a range of xsd:duration.  We need to ensure that it's possible to define some number of weeks using a duration string.

However, it looks like xsd:duration is a specific implementation of ISO8601:
http://books.xmlschemata.org/relaxng/ch19-77073.html

It leaves out weeks for some reason, even though they are defined in ISO8601 itself:
https://www.digi.com/resources/documentation/digidocs/90001437-13/reference/r_iso_8601_duration_format.htm

I can see a few options:
- Stick with the existing range and make sure our code converts anything with weeks in it to an equivalent number of days and adds those to any existing days in a duration string
- Find a way to reliably reference the ISO8601 duration standard directly and update the range of the affected properties to use it instead
- Stick with the existing range and do not permit publishing data that uses weeks, instead requiring days (or months?) to be used

Thoughts?

**Comment by cwd-mparsons** [comment]
I don't think that we can arbitrarily change weeks to days. 
A course could be 5 weeks, with 3 hours a week. 
The actual work is not 5 days with 3 hours per day. The course will always be 5 weeks, and cannot be completed in 'n' days. 
In the latter example, 15 hours might be acceptable - as it correctly states the duration not elapsed.

**Comment by siuc-nate** [comment]
Ahh yeah, good catch.  I wonder why the XSD spec leaves out weeks.

**Comment by philbarker** [comment]
@siuc-nate to answer you question, I think it was the other way round. ISO added weeks to ISO 8601-2015; W3C XML XSD Datatypes was published in 2012. Which explains without helping ¯\_(ツ)_/¯

**Comment by siuc-nate** [comment]
Ah, that would explain it, thanks. 

Phil, I'd be interested in hearing any suggestions you might have as to the root issue - we have data that includes weeks and need a way to include it.  I suspect that means changing the data type from xsd:duration to something else (whatever the equivalent of iso8601:duration would translate to?) but I'm at the edge of my knowledge here.

I don't suppose there's any chance of getting the XSD schema updated to include weeks?

**Comment by philbarker** [comment]
Even though ISO 8601 is what the spec (and schema.org) references, I think that bindings are stuck with xsd:duration, I don't know of another useful alternative. 

However from the discussion above it looks like you are talking about two conceptually different things: the duration, i.e. the five weeks from the start to the end of the learning opportunity; and the learning time, i.e. the time 5 x 3 hours per week spent learning. So I don't see a problem in saying that the duration of a LearningOpportunity is 35 days instead of 5 weeks. If you want to talk in terms of this equating to 15 hours or 3 hours per week, then schema.org has [timeRequired](http://schema.org/timeRequired) and [courseWorkload](http://schema.org/courseWorkload) respectively.

In short 1 week == 7 days

**Comment by siuc-nate** [comment]
So it sounds like the plan should be to convert/republish the existing data to use days instead of weeks, and then remove/hide the notion of weeks from our interfaces and documentation so that we're compliant with the XSD spec end to end.

**Comment by cwd-mparsons** [comment]
There are 109 credentials and 26 learning opportunities that have a duration in weeks.

Screen snippet of the entry of duration in the manual entry:
![image](https://user-images.githubusercontent.com/26332112/68801247-50f2d380-0621-11ea-90d8-7e9168e49b3a.png)

 
Screen snippet of the property instruction with the bulk upload:
![image](https://user-images.githubusercontent.com/26332112/68800903-8cd96900-0620-11ea-9ec4-4b2070cf4b39.png)

**Comment by jkitchensSIUC** [comment]
@cwd-mparsons so the only issue is with weeks, not with years, months, days, hours or minutes?

**Comment by cwd-mparsons** [comment]
Yes, the issue is only for weeks.
As noted by Nate, the xsd:duration doesn't include weeks:

> However, it looks like xsd:duration is a specific implementation of ISO8601:
> http://books.xmlschemata.org/relaxng/ch19-77073.html
> 
> It leaves out weeks for some reason, even though they are defined in ISO8601 itself:
> https://www.digi.com/resources/documentation/digidocs/90001437-13/reference/r_iso_8601_duration_format.htm

![image](https://user-images.githubusercontent.com/26332112/68803102-c6ac6e80-0624-11ea-9736-70f4014a0edc.png)

**Comment by siuc-nate** [comment]
The plan is to:
- Stick with the xsd:duration spec
- Update existing data to convert weeks to days
- Remove/hide weeks from interfaces.

**Comment by jkitchensSIUC** [comment]
@cwd-mparsons looks as though this is no longer a CTDL issue but an interface issue with the publisher: API, Manual Entry and Bulk Upload.  Are you closing this and setting up a Trello card instead to make updates to API, Manual Entry and Bulk Upload.

**Comment by siuc-nate** [comment]
@philbarker Should we always convert weeks to days (since this is a known and reliable calculation) or should we attempt to convert weeks to months (which _usually_ have four weeks, but not exactly), years, etc.?  Is there a best practice for this?

**Comment by philbarker** [comment]
@siuc-nate I don't know of any specific best practice in this. Probably depends on what the specific data is. I mean, I would generally go for a non-lossy / exact data transform (i.e. days), but if you have any 26 or 52 week courses then 6 months or 1 year would be more natural. Is there any way to sound out the data providers for the tricky cases (e.g. 12 weeks)?

**Comment by siuc-nate** [comment]
We're discussing it internally, but it's likely that we'll end up doing something like that.

**Comment by siuc-nate** [comment]
@philbarker What about https://schema.org/Duration ?  If we wanted to use an ISO 8601 duration string that included weeks, what would the property range and context for the duration properties look like if it used that?

e.g.:
```
{
  "@context": {
    "ceterms:exactDuration": { "@type": "schema:Duration" }
  }
}
```
```
{
  "@id": "ceterms:exactDuration",
  "schema:rangeIncludes": [
    "schema:Duration"
  ]
}
```

Would those be the correct encodings to convey a desired value like?:
```
{
  "ceterms:exactDuration": "P5M3W10D"
}
```

**Comment by philbarker** [comment]
@siuc-nate  You could do use schema:Duration, though I don't know how you would validate a value if not against xsd:duration (if validation is an issue)

I've not seen `@type` used in the context block in JSON-LD for anything other than showing that the name is to be interpreted as an `@id` (`@type` is overloaded and works differently in the context to how it works in the main body).  I think you want to be making those changes to the CTDL schema definition files. I see the RDFS/ttl schema are now deprecated, are you now using JSON schema? 

I think I need to know more about what you're doing and how before commenting on specific implementation issues.

**Comment by siuc-nate** [comment]
We handle validation internally, though I guess that wouldn't be much help to other systems that would produce or consume data with weeks in it.

The second example shows how we would update our schema definition to show the intended range of the property.  It's unfortunate that the JSON-LD context is so limited in what can be done with it.

We used JSON schema at one point for validation within the registry, but it proved too cantankerous to maintain given all the different possible combinations of "valid" data presented by our minimum data policy.  So our validation uses a bespoke process that is a lot easier for us to manage internally.

**Comment by philbarker** [comment]
I did a bit more poking about and did find an example  on the [JSON-LD playground](https://json-ld.org/playground/) of `@type` being used for something other than `@id` in the way you suggested initially.
However, 
```
{
  "@context": {
    "sdo": "http://schema.org/",
    "ceterms": "http://purl.org/ctdl/terms/",
    "ceterms:exactDuration": {
      "@type": "sdo:Duration"
    }
  },
  "ceterms:exactDuration": "P5M3W10D"
}
```
translates to 
`_:b0 <http://purl.org/ctdl/terms/exactDuration> "P5M3W10D"^^<http://schema.org/Duration> .`

That's treating schema.org/Duration as a datatype for a literal not a class type for an object which is how it is defined. It might work for what you want, I don't know, I've never tried it. It doesn't validate with the Google structured data testing tool.

A more standard (in the sense of usual, how it is in all the examples) schema.org way to express the data would be:
```
{
  "@context": {
    "sdo": "http://schema.org/",
    "ceterms": "http://purl.org/ctdl/terms/",
    }
  },
  "ceterms:exactDuration": "P5M3W10D"
}
```
which kind of ignores the typing altogether.  I can't come up with anything of the form  
```{
  "@context": {
    "sdo": "http://schema.org/",
    "ceterms": "http://purl.org/ctdl/terms/"
  },
  "ceterms:exactDuration": {
    "@type": "sdo:Duration",
    ....: "P5M3W10D"}
}```
that passes the Google structured data validator.

I'll try to find out what is the intention behind schema.org/Duration, but at the moment, as far as I can tell, you might as well just say in the human readable docs that exactDuration is an ISO8601 string and in the machine readable docs treat it as a literal.

**Comment by siuc-nate** [comment]
It did strike me as odd that [schema.org/Duration](https://schema.org/Duration) was a class with its own properties, but was documented to be a string.  I'd be curious to know what you find out in regard to what was intended by that.  Perhaps it's supposed to be an object with a value property somewhere (perhaps `schema:name` or `schema:identifier`) that carries the string?

Thank you for looking into all of this.

Your suggestion of treating it like a literal from the machine perspective may be worth exploring, but I don't know if it'd be worth losing the ability to compute, compare, sort, etc., all of the other durations without weeks in order to accommodate weeks.

**Comment by siuc-nate** [comment]
Per our 11-26-2019 meeting:
- We will change the range to the property to use schema:Duration instead of xsd:duration
- We will **not** alter/convert the data that uses weeks

Proposal:
**Remove:**
> **Subject:** cterms:minimumDuration
> **Predicate:** schema:rangeIncludes
> **Object:** xsd:duration

> **Subject:** cterms:maximumDuration
> **Predicate:** schema:rangeIncludes
> **Object:** xsd:duration

> **Subject:** cterms:exactDuration
> **Predicate:** schema:rangeIncludes
> **Object:** xsd:duration

> **Subject:** cterms:renewalFrequency
> **Predicate:** schema:rangeIncludes
> **Object:** xsd:duration

**Add:**
> **Subject:** cterms:minimumDuration
> **Predicate:** schema:rangeIncludes
> **Object:** schema:Duration

> **Subject:** cterms:maximumDuration
> **Predicate:** schema:rangeIncludes
> **Object:** schema:Duration

> **Subject:** cterms:exactDuration
> **Predicate:** schema:rangeIncludes
> **Object:** schema:Duration

> **Subject:** cterms:renewalFrequency
> **Predicate:** schema:rangeIncludes
> **Object:** schema:Duration

**Comment by jkitchensSIUC** [comment]
See this document for the proposed solution https://docs.google.com/document/d/1d2kmG_9wbhE0t3hT4uwyXstYh-55Ma3qg9DWF-hJpVE/edit?usp=sharing.  

The issue is a Registry configuration file that impacts the queries for the search endpoint.  The goal is NOT to change any data entry.

@cwd-mparsons is to post a GitHub issue to the Registry repo.  He can link it here so it can be followed.

**Comment by siuc-nate** [comment]
the CTDL proposal is in the post just above yours.
https://github.com/CredentialEngine/Schema-Development/issues/636#issuecomment-558790279

**Comment by cwd-mparsons** [comment]
Registry team issue to request ability for CE staff to submit direct updates to the schema for an environment:
https://github.com/CredentialEngine/CredentialRegistry/issues/289

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
