### ISSUE TITLE
dateCreated is xsd:date for competencyFramework and xsd:dateTime for conceptScheme. Should the latter also be xsd:date?

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/Schema-Development#637]

**Comment by siuc-nate** [comment]
I'd say that makes sense.

**Comment by stuartasutton** [comment]
Agreed. Makes sense.

**Comment by siuc-nate** [comment]
Since it's the same property in both classes, this is already the case for the schema - however, there appears to be a discrepancy in the spreadsheet used to track this information: https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1476845803

**Comment by stuartasutton** [comment]
Update the spreadsheet.

We should consider whether we shouldn't mothball the spreadsheet, it was created to define and sync the development of the CaSS editor. The authority should be the regular tables.

**Comment by stuartasutton** [comment]
I have to expand on what I meant by "regular tables".  The regular tables defining terms in the CTDL family of specifications do not define any constraints beyond domain and range as defined by a particular application profile (e.g., CTDL-ASN)...how should/do we document constraints in profiles?

**Comment by siuc-nate** [comment]
There's a bespoke mechanism in the schema management system used to handle constraints.  These show up in a few places:
https://credreg.net/registry/policy
https://credreg.net/ctdl/mapping?profileID=registry
https://credreg.net/ctdl/schema?profileID=registry
