### ISSUE TITLE
Review CTDL Minimum Data Policy with regard to ceterms:FinancialAssistanceProfile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#639]
Now that Financial Assistance Profile has been updated with the financial assistance type vocabulary, we need to examine its properties to see if any make sense as required/recommended.

**Comment by stuartasutton** [comment]
See Oct 29th in CTDL Running Topics:

https://docs.google.com/document/d/1eaCNlDrb2ZNNpbnYkVzh98ve9p41BB8BQFNAGSIUybk/edit#heading=h.6vat9w3pslrv

Stuart

**Comment by jeannekitchens** [comment]
@siuc-nate @stuartasutton what needs to be done to close this issue?

**Comment by siuc-nate** [comment]
We need to determine required/recommended properties for [Financial Assistance Profile](https://credreg.net/ctdl/terms/FinancialAssistanceProfile#FinancialAssistanceProfile). Given its limited property set and our lack of hard knowledge of how it will be used, I think it makes sense for its properties to only be recommended at this time.

**Comment by stuartasutton** [comment]
@siuc-nate name and description should be safe

**Comment by siuc-nate** [comment]
Safe to recommend? or require?

**Comment by stuartasutton** [comment]
Well it is always safe to recommend...but having a class where nothing is required seems to go against the grain.

**Comment by siuc-nate** [comment]
Per our 5-14-2020 meeting:

**Update Minimum Data Policy:**
Required:
- ceterms:FinanicalAssistanceProfile.ceterms:name
Requires at least one of:
- ceterms:FinanicalAssistanceProfile.ceterms:description
- ceterms:FinanicalAssistanceProfile.ceterms:financialAssistanceType
- ceterms:FinanicalAssistanceProfile.ceterms:subjectWebpage

Recommended:
- ceterms:Credential (and subclasses).ceterms:financialAssistance
- ceterms:AssessmentProfile.ceterms:financialAssistance
- ceterms:LearningOpportunityProfile.ceterms:financialAssistance

**Comment by siuc-nate** [comment]
These changes have been made in the pending registry policy.
