### ISSUE TITLE
Update financial assistance vocabulary military terms

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#640]
We learned from SOLID today that the categorization of military financial aid as found in [CEDS](https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=41080) is incorrect. Specifically:

- DoD Tuition Assistance is only applicable to Active Duty, Reserve, and Guard members - not Veterans.
- The Post-9/11 GI Bill applies both to Active Duty and Veterans.

As such, categorizing either term as a subconcept of Veterans' financial aid is incorrect. That term may be useful in other cases, however.

I propose the following changes:

1. Create a new, broader concept for military-related financial aid:
> **URI:** financialAid:Military
> **Label:** Military
> **Definition:** Financial assistance available to current and/or former members of the military.

2. Remove the incorrect subconcept categorizations:
> **Subject:** financialAid:DoDTuitionAssistance
> **Predicate:** skos:broader
> **Object:** financialAid:Veteran

> **Subject:** financialAid:Post911GIBill
> **Predicate:** skos:broader
> **Object:** financialAid:Veteran

3. Add the correct subconcept categorizations:
> **Subject:** financialAid:DoDTuitionAssistance
> **Predicate:** skos:broader
> **Object:** financialAid:Military

> **Subject:** financialAid:Post911GIBill
> **Predicate:** skos:broader
> **Object:** financialAid:Military

> **Subject:** financialAid:Veteran
> **Predicate:** skos:broader
> **Object:** financialAid:Military

**Comment by stuartasutton** [comment]
Sounds reasonable to me.

**Comment by cwd-mparsons** [comment]
In general it would be very useful to have a description for the concepts. Currently the concept definition is the same as the label. The definition could include useful information such as to whom it applies.

**Comment by stuartasutton** [comment]
In general, these came from CEDS, did they not? Were there definitions there?

**Comment by siuc-nate** [comment]
No, all of the CEDS terms had the same label and definition.

https://ceds.ed.gov/element/001610#DODTuitionAssistance
https://ceds.ed.gov/element/001610#Post911GIBill

**Comment by stuartasutton** [comment]
# Draft Definitions:

## Department of Defense (DoD) Tuition Assistance

> SEE: https://www.dantes.doded.mil/FinancialAid/MilitaryTuitionAssistance.html

DEFINITION:
Department of Defense (DoD) Tuition Assistance (TA) program provides financial assistance to Service members for voluntary off-duty education programs in support of professional and personal self-development goals.

COMMENT:
TA is available for courses that are offered in the classroom or by distance learning and are part of an approved academic degree or certificate program. The courses must be offered by schools that are: (a) recognized by the U.S. Department of Education; and (b) are signatories to the current DoD Voluntary Education Partnership Memorandum of Understanding (DOD MOU).

## Post-9/11 GI Bill (Chapter 33)

DEFINITION:


## Montgomery GI Bill Active Duty (MGIB-AD)

DEFINITION:

## Montgomery GI Bill Selected Reserve (MGIB-SR)

DEFINITION:

> SEE:
> * https://www.va.gov/education/about-gi-bill-benefits/
> * https://www.militaryonesource.mil/education-employment/for-service-members/preparing-for-higher-education/how-to-use-the-military-tuition-assistance-program

**Comment by siuc-nate** [comment]
See #651
