### ISSUE TITLE
Add a qdata property to signal data suppression/masking

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#641]
In some publicly shared datasets, select information may not be provided to protect the identity of subjects by: (a) *data suppression* through removal or deletion of data, or (b) *data masking*  through concealing or encrypting select information.  

We need to add a `qdata:dataWithheld` property with a two-value concept scheme:  `Data Suppressed` and `Data Masked`.

In the domain model, such suppression/masking can occur in three entities:

`QuantitativeValue`
`MonetaryAmount`
`MonetaryAmountDistribution`

### Property
>**URI:** qdata:dataWithheldType
>**Definition:** Data has been suppressed or masked to protect the identity of subjects.
>**Domain Includes:** qdata:QuantitativeValue,  qdata:MonetaryAmount, qdata:MonetaryAmountDistribution

### Concept Scheme 
>**URI:** qdata:WithheldDataType
**Definition:** Types of process for withholding data in a dataset.
**Type:** skos:ConceptScheme

### Concept
>**URI:** withheldData:DataSuppressed
**Definition:** Select information withheld or removed to protect the identities of subjects.
**Type:** skos:Concept

### Concept
>**URI:** withheldData:DataMasked
**Definition:** Select information concealed or encrypted to protect the identities of subjects.
**Type:** skos:Concept

See: *The Glossary of Education Reform*
>https://www.edglossary.org/data-suppression/
https://www.edglossary.org/data-masking/

**Comment by siuc-nate** [comment]
I would recommend using "type" as part of the property's name to be consistent with other properties that use vocabularies.  It may also be good to avoid enumerating the concepts in the definition for the concept scheme itself, so as to keep it flexible, as that kind of thing has bitten us before.

**Comment by stuartasutton** [comment]
Adding type (qdata:dataWithheldType) is OK. I don't understand the remainder of your comment, Nate. Where is anything enumerated.

**Comment by siuc-nate** [comment]
The definition for dataWithheld(Type) says:
"Data has been **suppressed** or **masked** to protect the identity of subjects."
Which enumerates the terms in the concept scheme.

**Comment by stuartasutton** [comment]
That's ok, Nate. Those are the only two ways data that exists in this context doesn't appear. The reason not to list in such a case is because there may be other ways the data is not present. In this case it is either not present or rendered invisible or inaccessible.

So what phrase to you suggest for "suppressed or masked"?

**Comment by siuc-nate** [comment]
Maybe just broaden it a bit, in case we run into something later (and tuning to match our other definitions that point to concepts). Something like:
"Type of suppression, masking, or other modification made to the data to protect the identities of its subjects; select from an existing enumeration of such types"

**Comment by stuartasutton** [comment]
That's fine with me.

**Comment by siuc-nate** [comment]
Updates:

### Property
>**URI:** qdata:dataWithholdingType
>**Definition:** Type of suppression, masking, or other modification made to the data to protect the identities of its subjects.
>**Domain Includes:** qdata:QuantitativeValue, qdata:MonetaryAmount, qdata:MonetaryAmountDistribution

### Concept Scheme 
>**URI:** qdata:DataWithholdingCategory
**Definition:** Categories of processes for withholding data in a data set.
**Type:** skos:ConceptScheme

### Concept
>**URI:** dataWithholding:DataSuppressed
**Definition:** Select information withheld or removed to protect the identities of subjects.
**Type:** skos:Concept

### Concept
>**URI:** dataWithholding:DataMasked
**Definition:** Select information concealed or encrypted to protect the identities of subjects.
**Type:** skos:Concept

**Comment by siuc-nate** [comment]
These changes have been made and noted in the history tracking.
