### ISSUE TITLE
Update ceterms:programTerm to point to a Progression Model

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#643]
Per #576 and our 12-4-2019 meeting:

ceterms:programTerm will have its range updated to point to ceterms:CredentialAlignmentObject, which in turn will point to a Progression Model that will be user-defined.

**Comment by stuartasutton** [comment]
An abstract `ProgressionModel` class exists in ASN (http://purl.org/ASN/schema/core/ProgressionModel) with the following definition: 

>Model of identifiable points along a developmental progression including increasing levels of competence, achievement or temporal position (e.g., "Second Quarter").

Shouldn't we just reference it?  There is documented in the [ASN `Rubric`](http://standards.asn.desire2learn.com/rubric.html#pm) file.  We should consider making our [`ProficiencyScale`](https://purl.org/ctdlasn/terms/ProficiencyScale) a subclass of the `asn:ProgressionModel`

**Comment by siuc-nate** [comment]
This property is currently unstable. Do we want to also make it stable?

**Comment by jeannekitchens** [comment]
@siuc-nate @stuartasutton what do we need to do to finalize this issue and close it?

**Comment by siuc-nate** [comment]
I made the property stable.  I also updated the range and noted this in the history tracking.
