### ISSUE TITLE
Should Jurisdiction based QA like assertedIn require the entry of one or more asserted by Organizations

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/Schema-Development#646]
@stuartasutton @siuc-nate 
Currently in the publisher and Assistant API, Jurisdiction based QA properties like assertedIn, and approvedIn do NOT require that an assertedBy organization be present. 
The publisher used to have an edit to require an org, but was removed. I could not find a reference to this scenario in github.

Shouldn't an organization be required?
That is if a credential is accredited in a particular state, shouldn't there be a property to indicated who does the accreditation? Otherwise anyone can make claims that a credential is accredited.

**Comment by siuc-nate** [comment]
ceterms:accreditedIn is just a property, so there's no way to associate another piece of data like "who entered the value for this property".  I raised this issue back when we added the "__In" properties and I think the solution was just to rely on the combination of ceterms:accreditedIn and ceterms:accreditedBy, along with the data's publisher, to know who made the assertion.

**Comment by mparsons-ce** [comment]
ceterms:accreditedIn has a range of jurisdiction profile. The latter includes the property assertedBy.
So why couldn't assertedBy be required for the 'registry profile' of assertedIn?

**Comment by siuc-nate** [comment]
Wouldn't that cause assertedBy to be required across the board in jurisdiction profile? (I'm not sure we have the system setup to enable requiring a property in a class only if the class is used as the value for some other property).  Isn't the publisher of the information the ultimate asserting body?

Would this change solve a problem/use case?

**Comment by siuc-nate** [comment]
Actually, wouldn't this data be instead carried in the credential that represents the accreditation?  e.g.
- Organization A accredits Organization B with ceterms:QualityAssuranceCredential C
- ceterms:QualityAssuranceCredential C has a ceterms:jurisdiction (and corresponding ceterms:JurisdictionProfile) that contains the location(s) in which that ceterms:QualityAssuranceCredential is valid/recognized/etc.

**Comment by stuartasutton** [comment]
No, let's not create credentials to represent accreditations. An QA agent takes an **action** to accredit.  CTDL  accommodates documenting such actions. The accredited organization can reference that action. We have been here before (e.g., the California Community College "Star Awards" as action or credential) and have not resolved it. 

Let's not complicate the definition of a credential any further than necessary by adding to a retrieval pool credentials for accreditations.. 

I have an action on myself to spend some time documenting use of the action properties.

**Comment by stuartasutton** [comment]
One other assumption that I don't think we should make is that just because an org claims a credential is "accredited By" some other org that there necessarily has to be a record of that claim by the other org in the CER.

**Comment by mparsons-ce** [comment]
There are many cases (mainly PECB), where:
- a jurisdiction assertion is created specifying Global
- indicates accreditedIn, approvedIn, etc
For example, see (under extra information):
https://credentialengine.org/publisher/editor/credential/3385
https://credentialengineregistry.org/graph/ce-afa9c147-fe16-4eea-bee1-f11c0911d40e

Wouldn't the latter be interpreted as PECB is stating that the credential is accredited (etc.) globally?
However, there is no indication of who does the accreditation. 
Aren't these the types of blanket assertions that should be avoided, or should there be guidance to indicated accreditedIn is more general and lacks the weight of accreditBy?

**Comment by siuc-nate** [comment]
Very early on in the development of CTDL, we had a QualityAssuranceProfile.  Its purpose was to describe the QA, who offered it, what it required to earn/maintain it, where it was applicable, etc. It ultimately was functionally identical to a credential (the only difference being that it was usually awarded to organizations rather than people), so we created the [ceterms:QualityAssuranceCredential](https://credreg.net/ctdl/terms#QualityAssuranceCredential) class to use instead.  This is why the various ___Action profiles have a [ceterms:instrument](https://credreg.net/ctdl/terms/instrument) property that enables pointing to the ceterms:QualityAssuranceCredential that was awarded (and whose requirements were applied in the evaluation of the organization in question, etc).

**Comment by siuc-nate** [comment]
>One other assumption that I don't think we should make is that just because an org claims a credential is "accredited By" some other org that there necessarily has to be a record of that claim by the other org in the CER.

The two-way validation of QA (and/or the lack thereof) is another subject that has come up at various times in the past. It may be beyond the scope of "what do we do with the ___In properties?"

>Wouldn't the latter be interpreted as PECB is stating that the credential is accredited (etc.) globally?

Correct.

>However, there is no indication of who does the accreditation.

That data is held in the accreditedBy property.  It is true that these two data points being in separate properties not bound together by any kind of profile means there is no way to directly associate which body did which accreditation (in the event there is more than one of either), which is the problem I brought up years ago during implementation of the ___In properties, but I believe the treatment of this is along the lines of the various ____URL and ____Description property pairs we use elsewhere in CTDL.
![image](https://user-images.githubusercontent.com/21346519/71995525-55420400-3200-11ea-8278-47271696e368.png)

>Aren't these the types of blanket assertions that should be avoided, or should there be guidance to indicated accreditedIn is more general and lacks the weight of accreditBy?

I'm not sure what you mean.  Are you saying the PECB credentials aren't accredited globally?

**Comment by siuc-nate** [comment]
The alternative that CTDL is already designed to handle would be:

- `Some Credential` is `accreditedBy` `Some QA Org`
- Ideally `Some QA Org` also `accredits` `Some Credential`
- `Some QA Org` publishes an `AccreditAction` (which covers the "asserted by" functionality this thread is looking for) which points to `Accreditation Credential` via its `instrument` property
- That same `AccreditAction` contains data necessary to reify the relationship that says `Some QA Org` granted `Accreditation Credential` to `Some Credential` as of `startDate` until `endDate` etc.
- `Some QA Org` publishes that same `Accreditation Credential`
- The `Accreditation Credential`, by virtue of being a subclass of `Credential`, describes:
  - Who offers it
  - What is required to earn it
  - What is required to maintain it
  - Where it is valid (negating the need for the ____In properties)
  - Any associated costs
  - etc.

**Comment by mparsons-ce** [comment]
> I'm not sure what you mean. Are you saying the PECB credentials aren't accredited globally?

A key concern regarding data in the registry is having valid data. Anyone can state that their credential is approved, accredited, recognized, etc. The concern is that consumers can have confidence that these assertions are valid.

The PECB has one QA-accreditedBy assertion,.
That is great but there are no other QA assertions.

**Comment by siuc-nate** [comment]
That problem applies to all of the ___By assertions though, doesn't it?  Since they're effectively reverse assertions, you can't really prove any of them unless the QA org in question has published a corresponding QA assertion.

**Comment by mparsons-ce** [comment]
Proof is not the current issue, just whether an assertion should be stated like the _Bys

**Comment by stuartasutton** [comment]
Precisely. I can't make an accreditedBy by Org B assertion unless that assertion is made by Org B AND Org B is in the registry. And what if Org B makes the assertion on their website but sees no value in maintaining a record in the CER? If the answer is that they can't make the accreditedBy by Org B assertion in the CER for lack of an in-CER reciprocal assertion (even if it exists elsewhere), then we have invented a closed little world.

**Comment by siuc-nate** [comment]
>I can't make an accreditedBy by Org B assertion unless that assertion is made by Org B AND Org B is in the registry.

We've been handling this one for a long time now by:
- Allowing one-way assertions (e.g. "accreditedBy" without any corresponding "accredits")
- Using blank nodes to stand in for the QA Org records

**Comment by stuartasutton** [comment]
Good. So this means that there's a org bnode embedded in the credential description.

**Comment by siuc-nate** [comment]
It sounds like the answer to this is to use a blank node as the value of `ceterms:assertedBy` inside the Jurisdiction Profile that is itself the value for `ceterms:accreditedIn` (et al).  Does that solve this issue? @mparsons-ce @stuartasutton

**Comment by stuartasutton** [comment]
I somehow think that the original question was more a policy question than a technical one. We've long settled the use of bnodes in such cases.

**Comment by siuc-nate** [comment]
Per our 10-13-2020 meeting:

This is handled: https://github.com/CredentialEngine/Schema-Development/issues/646#issuecomment-698414950
