### ISSUE TITLE
Add ceterms:OccupationType and ceterms:industryClassification to CTDL-ASN

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#650]
A competency framework may be classified as pertaining to an occupation and/or an industry; therefore, ceterms:OccupationType and ceterms:industryClassification are needed. 

As concept specializations, both could be considered as subproperties of ceasn:conceptKeyword and ceasn:conceptKeyword; but, I don't think it would be really kosher to add those the subproperty assertions to ceasn terms.

**Comment by siuc-nate** [comment]
This is already how they work:
https://credreg.net/ctdlasn/terms#CompetencyFramework has the `ceterms:industryType` and `ceterms:occupationType` properties, which already point to (via Credential Alignment Objects, as with CTDL) Occupation Classification and Industry Classification.
https://credreg.net/ctdlasn/terms#industryType
https://credreg.net/ctdlasn/terms#occupationType

**Comment by stuartasutton** [comment]
My mistake. When you look at the list of properties athttps://credreg.net/ctdlasn/terms/ you'd assume they were in alpha order by property, not by namespace.
