### ISSUE TITLE
Add broad categories to the Financial Assistance concept scheme

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#651]
Per our 2/28/2020 meeting with representatives from Kansas:

The [Financial Assistance](https://credreg.net/ctdl/terms#FinancialAssistance) concept scheme has a number of terms that appear to fit naturally into categories, but we do not currently have categories for such terms.  Namely:
- Scholarship
- Grant
- Loan
- Work Based (to cover the remaining terms)

These terms would be useful in documenting data from Kansas:
https://ksdegreestats.org/ProspectusController?app=prospectus&ficeInstId=001925&programNbr=26

Naturally, we would also need to adjust the existing skos:broader/skos:narrower attributes to enable the following structure (new terms in bold):
- financialAid:General
  - **financialAid:Scholarship**
    - financialAid:FederalScholarship
    - financialAid:StateLocalScholarship
    - financialAid:InstitutionalScholarship
    - financialAid:PrivateScholarship
    - financialAid:OtherScholarship
  - **financialAid:Grant**
    - financialAid:InstitutionalGrant
    - financialAid:OtherFederalGrant
    - financialAid:StateLocalGrant
    - financialAid:PellGrant
    - financialAid:PrivateGrant
    - financialAid:OtherGrant
  - **financialAid:Loan**
    - financialAid:FederalSubsidizedLoan
    - financialAid:FederalUnsubsidizedLoan
    - financialAid:StateLoan
    - financialAid:InstitutionalLoan
    - financialAid:ParentPLUSLoan
    - financialAid:PrivateLoan
    - financialAid:OtherLoan
  - **financialAid:WorkBased**
    - financialAid:Assistantship
    - financialAid:FederalWorkStudy
    - financialAid:StateWork
    - financialAid:OtherOnCampusWork
- financialAid:Veteran (See #640 for changes here)
  - financialAid:Post911GIBill
  - financialAid:DoDTuitionAssistance

**As an alternative to creating new terms**, we should consider whether it would be semantically correct for Kansas (or any similar case) to simply select all of the terms that would otherwise be under one of the categories above.  I doubt it, but, we should probably discuss it.

See also #652 and #640

**Comment by stuartasutton** [comment]
There is nothing to say that picking FinancialAid:Grant means You’ve picked “everything below”. It’s just as rational to think that the heading does nothing but organize a set of concepts. In fact, ASN has a property that we do not use that provides a “recommendation” whether a concept is “indexable”. With my example, a recommendation of “false” for FinancialAid:Grant means only index to to terms under it with a recommendation of “true”. concepts

**Comment by siuc-nate** [comment]
If you apply the proposed changes from #640 as well, the hierarchy would look like this (new terms in bold):

- financialAid:General
  - **financialAid:Scholarship**
    - financialAid:FederalScholarship
    - financialAid:StateLocalScholarship
    - financialAid:InstitutionalScholarship
    - financialAid:PrivateScholarship
    - financialAid:OtherScholarship
  - **financialAid:Grant**
    - financialAid:InstitutionalGrant
    - financialAid:OtherFederalGrant
    - financialAid:StateLocalGrant
    - financialAid:PellGrant
    - financialAid:PrivateGrant
    - financialAid:OtherGrant
  - **financialAid:Loan**
    - financialAid:FederalSubsidizedLoan
    - financialAid:FederalUnsubsidizedLoan
    - financialAid:StateLoan
    - financialAid:InstitutionalLoan
    - financialAid:ParentPLUSLoan
    - financialAid:PrivateLoan
    - financialAid:OtherLoan
  - **financialAid:WorkBased**
    - financialAid:Assistantship
    - financialAid:FederalWorkStudy
    - financialAid:StateWork
    - financialAid:OtherOnCampusWork
- **financialAid:Military**
    - financialAid:Veteran
    - financialAid:Post911GIBill
    - financialAid:DoDTuitionAssistance

**Comment by siuc-nate** [comment]
Changes to implement:

Create new skos:Concepts:
---
Summary: Create new terms to act as the broad categories of financial aid. These would be selectable (in order to facilitate Kansas's use case).

> **URI**: financialAid:Scholarship
> **Label**: Scholarship
> **Definition**: Scholarship
> **Subconcept Of**: financialAid:General

> **URI**: financialAid:Grant
> **Label**: Grant
> **Definition**: Grant
> **Subconcept Of**: financialAid:General

> **URI**: financialAid:Loan
> **Label**: Loan
> **Definition**: Loan
> **Subconcept Of**: financialAid:General

> **URI**: financialAid:WorkBased
> **Label**: Work Based
> **Definition**: Work Based
> **Subconcept Of**: financialAid:General

> **URI**: financialAid:Military
> **Label**: Military
> **Definition**: Military


Recategorize existing concepts
---
Move existing concepts from being categorized as either "General" or "Veteran" to the new categories.

> **URI**: financialAid:Assistantship
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Scholarship

> **URI**: financialAid:DoDTuitionAssistance
> **Remove skos:broader**: financialAid:Veteran
> **Add skos:broader**: financialAid:Military

> **URI**: financialAid:FederalScholarship
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Scholarship

> **URI**: financialAid:FederalSubsidizedLoan
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Loan

> **URI**: financialAid:FederalUnsubsidizedLoan
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Loan

> **URI**: financialAid:FederalWorkStudy
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:WorkBased

> **URI**: financialAid:InstitutionalGrant
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Grant

> **URI**: financialAid:InstitutionalLoan
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Loan

> **URI**: financialAid:InstitutionalScholarship
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Scholarship

> **URI**: financialAid:OtherFederalGrant
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Grant

> **URI**: financialAid:OtherGrant
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Grant

> **URI**: financialAid:OtherLoan
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Loan

> **URI**: financialAid:OtherOnCampusWork
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:WorkBased

> **URI**: financialAid:OtherScholarship
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Scholarship

> **URI**: financialAid:ParentPLUSLoan
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Loan

> **URI**: financialAid:PellGrant
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Grant

> **URI**: financialAid:Post911GIBill
> **Remove skos:broader**: financialAid:Veteran
> **Add skos:broader**: financialAid:Military

> **URI**: financialAid:PrivateGrant
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Grant

> **URI**: financialAid:PrivateLoan
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Loan

> **URI**: financialAid:PrivateScholarship
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Scholarship

> **URI**: financialAid:StateLoan
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Loan

> **URI**: financialAid:StateLocalGrant
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Grant

> **URI**: financialAid:StateLocalScholarship
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:Scholarship

> **URI**: financialAid:StateWork
> **Remove skos:broader**: financialAid:General
> **Add skos:broader**: financialAid:WorkBased

> **URI**: financialAid:Veteran
> **Add skos:broader**: financialAid:Military

**Comment by philbarker** [comment]
(on a very minor point) Is it too late to settle on a shorter prefix?  

I know it's only a convention, anyone can choose what they want and what we use chouls only affect us, but people often copy what's used in the spec docs.

`fin:` would be my choice, or `aid:`, but maybe worth checking it's not widely used by anything vocabulary we're likely to bump into.

**Comment by siuc-nate** [comment]
It's not impossible, but we do already use these terms and I suspect there's a lot of existing code and data that is looking for that prefix - I don't think we gain much from changing it relative to the cost of doing so.  We do also use prefixes of about that length in our other vocabularies, so it's not unusual.

**Comment by philbarker** [comment]
OK, I think the answer is that it is too late. No problem.

**Comment by siuc-nate** [comment]
Per our [planning document](https://docs.google.com/document/d/1Grode_oEh7DN-eL_-br7a0j5Gfc3hIwEEepqGEiCjXE/edit), the changes to be made now include a complex variety of `create`s, `add`s, `remove`s, `deprecate`s, etc.  This is probably one of the more complex combinations of changes we've made, at least in a while.

I walked through the document and, comparing it to the [existing terms](https://credreg.net/ctdl/terms/FinancialAssistanceProfile), captured the changes in this spreadsheet:
https://docs.google.com/spreadsheets/d/1S-p1tCk5RMFltFcoFLiJJ8fuhCpDpvw7zmFVQs-BdBo/edit#gid=0

I suspect the above will be more readable than the usual formal format we use in these threads.   Nevertheless:
**Update:** 
> **URI:** ceterms:FinancialAssistance
> **Remove Definition:** Types of financial assistance
> **Add Definition:** Types of financial assistance typically available in the United States.

**Update:** 
> **URI:** financialAid:General
> **Remove Definition:** Generally-available financial assistance.
> **Add Definition:** Types of financial aid for students towards education, training, or related costs of pursuing a credential, program, or other resource.

**Create:** 
> **URI:** financialAid:Scholarship
> **Add Label:** Scholarship
> **Add Definition:** Financial aid award based on student achievement and other criteria for education that doesn’t require repayment.
> **Add Broader:** financialAid:General
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Update:** 
> **URI:** financialAid:FederalScholarship
> **Remove Definition:** Federal Scholarship
> **Remove Broader:** financialAid:General
> **Add Definition:** Financial aid award, which doesn’t require repayment, from the Federal Government based on student achievement and other criteria for education.
> **Add Broader:** financialAid:Scholarship

**Update:** 
> **URI:** financialAid:StateLocalScholarship
> **Remove Definition:** State or Local Scholarship
> **Remove Broader:** financialAid:General
> **Add Definition:** Financial aid award, which doesn’t require repayment, from a state, province, region, and/or local government based on student achievement and other criteria for education.
> **Add Broader:** financialAid:Scholarship

**Update:** 
> **URI:** financialAid:InstitutionalScholarship
> **Remove Definition:** Institutional Scholarship
> **Remove Broader:** financialAid:General
> **Add Definition:** Financial aid award, which doesn’t require repayment, from an educational institution based on student achievement and other criteria for education.
> **Add Broader:** financialAid:Scholarship

**Update:** 
> **URI:** financialAid:PrivateScholarship
> **Remove Definition:** Private Scholarship
> **Remove Broader:** financialAid:General
> **Add Definition:** Financial aid award, which doesn’t require repayment, from a private entity, including employers, based on student achievement and other criteria for education.
> **Add Broader:** financialAid:Scholarship

**Update:** 
> **URI:** financialAid:OtherScholarship
> **Remove Definition:** Other Scholarship
> **Remove Broader:** financialAid:General
> **Add Definition:** Financial aid award, which doesn’t require repayment, from one or more other sources based on student achievement and other criteria.
> **Add Broader:** financialAid:Scholarship

**Create:** 
> **URI:** financialAid:Grant
> **Add Label:** Grant
> **Add Definition:** Financial subsidy, which doesn’t require repayment, based on meeting requirements determined by the grantor.
> **Add Broader:** financialAid:General
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Update:** 
> **URI:** financialAid:InstitutionalGrant
> **Remove Definition:** Institutional Grant
> **Remove Broader:** financialAid:General
> **Add Definition:** Financial subsidy, including free or discounted tuition or other fees, which doesn’t require repayment, based on meeting requirements determined by an educational institution.
> **Add Broader:** financialAid:Grant

**Create:** 
> **URI:** financialAid:FederalGrant
> **Add Label:** Federal Grant
> **Add Definition:** Financial subsidy, which doesn’t require repayment, based on meeting requirements determined by the Federal Government.
> **Add Broader:** financialAid:Grant
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Update:** 
> **URI:** financialAid:StateLocalGrant
> **Remove Definition:** State or Local Grant
> **Remove Broader:** financialAid:General
> **Add Definition:** Financial subsidy, which doesn’t require repayment, based on meeting requirements determined by a state, province, region, and/or local government.
> **Add Broader:** financialAid:Grant

**Update:** 
> **URI:** financialAid:PellGrant
> **Remove Definition:** Pell Grant
> **Remove Broader:** financialAid:General
> **Add Definition:** Financial subsidy, which doesn’t require repayment, that the Federal Government provides based on the financial needs of the student.
> **Add Broader:** financialAid:Grant

**Update:** 
> **URI:** financialAid:PrivateGrant
> **Remove Definition:** Private Grant
> **Remove Broader:** financialAid:General
> **Add Definition:** Financial subsidy, which doesn’t require repayment, based on meeting requirements determined by a private entity, including employers.
> **Add Broader:** financialAid:Grant

**Create:** 
> **URI:** financialAid:WIOA
> **Add Label:** Workforce Investment Opportunity Act (WIOA)
> **Add Definition:** Financial aid established on behalf of a qualified participant with a training provider that is on the state's Eligible Training Provider List (ETPL).
> **Add Broader:** financialAid:Grant
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Create:** 
> **URI:** financialAid:PromiseProgram
> **Add Label:** Promise Program
> **Add Definition:** Program with minimal requirements that pays for tuition, without requiring repayment, for students in a given area.
> **Add Broader:** financialAid:Grant
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Create:** 
> **URI:** financialAid:LoanForgivenessProgram
> **Add Label:** Loan Forgiveness Program
> **Add Definition:** Program that forgives the remaining balance on a loan after meeting certain requirements.
> **Add Broader:** financialAid:Grant
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Update:** 
> **URI:** financialAid:OtherGrant
> **Remove Definition:** Other Grant
> **Remove Broader:** financialAid:General
> **Add Definition:** Financial subsidy based on meeting requirements from one or more other sources.
> **Add Broader:** financialAid:Grant

**Create:** 
> **URI:** financialAid:Loan
> **Add Label:** Loan
> **Add Definition:** Financial aid that requires repayment with terms determined by the entity providing the loan.
> **Add Broader:** financialAid:General
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Update:** 
> **URI:** financialAid:FederalSubsidizedLoan
> **Remove Definition:** Federal Subsidized Loan
> **Remove Broader:** financialAid:General
> **Add Definition:** Loan from the Federal Government that is based on financial needs of the student and is intended to offset costs related to education, living, and resources.
> **Add Broader:** financialAid:Loan

**Update:** 
> **URI:** financialAid:FederalUnsubsidizedLoan
> **Remove Definition:** Federal Unsubsidized Loan
> **Remove Broader:** financialAid:General
> **Add Definition:** Loan from the Federal Government that does not require evidence of the financial needs of the student, and is intended to offset costs related to education, living, and resources.
> **Add Broader:** financialAid:Loan

**Create:** 
> **URI:** financialAid:StateLocalLoan
> **Add Label:** State or Local Loan
> **Add Definition:** Loan from a state, province, region, and/or local government that is intended to offset costs related to education, living, and resources.
> **Add Broader:** financialAid:Loan
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Update:** 
> **URI:** financialAid:InstitutionalLoan
> **Remove Definition:** Institutional Loan
> **Remove Broader:** financialAid:General
> **Add Definition:** Loan from an educational institution that is intended to offset costs related to education, living, and resources.
> **Add Broader:** financialAid:Loan

**Update:** 
> **URI:** financialAid:ParentPLUSLoan
> **Remove Definition:** Parent PLUS Loan
> **Remove Broader:** financialAid:General
> **Add Definition:** Loan from the Federal Government available to the parents of dependent students.
> **Add Broader:** financialAid:Loan

**Update:** 
> **URI:** financialAid:PrivateLoan
> **Remove Definition:** Private Loan
> **Remove Broader:** financialAid:General
> **Add Definition:** Loan from a private entity, including employers, that is intended to offset costs related to education, living, and resources.
> **Add Broader:** financialAid:Loan

**Update:** 
> **URI:** financialAid:OtherLoan
> **Remove Definition:** Other Loan
> **Remove Broader:** financialAid:General
> **Add Definition:** Loan from one or more other sources that is intended to offset costs related to education, living, and resources.
> **Add Broader:** financialAid:Loan

**Create:** 
> **URI:** financialAid:WorkBased
> **Add Label:** Work Based
> **Add Definition:** Financial compensation for participating in work-based learning opportunities.
> **Add Broader:** financialAid:General
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Create:** 
> **URI:** financialAid:AcademicAssistantship
> **Add Label:** Academic Assistantship
> **Add Definition:** Paid employment in which students receive tuition or other reimbursement for the tasks they perform for faculty members, departments, and/or educational institutions.
> **Add Broader:** financialAid:WorkBased
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Update:** 
> **URI:** financialAid:FederalWorkStudy
> **Remove Definition:** Federal Work Study
> **Remove Broader:** financialAid:General
> **Add Definition:** Program funded by the Federal Government designed to provide part-time jobs for students to offset educational expenses.
> **Add Broader:** financialAid:WorkBased

**Create:** 
> **URI:** financialAid:StateLocalWork
> **Add Label:** State or Local Work
> **Add Definition:** Program funded by a state, province, region, and/or local government designed to provide work for students to offset educational expenses.
> **Add Broader:** financialAid:WorkBased
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Update:** 
> **URI:** financialAid:OtherOnCampusWork
> **Remove Definition:** Other On-Campus Work
> **Remove Broader:** financialAid:General
> **Add Definition:** Paid non-academic employment available for students on an educational institution’s campus.
> **Add Broader:** financialAid:WorkBased

**Create:** 
> **URI:** financialAid:CoOperative
> **Add Label:** Co-Operative
> **Add Definition:** Paid work experience utilized by approved career and technical education programs to combine classroom and on-the-job training and education which provides academic credit for structured job experience.
> **Add Broader:** financialAid:WorkBased
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Create:** 
> **URI:** financialAid:Internship
> **Add Label:** Internship
> **Add Definition:** Time-limited work offered by an organization approved by a qualified institution to gain experience or satisfy requirements for another resource.
> **Add Broader:** financialAid:WorkBased
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Create:** 
> **URI:** financialAid:Apprenticeship
> **Add Label:** Apprenticeship
> **Add Definition:** Combination of on-the-job training and related instruction that meets standards in which workers learn the practical and theoretical aspects of a skilled occupation.
> **Add Broader:** financialAid:WorkBased
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Create:** 
> **URI:** financialAid:Military
> **Add Label:** Military
> **Add Definition:** Financial aid available to active duty service members, veterans, and/or their qualified family members.
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Create:** 
> **URI:** financialAid:VEAP
> **Add Label:** Veteran Educational Assistance Program
> **Add Definition:** Financial assistance provided to qualified active duty service members and veterans as a matching program that is intended to offset educational expenses.
> **Add Broader:** financialAid:Military
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Update:** 
> **URI:** financialAid:Post911GIBill
> **Remove Definition:** Post 9-11 GI Bill
> **Remove Broader:** financialAid:Veteran
> **Add Label:** Post 9-11 GI Bill
> **Add Definition:** Financial assistance provided to qualified active duty service members, veterans, and qualified family members that is based on military service and intended to offset costs related to education, living, and resources.
> **Add Broader:** financialAid:Military

**Update:** 
> **URI:** financialAid:DoDTuitionAssistance
> **Remove Definition:** Department of Defense Tuition Assistance
> **Remove Broader:** financialAid:Veteran
> **Add Definition:** Financial assistance provided to qualified active duty service members and their families for voluntary off-duty educational programs in support of professional and personal self-development goals.
> **Add Broader:** financialAid:Military

**Create:** 
> **URI:** financialAid:VocationalRehabilitation
> **Add Label:** Vocational Rehabilitation
> **Add Definition:** Financial for veterans with a qualifying service-connected disability rating for training or education related to pursuit of a career or career-related resource.
> **Add Broader:** financialAid:Military
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Create:** 
> **URI:** financialAid:StateLocalMilitaryAssistance
> **Add Label:** State or Local Military Assistance
> **Add Definition:** Financial aid provided by a state or local government to active duty service members, veterans, and/or qualified family members.
> **Add Broader:** financialAid:Military
> **Add InScheme:** ceterms:FinancialAssistance
> **Add Status:** vs:pending

**Deprecate:** 
> **URI:** financialAid:Veteran
> **Remove Status:** vs:stable
> **Add Status:** vs:deprecated
> **Add Superseded By:** financialAid:VEAP

**Deprecate:** 
> **URI:** financialAid:Assistantship
> **Remove Status:** vs:stable
> **Add Status:** vs:deprecated
> **Add Superseded By:** financialAid:AcademicAssistantship

**Deprecate:** 
> **URI:** financialAid:OtherFederalGrant
> **Remove Status:** vs:stable
> **Add Status:** vs:deprecated
> **Add Superseded By:** financialAid:FederalGrant

**Deprecate:** 
> **URI:** financialAid:StateLoan
> **Remove Status:** vs:stable
> **Add Status:** vs:deprecated
> **Add Superseded By:** financialAid:StateLocalLoan

**Deprecate:** 
> **URI:** financialAid:StateWork
> **Remove Status:** vs:stable
> **Add Status:** vs:deprecated
> **Add Superseded By:** financialAid:StateLocalWork

Note: I think it's better to eat the above `deprecate`s now while we're making all these changes and not have to worry about the URI differences later.

**Comment by jeannekitchens** [comment]
@siuc-nate shouldn't this be closed?  If so, please close it as this financial assistance concept scheme was updated in August 2020.  If not, please update this with the issue.

**Comment by siuc-nate** [comment]
Yes, sorry - I forgot to do that.

The above changes were made in CTDL and added to the history tracking.
