### ISSUE TITLE
Enable Financial Assistance Profile to indicate the amount of financial assistance available

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#652]
Per our 2/28/2020 meeting with representatives from Kansas:

The [Financial Assistance Profile](https://credreg.net/ctdl/terms#FinancialAssistanceProfile) class does not currently have a means of indicating the amount of financial assistance available; only a description, type, and webpage link.

I believe this may have been an oversight - we should discuss the best way to include this information.  I suspect it will be done via schema:QuantitativeValue.  This would enable expressing both exact values and value ranges, as well as typing and other descriptive information.

This would be useful in documenting the information on this page:
https://ksdegreestats.org/ProspectusController?app=prospectus&ficeInstId=001925&programNbr=26

See also #651

**Comment by stuartasutton** [comment]
Nothing wrong with a property with a range of schema:QuantitativeValue. The FinancialAssistance class was deliberately sparse including only the very obvious knowing that instances would inform us of useful additions.

**Comment by siuc-nate** [comment]
Proposal:
> **URI:** ceterms:financialAssistanceValue
> **Label:** Financial Assistance Value
> **Definition:** Description of the type and amount of financial assistance available.
> **Domain:** ceterms:FinancialAssistanceProfile
> **Range:** ceterms:QuantitativeValue

The name of the property is meant to be in line with other properties like creditValue and transferValue.

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
