### ISSUE TITLE
qdata property domain updates (3 properties)

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#653]
In working through an example with @siuc-nate for the Kansas City Kansas Community College, three property domain declarations made working through the example awkward. To eliminate the problem, I propose three revised domains for the following properties:
1. `qqata:earningsDistribution` (current domain: `qdata:SubjectProfile`);
2. `qdata:earningsAmount` (current domain: `qdata:SubjectProfile`); and
3. `qdata:administrationProcess` (current domain: `qdata:SubjectProfile`); 

The domain should be changed to the following:
1. `qqata:earningsDistribution` (new domain: `qdata:DataProfile`);
2. `qdata:earningsAmount` (new domain: `qdata:DataProfile`); and
3. `qdata:administrationProcess` (new domain: `qdata:DataSetProfile`);

The resulting domain graphic:

<img width="1000" alt="2020-03-01 EE_Earnings_Model" src="https://user-images.githubusercontent.com/2939046/75694256-1313cc80-5c5d-11ea-9900-433cb6102610.png">

**Comment by siuc-nate** [comment]
These changes have been made in pending QData and noted in the history tracking.
