### ISSUE TITLE
Additional properties for qdata

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#654]
There are three properties we need to add to the qdata namespace. The first was a property existing in the original modeling that somehow was left off and two are new:

>**Property:** qdata:meetEmploymentCriteria
**Definition:** Number of holders that meet the prescribed employment threshold in terms of earnings or time engaged in work as defined for the data set (employmentDefinition)."
**Domain:** qdata:DataProfile
**Range:** schema:QuantitativeData

>**Property:** qdata:regionalEmploymentRate
**Definition:** Rate computed by dividing the number of holders or subjects in the region meeting the data set's criteria of employment (meetEmploymentCriteria) by the number of holders or subjects in the region for which data was available (dataAvailable).
**Subproperty Of:** qdata:employmentRate
**Domain:** qdata:DataProfile
**Range:** schema:QuantitativeData

>**Property:** qdata:regionalEarningsDistribution
**Definition:** Reference to an entity describing median earnings as well as earnings at various percentiles for holders or subjects in the region.
**Subproperty Of:** qdata:earningsDistribution
**Domain:** qdata:DataProfile
**Range:** schema:QuantitativeData

**Comment by siuc-nate** [comment]
These changes have been made in pending QData and noted in the history tracking.
