### ISSUE TITLE
Handling concentrations within a degree (beyond identifying)

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#655]
DATA MODELING ISSUE:
Tiffin University published multiple "Bachelor of Arts in Education" credentials, each with a different degree concentration.  Determine whether these are distinct credentials that are correctly published separately, or if they should have been published as one single credential with multiple concentrations (and who should authoritatively make that decision.

**Comment by siuc-nate** [comment]
In my opinion, the criteria is about the same as what we use for guidance on when to issue a new CTID vs when to just update the version of an existing CTID:
1) It is ultimately up to the publisher of the data to decide, but:
2) The best practice is to issue a new CTID whenever the new credential and the old credential can't be readily swapped for one another in most situations (i.e. the requirements or significance of the two credentials are sufficiently different)

It's a bit ambiguous but I think we'd run into other issues if we tried to make it more specific.

In Tiffin's case, it's a (hopefully) simple question of whether or not a Bachelor of Arts with one concentration could be readily swapped for a Bachelor of Arts in another concentration. Unfortunately, [looking at](https://credentialfinder.org/credential/6562/Bachelor_of_Arts_in_Education) [a few](https://credentialfinder.org/credential/6575/Bachelor_of_Arts_in_Education) [examples](https://credentialfinder.org/credential/6559/Bachelor_of_Arts_in_Education), there isn't enough information to be able to tell one way or another - something like the requirements being different would be an indicator that they should probably be separate.  But if all we have to go on is the label of the concentration itself, then we'll have to leave it up to Tiffin.

**Comment by siuc-nate** [comment]
Example diagram:
https://drive.google.com/file/d/13NpJJt7eaijrSIE1c6wMrRq86GgND68x/view?usp=sharing

**Comment by siuc-nate** [comment]
Per our 10-13-2020 meeting:

This has been handled by https://credreg.net/ctdl/terms/degreeConcentration
