### ISSUE TITLE
need a property for credentialAwarded

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/Schema-Development#660]
The Google [Job training](https://developers.google.com/search/docs/data-types/job-training#program-guidelines) product recommends that the [`schema:occupationalCredentialAwarded`](https://schema.org/occupationalCredentialAwarded) is used (and they probably should use `educationalCredentialAwarded`).

The closest match in CTDL is [`ceterms:isRequiredFor`](https://credreg.net/ctdl/terms#isRequiredFor) however there is a difference in that `ceterms:isRequiredFor` may be necessary but not sufficient, whereas `occupational`/`educationalCredentialAwarded` implies that the associated program is sufficient. (That the programme is sufficient to prepare students for an occupation is a requirement for listing in Google Job Training search, preparatory courses aren't accepted.)

A `credentialAwarded` term in CTDL defined as "the credential for which successful completion of this learning opportunity and/or assessment is sufficient" would remove this mis-match

**Comment by siuc-nate** [comment]
We capture this, but through a different set of properties:

Credential -> requires -> Condition Profile
Which then branches off to (usually) one or more requirements, such as 
- Assessment
- Learning Opportunity
- Competency
- Other Credential
- etc.

So for a program that is entirely sufficient to earn a Credential, the data would be:

Credential -> requires -> ConditionProfile -> targetLearningOpportunity -> LearningOpportunityProfile.

**Comment by siuc-nate** [comment]
Additionally, since CTDL is Credential-centric (ie the Credential tells you what it requires), a property like that could lead to a mismatch in the data where a Credential defines two or more requirements, but the data for an Assessment or Learning Opportunity has a `credentialAwarded` value pointing back to that Credential, meaning a consumer of the data might not notice that there are more requirements than just the one.

**Comment by philbarker** [comment]
So the "provided there are no other requirements" & "assuming not other values present" conditions are things that we need to check for before exporting schema.org markup for Job Training.

That's OK, provided Assessments within programs aren't listed separately from the Learning Opportunities that are those programs.  (In which case you would have to tweak the condition accordingly.)

**Comment by siuc-nate** [comment]
Correct - if the conditions match up, then we can export data using `schema:occupationalCredentialAwarded`.  Otherwise, we'll have to work out something else.

**Comment by philbarker** [comment]
Added note to the mapping spreadsheet
