### ISSUE TITLE
How to specify no renewal period - starting with guidance

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/Schema-Development#663]
NavyCOOL has licences and certifications. Many of these will have a renewal period. 
Some have a value of 'lifetime'. This of course implies there is no renewal period. 
However, people cannot interpret the absence of a renewal period to imply there is no renewal necessary. 
What would the recommendations be for this scenario?
We appear to be limited to text, without adding another property.

**Comment by jeannekitchens** [comment]
@mparsons-ce identify the properties relevant to this and provide some actual examples.

**Comment by mparsons-ce** [comment]
The issue is in regard to the property renewlFrequency:

> https://credreg.net/ctdl/terms/renewalFrequency#renewalFrequency
> Frequency with which the credential needs to be renewed.
> Range: schema:Duration

If an organization has a, say licence, that has a renewal period of 'lifetime', there is no means to express this. As noted the absence of a renewal frequency cannot always be interpreted as meaning there is no renewal required.

**Comment by siuc-nate** [comment]
>cannot always be interpreted as meaning there is no renewal required.

Doesn't "lifetime" effectively mean exactly that, though?

**Comment by mparsons-ce** [comment]
The question relates to being able to express that renewals are not required. 

Sample from NavyCOOL
![image](https://user-images.githubusercontent.com/58825866/78051990-17a6d000-7344-11ea-9e31-a59212956317.png)

**Comment by stuartasutton** [comment]
If you are using schema:Duration, why not just put it in schema:description

**Comment by mparsons-ce** [comment]
The schema:Duration is the ISO8601 string.

**Comment by siuc-nate** [comment]
So the recommendation is to handle these cases by using the description field of a Duration Profile instead of any of its min/max/exact duration properties, correct?

**Comment by siuc-nate** [comment]
The approach will be to use schema:description.
