### ISSUE TITLE
Remove schema:QuantitativeValue from the domain of ceterms:description

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#665]
Back when Quantitative Value was added to CTDL, as the main issue (#564) for that class clearly indicates that schema:description is meant to be used. However, the main issue for QData (#628) clearly shows that ceterms:description should be used.  

Right now the class has both properties.  We should be using schema:description to maximize compatibility across schemas.

Enter as Pending May 14, 2020:
**Remove:**
> **Subject:** ceterms:description
> **Predicate:** schema:domainIncludes
> **Object:** schema:QuantitativeValue

(I'll also need to double check the schema management system's entries for QData to make sure schema:description correctly shows up in that class's internal data and not just the display as well)

**Comment by siuc-nate** [comment]
@stuartasutton Why was this closed?

**Comment by stuartasutton** [comment]
Accident?

**Comment by siuc-nate** [comment]
This change has been made in pending QData and noted in the history tracking.
