### ISSUE TITLE
Add ceterms:hasPart to certerms:Pathway

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#667]
Based on our 4-1-2020 meeting:

The ceterms:Pathway class needs to be able to reference all of its member components, regardless of whether or not they are destination components.  We should extend the domain of ceterms:hasPart to include ceterms:Pathway.

It may also make sense to add ceterms:isPartOf to all of the PathwayComponent subclasses.

**Comment by mparsons-ce** [comment]
@siuc-nate With the addition of hasPart, what is the difference for the use of hasChild?
hasChild definition:

> The referenced resource is lower in some arbitrary hierarchy than this resource.

hasPart:

>  Indicates a separately identifiable and independently useful component of the entity.

Or is hasChild meant to mean a direct child, rather just somewhere lower in the arbitrary hierarchy?

**Comment by siuc-nate** [comment]
Correct - hasChild/isChildOf indicate direct relationships while hasPart/isPartOf indicate "in there somewhere" relationships (including the direct ones), just as with competency frameworks and competencies (though we do not have hasPart in CTDL-ASN)

**Comment by stuartasutton** [comment]
No, CTDL-ASN does not and as far as I know, there has been no call for such a property in ASN's 20 years.

**Comment by siuc-nate** [comment]
Is that to promote the nature of competencies as being things that can appear in multiple frameworks?  If so, that kind of bottom-up strategy makes sense (the competency "knows" what it's a part of").  

For something that's more top-down like a pathway, where the nodes are (presumably) all always only ever part of that pathway, it may make more sense to use hasPart and not need isPartOf.

Thoughts?

**Comment by stuartasutton** [comment]
Nate, if we were fully RDF enabled top to bottom, we'd not expect
inclusions of inverses (e.g. isPartOf/hasPart). Each triple store that
consumes the data can generate the inverse of any value it's given if it
needs it locally.

**Comment by siuc-nate** [comment]
This issue has been replaced by #672

**Comment by siuc-nate** [comment]
@stuartasutton To confirm:
Should ceterms:Pathway have ceterms:hasPart or not? It's present on the spreadsheet referenced in #672 but no mention is made there of using hasPart.

**Comment by mparsons-ce** [comment]
per meeting on July 16, 2020 Stuart agreed that ceterms:Pathway will NOT have the property ceterms:hasPart .
