### ISSUE TITLE
Add ceterms:isPartOf to all Pathway Component classes

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#672]
Per our 4-14-2020 meeting:
As part of implementing the changes [here](https://docs.google.com/spreadsheets/d/1wYEEvaDX0TGRrdsHwFEkxloJCctas0E3fNdilLSHWb8/edit#gid=0), we will add ceterms:isPartOf to all of the PathwayComponent subclasses.

> **Subject:** ceterms:isPartOf
> **Predicate:** schema:domainIncludes
> **Object**: ceterms:PathwayComponent subclasses

> **Subject:** ceterms:isPartOf
> **Predicate:** schema:rangeIncludes
> **Object:** ceterms:Pathway

**Comment by stuartasutton** [comment]
Yes. This is correct.

**Comment by siuc-nate** [comment]
Reopening this to make sure it gets done

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
