### ISSUE TITLE
Confirm status of CTID in PathwayComponent

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/Schema-Development#674]
@stuartasutton @jeannekitchens @siuc-nate 

The [google sheet for pathway terms](https://docs.google.com/spreadsheets/d/1wYEEvaDX0TGRrdsHwFEkxloJCctas0E3fNdilLSHWb8/edit#gid=0) currently does not have a property of CTID for any of the pathway components. 
In the past it was going to be included. 
I want to confirm if a CTID is going to be property, and as a result a PathwayComponent would be a top level document in the registry. 

So this is basically a decision request (1):
    Will there be a CTID in PathwayComponent

The same back and forth has occurred for ComponentCondition. So decision request (2):
    Will there be a CTID in ComponentCondition

**Comment by stuartasutton** [comment]
I am somewhat indifferent to the answer to either of the two decision requests regarding CTID. I am not indifferent to whether PathwayComponents are identified by URI--they must not be bnodes. While I cannot immediately think of any reason for referencing a ComponentCondition outside the context of the graph in which it is created, I also can think of no good reason they should not also be identified by URI.

**Comment by siuc-nate** [comment]
@stuartasutton Not that I don't necessarily agree about PathwayComponents needing a CTID, but I am curious what the use case would be for referencing, from an external source, something that is meant to just be a pointer to something else.

**Comment by jeannekitchens** [comment]
@siuc-nate did this get supplanted by another GitHub issue per discussion last week? If so, please refer to it and close this issue.

**Comment by siuc-nate** [comment]
Yes. This will be handled by #678
