### ISSUE TITLE
Create a PathwaySet class

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#677]
Per our 4-16-2020 meeting:

Create a PathwaySet class to collectively describe and reference sets of pathways:
> **URI:** ceterms:PathwaySet
> **Label:** Pathway Set
> **Definition:** A roadmap of multiple related pathways that lead to one or more destinations.
> **Properties:** 
> - ceterms:name
> - ceterms:description
> - ceterms:subjectWebpage
> - ceterms:ctid
> - ceterms:hasPathway
> - ceterms:ownedBy
> - ceterms:offeredBy

Create a hasPathway property to go with it:
> **URI:** ceterms:hasPathway
> **Label:** Has Pathway
> **Definition:** A pathway related to this resource.
> **Domain:** ceterms:PathwaySet
> **Range:** ceterms:Pathway

**Comment by jeannekitchens** [comment]
@siuc-nate goes with the pathway updates in pending to be released this month.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
