### ISSUE TITLE
Add ceterms:ctid to PathwayComponent subclasses

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#678]
Per our 4-16-2020 meeting:
In order to be able to build a graph of Pathway Components and be able to reference them externally, and ensure that they work like any other object with a URI in the registry, they need to have CTIDs.

**Add:**
> **Subject:** ceterms:ctid
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:PathwayComponent subclasses

**Comment by jeannekitchens** [comment]
@siuc-nate for April Pathway terms updates.

**Comment by jeannekitchens** [comment]
@siuc-nate part of April pathway updates.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
