### ISSUE TITLE
Determine if Completion Certificate Subclass of Credential is Needed

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#679]
State of NJ has indicated none of the current certificate definitions work for a certificate of completion.  I have requested examples so we can review them and determine if an additional subclass is needed.   

For example:

Completion Certificate - Credential to acknowledge completion of requirements for an assignment, activity, course, or task.

Examples 
http://www.njtrainingsystems.org/Program/Default.aspx?ProgramID=39652
http://www.njtrainingsystems.org/Program/Default.aspx?ProgramID=47764

**Comment by stuartasutton** [comment]
This category is somewhat of a bottomless pit. There are also "certificates of attendance". For example, as Director of DCMI, I used to get request every year for such a certificates from attendees to the annual conference that have no other value than identifying where someone was at a certain point in time (of course they could have spent the conference time sight seeing for all I know) or as proof of attendance for purposes of expense reimbursement (again, flimsy proof). Certificates of Attendance have no such inherent notion of "completion of requirements".

**Comment by jeannekitchens** [comment]
Providing this draft definition.

Certificate of Completion- Acknowledgement of completion of an activity, assignment, or training.

**Comment by siuc-nate** [comment]
Participation Certificate - Acknowledgement of participation in, completion of, or attendance of an activity, assignment, or training.

**Comment by jeannekitchens** [comment]
This is the suggested definition from State of New Jersey .

Certificate of Completion- Acknowledgement of completion of an activity, assignment, or training that may or may not be preparation for another credential.

**Comment by siuc-nate** [comment]
Cleaning that up a bit:
Completion Certificate - Acknowledgement of completion of an activity, assignment, or training that may be preparation for another credential.

Do we want to include the notions of "participation" or "attendance" as we discussed in our previous meeting about this?

**Comment by philbarker** [comment]
@siuc-nate I think you have changed the meaning to exclude those credentials that may not (are not permitted to) lead to another credential, which seems the opposite of the original intent.

**Comment by siuc-nate** [comment]
I would think that "may" implies "may not", otherwise it would be "must" - but I guess it doesn't hurt to include "or may not".

**Comment by philbarker** [comment]
> I would think that "may" implies "may not", otherwise it would be "must"

May may mean "permitted", so:
CompletionCertificateA may be used as preparation for CredentialZ
CompletionCertificateB may not be used as preparation for CredentialZ

Better keep as "may or may not" to avoid doubt.

**Comment by siuc-nate** [comment]
Makes sense.

Updated proposal:
Completion Certificate - Acknowledgement of completion of an activity, assignment, or training that may or may not be preparation for another credential.

**Comment by siuc-nate** [comment]
> **URI:** ceterms:CompletionCertificate
> **Label:** Completion Certificate
> **Definition:** Acknowledgement of completion of an activity, assignment, training, or other requirements.
> **Comment:** This credential may or may not be preparation for another credential.

**Comment by siuc-nate** [comment]
@jeannekitchens I don't receive notifications if you tag me by updating my post.  I just now saw this.

**Comment by siuc-nate** [comment]
> **URI:** ceterms:CompletionCertificate
> **Label:** Completion Certificate
> **Definition:** Acknowledgement of participation with or completion of an assignment, training or other activity.
> **Comment:** This credential may or may not be preparation for another credential.

**Comment by siuc-nate** [comment]
Just to confirm - we are currently including "participation" as part of the definition of this. @philbarker had advised that this is not the same thing as completion. I see his point.  Should we remove "participation" so that the definition reads:
> Acknowledgement of completion of an assignment, training or other activity.

@jeannekitchens @stuartasutton @mparsons-ce @philbarker please confirm.

**Comment by stuartasutton** [comment]
That is correct, they are not the same. The certificates DCMI provides on request to conference attendees are for attendance/participation where there is no sense of completion. Just trying to avoid creating yet another certificate for these activities when it can be satisfied here with a simple "or".

**Comment by siuc-nate** [comment]
So should it instead be:
> Acknowledgement of attendance of, participation with, and/or completion of an assignment, training, or other activity
?
My worry is that lumping these together will mean that this credential isn't specific enough to "completion" and we could end up with three new credentials as subclasses of this one rather than just two or maybe three standalone credentials given the route we're on.

**Comment by stuartasutton** [comment]
That's ok with me, Nate, but, please, no complaints about proliferation later.

**Comment by philbarker** [comment]
+1 for completion only; it's what NJ asked for

**Comment by siuc-nate** [comment]
>That's ok with me, Nate, but, please, no complaints about proliferation later.

My concern in that post was that combining everything into one credential type would force us to revisit this problem and create an additional set of credential types, rather than being a solution in and of itself.  That would lead to us having a rather useless umbrella credential type in addition to one that solves this problem.  That's what I am trying to avoid.

>+1 for completion only; it's what NJ asked for

I updated the proposal [here](https://github.com/CredentialEngine/Schema-Development/issues/679#issuecomment-625835878) with the more specific definition.

**Comment by manndoris-CEPI** [comment]
Are we talking about a specific group? (K-12, IHE etc.) Also the term "Credential" generally is used to identify when someone has successfully completed a prescribed curricula and is considered qualified in a specific activity or area. Dictionary: "a qualification, achievement, personal quality, or aspect of a person's background, typically when used to indicate that they are suitable for something." This items sounds more like a completion status to me.

**Comment by jeannekitchens** [comment]
@manndoris-CEPI thanks so much for asking about this type of credential.  The credential and its definition are not aimed at a particular group or grade level.  If a credential, such as a completion certificate, is intended for a specific group or grade level, there are other CTDL properties for indicating this (for any type of credential).  All types of credentials with the CTDL are subclasses of [Credential ](https://credreg.net/ctdl/terms#Credential).  The definition of CTDL Credential matches the definition you quote.  The Completion Certificate is a type of credential that is offered and earned for meeting completion criteria determined by the credential offerer.   In this case, the criteria is completion.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
