### ISSUE TITLE
Credit/point value for PathwayComponent

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#680]
Back in the Pathway work group days in collaboration with the pathways work in IMS CLR (placed on hold), there was a "pointValue" property (which was brought over to CTDL pathway) for describing entities for which "points" are available. There was a second property for "defaultCredit" which we did not bring over because its was ambiguous (default?). BUT, with issues around ceterms:creditValue settled (using a range of schema:QuantitativeValue), should we add ceterms:creditValue to the PathwayComponent subclasses, or, should we just tweak the definition of "pointValue" to read:

> Points or credits associated with this resource, or possible points or credits.

**Comment by siuc-nate** [comment]
I think we need to settle the issues ( #590 ) with how credit is described first before we go changing anything in pathways.

**Comment by siuc-nate** [comment]
This is covered by #690 and #692
