### ISSUE TITLE
Create terms to describe Transfer Value

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#683]
Per our 4-23-2020 meeting:

We need to create terms to allow organizations to describe the credit transfer, work experience transfer, or other similar notions that they assert about other things.

The new class, TransferValueProfile, would be a top-level class akin to CostManifest or ConditionManifest.  This profile could be useful by credentialing organizations as well as organizations that many credit transfer recommendations.  We need to look at whether or not "Recommendation" needs to be appended to the terms and have the definitions so they can cover both 3rd party credit transfer recommendations and 1st party credit transfer.

**New Class:**
> **URI:** ceterms:TransferValueProfile
> **Label:** Transfer Value Profile
> **Definition:** Description of transfer value for a resource.
> **Properties:** ceterms:name, ceterms:description, ceterms:ctid, ceterms:subjectWebpage, ceterms:startDate, ceterms:endDate, ceterms:statusType (#675), ceterms:identifier (#666), ceterms:transferValue (see #590 for credit-related items), ceterms:ownedBy, ceasn:derivedFrom

**Updated Properties:**
**Add:**
> **Subject:** ceterms:owns
> **Predicate:** schema:rangeIncludes
> **Object:** ceterms:TransferValueProfile

**Add:**
> **Subject:** ceterms:recognizes
> **Predicate:** schema:rangeIncludes
> **Object:** ceterms:TransferValueProfile

**Remove:**
> **Subject:** ceterms:recognizes
> **Predicate:** rdfs:comment
> **Object:** "Credential, learning opportunity or assessment that the agent recommends, endorses, indicates preference for, or otherwise provides a positive judgment."

**Add:**
> **Subject:** ceterms:recognizes
> **Predicate:** rdfs:comment
> **Object:** "Resource that the agent recommends, endorses, indicates preference for, or otherwise provides a positive judgment."

**Add:**
> **Subject:** ceasn:derivedFrom
> **Predicate:** schema:rangeIncludes
> **Object:** ceterms:TransferValueProfile

**New Properties:**
> **URI:** ceterms:transferValue
> **Label:** Transfer Value
> **Definition:** A suggested or articulated credit- or point-related transfer value.
> **Domain:** ceterms:TransferValueProfile
> **Range:** schema:QuantitativeValue

> **URI:** ceterms:transferValueFrom
> **Label:** Transfer Value From
> **Definition:** Resource that provides the transfer value described by this resource, according to the entity providing this resource.
> **Domain:** ceterms:TransferValueProfile
> **Range:** ceterms:Credential (and subclasses), ceterms:LearningOpportunityProfile, ceterms:AssessmentProfile

> **URI:** ceterms:transferValueFor
> **Label:** Transfer Value For
> **Definition:** Resource that accepts the transfer value described by this resource, according to the entity providing this resource.
> **Domain:** ceterms:TransferValueProfile
> **Range:** ceterms:Credential (and subclasses), ceterms:LearningOpportunityProfile, ceterms:AssessmentProfile

> **URI:** ceterms:learningMethodDescription
> **Label:** Learning Method Description
> **Definition:** Description of the learning methods for a resource.
> **Domain:** ceterms:LearningOpportunityProfile, ceterms:AssessmentProfile
> **Range:** rdf:langString

> **URI:** ceterms:assessmentMethodDescription
> **Label:** Assessment Method Description
> **Definition:** Description of the assessment methods for a resource.
> **Domain:** ceterms:AssessmentProfile, ceterms:LearningOpportunityProfile
> **Range:** rdf:langString

Sample:
```
{
  "@graph": [
    {
    "@id": "https://credentialengineregistry.org/resources/ce-zxyw",
      "@type": "ceterms:QACredentialOrganization",
      "ceterms:name": { "en": "ACE" },
      "ceterms:owns": [
        "https://credentialengineregistry.org/resources/ce-abc123..."
      ]
    },
    {
      "@type": "ceterms:TransferValueProfile",
      "@id": "https://credentialengineregistry.org/resources/ce-abc123...",
      "ceterms:ctid": "ce-abc123...",
      "ceterms:statusType": "statusCategory:Active",
      "ceterms:transferValueFrom": "https://credentialengineregistry.org/resources/ce-0039492...",
      "ceterms:codedNotation": "0276",
      "ceterms:identifier": [
        {
          "@type": "ceterms:IdentifierValue",
          "ceterms:identifierValueCode": "0276",
          "ceterms:name": { "en": "ACE Course Code" }
        }
      ]
      "ceterms:transferValue": {
        "@type": "schema:QuantitativeValue",
        "schema:description": { "en": "In the upper-division baccalaureate degree category, 3 semester hours in fire science, fire technology, or introduction to chemistry (11/19)." },
        "schema:value": 3,
        "schema:unitText": "creditUnit:DegreeCredit"
      },
      "ceterms:startDate": "2019-11-1",
      "ceterms:endDate": "2022-10-31",
      "ceterms:name": { "en": "Advanced Science of Hazardous Materials Response" },
      "ceterms:description": { "en": "The course objective is for students to analyze and evaluate the science component to implement a risk-based response at a hazardous materials/weapons of mass destruction (WMD) incident." },
      "ceterms:ownedBy": [
        "https://credentialengineregistry.org/resources/ce-zxyw"
      ]
    },
    {
      "@type": "ceterms:LearningOpportunityProfile",
      "@id": "https://credentialengineregistry.org/resources/ce-0039492...",
      "ceterms:name": { "en": "Advanced Science of Hazardous Materials Response" },
      "ceterms:description": { "en": "The course objective is for students to analyze and evaluate the science component to implement a risk-based response at a hazardous materials/weapons of mass destruction (WMD) incident." },
      "ceterms:offeredBy": [
        "https://credentialengineregistry.org/resources/ce-1234567...",
      ],
      "ceterms:estimatedDuration": [
        {
          "@type": "ceterms:DurationProfile",
          "schema:exactDuration": "P6D"
        },
        {
          "@type": "ceterms:DurationProfile",
          "schema:exactDuration": "PT45H30M"
        }
      ],
      "ceterms:teaches": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:targetNodeDescription": { "en": "Upon completion of the course, the student will be able to apply the fundamentals of hazardous materials/weapons of mass destruction (WMD) response; evaluate classification technologies and their capabilities, applications and limitations; evaluate the field identification technologies and their capabilities, applications and limitations; and apply the science component of a risk-based response process to actual and simulated hazardous materials/weapons of mass destruction (WMD) scenarios." }
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:targetNode": "https://credentialengineregistry.org/resources/ce-0283905..."
        }
      ],
      "ceterms:learningMethodDescription": { "en": "The methods of instruction include audio visual materials, practical exercises, learner presentations, lecture, discussion, and classroom exercise. The general course topics include." },
      "ceterms:assessmentMethodDescription": { "en": "The methods of assessment include graded group activity, presentations, examinations, and performance rubrics (checklists) with a minimum passing score of 70 percent." }
    }
  ]
}

```

![image](https://user-images.githubusercontent.com/21346519/81832996-c7a35780-9504-11ea-88c3-c98dc6e9d81c.png)

**Comment by jeannekitchens** [comment]
We likely will need a transfer value type but to set this up to pilot with our partner may not need it initally.  However, we know the following use cases need to be enabled:
1. credit transfer value for military experience.
2. credit transfer value for prior learning assessment.
3. credit transfer value for completing courses or exams.

**Comment by siuc-nate** [comment]
That essentially boils down to transfer value for work experience and/or education experience, which is in alignment with all of the other "educational/occupational" notions we run into in other contexts.  And in the end, all of that is expressed as some combination of descriptive text and/or competencies, so I think we're pretty close to what we need.

**Comment by mparsons-ce** [comment]
@siuc-nate Confirming profile properties. The example uses codedNotation and the property list at the top does not. The property list included ceterms: identifier. Is the latter to be used instead of codedNotation?

**Comment by siuc-nate** [comment]
Probably - we need to solve the related github issue first.

**Comment by jeannekitchens** [comment]
@stuartasutton @siuc-nate @mparsons-ce need to be sure subjects and CIP codes are included.

**Comment by siuc-nate** [comment]
Instead of using the various targetAssessment/LearningOpportunity/Credential properties, which are intentionally somewhat ambiguous, would it make more sense (in terms of future-proofing) to use two properties like:

> **URI:** ceterms:transferValueFrom
> **Label:** Transfer Value From
> **Definition:** Resource that provides the transfer value described by this resource, according to the entity providing this resource.
> **Domain:** ceterms:TransferValueProfile
> **Range:** ceterms:Credential (and subclasses), ceterms:LearningOpportunityProfile, ceterms:AssessmentProfile

> **URI:** ceterms:transferValueFor
> **Label:** Transfer Value For
> **Definition:** Resource that accepts the transfer value described by this resource, according to the entity providing this resource.
> **Domain:** ceterms:TransferValueProfile
> **Range:** ceterms:Credential (and subclasses), ceterms:LearningOpportunityProfile, ceterms:AssessmentProfile

In the ACE use case, only the former would be used, but this would also allow other use cases where both the provider and recipient programs/assessments are known and need to be indicated (where just saying "targetLearningOpportunity" would be too vague).

The use of "according to the entity providing this resource" is to ensure that it is understood that the resource providing the TransferValueProfile is the one making the assertions, rather than those other resources themselves.

**Comment by siuc-nate** [comment]
@jeannekitchens 
>need to be sure subjects and CIP codes are included.

I updated the proposal in the first post to include `ceterms:subject` and `ceterms:instructionalProgramType`

**Comment by jeannekitchens** [comment]
@siuc-nate @stuartasutton we also need to be sure that all terms proposed for Transfer Value that are useful to Credential, Learning Opp, or Assessment are proposed to be included with those classes.  For example, the assessment and learning method terms.

**Comment by stuartasutton** [comment]
@siuc-nate & @jeannekitchens, we need to return to the domain model and extend it to make sure that it enables both *credit value services* and *articulation agreements* as noted in the Transfer Value Proposal document: https://docs.google.com/document/d/1wYjLePVZORQN8DgXE3ox66jviZXyEc4wvuWFFSwinfk/edit#. Currently, the model handles *services* such as ACE, but not *agreements*. 

Nate's comment above at  https://github.com/CredentialEngine/Schema-Development/issues/683#issuecomment-623548955 touches on this difference. Updating the model to accommodate *agreements* would force us to deal with the "vagueness" Nate notes in the meaning of `targetLearningOpportunity`. That property is NOT vague when we consider *services* like ACE; but, vagueness is triggered by its use with *agreements* where such relationships are more aptly handled using `ceterms:advancedStandingFrom` and `ceterms:isAdvancedStandingFor`. However, I do not agree that `ceterms:advancedStandingFrom` is appropriate with *services* given the property's suggestive overtones of "from/to" since *services* have uses that have no "from/to" intension.

**Comment by siuc-nate** [comment]
Agreed, hence my suggestion for two separate properties to indicate the "from" and the "for" sides of value description.  That allows covering use cases where one or both ends of the value description are known, including some potential future case where a particular learning opportunity might receive a specific amount of value from some other, more ambiguous source (like a generic high school diploma or GED rather than a specific one).

**Comment by siuc-nate** [comment]
My above suggestion would also require using two separate properties instead of `targetProvidedBy` to distinguish between the organization that provides the "from" resource and the organization that provides the "for" resource.

**Comment by siuc-nate** [comment]
Per our 5-12-2020 meeting:

The original post has been updated with a raft of changes to enable both the ACE use case and a transfer articulation use case.

**Comment by siuc-nate** [comment]
I have updated the proposal to use `owns` and `ownedBy` instead of both `owns` and `offers` (and their inverses), since this seems more semantically correct.

**Comment by siuc-nate** [comment]
Per our 5-14-2020 meeting:

New terms below will be moved from vs:pending to vs:unstable when the release goes live.

**Add:**
> **URI:** ceterms:TransferValueProfile
> **Label:** Transfer Value Profile
> **Definition:** Description of transfer value for a resource.
> **Properties:** ceterms:name, ceterms:description, ceterms:ctid, ceterms:subjectWebpage, ceterms:startDate, ceterms:endDate, ceterms:statusType (#675), ceterms:identifier (#666), ceterms:transferValue (see #590 for credit-related items), ceterms:ownedBy, ceasn:derivedFrom

**Updated Properties:**
**Add:**
> **Subject:** ceterms:owns
> **Predicate:** schema:rangeIncludes
> **Object:** ceterms:TransferValueProfile

**Add:**
> **Subject:** ceterms:recognizes
> **Predicate:** schema:rangeIncludes
> **Object:** ceterms:TransferValueProfile

**Remove:**
> **Subject:** ceterms:recognizes
> **Predicate:** rdfs:comment
> **Object:** "Credential, learning opportunity or assessment that the agent recommends, endorses, indicates preference for, or otherwise provides a positive judgment."

**Add:**
> **Subject:** ceterms:recognizes
> **Predicate:** rdfs:comment
> **Object:** "Resource that the agent recommends, endorses, indicates preference for, or otherwise provides a positive judgment."

**Add:**
> **Subject:** ceasn:derivedFrom
> **Predicate:** schema:rangeIncludes
> **Object:** ceterms:TransferValueProfile

**New Properties:**
> **URI:** ceterms:transferValue
> **Label:** Transfer Value
> **Definition:** A suggested or articulated credit- or point-related transfer value.
> **Domain:** ceterms:TransferValueProfile
> **Range:** schema:QuantitativeValue

> **URI:** ceterms:transferValueFrom
> **Label:** Transfer Value From
> **Definition:** Resource that provides the transfer value described by this resource, according to the entity providing this resource.
> **Domain:** ceterms:TransferValueProfile
> **Range:** ceterms:Credential (and subclasses), ceterms:LearningOpportunityProfile, ceterms:AssessmentProfile

> **URI:** ceterms:transferValueFor
> **Label:** Transfer Value For
> **Definition:** Resource that accepts the transfer value described by this resource, according to the entity providing this resource.
> **Domain:** ceterms:TransferValueProfile
> **Range:** ceterms:Credential (and subclasses), ceterms:LearningOpportunityProfile, ceterms:AssessmentProfile

> **URI:** ceterms:learningMethodDescription
> **Label:** Learning Method Description
> **Definition:** Description of the learning methods for a resource.
> **Domain:** ceterms:LearningOpportunityProfile, ceterms:AssessmentProfile
> **Range:** rdf:langString

> **URI:** ceterms:assessmentMethodDescription
> **Label:** Assessment Method Description
> **Definition:** Description of the assessment methods for a resource.
> **Domain:** ceterms:AssessmentProfile, ceterms:LearningOpportunityProfile
> **Range:** rdf:langString

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.

**Comment by siuc-nate** [comment]
Per our 5-19-2020 meeting:
Remove Transfer Value Profile from the domain and range of ceterms:derivedFrom

**Comment by siuc-nate** [comment]
Also **add** to unstable:
**> URI:** ceterms:valueEndorsement
**> Label:** Value Endorsement
**> Definition:** The referenced resource establishes or recommends an equivalent transfer value.
**> Domain:** ceterms:TransferValueProfile
**> Range:** ceterms:TransferValueProfile

**Comment by siuc-nate** [comment]
Both of the above changes have been made in pending CTDL and updated in the history tracking.
