### ISSUE TITLE
Pathways: Need to update 2 context files

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#689]
The following properties are missing from context files needed for pathways:

(1) /ctdlasn/ missing:
>ceterms/precedes

(2) /ctdl/ missing:
>asn:hasProgressionModel
asn:hasProgressionLevel
ceasn:hasChild
skos:notation
ceterms:componentDesignation

**Comment by siuc-nate** [comment]
This should be fixed now.  It looks like we meant to combine the context files anyway at some point in the past, but there was a bug with how it worked.  Try again and let me know.

**Comment by jeannekitchens** [comment]
@stuartasutton can this be closed?

**Comment by stuartasutton** [comment]
Before closing, can Nate clarify "combine the context files"? Does it mean that we are now using a single context file or two identical context files? Is a single context file, which is it?

**Comment by siuc-nate** [comment]
Both URIs will return the same data/same context file.
