### ISSUE TITLE
Pathway/CourseComponent add ceterms:creditValue

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#690]
ceterms:CourseComponent needs to have ceterms:creditValue added (not required); additionally, add ceterms:CourseComponent to the domain of ceterms:creditValue.

Determine policy implication  (not required)

**Comment by siuc-nate** [comment]
Change to make:
**Add:**
> **Subject:** ceterms:creditValue
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:CourseComponent

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
The registry policy has been updated with the pending changes.
