### ISSUE TITLE
Add keyword to ceterms Pathway

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/Schema-Development#691]
Currently Pathway doesn't have a Keyword property. Jeanne has mentioned that this should probably be added.

**Comment by stuartasutton** [comment]
My sense is that conceptKeyword and contentTerm should be added to as many
entities as rationally possible.

**Comment by siuc-nate** [comment]
Proposal:

**Add:**
> **Subject:** ceterms:keyword
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Pathway

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
