### ISSUE TITLE
Change range of ceterms:pointValue from float to schema:QuantitativeValue

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#692]
Making this change is to standardize the range treatment of both creditValue and pointValue.

**Comment by siuc-nate** [comment]
Changes to make:
**Remove:**
> **Subject:** ceterms:pointValue
> **Predicate:** schema:rangeIncludes
> **Object:** xsd:float

**Add:**
> **Subject:** ceterms:pointValue
> **Predicate:** schema:rangeIncludes
> **Object:** schema:QuantitativeValue

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
