### ISSUE TITLE
Remove the subclass assertion from JournemanCertificate & MasterCertificate

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#693]
Both [ceterms:JouneymanCertificate](https://purl.org/ctdl/terms/JourneymanCertificate) and  [ceterms:MasterCertificate](https://purl.org/ctdl/terms/MasterCertificate) have been declared erroneously as subclasses of [ceterms:ApprenticeshipCertificate](https://purl.org/ctdl/terms/ApprenticeshipCertificate).  See at [https://credreg.net/page/typeslist](https://credreg.net/page/typeslist): 

<img width="1021" alt="Screen Shot 2020-05-13 at 6 58 18 AM" src="https://user-images.githubusercontent.com/2939046/81822017-733daf00-94e7-11ea-80c1-e6f6b95af6cc.png">

The subclass assertion should be removed from both.

**Comment by siuc-nate** [comment]
Changes to make:

**Remove:**
> **Subject:** ceterms:JourneymanCertificate
> **Predicate:** rdfs:subClassOf
> **Object:** ceterms:ApprenticeshipCertificate

> **Subject:** ceterms:MasterCertificate
> **Predicate:** rdfs:subClassOf
> **Object:** ceterms:ApprenticeshipCertificate

**Add:**
> **Subject:** ceterms:JourneymanCertificate
> **Predicate:** rdfs:subClassOf
> **Object:** ceterms:Certificate

> **Subject:** ceterms:MasterCertificate
> **Predicate:** rdfs:subClassOf
> **Object:** ceterms:Certificate

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
