### ISSUE TITLE
Add ceterms:requiredForParentCompletion property on ceterms:PathwayComponent

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#697]
A ceterms:PathwayComponent (and it's subclasses) needs a way of identifying **whether or not** it is required for fulfillment of its parent ceterms:PathwayComponent. It is necessary even where the parent Component has a condition requiring selection of only a subset of its child Component--i.e., all siblings in the sibling array from which choices may be made need the be able to indicate whether they are needed for completion of the parent. 

To handle this need, we propose the addition of a ceterms:requiredForParentCompletion defined as: 
>"An indicator whether or not the pathway component being described is required for successful completion of its parent component." 

**Domain:** ceterms:PathwayComponent
**Range** xsd:boolean

**Comment by siuc-nate** [comment]
Isn't this already handled by ComponentCondition?  Just use one to point at the nodes the parent absolutely requires.

Example:
```
{
	"@type": "ceterms:BasicComponent",
	"ceterms:description": { "en": "Complete Course A and Course B and a choice between Courses C, D, and E" },
	"ceterms:hasCondition": [
		{
			"@type": "ceterms:ComponentCondition",
			"ceterms:requiredNumber": 2,
			"ceterms:targetComponent": [
				"https://.../CourseA",
				"https://.../CourseB"
			]
		},
		{
			"@type": "ceterms:ComponentCondition",
			"ceterms:requiredNumber": 1,
			"ceterms:targetComponent": [
				"https://.../CourseC",
				"https://.../CourseD",
				"https://.../CourseE"
			]
		}
	]
}
```

**Comment by siuc-nate** [comment]
In addition, if there's ever a case where a node has more than one parent, it won't be possible to tell which parent(s) that boolean is referring to.

```
[
  {
    "@type": "ceterms:BasicComponent",
    "@id": "Basic1",
    "ceasn:hasChild" [
      "Basic3",
      "Basic4"
    ]
  }
  {
    "@type": "ceterms:BasicComponent",
    "@id": "Basic2",
    "ceasn:hasChild" [
      "Basic3",
      "Basic5"
    ]
  }
  {
    "@type": "ceterms:BasicComponent",
    "@id": "Basic3",
    "ceterms:requiredForParentCompletion": true
  }
  {
    "@type": "ceterms:BasicComponent",
    "@id": "Basic4"
  }
  {
    "@type": "ceterms:BasicComponent",
    "@id": "Basic5"
  }
]
```

**Comment by siuc-nate** [comment]
Also, I don't think things should describe properties of other things, to the extent that we can help it.  In my opinion, the parent should instead list the components that it requires for completion.  Instead of:
`I know the thing over there well enough to assert that I am required for that`
we want:
`I require that`
As the parent node is the authoritative one that "knows" its own requirements.  This matters a little less in the sense that pathways tend to be one cohesive unit of data from the same publisher, but I still think it's better for something to describe itself than to describe something else.

**Comment by stuartasutton** [comment]
No. Component condition handles what’s required (selection-wise) for THIS component and requiredForParentCompletion is for the PARENT.

Sent from my iPhone

> On Jul 2, 2020, at 8:08 AM, siuc-nate <notifications@github.com> wrote:
> Also, I don't think things should describe properties of other things, to the extent that we can help it.
> 
If it were the badge making that assertion, I might agree. But it’s the pathway making it...which is one cohesive unit as you note. The “rule” you state is too categorical, Nate. Sometimes it’s not appropriate to make such assertions and sometimes it is appropriate and useful.

**Comment by stuartasutton** [comment]
Nate, a componentNode cannot have a parent in a different pathway...the
Badge a component node represents obviously can.

**Comment by siuc-nate** [comment]
That still doesn't solve the problem I highlighted [here](https://github.com/CredentialEngine/Schema-Development/issues/697#issuecomment-653059731).  And I understand the property would be on the child node - but the description of what is required for what is already handled, unless I am missing something.  Can you provide an example showing something being required for something else that is handled by this and can't be handled by ComponentCondition?

> a componentNode cannot have a parent in a different pathway

The situation in my example would be nodes in the same pathway, unless we intend to strictly enforce only hierarchical tree structures as pathways.

**Comment by stuartasutton** [comment]
Then make it an object property with a range of PathwayComponent instead of boolean. If there are the very occasional multiple parents, it can reference any for which the assertion is valid.

**Comment by siuc-nate** [comment]
This?:
```
{
	"@type": "ceterms:BasicComponent",
	"@id": "component1"
},
{
	"@type": "ceterms:BasicComponent",
	"@id": "component2",
	"ceterms:requiredForParentCompletion": [
		"component1"
	]
},
{
	"@type": "ceterms:BasicComponent",
	"@id": "component3",
	"ceterms:requiredForParentCompletion": [
		"component1"
	]
},
{
	"@type": "ceterms:BasicComponent",
	"@id": "component4",
	"ceterms:requiredForParentCompletion": [
		"component1"
	]
}
```

Wouldn't this be simpler?:
```
{
	"@type": "ceterms:BasicComponent",
	"@id": "component1",
	"ceterms:requiredForCompletion": [
		"component2",
		"component3",
		"component4"
	]
},
{
	"@type": "ceterms:BasicComponent",
	"@id": "component2"
},
{
	"@type": "ceterms:BasicComponent",
	"@id": "component3"
},
{
	"@type": "ceterms:BasicComponent",
	"@id": "component4"
}
```

I still don't see how this solves a problem that isn't already solved, though.  Do you have an example showing the specific use case this meets that isn't already met?

**Comment by stuartasutton** [comment]
@siuc-nate , you changed this from being a bottom up assertion (I am necessary to my parent completion) to a top down (here's the children that are necessary to complete me)...which you are correct is already covered.

I am going to drop the proposal and close this issue for the time being.
