### ISSUE TITLE
Backlog - Potential for Additional Certificates

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#700]
Real world use cases are needed so this is to log this request as a follow up to the Certificate of Completion class addition.  

Per a CLAG member, there is hard core evidence for the below types of certificates:
Assessment Based Certificates – Both ANSI and ICE/NCCA accredited organizations that award Assessment Based Certificates
Certificate of Participation and Certificate of Achievement are often given by Professional Societies and Universities.  You can google and find hundreds of examples.

Lumina uses these terms all the time.  In our work with APLU, we use these terms and the Universities understand the terms.

**Comment by siuc-nate** [comment]
> Assessment Based Certificate

`ceterms:Certificate -> ceterms:requires -> ceterms:AssessmentProfile`

> Certificate of Participation

This would probably have to be another class as we discussed during the creation of `ceterms:CertificateOfCompletion`

> Certificate of Achievement

We'll need a definition, because this just sounds like a `ceterms:Certificate` otherwise.

**Comment by jeannekitchens** [comment]
We can reopen this if there is a need and can confirm definitions.
