### ISSUE TITLE
Occupations, Jobs, Work Roles, and Tasks

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#701]
This issue is to consolidate the various issues surrounding the Occupation, Job, Work Role, and Task classes.
#662 #644 #623 #694 

Proposal:
---
**Create four new classes:**
> **URI:** ceterms:Occupation
> **Label:** Occupation
> **Definition:** Profession, trade, or career field that may involve training and/or a formal qualification.
> **Properties:** ceterms:ctid, ceterms:name, ceterms:description, ceasn:comment, ceterms:versionIdentifier, ceterms:subjectWebpage, ceterms:keyword, ceterms:occupationType, ceterms:industryType, ceterms:hasJob, ceterms:hasWorkRole, ceterms:identifier, ceterms:classification, ceterms:sameAs, ceasn:abilityEmbodied, ceasn:skillEmbodied, ceasn:knowledgeEmbodied

> **URI:** ceterms:Job
> **Label:** Job
> **Definition:** Set of responsibilities based on work roles within an occupation as defined by an employer.
> **Comment:** Job describes an abstraction or template that specific job postings or openings could be instances of.
> **Properties:** ceterms:ctid, ceterms:name, ceterms:description, ceasn:comment, ceterms:versionIdentifier, ceterms:subjectWebpage, ceterms:keyword, ceterms:occupationType, ceterms:industryType, ceterms:hasOccupation, ceterms:offeredBy, ceterms:hasWorkRole, ceterms:hasTask, ceasn:abilityEmbodied, ceasn:skillEmbodied, ceasn:knowledgeEmbodied, ceterms:identifier, ceterms:classification, ceterms:sameAs

> **URI:** ceterms:WorkRole
> **Label:** Work Role
> **Definition:** Collection of tasks and competencies that embody a particular function in one or more jobs.
> **Properties:** ceterms:ctid, ceterms:name, ceterms:description, ceasn:comment, ceterms:versionIdentifier, ceterms:hasTask, ceasn:abilityEmbodied, ceasn:skillEmbodied, ceasn:knowledgeEmbodied, ceterms:identifier, ceterms:classification

> **URI:** ceterms:Task
> **Label:** Task
> **Definition:** Specific activity, typically related to performing a function or achieving a goal.
> **Properties:** ceterms:ctid, ceterms:name, ceterms:description, ceasn:comment, ceterms:versionIdentifier, ceasn:abilityEmbodied, ceasn:skillEmbodied, ceasn:knowledgeEmbodied, ceasn:hasChild, ceasn:isChildOf, ceasn:listID, ceterms:identifier, ceterms:classification

**Drop one class to avoid confusion with ceterms:Task**
> **URI:** ceterms:TaskProfile

**Create several new properties:**
> **URI:** ceterms:hasOccupation
> **Label:** Has Occupation
> **Definition:** Occupation related to this resource.
> **Domain:** ceterms:Job
> **Range:** ceterms:Occupation

> **URI:** ceterms:hasJob
> **Label:** Has Job
> **Definition:** Job related to this resource.
> **Domain:** ceterms:Occupation
> **Range:** ceterms:Job

> **URI:** ceterms:hasWorkRole
> **Label:** Has Work Role
> **Definition:** Work Role related to this resource.
> **Domain:** ceterms:Occupation, ceterms:Job
> **Range:** ceterms:WorkRole

> **URI:** ceterms:hasTask
> **Label:** Has Task
> **Definition:** Task related to this resource.
> **Domain:** ceterms:Job, ceterms:WorkRole
> **Range:** ceterms:Task

> **URI:** ceterms:hasSpecialization
> **Label:** Has Specialization
> **Definition:** More specialized profession, trade, or career field that is encompassed by the one being described.
> **Domain:** ceterms:Occupation
> **Range:** ceterms:Occupation

> **URI:** ceterms:isSpecializationOf
> **Label:** Is Specialization Of
> **Definition:** Less specialized profession, trade, or career field that encompasses the one being described.
> **Domain:** ceterms:Occupation
> **Range:** ceterms:Occupation

**Modify existing properties by adding domains or ranges:**
> **URI:** ceterms:ctid
> **Add Domain:** ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task

> **URI:** ceterms:name
> **Add Domain:** ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task

> **URI:** ceterms:description
> **Add Domain:** ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task

> **URI:** ceasn:comment
> **Add Domain:** ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task

> **URI:** ceterms:versionIdentifier
> **Add Domain:** ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task

> **URI:** ceterms:identifier
> **Add Domain:** ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task

> **URI:** ceterms:classification
> **Add Domain:** ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task

> **URI:** ceasn:knowledgeEmbodied
> **Add Domain:** ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task

> **URI:** ceasn:skillEmbodied
> **Add Domain:** ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task

> **URI:** ceasn:abilityEmbodied
> **Add Domain:** ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task

> **URI:** ceterms:subjectWebpage
> **Add Domain:** ceterms:Occupation, ceterms:Job

> **URI:** ceterms:keyword
> **Add Domain:** ceterms:Occupation, ceterms:Job

> **URI:** ceterms:industryType
> **Add Domain:** ceterms:Occupation, ceterms:Job

> **URI:** ceterms:occupationType
> **Add Domain:** ceterms:Occupation, ceterms:Job

> **URI:** ceterms:sameAs
> **Add Domain:** ceterms:Occupation, ceterms:Job

> **URI:** ceterms:offers
> **Add Range:** ceterms:Job

> **URI:** ceterms:offeredBy
> **Add Domain:** ceterms:Job

> **URI:** ceasn:listID
> **Add Domain:** ceterms:Task

> **URI:** ceasn:hasChild
> **Add Domain:** ceterms:Task
> **Add Range:** ceterms:Task

> **URI:** ceasn:isChildOf
> **Add Domain:** ceterms:Task
> **Add Range:** ceterms:Task

> **URI:** ceterms:identifier
> **Add Domain:** ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task

**Modify existing property definitions/comments/usage notes to accommodate the updated usage:**
> **URI:** ceasn:comment
> **Remove Definition:** Supplemental text provided by the promulgating body that clarifies the nature, scope or use of this competency.
> **Add Definition:** Supplemental text provided by the promulgating body that clarifies the nature, scope or use of this resource.
> **Remove Comment:** Use this property when the text provides useful context for this competency.
> **Add Comment:** Use this property when the text provides useful context for this resource.

> **URI:** ceterms:occupationType
> **Remove Comment:** For U.S. credentials, best practice is to identify an occupation using a framework such as the O\*Net. Other credentials may use any framework of the class ceterms:OccupationClassification, such as the EU's ESCO, ISCO-08, and SOC 2010.
> **Add Comment:** For U.S. resources, best practice is to identify an occupation using a framework such as the ONet. Other resources may use any framework of the class ceterms:OccupationClassification, such as the EU's ESCO, ISCO-08, and SOC 2010.

> **URI:** ceterms:industryType
> **Remove Comment:** Best practice in identifying industries for U.S. credentials is to provide the NAICS code using the ceterms:naics property. Other credentials may use the ceterms:industrytype property and any framework of the class ceterms:IndustryClassification.
> **Add Comment:** Best practice in identifying industries for U.S. resources is to provide the NAICS code using the ceterms:naics property. Other resources may use the ceterms:industrytype property and any framework of the class ceterms:IndustryClassification.

> **URI:** ceasn:listID
> **Remove Definition:** An alphanumeric string found in the source framework indicating the relative position of a competency in an ordered list of competencies such as "A", "B", or "a", "b", or "I", "II", or "1", "2".
> **Add Definition:** An alphanumeric string indicating the relative position of a resource in an ordered list of resources such as "A", "B", or "a", "b", or "I", "II", or "1", "2".

**Update the Registry policy as follows:**
> **Class:** ceterms:Occupation
> **Required:** ceterms:ctid, ceterms:name, ceterms:description
> **Recommended:** ceterms:subjectWebpage, ceterms:keyword, ceterms:occupationType, ceterms:industryType, ceterms:hasJob

> **Class:** ceterms:Job
> **Required:** ceterms:ctid, ceterms:name, ceterms:description
> **Recommended:** ceterms:subjectWebpage, ceterms:keyword, ceterms:occupationType, ceterms:industryType, ceterms:hasOccupation, ceterms:hasWorkRole, ceterms:offeredBy

> **Class:** ceterms:WorkRole
> **Required:** ceterms:ctid, ceterms:name
> **Recommended:** ceterms:description, ceterms:hasOccupation, ceterms:hasTask

> **Class:** ceterms:Task
> **Required:** ceterms:ctid, ceterms:description
> **Recommended:** ceterms:name, ceasn:hasChild, ceasn:isChildOf, ceasn:abilityEmbodied, ceasn:skillEmbodied, ceasn:knowledgeEmbodied

References:
---
Reference Folder:
https://drive.google.com/drive/folders/1IxYFi3Hkj1xy0uWApVp0sGSNy0eWQ1Id

Reference Spreadsheet:
https://docs.google.com/spreadsheets/d/1SMsoT2yZ7jgNSdr-okd90Rg614r133ELamesgOMUDPQ/edit?usp=drive_web&ouid=108566654743029319923

Reference Diagrams:
https://drive.google.com/drive/folders/1pD-Rc5z5uNzKyWu7cdcefNvYT8TGKq5A
![image](https://user-images.githubusercontent.com/21346519/86824901-60150e80-c054-11ea-8431-5c1f56824bd6.png)

**Comment by siuc-nate** [comment]
@stuartasutton Currently, https://credreg.net/ctdlasn/terms/taskEmbodied has a range of xsd:anyURI. Should it instead have a range of ceterms:Task?

**Comment by siuc-nate** [comment]
We should consider using ceterms:identifier (#666) in place of (or in addition to?) ceterms:codedNotation for Work Roles and possibly the other classes.

**Comment by stuartasutton** [comment]
Yup

**Comment by siuc-nate** [comment]
Proposal from #704:

Create two new properties, `ceterms:hasSpecialization` and `ceterms:isSpecializationOf` which would enable constructing a hierarchy of `ceterms:Occupation` classes.

@philbarker will provide definitions.

**Comment by philbarker** [comment]
Defintions
ceterms:hasSpecialization "more specialized profession, trade, or career field that is encompassed by the one being described"
ceterms:isSpecializationOf "less specialized profession, trade, or career field that encompasses the one being described"

**Comment by siuc-nate** [comment]
Per our 8-25-2020 meeting:
Proposal:

**Add:**
> **URI:** ceterms:hasSpecialization
> **Label:** Has Specialization
> **Definition:** More specialized profession, trade, or career field that is encompassed by the one being described.

**Add:**
> **URI:** ceterms:isSpecializationOf
> **Label:** Is Specialization Of
> **Definition:** Less specialized profession, trade, or career field that encompasses the one being described.

**Comment by siuc-nate** [comment]
Merged in #711

**Comment by siuc-nate** [comment]
To capture recent discussions:

We also need some kind of general property to enable categorizing or classifying Work Roles (and potentially other items, depending on what sample data reveals).  I'll get the ball rolling:

> **URI:** ceterms:category
> **Label:** Category
> **Definition:** Category or classification of the resource.
> **Domain:** ceterms:WorkRole (and potentially others - TBD)
> **Range:** ceterms:CredentialAlignmentObject

This would function a lot like ceasn:competencyCategory in that it provides a way to categorize/classify things, but with the benefit of being able to directly reference things where such categories exist as standalone, URI-referenceable entities.

**Comment by siuc-nate** [comment]
Discussion of ceterms:category (now ceterms:classification) is happening over in #715.  Go there for its resolution.

For the rest of the things in this thread, I have updated the original post to reflect the current state (including use of ceterms:classification and the removal of ceterms:codedNotation).  The original post now reflects the current/final proposal.

**Comment by siuc-nate** [comment]
It was a slog, but I think I got all of the changes from this issue into the schema management system and history tracking.  I'll handle the changes for identifier and classification as part of finishing off #715.  The rest should now be in pending CTDL.
