### ISSUE TITLE
learnMethod:Prerecorded

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#709]
In our transfer value data for [this example](https://github.com/CredentialEngine/Schema-Development/blob/master/Transfer%20Value%20Profile/ACE%20-%20Packet%20Switched%20Networks%20(With%20Current%20Properties).json), we have encountered some learning methods that we don't currently have concepts for:

"Methods of instruction include lecture, discussion, laboratory exercises, videotapes, and a final examination."

We have lecture, discussion, and laboratory exercises.  We don't have anything to cover videotapes.  I don't think we need "final examination" as a learning method (we have an equivalent assessment method).

But I think we could use another learning method (Definition and comment trimmed down from what's used in [this wikipedia article](https://en.wikipedia.org/wiki/Multimedia)):

> **URI:** learnMethod:Multimedia
> **Label:** Multimedia
> **Definition:** Combination of text, audio, images, animations, video, and/or interactive content.
> **Comment:** Multimedia contrasts with rudimentary media such as text-only or traditional forms of printed or hand-produced material.

This will also probably apply to a lot of courses going on nowadays as well.

**Comment by stuartasutton** [comment]
@siuc-nate, the definition's use of "combination of" may be interpreted as media that includes all of them. Perhaps: "Recorded media including text, audio, images, animations, video, and/or interactive content."

**Comment by siuc-nate** [comment]
"Recorded" somewhat clashes with "interactive" in some ways.

Perhaps:
"Combination of one or more types of media such as text, audio, images, animations, video, and/or interactive content."

Or maybe:
"Media consisting of text, audio, images, animations, video, and/or interactive content."
With a different comment: "Multimedia typically includes a combination of types of media, such as audio and video, or text and images."

I prefer the former.

**Comment by stuartasutton** [comment]
"Text" alone could be a book...not what's intended is it?

**Comment by jeannekitchens** [comment]
Who requested this?  Is this to propose adding a term here https://credreg.net/ctdl/terms#LearningMethod?

**Comment by siuc-nate** [comment]
@stuartasutton 
It is not what's intended, but, I don't think we need to split hairs too finely since we're trying to define this in the context of being a learning method type rather than strictly trying to draw the line at what is and isn't multimedia (arguably from the "multi" in the name, my definition above should use "two or more" rather than "one or more", but that would discount standalone audio, which we also don't want to do).  

I'm still open to working on the definition of course.  Maybe it would help if we focused less on the "type" and more on the "method" aspect of this being a learning method?  Something like:
**Definition:** "Presentation or review of media such as audio, video, images, animations, and/or interactive content."
**Comment:** "Multimedia goes beyond, but may also include, simple text content to provide a richer learning experience."

@jeannekitchens 
As indicated in my original post, this is a result of trying to map the values from the learning methods in our transfer value profile example to learning methods present in our schema.

**Comment by philbarker** [comment]
Multimedia is a content format, not a learning method. If multimedia content alone is being used, the learning method is likely [learnMethod:SelfPaced](https://purl.org/ctdl/vocabs/learnMethod/SelfPaced); in this case it seems likely the videos provide a self-paced supplement the lectures.

**Comment by siuc-nate** [comment]
It could also refer to videos/audio played in the classroom, which wouldn't be self-paced.  You are right that we aren't trying to describe media formats - we're trying to say "Learning by watching a video/listening to audio/looking at images/etc."

**Comment by siuc-nate** [comment]
Per our 9-14-2020 meeting:

"Multimedia" is too broad; use "Prerecorded" instead to narrow this down to video/audio that is prerecorded.

> **URI:** learnMethod:Prerecorded
> **Label:** Prerecorded
> **Definition:** Learning by using video, audio, or other prerecorded content.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
