### ISSUE TITLE
Support Education & Training to Jobs Use Case: Identify the work roles, tasks and competencies for a stage in an engineering lifecycle.

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#710]
@philbarker what additional properties are needed to support this use case?

For example, tasks could be characterized as operations or maintenance.  This works for engineered sytems where personnel often have a role of working on primarily one over the other.  For cybersecurity there's lifecycle management of networks, servers, and devices on the network.

**Comment by siuc-nate** [comment]
I think this is a data thing rather than a schema thing.  For example, you could create a work role that embodies the tasks relevant to a particular product's life cycle.  The properties to do so already exist.

In addition, many tasks will be applicable at multiple stages of a life cycle.

**Comment by philbarker** [comment]
@jeannekitchens we would need to be able to organise tasks by lifecycle, so a property to link a task to a concept scheme for lifecycle stages.

@siuc-nate The workforce categories in the [2017 NICE framework](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-181.pdf) (p11) have some element of lifecycle in them, and the work roles are listed against these categories on subsequent pages.

**Comment by philbarker** [comment]
Example life cycles 

- [ADDIE](https://en.wikipedia.org/wiki/ADDIE_Model) (Analysis, Design, Development, Implementation, Evaluation) 

- [CDIO](https://en.wikipedia.org/wiki/CDIO_Initiative) Conceive Design Implement Operate

**Comment by siuc-nate** [comment]
Example from the PDF @philbarker [linked above](https://github.com/CredentialEngine/Schema-Development/issues/710#issuecomment-680022768):
![image](https://user-images.githubusercontent.com/21346519/91214996-78f78300-e6d9-11ea-97e0-f4082cbdf605.png)

**Comment by philbarker** [comment]
The example I prepared of the NICE framework did not incorporate what they call "categories" listed above. These are groupings of specialties which don't to me seem like occupations. 

We could generalize this use case to a need to accomodate "classification"->(Concept)

Q: what would be domain? Tasks still makes sense to me: even though NICE presents them as groupings of specialties, the key entities in NICE are Task and WorkRole, so it is these that ultimately are being classified by these category.

**Comment by siuc-nate** [comment]
Merging this into #701 (see https://github.com/CredentialEngine/Schema-Development/issues/701#issuecomment-689826418 )
