### ISSUE TITLE
Update Definition for ceterms:codedNotation

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#712]
@stuartasutton you noted that we talked about revising ceterms:codedNotation and suggested, "A notation, also known as classification code, is a string of characters [such as "T58.5" or "303.4833"] used to uniquely identify a concept within the scope of a given concept scheme." (sameAs skos:notation).  The definition & existing comment strongly suggests that the range should be CredentialAlignmentObject/DefinedTerm. Current data could nevertheless be a blank node with the literal.  I'm tagging @siuc-nate on this a well to get this written up in the standard proposal format and merged with the Education & Training to Jobs master list of schema updates.

**Comment by siuc-nate** [comment]
Proposal:

**Remove:**
> **Subject:** ceterms:codedNotation
> **Predicate:** rdfs:comment
> **Object:** "Set of alpha-numeric symbols that uniquely identifies an item and supports its discovery and use."

**Add:**
> **Subject:** ceterms:codedNotation
> **Predicate:** rdfs:comment
> **Object:** "String of alpha-numeric characters that uniquely identifies an item within the scope of some framework, scheme, or other organizing mechanism."

**Comment by stuartasutton** [comment]
I'd like to see "classifies" as part of this definition:

Subject: ceterms:codedNotation
Predicate: rdfs:comment
Object: "String of alpha-numeric characters that uniquely identifies or classifies an item within the scope of some framework, scheme, or other organizing mechanism."

**Comment by siuc-nate** [comment]
Updated proposal:

**Remove:**
> **Subject:** ceterms:codedNotation
> **Predicate:** rdfs:comment
> **Object:** "Set of alpha-numeric symbols that uniquely identifies an item and supports its discovery and use."

**Add:**
> **Subject:** ceterms:codedNotation
> **Predicate:** rdfs:comment
> **Object:** "String of alpha-numeric characters that uniquely identifies or classifies an item within the scope of some framework, scheme, or other organizing mechanism."

Per @jeannekitchens the existing comment for codedNotation is: "Examples include the alpha-numeric code "CCSS.MATH.CONTENT.HSA.CED.A.2" identifying a node in the U.S. Common Core State Standards on creating equations in algebra, or, the code "8021" in the U.S. Standard Industrial Classification (SIC) for identifying the occupational context for "Offices and Clinics of Dentists"."

**Comment by siuc-nate** [comment]
This issue has been superseded by #715. Go there for the resolution.
