### ISSUE TITLE
Ensure harmonious definitions and guidance around codedNotation, identifier, category, etc.

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#715]
**Problems:**
- There does not appear to be much harmony in how identifiers are modeled and used, and guidance is lacking.
- There are disjoints between domains and ranges, and multiple outstanding proposals that are holding up other work.
- It's not obvious when to use one property over another.

**Objectives:**
- Take a step back and determine how to do this the "right" way regardless of our current implementation.
- Create a unified theory of identification across CTDL and CTDL-ASN that can be used to reliably determine what kind of identifier to use and when and how to use it.
- Ensure consistency across properties and classes in their usage, definitions, etc. across CTDL and CTDL-ASN.
- Ensure that our approach maps cleanly to schema.org for conversion to its properties (or use its terms outright).
- Ensure our approach works for a wide variety of identifiers from various sources.
- Determine how to handle [edge cases like composite and partial identifiers](https://github.com/CredentialEngine/Schema-Development/issues/666#issuecomment-681154448).

**Affected projects (beyond just general CTDL/CTDL-ASN use):**
- Transfer Value Profile (Need to determine what kind of identification to use for Transfer Value Profiles, Learning Opportunities, etc.)
- Pathways (Need to determine what kind of identification to use for Components)
- Occupation/Training to Jobs (Need to determine what kind of identification to use for Work Roles et al)
- Google Training (Need to determine what kind of schema.org class/properties to map identifiers to)
- Navy ARTT (Need to establish best practice/pattern for modeling these kinds of identifiers)

**Properties and ranges used to point to identifiers:**
[ceterms:codedNotation](https://credreg.net/ctdl/terms/codedNotation) -> xsd:string
[ceasn:codedNotation](https://credreg.net/ctdlasn/terms/codedNotation) -> xsd:string
[ceasn:altCodedNotation](https://credreg.net/ctdlasn/terms/altCodedNotation) -> xsd:string
[ceasn:identifier](https://credreg.net/ctdlasn/terms/identifier) -> xsd:anyURI
[ceterms:alternativeIdentifier](https://credreg.net/ctdl/terms/alternativeIdentifier) -> ceterms:IdentifierValue
[ceterms:versionIdentifier](https://credreg.net/ctdl/terms/versionIdentifier) -> ceterms:IdentifierValue
[ceterms:identifier](https://github.com/CredentialEngine/Schema-Development/issues/666) (proposed) -> ceterms:IdentifierValue
[ceterms:category](https://github.com/CredentialEngine/Schema-Development/issues/701#issuecomment-689826418) (proposed) -> ceterms:CredentialAlignmentObject -> skos:Concept
[ceasn:altIdentifier](https://github.com/CredentialEngine/Schema-Development/issues/599) (proposed) -> schema:PropertyValue

**Classes and properties used to identify things:**
[ceterms:IdentifierValue](https://credreg.net/ctdl/terms/IdentifierValue) (Already exists in CTDL and is used for most properties)
- ceterms:name -> rdf:langString
- ceterms:description -> rdf:langString
- ceterms:identifierType -> rdf:langString
- ceterms:identifierValueCode -> xsd:string

[skos:Concept](https://credreg.net/ctdlasn/terms/Concept) (Offers the flexibility of a concept/scheme but with the awkwardness of the Credential Alignment Object in the middle)
- skos:prefLabel -> rdf:langString
- skos:definition -> rdf:langString
- skos:inScheme -> skos:ConceptScheme
- skos:notation -> xsd:string

[schema:PropertyValue](https://schema.org/PropertyValue) (Comes directly from schema.org but has conflicting/confusing documentation on how it's meant to be used, [as Phil points out here](https://github.com/CredentialEngine/Schema-Development/issues/681#issuecomment-624676644))
- schema:name -> rdf:langString
- schema:propertyID -> xsd:anyURI
- schema:value -> xsd:string
- schema:identifier -> xsd:string

**Relevant Issues:**
- [Occupations, Jobs, Work Roles, and Tasks](https://github.com/CredentialEngine/Schema-Development/issues/701)
- [Mapping to identifier -> PropertyValue](https://github.com/CredentialEngine/Schema-Development/issues/681)
- [Create ceterms:identifier](https://github.com/CredentialEngine/Schema-Development/issues/666)
- [Add altIdentifier property to CTDL-ASN](https://github.com/CredentialEngine/Schema-Development/issues/599)
- [Update Definition for ceterms:codedNotation](https://github.com/CredentialEngine/Schema-Development/issues/712)

**Comment by siuc-nate** [comment]
To get the ball rolling:

The closest I have to a consistent way of determining what kind of data belongs with what kind of identifier property is [stated in some detail here](https://github.com/CredentialEngine/Schema-Development/issues/666#issuecomment-681111080), though it does not handle [certain edge cases](https://github.com/CredentialEngine/Schema-Development/issues/666#issuecomment-681154448).  Still, as a starting point, it can be summarized like this:

- A code is a `ceterms:codedNotation` if:
  - The code exclusively "resolves" (for lack of a better word) to the thing it is attached to 
  - The thing it is attached to is also the thing that explains what the code means
- A code is a `ceterms:identifier` if:
  - The code is exclusively assigned to the thing it is attached to
  - The code "resolves" (for lack of a better word) to some other thing that explains what the code means
- A code is a `ceterms:category` if:
  - The code is not necessarily exclusive to the thing it is attached to
  - The code "resolves" (for lack of a better word) to some other thing that explains what the code means

For example:
- `CCSS.MATH.CONTENT.HSA.CED.A.2` would "resolve" to exactly one (official) object which also provides an explanation of what that code means, thus it would be a `ceterms:codedNotation`
- An IPEDS ID, DUNS number, etc. (ignoring for a moment that these have dedicated properties already) would be assigned exclusively to one object (such as an organization) but "resolve" to some other thing (effectively a Concept) that provides an explanation of what the code means. Thus each of these would be a `ceterms:identifier`
- A NICE/NIST Specialty area would be assigned to multiple work roles and also be explained somewhere other than the work role itself, thus the specialty area would be a `ceterms:category`

However, these edge cases do not fall neatly into one of the rules above. Both come from the Navy project, specifically the GEIA 0007 part of it:
- `HGONGAA` is a composite code where each letter (or pair of letters in the case of the `AA` at the end) is a reference to a concept somewhere else. In essence, `H`, `G`, `O`, `N`, `G`, and `AA` are all (according to the rules above) `ceterms:category`s, but taken together (`HGONGAA`) they are a sort-of `ceterms:identifier` except that `HGONGAA` appears on multiple entities (it is not exclusive), which arguably makes it a `ceterms:category` except that, because it is a composite code formed from several other categories, no such singular category `HGONGAA` actually exists.
- Codes where _some_ instances of the code (such as `AA`) are predefined but other instances are deliberately left up to the creator of the data to define are sort of a cross between a `ceterms:category` and a `ceterms:codedNotation`

**Comment by siuc-nate** [comment]
There may be some advantages to simplifying things by just always using a certain class.

If we follow the chain of links from @philbarker 's [post here](https://github.com/CredentialEngine/Schema-Development/issues/681#issuecomment-624676644) to the [related schema.org issue here](https://github.com/schemaorg/schemaorg/issues/2549) and then on to the implied(?) solution to that issue [here](https://github.com/ESIPFed/science-on-schema.org/blob/master/guides/Dataset.md#identifier), we find a lot of guidance around the use of schema:PropertyValue which overlaps quite a bit with what our ceterms:IdentifierValue accomplishes.  The guidance is in a slightly different context but the most important/least confusing piece is here:

> - `schema:value` as the identifier value `10.5066/F7VX0DMQ`
> - `schema:propertyID` is the registry.identifiers.org URI for the identifier scheme `https://registry.identifiers.org/registry/doi`,
> - `schema:url` is the resolvable url (if one exists) for that identifier `https://doi.org/10.5066/F7VX0DMQ`.

Our ceterms:IdentifierValue lacks a means of referencing a URL or a scheme for the identifier (aside from what can be conveyed through its name and description fields).  So at first glance, `schema:PropertyValue` seems like a winner.

**However:**

PropertyValue's usage is not clear from its documentation:
- The guidance for PropertyValue gets muddier the further into that last article you go, and the properties don't seem to line up (e.g. `schema:propertyID` is actually the URI of the framework, not the property)
- The examples on schema.org for PropertyValue do not match what is in that article (e.g. use of "name" instead of "propertyID")
- Google does not match schema.org's examples here either

This ultimately results in having to [duplicate data in multiple fields](https://github.com/CredentialEngine/Schema-Development/issues/681#issuecomment-624676644), which is simply not something we want to burden our data publishers with.

Notably our ceterms:CredentialAlignmentObject could have a _lot_ of utility here, and the usage would fall neatly in line with how we use it for identifiers like `ceterms:industryType` and `ceterms:occupationType` and `ceterms:instructionalProgramType` and so on:
- `ceterms:codedNotation` as the identifier value `10.5066/F7VX0DMQ`
- `ceterms:framework` is the registry.identifiers.org URI for the identifier scheme `https://registry.identifiers.org/registry/doi`,
- `ceterms:targetNode` is the resolvable url (if one exists) for that identifier `https://doi.org/10.5066/F7VX0DMQ`.

As a bonus, it also has `ceterms:targetNodeName` and `ceterms:targetNodeDescription` so it also covers the ground covered by `ceterms:IdentifierValue` if it needs to do so.

So right now my proposal is to ditch ceterms:IdentifierValue entirely and use ceterms:CredentialAlignmentObject in its stead. This gives us the best of both worlds ("put the data here" and/or "reference the data somewhere else"), is already in use all over the place, and aligns with our usage for the aforementioned ____Type properties.

That would change our relevant identifier property set to look like this, which is way more consistent with the rest of CTDL:
[ceterms:codedNotation](https://credreg.net/ctdl/terms/codedNotation) -> xsd:string
[ceasn:codedNotation](https://credreg.net/ctdlasn/terms/codedNotation) -> xsd:string
[ceasn:altCodedNotation](https://credreg.net/ctdlasn/terms/altCodedNotation) -> xsd:string
[ceasn:identifier](https://credreg.net/ctdlasn/terms/identifier) -> xsd:anyURI
[ceterms:alternativeIdentifier](https://credreg.net/ctdl/terms/alternativeIdentifier) -> ceterms:CredentialAlignmentObject -> skos:Concept (if applicable)
[ceterms:versionIdentifier](https://credreg.net/ctdl/terms/versionIdentifier) -> ceterms:CredentialAlignmentObject -> skos:Concept (if applicable)
[ceterms:identifier](https://github.com/CredentialEngine/Schema-Development/issues/666) (proposed) -> ceterms:CredentialAlignmentObject -> skos:Concept (if applicable)
[ceterms:category](https://github.com/CredentialEngine/Schema-Development/issues/701#issuecomment-689826418) (proposed) -> ceterms:CredentialAlignmentObject -> skos:Concept (if applicable)
[ceasn:altIdentifier](https://github.com/CredentialEngine/Schema-Development/issues/599) (proposed) -> ceterms:CredentialAlignmentObject -> skos:Concept (if applicable)

**Comment by philbarker** [comment]
Here's my shot at a tabula rasa approach, based just on some principles, ignoring what CE does now:

Principles:
1. Identifiers are names for things. [note: a thing can have more than one name]
2. Good identifiers are unique (they name only one thing), resolvable (given the identifier you can find the thing or information about the thing) and persistent (they don't change with time)
3. The best identifiers are universal/global, i.e. they can be used beyond the context in which they were created and still be good.
4. Many different schemes exist for creating identifiers, e.g. ISBN, GUID, URN, DOI -- determining how good these are is left as an exercise for the reader
5. URNs have a privileged position in Linked Data (they suit a decentralized web) and specifically the HTTP URI scheme is regarded as the best (being unique, resolvable, and potentially persistent)
6. In other contexts other schemes have privileged positions
7. As well as identifying things individually it is useful to classify them, ie group them into classes.
8. In any given context some classification schemes are more important that others
9. Anything that has an individual existence can be identied: this includes physical objects, digital representations, events, concepts and metaphysical notions. 

From 7 & 9: the classes into which things are grouped when classifying them can be identified. 

Consequences
1. We should give primacy to HTTP URIs as the primary naming / identifying mechanism to facilitate access via the web to our and other people's resources.  This is the `@id` identifier in JSON-LD, and while we may choose to call it something else we should be clear that is what it is. (In RDF it is not a Literal, BTW, xsd:anyURI is a Literal, though we may store it as a string)
2. We should allow other identifiers, but as these are not web-native we will need to explain more about the scheme being used
3. We should allow for classification schemes to be used
4. In some contexts we may want to privilege certain schemes over others.

Additionally, I think we should avoid introducing discrepancies between names for properties in different namespaces.

**Comment by philbarker** [comment]
Here's my thoughts on Nate's proposal (and thank you Nate for digging through what is a frustratingly muddled and infuriatingly inconsistent area on schema.org)

* I would resist introducing a `ceterms:identifier` property that was at odds with the `ceasn:identifier` property. 
* Likewise, why `ceasn:altIdentifier` and not `ceasn:alternativeIdentifier` to be consistent with `ceterms:alternativeIdentifier`?
* It seems a shame to reject the concept of an IdentifierValue class just because schema.org has botched it. We could do it right and propose it to schema.org.
* I would not use the same class for identifiers as for categories. That's similar thinking to what got schema.org where it is. The class you use for categories will need identifiers, and so you'll wind up with identifiers that have identifiers, and if you find that confusing, don't do it.
* Also, if you want to make sure that classifiers don't get used as identifiers, use different classes for them.
* Alignment objects work OK for classification/categories (though http://schema.org/CategoryCode works too).
* Avoid pointing identifiers to Concepts.

In summary: "alignment" is close enough to "classification" to use alignment objects. I don't think alignment objects work for identification.

Whatever you use, I think you need a class for non-http URI identifiers that has the properties (or properties that map to): `identifierValue`, `identifierScheme`, `schemeURI` and a class for category codes which has the properties `identifier` [for the http URI], `codeValue`, `codeScheme`,  `schemeURI`

I would consider some naming convention for properties that clarifies whether they are for categorization purposes or identification, so `socClassification` never `socIdentifier` even though the value might be an identifier of a SOC code--but that boat may have sailed.

[I've probably used classified and categorized inconsistently, I mean the same thing]

Hope this helps.

**Comment by siuc-nate** [comment]
Thanks Phil, I appreciate you wading through my lengthy posts and going in-depth on your analysis.  I agree with your principles and think that's the kind of mindset we should have here.

With regard to your second post, I mostly follow it, but I got tripped up about here:
>Whatever you use, I think you need a class for non-http URI identifiers that has the properties (or properties that map to): `identifierValue`, `identifierScheme`, `schemeURI` and a class for category codes which has the properties `identifier` [for the http URI], `codeValue`, `codeScheme`,  `schemeURI`

I'm not quite sure I get what class(es?) you're proposing - can you provide some examples to illustrate how these would be used?

Also, if you could tie your points back to the actual classes/properties (both current and proposed) in terms of what we should (or shouldn't) do with them, that would be helpful as well.

**Comment by philbarker** [comment]
@siuc-nate sorry that what I wrote there was confusing. I didn't want to go too far without checking we were all in accord, so I deliberately wasn't suggesting a specific class, I just gave something between functional requirements and a straw man proposal for satisfying those reqs.

Specifically I didn't want preclude using `ceterms:CredentialAlignmentObject` for Category Codes. Ideally (given a blank slate) I would suggest using SKOS or `schema:CategoryCode`, or something very similar re-declared in the ceterms namespace. However, in drafting this reply, I find that when I try use `ceterms:CredentialAlignmentObject` for category codes it gets very confusing  (which will lead to the sort of confusion that brought us here). Essentially you're then saying an Alignment Object, which was designed to point to something with a Category Code, can be a Category Code; so it can point to itself. That is something we should avoid. Using Alignment Objects for Category Codes is building on a use case for the AlignmentObject (lack of linked data representation of things like Categories) that we are actually trying to eliminate.

Also, I am a bit iffy about some of the names we've been using. I've chosen several of them just to avoid name/Name clashes between properties and classes; other just fit with what we already have. For example I don't like `CategoryCode` for what actually represents a category (and the code used to name the category is one of the properties of that), I would prefer:
`(Resource)--[classification]-->(Category)`
`(Category)--[categoryCode]->"string"`

Commenting specifically on your proposal & what exists:

**No change to** 
> ceterms:codedNotation -> xsd:string
> ceasn:codedNotation -> xsd:string
> ceasn:altCodedNotation -> xsd:string
> ceasn:identifier -> xsd:anyURI

**Changes to**
> ceterms:alternativeIdentifier -> ceterms:CredentialAlignmentObject -> skos:Concept (if applicable)
> ceterms:versionIdentifier -> ceterms:CredentialAlignmentObject -> skos:Concept (if applicable)

Better to point these to an IdentifierValue. An identifier is not a Concept.

> ceterms:identifier (proposed) -> ceterms:CredentialAlignmentObject -> skos:Concept (if applicable)

I'm not sure what this is for. Call it something else so it doesn't get confused with ceasn:identifier, 

I note we already have ceterms:alternativeIdentifier which points IdentifierValue

> ceterms:category (proposed) -> ceterms:CredentialAlignmentObject -> skos:Concept (if applicable)

I could live with this but I think it would be better to: call this `classification` and have a new ceterms:Category, or just use skos:Concept directly.

> ceasn:altIdentifier (proposed) -> ceterms:CredentialAlignmentObject -> skos:Concept (if applicable)

Call this ceterms:alternativeIdentifier to be consistent with ceterms:alternativeIdentifier; point it to an IdentifierValue. 

**Additional changes:**
add `ceterms:identifier` -> xsc:anyURI to mirror ceasn, you should be able to handle http URIs for things not in the credential registry

Clean up `ceterms:IdentifierValue`
- _deprecate_ `description` on `IdentifierValue`, it shouldn't be necessary
- _keep_ identifierType (xsd:string), it will do for what I called `identifierScheme`; 
- _maybe add_ `identifierTypeUrl` (xsd:anyURL), it's an open question (to me) whether we need a URL to link to the identifier scheme (I called it `identifierSchemeURL`) but it is useful to disambiguate [SIC](https://www.gov.uk/government/publications/standard-industrial-classification-of-economic-activities-sic) from [SIC](https://www.osha.gov/pls/imis/sicsearch.html)
- _deprecate_ `name` on `IdentifierValue`, having it just creates confusion between name and identifierValueCode
- _keep_ identifierValueCode (xsd:string), it will do for what I called `identifierValue` and serves to avoid having a Class and property with nearly the same name

If you want to avoid the problems with using `ceterms:CredentialAlignmentObject` to point to concepts as well as represent concepts, and don't want to just use SKOS, I would:

add `ceterms:Category` ("A concept used to classify or categorize resources") with properties `identifier`, `categoryCode`, `codingScheme`, `schemeURI`

**Comment by siuc-nate** [comment]
Per our 9-14-2020 meeting:

Proposal (incomplete, to continue later):
- Deprecate/alter ceterms:codedNotation
- Deprecate ceasn:codedNotation, ceasn:altCodedNotation, ceasn:identifier, ceterms:alternativeIdentifier
- Modify the ceterms:IdentifierValue class, and create a new class for classification such that the classes cover:

Identifier:
- alphanumeric code itself (string) ceterms:codedNotation
- coding scheme name (langString) ceterms:frameworkName
- coding scheme (URI) ceterms:framework

Category:
- alphanumeric code itself (string) ceterms:codedNotation
- coding scheme name (langString) ceterms:frameworkName
- coding scheme (URI) ceterms:framework

Potential proposal per @philbarker:

URI: ceterms:IdentifierValue
Label: Identifier Value
Definition: TBD
Properties: ceterms:identifierType, ceterms:identifierValueCode, ceterms:identifierTypeURI
Referenced By: ceterms:identifier

URI: ceterms:Category
Label: Category
Definition: TBD
Properties: ceterms:identifier, ceterms:categoryCode, ceterms:codingScheme, ceterms:schemeURI
Referenced By: ceterms:classification

**Comment by philbarker** [comment]
I made some small edits

**Identifier:**
`-` Definition: Contextualized identifier for a resource.`

`+` Definition: Identifier and, where possible, information about the identifier scheme from which it is drawn.

`-` Usage Note: Where a specific property for an identifier exists, the best practice is to use that property instead of this one.

`+` Usage Note: Where a specific property for the identifier scheme exists, the best practice is to use that property instead of this one.


**ceterms:classification**
`-` Usage Note: Where a specific property for a classification exists, the best practice is to use that property instead of this one.

`+` Usage Note: Where a specific property for a classification scheme exists, the best practice is to use that property instead of this one.

**Comment by stuartasutton** [comment]
Adding to Phils comment at https://github.com/CredentialEngine/Schema-Development/issues/715#issuecomment-693274590, with the Usage Notes, consider adding to each at least one example of a "more specific property".

**Comment by siuc-nate** [comment]
The notion of "where available" kind of embeds policy into the definition and I think we should try to avoid that.  I prefer the original definition in that sense.

As for the usage notes, +1 to Stuart's suggestion, as it will help clarify the original intent of the usage note which was at the property level, not the scheme level:
> When a specific property for an identifier exists, such as ISBN, DUNS, CTID, etc., that property should be used instead of this one.
> When a specific property for a classification exists, such as NAICS, SOC, CIP, etc., that property should be used instead of this one.

Or, if we want to be more CTDL-centric:
> When a specific property for an identifier exists, such as CTID, DUNS, ISICV4, etc., that property should be used instead of this one.
> When a specific property for a classification exists, such as industryType, credentialType, organizationType, etc., that property should be used instead of this one.

**Comment by philbarker** [comment]
> The notion of "where available" kind of embeds policy into the definition and I think we should try to avoid that. 

Fair enough. My intent was to emphasize that it doesn't just point to an identifier, it's identifier and scheme.

>When a specific property for an identifier exists, such as ISBN, DUNS, CTID, etc., that property should be used instead of this one.

I had "When a _more_ specific property for an identifier _scheme_ exists" because 
a) the properties are for the schemes, not each identifier
b) sometimes the property is not for a single scheme, for example we have `ceterms:occupationType` and `ceterms:industryType` classifying Occupation, which are more specific, but not specific to a single scheme.

**Comment by siuc-nate** [comment]
I think using "identifier scheme" in the usage note is too scheme-centric while the property itself is identifier-centric.  Maybe something more like:
>When a more specific property for an identifier (based on that identifier's scheme) exists, such as [list of examples], that property should be used instead."

**Comment by siuc-nate** [comment]
Works for me.  Should we use the more general example list or the CTDL-centric one (or some third one)?

**Comment by philbarker** [comment]
CTDL-centric examples make sense to me

**Comment by stuartasutton** [comment]
I agree with Phil: CTDL-centric

**Comment by siuc-nate** [comment]
So to summarize, is the following correct?:

Definition for `ceterms:identifier`:
"Contextualized identifier for the resource."

Usage note for `ceterms:identifier`:
"When a more specific property exists, such as CTID, DUNS, ISICV4, etc., that property should be used instead."

Usage note for `ceterms:classification`:
"When a more specific property exists, such as credentialType, organizationType, industryType, etc., that property should be used instead."

**Comment by philbarker** [comment]
I don't understand that definition for identifier. If you want to remove "where available" from what I suggested, fine. However, I think we also noticed that the current definition for IdentifierValue isn't very good, so let's address that as well.  We could use almost the same definition for both, but how about:

Definition for `ceterms:identifier`:
"Identifier and information about the identifier scheme from which it is drawn."

Definition for `ceterms:IdentifierValue`:
"Means of unambiguously indentifying a resource, typically comprising a name or alphanumeric token, and a scheme for creating these names and assigning them to resources."

ISICV4 is the "International Standard of Industrial **Classification**" It should be listed as a more specific property for classification not identifier.

Some other examples if you want them:
identifiers: `ceterms:opeID` `ceterms:ncesID` `ceterms:leiCode` `ceterms:fein`
classifications: `ceterms:naics` `ceterms:isicV4`

**Comment by siuc-nate** [comment]
Following the above posts, how about these:
> **URI:** ceterms:identifier
> **Label:** Identifier
> **Definition:**  Alphanumeric identifier and information about its origin, context, or scheme.
> **Usage Note:** Where a more specific property for the identifier's origin, context, or scheme exists, such as ceterms:opeID, ceterms:ncesID, ceterms:leiCode, etc., the best practice is to use that property instead of this one.
> **Domain:** ceterms:Credential (and subclasses), ceterms:LearningOpportunityProfile, ceterms:AssessmentProfile, ceterms:PathwayComponent subclasses, ceterms:TransferValueProfile, ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task, ceterms:CredentialOrganization, ceterms:QACredentialOrganization
> **Range:** ceterms:IdentifierValue

> **URI:** ceterms:classification
> **Label:** Classification
> **Definition:** Category or classification and information about its origin, context, or scheme.
> **Usage Note:** Where a more specific property for a classification's origin, context, or scheme exists, such as ceterms:naics, ceterms:isicV4, ceterms:credentialType, etc., the best practice is to use that property instead of this one.
> **Domain:** ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task
> **Range:** skos:Concept

**Comment by philbarker** [comment]
I'm not convinced that adding "origin and context" clarifies anything. It's ok in the definition, I guess, but I find it's use in the usage note confusing because the property for the "identifier's origin, context, or scheme" will be ceterms:identifierType.

Also the usage note sentence structure is a bit tortured.

How about "Specific properties exist in CTDL for several types of [identifier/classification] eg. [...]. It is best practice to use these specific properties where appropriate."

You OK with the update I suggested to the definition of IdentifierValue?

**Comment by siuc-nate** [comment]
Use of "scheme" alone seemed a little too strict and I don't want to confuse a generic "scheme" for an explicit "concept scheme" (though maybe that's appropriate for classification).  I see your point on the usage note though, that does kind of start to blur the line between the property itself and what that property points to for its value.  Perhaps it would be better to leave that part out and shorten the usage note, e.g.:

"Where a more specific property exists, such as [...], use that property instead of this one."

I like the enhanced definition for IdentifierValue but I would tweak it a little bit:
"Means of identifying a resource, typically consisting of an alphanumeric token and a context or scheme from which that token originates."
Restricting this to "unambiguous" cases would make it harder to dump all of the data that currently uses codedNotation into IdentifierValues for this property, since few if any of them will have anything other than just the alphanumeric token to go by.

Maybe to align my previous suggestions a little bit better with the above, and walk back my attempt to mirror the two properties:
**Identifier:** Alphanumeric token that identifies this resource and information about the token's originating context or scheme.
**Classification:** Category or classification of this resource.

Since Classification references a skos:Concept, the notion of that concept also describing its source scheme is kind of inherent and isn't really as relevant (or worth emphasizing) as it is with Identifier referencing an IdentifierValue.

To summarize:
> **URI:** ceterms:identifier
> **Label:** Identifier
> **Definition:**  Alphanumeric token that identifies this resource and information about the token's originating context or scheme.
> **Usage Note:** Where a more specific property exists, such as ceterms:opeID, ceterms:ncesID, ceterms:leiCode, etc., use that property instead of this one.
> **Domain:** ceterms:Credential (and subclasses), ceterms:LearningOpportunityProfile, ceterms:AssessmentProfile, ceterms:PathwayComponent subclasses, ceterms:TransferValueProfile, ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task, ceterms:CredentialOrganization, ceterms:QACredentialOrganization
> **Range:** ceterms:IdentifierValue

> **URI:** ceterms:classification
> **Label:** Classification
> **Definition:** Category or classification of this resource.
> **Usage Note:** Where a more specific property exists, such as ceterms:naics, ceterms:isicV4, ceterms:credentialType, etc., use that property instead of this one.
> **Domain:** ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task
> **Range:** skos:Concept

**Remove:**
> **Subject:** ceterms:IdentifierValue
> **Predicate:** rdfs:comment
> **Object:** Alphanumeric Identifier value.

**Add:**
> **Subject:** ceterms:IdentifierValue
> **Predicate:** rdfs:comment
> **Object:** Means of identifying a resource, typically consisting of an alphanumeric token and a context or scheme from which that token originates.

**Comment by philbarker** [comment]
OK, I'll settle for that. Looks much better than what we had at the start of this issue.

**Comment by siuc-nate** [comment]
Following the above posts, is this correct?:

Proposal:
---
Create `ceterms:identifier`

> **URI:** ceterms:identifier
> **Label:** Identifier
> **Definition:**  Alphanumeric token that identifies this resource and information about the token's originating context or scheme.
> **Usage Note:** Where a more specific property exists, such as ceterms:opeID, ceterms:ncesID, ceterms:leiCode, etc., use that property instead of this one.
> **Domain:** ceterms:Credential (and subclasses), ceterms:LearningOpportunityProfile, ceterms:AssessmentProfile, ceterms:PathwayComponent subclasses, ceterms:TransferValueProfile, ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task, ceterms:CredentialOrganization, ceterms:QACredentialOrganization
> **Range:** ceterms:IdentifierValue


---
Create `ceterms:identifierTypeName`

> **URI:** ceterms:identifierTypeName
> **Label:** Identifier Type Name
> **Definition:** Formal name or acronym of the framework, scheme, type, or other organizing principle of this identifier, such as ISBN or ISSN.
> **Domain:** ceterms:IdentifierValue
> **Range:** rdf:langString


---
Create `ceterms:classification`

> **URI:** ceterms:classification
> **Label:** Classification
> **Definition:** Category or classification of this resource.
> **Usage Note:** Where a more specific property exists, such as ceterms:naics, ceterms:isicV4, ceterms:credentialType, etc., use that property instead of this one.
> **Domain:** ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task
> **Range:** skos:Concept


---
Modify `ceterms:identifierType` to point to a URI instead and tweak its definition

**Remove:**
> **Subject:** ceterms:identifierType
> **Predicate:** schema:rangeIncludes
> **Object:** rdf:langString

> **Subject:** ceterms:identifierType
> **Predicate:** rdfs:comment
> **Object:** "Formal name or acronym of the identifier type such as ISBN and ISSN."

**Add:**
> **Subject:** ceterms:identifierType
> **Predicate:** schema:rangeIncludes
> **Object:** xsd:anyURI

> **Subject:** ceterms:identifierType
> **Predicate:** rdfs:comment
> **Object:** "Framework, scheme, type, or other organizing principle of this identifier."


---
Modify `ceterms:IdentifierValue` to remove name and description, and to clarify its definition

**Remove:**
> **Subject:** ceterms:name
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:IdentifierValue

> **Subject:** ceterms:description
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:IdentifierValue

> **Subject:** ceterms:IdentifierValue
> **Predicate:** rdfs:comment
> **Object:** Alphanumeric Identifier value.

**Add:**
> **Subject:** ceterms:IdentifierValue
> **Predicate:** rdfs:comment
> **Object:** Means of identifying a resource, typically consisting of an alphanumeric token and a context or scheme from which that token originates.


---
Deprecate `ceterms:codedNotation` and `ceterms:alternativeIdentifier`, and mark them as being superseded by `ceterms:identifier`

**Remove:**
> **Subject:** ceterms:codedNotation
> **Predicate:** vs:term_status
> **Object:** vs:stable

> **Subject:** ceterms:alternativeIdentifier
> **Predicate:** vs:term_status
> **Object:** vs:stable

**Add:**
> **Subject:** ceterms:codedNotation
> **Predicate:** vs:term_status
> **Object:** vs:deprecated

> **Subject:** ceterms:alternativeIdentifier
> **Predicate:** vs:term_status
> **Object:** vs:deprecated

> **Subject:** ceterms:codedNotation
> **Predicate:** meta:supersededBy
> **Object:** ceterms:identifier

> **Subject:** ceterms:alternativeIdentifier
> **Predicate:** meta:supersededBy
> **Object:** ceterms:identifier


---
Update credential registry data such that:
- Wherever there was once a `ceterms:codedNotation` or `ceterms:alternativeIdentifier`, use `ceterms:identifier` with the value from `ceterms:codedNotation`/`ceterms:alternativeIdentifier` as the value for the `ceterms:IdentifierValue`'s `ceterms:identifierValueCode` property.


---
Several examples of what this kind of data would look like [can be found here](https://github.com/CredentialEngine/Schema-Development/blob/master/Identifiers%20and%20Classifications/Identifiers%20and%20Classifications%20Sample.json).

**Comment by siuc-nate** [comment]
Would it be worth keeping `ceterms:codedNotation` around for special cases like `ceterms:CredentialAlignmentObject`?

Compare this overwrought thing:
```
{
    "ceterms:occupationType": [
      {
        "@type": "ceterms:CredentialAlignmentObject",
        "ceterms:frameworkName": { "en": "US Army MOS Codes" },
        "ceterms:targetNodeName": { "en": "INFANTRYMAN" },
        "ceterms:identifier": [
          {
            "@type": "ceterms:IdentifierValue",
            "ceterms:identifierValueCode": "11B"
          }
        ],
        "ceterms:targetNode": "https://www.goarmy.com/careers-and-jobs/browse-career-and-job-categories/combat/infantryman-11b.html"
      }
    ]
}
```
to this much more readable version:
```
{
    "ceterms:occupationType": [
      {
        "@type": "ceterms:CredentialAlignmentObject",
        "ceterms:frameworkName": { "en": "US Army MOS Codes" },
        "ceterms:targetNodeName": { "en": "INFANTRYMAN" },
        "ceterms:codedNotation": "11B",
        "ceterms:targetNode": "https://www.goarmy.com/careers-and-jobs/browse-career-and-job-categories/combat/infantryman-11b.html"
      }
    ]
}
```

**Comment by siuc-nate** [comment]
I have updated the [proposal comment](https://github.com/CredentialEngine/Schema-Development/issues/715#issuecomment-696900146) above to reflect my previous post's suggested tweak.

**Comment by philbarker** [comment]
OK (mutters something about using SKOS:Concept, but OK ;-) )

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.

Note, however, that we'll have quite a bit of registry data (and probably code) to update as well.
