### ISSUE TITLE
Should comment's be added to reinforce that CTDL does not deal with issued/earned entities

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#717]
Some terms in CTDL and CTDL-ASN may be used to describe entities associated with persons--e.g., a person's credential, assessment or learning opportunity.  Should terms with such potential associations in the wild have a comment where that terms may appear to otherwise apply (e.g., a property like expirationDate on a credential should not be considered as the expiration of an already earned credential).  

Which terms might present such a problem?

**Comment by siuc-nate** [comment]
Archiving this, as it hasn't seen demand in a few years.
