### ISSUE TITLE
Exports of CTDL and CTDL-ASN should not contain meta tags

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#718]
`Meta` tags are intended to serve local uses. However, the exports of the schema in JSON-LD include the `meta` tags.  They should not.

**Comment by siuc-nate** [comment]
They are meant to be tools for developers to make using the terms easier.  I think some of our own code uses them but we've also shown them to at least a few of our partners in the process of explaining the CTDL schema.  

I could see making them optional via a parameter or something, perhaps, but I wouldn't want to remove them entirely.

**Comment by philbarker** [comment]
I've been advising Learning Tapestry on how to create an DESM RDF version of various specs for T3 mapping project. I found the meta tag that specifies the target scheme of the Alignment Object in the range of some terms to be usefull in providing a value for the desm:valueSpace.

**Comment by stuartasutton** [comment]
Phil, I have no doubt of the utility in some contexts for having a property that says "here are the properties that belong to this class" (i.e. `meta:domainFor`) or a property that says "here is a history of this term's changes" (`meta:changeHistory`). My objections (particularly with `meta:domainFor`) here in an RDF schema is that RDFS **deliberately did not include such a property** for defining schemas because it is wrong--Classes do not "have" properties.  I have no objections to the presence of the meta terms in the property tables as an aid for developers and I was the one that pressed for including `meta:changeHistory`.  My objection is in the schema export.

**Comment by siuc-nate** [comment]
Are you referring specifically to the JSON-LD exports available from the [serializations pages like this one](https://credreg.net/ctdl/schema)?  I could add some extra links to these that would yield the schema without the meta tags if so.

**Comment by stuartasutton** [comment]
Yes, I am referring specifically to the JSON-LD exports. Do you mean by "extra links" that you'd have a choice whether to export with the meta properties or without them?  If so, that would satisfy me.

**Comment by stuartasutton** [comment]
@siuc-nate, just to fill you in on one of the reasons including the meta tags (particularly the `domainFor`) is problematic. In processing a schema in the T3 schema mapping tool (DESM), the tool has to be able to download an rdf schema (json-ld, turtle etc.) and relying on rdfs, parse it for the mapping of properties. With the meta tag for `domainFor` present, the parse is simple because you have told them in a non-rdfs fashion which properties belong to which class when actually their parsing job in general with rdf schemas is more difficult because they have to rely instead on each property's domain to determine which class may be inferred. Totally different parsing problem.  For example in parsing Schema.org's json-ld schema, they have no such meta tag to solve the "which property to which class" and must rely on the domain declarations in the properties.

**Comment by stuartasutton** [comment]
@siuc-nate, where do we stand on this issue of "meta" properties in export--particularly the `meta:domainFor`?  I though we were going to have some means of downloading both with and without the "meta" properties.

**Comment by siuc-nate** [comment]
It's still on my to-do list, but that is the plan.

**Comment by stuartasutton** [comment]
Any idea of a timeline? If not (and that's OK), I'll set aside an hour or two and delete the eta tags from the copy of CTDL, CTDL-ASN and the concept schemes that I am preparing for the DESM testing of file uploads.

**Comment by siuc-nate** [comment]
I have updated the site:
https://credreg.net/ctdl/schema

You'll now see options to link to or download the schemas with or without meta properties.  This also works for individual terms by including `includemetaproperties=false` in the URL parameters:
https://credreg.net/ctdl/terms/Credential/json?includemetaproperties=false

**Comment by stuartasutton** [comment]
Thanks, Nate!

**Comment by jeannekitchens** [comment]
Updates made here https://credreg.net/ctdl/schema
