### ISSUE TITLE
Changes to Transfer Value Profile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#719]
Per our 9/22/2020 meeting:

Per #703:
---
Change the definition of `ceterms:TransferValueProfile`
**Current Definition:** Description of transfer value for a resource.
**New Definition:** Description of transfer value of a resource.

Per the [draft terms document](https://docs.google.com/document/d/1u0HQ45Cpc9tAQeP9V46IVMOUw9nQNawH4gChTyxUh6M/edit):
---

Change the property `ceterms:transferValue` to `ceterms:quantitativeTransferValue`
**Current Definition:** A suggested or articulated credit- or point-related transfer value.
**New Definition:** An explicit amount of transfer value.

--

Change the definition for `ceterms:transferValueFrom`:
**Current Definition:** Resource that provides the transfer value described by this resource, according to the entity providing this resource.
**New Definition:** Resource from which the described transfer value originates.

--

Change the definition for `ceterms:transferValueFor`:
**Current Definition:** Resource that accepts the transfer value described by this resource, according to the entity providing this resource.
**New Definition:** Resource for which the described transfer value is applicable.

--

Use `ceasn:derivedFrom` instead of `ceterms:valueEndorsement` and remove the "third party" restriction from `ceasn:derivedFrom`
**Current Definition:** A third party version of the entity being referenced that has been modified in meaning through editing, extension or refinement.
**New Definition:** A version of the entity being referenced that has been modified in meaning through editing, extension or refinement.

--

Change the definition of `ceterms:learningMethodDescription`
**Current Definition:** Description of the learning methods for a resource.
**New Definition:** Description of the methods used to conduct learning.

--

Change the definition of `ceterms:assessmentMethodDescription`
**Current Definition:** Description of the assessment methods for a resource.
**New Definition:** Description of the methods used to conduct assessment.

--

Change the definition of `ceterms:transferValueStatementDescription`
**Current Definition:** Textual statement of the nature of transfer value handled by the organization.
**New Definition:** Description of the nature of transfer value handled by the organization.

**Comment by siuc-nate** [comment]
>Change the property ceterms:transferValue to ceterms:quantitativeTransferValue
>Current Definition: A suggested or articulated credit- or point-related transfer value.
>New Definition: An explicit amount of transfer value.

I strongly disagree with this one, for two reasons:
- The current definition correctly conveys the intended meaning
- We have now changed the class itself from `schema:QuantitativeValue` to `ceterms:CreditValue` per #590. If anything, we should be using the existing `ceterms:creditValue` property instead of `ceterms:transferValue` here, but I think `ceterms:transferValue` is correct, since it is (in this context) the value of the transfer specifically.

**Comment by philbarker** [comment]
I have no strong opinion the property name: `transferValue` or `quantitativeTransferValue`

On the definition, I think the issue was that the transfer value might not be credit- or point- related (given some common interpretations of those terms).  I think we can live with expressing the transfer value with an object type called CreditValue so long as definitions make it clear that despite the name it has wider application than some strict definition of credit--or rather we have to live with that because we have no better idea for a name that works well for expressing CreditAndOtherThingsThatActAsCreditValue. I think Deb and Jeff have a good grasp of that issue.

**Comment by siuc-nate** [comment]
Then perhaps we should use `ceterms:creditValue` instead of any flavor of `ceterms:transferValue` until a strong enough use case arises that can't be solved with `ceterms:CreditValue`?

By the way, we accidentally broke our practice of not using the same string (with just a one-character capitalization difference) for the name of both a property and a class with `ceterms:creditValue`/`ceterms:CreditValue`

**Comment by siuc-nate** [comment]
With the exception of the changes for ceterms:transferValue (since those are still up in the air), I have made the other changes listed in the original post and noted them in the history tracking.

**Comment by philbarker** [comment]
@siuc-nate Given the issue comes from the observations that (a) not all transfers being of Credit, and (b) the things being transfered that are not Credit are varied and sometimes nebulous, I think it is a reasonable compromise to have a transferValue (or quantitativeTransferValue) property pointing to something described as best we can using a CreditValue.

**Comment by siuc-nate** [comment]
Fair enough.  I think we should stick with `ceterms:transferValue`.  The only reason "quantitative" transfer value was proposed is because it pointed to a `schema:QuantitativeValue`, which is no longer true.  If for some reason we decide down the road that this property needs to point at something other than a `ceterms:CreditValue` then we also don't want to be saddled with something tied to that class either.

**Comment by siuc-nate** [comment]
I have made the last remaining changes to the definition for `ceterms:transferValue` and noted it in the history tracking.
