### ISSUE TITLE
Update ceterms:keyword to reference ceasn:conceptKeyword

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#723]
Currently `ceasn:conceptKeyword` correctly claims to be equivalent to `ceterms:keyword`, while `ceterms:keyword` does not reciprocate.

Proposal:

**Add:**
> **Subject:** ceterms:keyword
> **Predicate:** owl:equivalentProperty
> **Object:** ceasn:conceptKeyword

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.

**Comment by stuartasutton** [comment]
This is correct.
