### ISSUE TITLE
Competence assertion as a credential

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/Schema-Development#725]
Can we nail this competence-not-credential thing and create a new subtype of Credential:  CompetenceAssertion which is no more than an assertion of a single competence.

**Comment by siuc-nate** [comment]
I think we already cover this with [MicroCredential](https://credreg.net/ctdl/terms/MicroCredential):
> Credential that addresses a subset of field-specific knowledge, skills, or competencies; often developmental with relationships to other micro-credentials and field credentials.

I can't think of what else a MicroCredential would be if not something that asserts one or a few competencies.

**Comment by siuc-nate** [comment]
I think the larger problem is that organizations don't typically think about the need for some kind of object that makes the competency assertion in the first place - from the sound of it, you can just assert that you have a competency, and that assertion is carried in the ether.  Whether it's a MicroCredential or a CompetenceAssertion or whatever, it's going to need to be a published thing with a CTID and all the other bells and whistles and unless/until organizations are willing to do that for every single competency that could be asserted, we haven't really solved the true underlying problem.

I think it makes a lot more sense to let the digital wallets and backpacks and countless other efforts that are ongoing to enable someone to claim they possess some competency or credential to carry this data and not do it in CTDL.

**Comment by stuartasutton** [comment]
Phil, if we can go back to the top (https://github.com/CredentialEngine/Schema-Development/issues/725#issue-713713769), what would be the potential domain(s) of a CompetenceAssertion property?

**Comment by philbarker** [comment]
Stuart, I was meaning a CompetenceAssertion to be a Class, a subclass of Credential.

Nate may have a point

**Comment by philbarker** [comment]
Closing this as we're now treating the competencies themselves as things that can have transfer value.
