### ISSUE TITLE
Differentiate Learning Programs and Courses

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#730]
Per our 10/20/2020 meeting:

This affects:
- Transfer Value Profile
- Google pathways/jobs
- ProPath
- Learning Opportunities in general

We need to determine how to best enable differentiating between a  Program and Course (and possibly an instance?) with regard to Learning Opportunity.  There are a few different approaches with different ramifications:

1. Add ceterms:classification to Learning Opportunity
  - This enables categorizing learning opportunities in a variety of publisher-defined ways

2. Create a new property like ceterms:learningOpportunityType
  - This would be a more explicit typing than classification and would also imply the need for a CE-defined vocabulary with terms like "Program" and "Course"

3. Create a Course class (or borrow the existing schema.org Course class) and use it to describe Courses, while relying on Learning Opportunity to describe programs
  - Technically this does not solve the problem of saying that a Learning Opportunity is (or is not) explicitly a program
  - We have always said that Learning Opportunity Profile covers a broad range including short courses so this would change how Learning Opportunity Profile is meant to be used

4. Create a Program class and a Course class as subclasses of Learning Opportunity Profile
  - This would allow Learning Opportunity Profile to continue to serve as-is as a catch-all entity for any kind of educational/training experience, as we have always defined/described/used it
  - It would allow us to specialize each of these classes as needed for the use cases/areas outlined above 
  - It has implications for how the search would work (e.g. would Programs and Courses show up in the Learning Opportunity search in the finder?)

**Comment by stuartasutton** [comment]
@siuc-nate, first, we have long standing [`ceterms:Course`](https://purl.org/ctdl/terms/Course) class defined as a subclass of both [`ceterms:LearningOpportunity`](https://purl.org/ctdl/terms/LearningOpportunity) and [`sdo:CreativeWork`](https://schema.org/CreativeWork). That's a good beginning.

We should probably confront head-on the fact that schema.org supports the use of an entity being of more than one class.  That's the path being taken by the proposed [`sdo:LearningResource`](https://schema.org/LearningResource) class that can be a "second class" added to the primary type on which the entity being described is based...e.g., [`sdo:Book`](https://schema.org/Book).

Just a thought.

**Comment by philbarker** [comment]
Let's step back and ask why we want to make this distinction, because I think the reason varies, and this might affect what we want.

For example, for [Google Job Training](https://developers.google.com/search/docs/data-types/job-training) requires that: 

> "The completion of the program prepares students for an occupation. Preparatory courses aren't accepted" 

-- so what they want are learning opportunities that in themselves lead to qualifications, as opposed to those that do so only as part of a bigger program. Whether those learning opportunities are single courses or programs that comprise several courses is not the immediate issue.

**Comment by jeannekitchens** [comment]
Begin with differentiating: Program, Course, Module, Unit, Lesson, Activity.

**Comment by philbarker** [comment]
Also consider how Course as a part of a program relates to [ceterms:CourseComponent](https://purl.org/ctdl/terms/CourseComponent) from pathways.

**Comment by philbarker** [comment]
Building on comment in #768: some learning opportunities are only offered as part of a pathway comprised by something bigger while others are that bigger thing, and others again are short and self-contained. That is we need to distinguish Course as in Stanford University's [CS101 Introduction to Computing Principles](Introduction to Computing Principles
) (ten weeks long, several hours per week, doesn't on its own lead to a credential)  from Course as in this [Course for Fire Safety](https://courseforfiresafety.com/states/CA) (as short as a single 1hr session, with a certificate at the end of it). 

So (with straw man names)

- Program: a complex combination of several smaller learning opportunites, with one or more pathway through the component learning opportunities
- Course/Module: a self contained but extensive learning opprtunity that is offered as part of a program
- Standalone-Course: a self contained learning opportunity that is offered without the expectation that other courses will be taken.

The Course, Module, Unit, Lesson, Activity. breakdown exists in [OER Schema](http://oerschema.org/). The definitions there aren't great ("Course: An instructional course") or are missing. We used them in the [K12 OCX Content Model](https://k12ocx.github.io/k12ocx-specs/contentmodel/), with Course as the top level (e.g. a middle-school maths course); Module and Unit as succesively smaller divisions of a Course; Lesson as a single session which comprised one or more Activity.

**Comment by siuc-nate** [comment]
Per our 7/27/2021 meeting:

- We will flesh out the existing [ceterms:Course](https://credreg.net/ctdl/terms) class
- We will create a ceterms:LearningProgram class to be a collection of courses with a definition based partially on the definition for [schema.org/EducationalOccupationalProgram](https://schema.org/EducationalOccupationalProgram)

**Comment by siuc-nate** [comment]
**Updates to ceterms:Course**
1. Update the definition:
  - From: "Structured sequence of one or more educational activities that aims to develop a prescribed set of knowledge, competence or ability of learners."
  - To: "Single structured sequence of one or more educational activities that aims to develop a prescribed set of knowledge, competence or ability of learners." 
2. Add all properties from Learning Opportunity Profile, since they may be applicable to standalone courses
3. Update the ranges of the properties that currently point to Learning Opportunity Profile to also point to Course

**Create ceterms:LearningProgram**
> **URI:** ceterms:LearningProgram
> **Label:** Learning Program
> **Definition:** Discrete set of Courses or Learning Opportunities.
> **Properties:** All of the properties from Learning Opportunity Profile
Note: All of the properties that currently point to Learning Opportunity Profile will also need to point to Learning Program

**Comment by philbarker** [comment]
### Proposal

Updates to `ceterms:Course`

**Remove:**
> **Subject:** ceterms:Course
> **Predicate:** rdfs:comment
> **Object:** "Structured sequence of one or more educational activities that aims to develop a prescribed set of knowledge, competence or ability of learners."@en-US ;

**Add:**
> **Subject:** ceterms:Course
> **Predicate:** rdfs:comment
> **Object:** "Single structured sequence of one or more educational activities that aims to develop a prescribed set of knowledge, competence or ability of learners."@en-US ;

**Add:**
> **Subject:** ceterms:Course
> **Predicate:** dct:description
> **Object:** "Course is distinct from Program, which aggregates several courses."@en-US

(Note, `ceterms:Course` is already a subclass of `ceterms:LearningOpportunity`, and `owl:equivalentClass` of `schema:Course`)

**Add:**
> **Subject:** {all the properties with schema:domainIncludes ceterms:LearningOpportunity}
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Course

**Add:**
> **Subject:** {all the properties with schema:rangeIncludes ceterms:LearningOpportunity}
> **Predicate:** schema:rangeIncludes
> **Object:** ceterms:Course

**Create ceterms:LearningProgram**
> **URI:** ceterms:LearningProgram
> **Label:** Learning Program
> **Definition:** Set of learning opportunities that leads to an outcome, usually a credential like a degree or certificate.
> **Properties:** All of the properties from Learning Opportunity Profile.

**Add:**
> **Subject:** ceterms:LearningProgram
> **Predicate:** rdfs:subClassOf 
> **Object:** ceterms:LearningOpportunity, schema:EducationalOccupationalProgram

**Comment by philbarker** [comment]
First cut proposal based on what we discussed 27 Jul 2021.

@siuc-nate is there enough detail under "Create ceterms:LearningProgram" or do you want me to break that down in to triples?

All: what are the consequences for `ceterms:LearningOpportunityProfile`? Should we add a comment about using the new classes in preferences to it? Also, note that these new classes are subClasses of `ceterms:LearningOpportunity`, not `ceterms:LearningOpportunityProfile` but get their properties from the latter. This gets us away from treating what is defined as the description of something as the thing it describes--which I like--but what are the consequences for the handbook etc?

**Comment by siuc-nate** [comment]
I would probably just append this:
**Add:**
> **Subject:** {all the properties with schema:rangeIncludes ceterms:LearningOpportunity}
> **Predicate:** schema:rangeIncludes
> **Object:** ceterms:LearningProgram

As for the subclassing: Given the usage of LearningOpportunityProfile, the lack of usage of LearningOpportunity, and the intended usage of Course/LearningProgram, it's probably more realistic and practical to make both of them a subclass of LearningOpportunityProfile instead.

**Comment by philbarker** [comment]
@siuc-nate Thanks. Have added property changes (both domain and ranges, though I realise the former is implied in the note for creating the class)

>  it's probably more realistic and practical to make both of them a subclass of LearningOpportunityProfile instead.

I would say it is less realistic but maybe more practical ;-)

We define LearningOpportunityProfile as a description of a learning opportunity but use it like instances are Learning Opportunities. We literally say that "an entity describing an educational or training opportunity" teaches some skill, when we could say that the learning opportunity does that. It's very JSONy and not very RDFy.

**Comment by siuc-nate** [comment]
I believe the distinction between the "thing" and the "profile of the thing" is intentional - or at least it was. @stuartasutton would need to be the one to explain the reasoning behind it back when we did it, though. We do the same with Assessment/AssessmentProfile but I don't think we do that with anything else.

**Comment by philbarker** [comment]
Per discussion 10 Aug, subclass of `LearningOpportunityProfile`

**Comment by philbarker** [comment]
The discussion of `ceterms:instructionalProgramType` in #798 about SCED, especially @stuartasutton's [comment](https://github.com/CredentialEngine/Schema-Development/issues/798#issuecomment-931468877):

> I don't think ceterms:InstructionalProgramClassification is correct based on the clear distinction between course and program.

convinces me that `ceterms:instructionalProgramType` should **not** be a proerty of `Course`.

I have updated tyhe proposal accordingly.

**Comment by siuc-nate** [comment]
Will ceterms:LearningProgram be unstable or stable? We already have ceterms:Course as stable.

**Comment by siuc-nate** [comment]
Expanding on my earlier post about instructionalProgramType:
- instructionalProgramType points to an InstructionalProgramClassification, which most often is a CIP code
- We use this property on credentials, assessments, learning opportunities, competencies, competency frameworks, etc.
- Real-world use cases show that the actual value (the important part) of CIP codes is that they precisely categorize the subject of the resource, regardless of whether or not the resource is a program
- If we remove instructionalProgramType from course, we will need to remove it from all of the other non-program classes as well, which means we'll need to either invent a new identical property that allows users to point to CIP codes, tell them to use ceterms;subject (or maybe ceterms;classification) instead, or tell them to "create a blank node ceterms:LearningProgram if you want to reference a CIP code"
- We would also have to update our code/systems/validation/etc to use whatever the alternative is to point to CIP codes instead of just using the property that is already setup and in-use today to point to CIP codes, meaning a lot of work for no actual benefit

It is my position that the type of thing being pointed **from** is irrelevant just as it's irrelevant in the case of industryType and occupationType, both of which point **from** things that are not industries or occupations.  

If the real-world use case is "I want to point to a CIP code from my [thing]" then we shouldn't care whether or not that [thing] is a program.  instructionalProgramType is not a schema:additionalType; it is not a soft subclassing of the entity being pointed from. It is a pointer to something that (literally) is an instructional program classification (a ceterms:InstructionalProgramClassification to be precise), so **it is a misinterpretation of both the intent and the actual usage of the property to read it as "this defines the type of program that my [thing] is"**.

As such, I think it would be a mistake to mess with how we currently use instructionalProgramType. It should stay where it is and be added to both ceterms:LearningProgram and ceterms:Course.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
