### ISSUE TITLE
Add ceterms:subject to ceterms:ValueProfile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#731]
In many cases, the credits that are part of a transfer value profile are credits in a particular subject separately defined from the subject(s) covered by a course.  In particular, a course may cover a raft of subjects but offer specific amounts of credit for specific subjects.

For example:
https://www.acenet.edu/National-Guide/Pages/Course.aspx?org=Jiffy+Lube+International&cid=84a34ff0-93c4-ea11-a812-000d3a33232a

Here we see a variety of credits where each credit is tied to a specific subject, and the subjects listed for the course are defined separately.

Proposal:

**Add:**
> **Subject:** ceterms:subject
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:ValueProfile

**Comment by philbarker** [comment]
Yes, that would be simpler than creating a bnode for a generic course for which it is transfer value just to put the subject there.

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
