### ISSUE TITLE
QData: schema:MonetaryAmount is missing schema:description

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#732]
In order to describe the monetary amount (e.g. "Average Wage" in ProPath), the [schema:MonetaryAmount](https://credreg.net/qdata/terms/MonetaryAmount) class in QData should have schema:description as one of its properties.

Usage:
```
{
  "qdata:earningsAmount": [
    {
      "@type": "schema:MonetaryAmount",
      "schema:currency": "USD",
      "schema:value": 15.91,
      "schema:description": { "en": "Average Wage" }
    }
  ]
}
```

Proposal:

**Add:**
> **Subject:** schema:description
> **Predicate:** schema:domainIncludes
> **Object:** schema:MonetaryAmount

**Comment by stuartasutton** [comment]
This is OK with me.

**Comment by siuc-nate** [comment]
This change has been made in pending QData and noted in the history tracking.
