### ISSUE TITLE
Determine how to capture information about learning opportunity/assessment compliance with regulations

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#733]
We need to be able to capture when a learning opportunity or assessment explicitly complies with specific regulations or laws.

For example:
![image](https://user-images.githubusercontent.com/21346519/97016875-e295e100-1512-11eb-871f-7b32827125dd.png)
https://apps.illinoisworknet.com/cis/wioatraining/program/1006549_1007283

**Comment by stuartasutton** [comment]
There is a **widely used** Dublin Core property that is intended to meet this use case: [`dcterms:conformsTo`](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/conformsTo) defined as:

>An established standard to which the described resource conforms.

Its range is the class [`dcterms:Standard`](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/Standard) defined as:

> A reference point against which other things can be evaluated or compared.

**Comment by philbarker** [comment]
[`ceterms:processStandards`](https://purl.org/ctdl/terms/processStandards) and [`ceterms:processStandardsDescription`](https://purl.org/ctdl/terms/processStandardsDescription) seem relevant (but check whether intent is a "conforms to" type relationship because that's not explicit in definition).

**Comment by jeannekitchens** [comment]
This is handled via #806 using ceterms:membershipCondition.

**Comment by siuc-nate** [comment]
Closing this, since it's handled per the above comment
