### ISSUE TITLE
Create WIOA properties for QData

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#734]
Per our 10/27/2020 meeting:

We need some additional properties to capture the WIOA related data for the QData schema.  Specifically:

> **URI:** qdata:totalWIOAParticipants
> **Label:** Total WIOA Participants
> **Definition:** Total participants in the WIOA program.
> **Domain:** qdata:DataProfile
> **Range:** schema:QuantitativeValue

> **URI:** qdata:totalWIOACompleters
> **Label:** Total WIOA Completers
> **Definition:** Total participants who completed the WIOA program, successfully or unsuccessfully.
> **Domain:** qdata:DataProfile
> **Range:** schema:QuantitativeValue

> **URI:** qdata:totalWIOAExiters
> **Label:** Total WIOA Exiters
> **Definition:** Total participants who successfully completed the WIOA program and exited WIOA.
> **Domain:** qdata:DataProfile
> **Range:** schema:QuantitativeValue

**Comment by stuartasutton** [comment]
These definitions look OK to me.

**Comment by siuc-nate** [comment]
These changes have been made in pending QData and noted in the history tracking.
