### ISSUE TITLE
Enable capturing employment outlook in QData

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#735]
Per our 10/27/2020 meeting:

Proposal:

> **URI:** qdata:employmentOutlook
> **Label:** Employment Outlook
> **Definition:** Projected employment estimate.
> **Domain:** qdata:DataProfile
> **Range:** schema:QuantitativeValue

**Comment by stuartasutton** [comment]
I think it is OK to run with.

**Comment by siuc-nate** [comment]
These changes have been made in pending QData and noted in the history tracking.
