### ISSUE TITLE
Expand what demographics data can be captured

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#736]
Per our 10/27/2020 meeting:

We need to be able to capture Holders related data for the following, as numbers or rates:
- Enrollment
- Gender
- Race
- Age
- Prior Education

Example:
http://www.careerbridge.wa.gov/Detail_Program.aspx?program=12183
"The information on this page is based on all students who exited the program (either completed or withdrew), during the most recent three years for which data is available."
![image](https://user-images.githubusercontent.com/21346519/97343083-0fb8fb00-1855-11eb-8a3a-0558e6c5f91a.png)

**Comment by mparsons-ce** [comment]
Prototyping: 
- add a property of say RelatedValue (type: ValueProfile) to ValueProfile
- that would allow the above like

"Statistic": [
	{
		"Description": "Enrollment",
		"RelatedValue": [
			{
				"Description": "Number of students completing the program",
				"Value": 76.0
			},
			{
				"Description": "Completion Rate",
				"Percentage": 100.0
			},
			{
				"Description": "Average number of students who completed each year",
				"Percentage": 38.0
			}
		]
	},
	{
		"Description": "Gender",
		"RelatedValue": [
			{
				"Description": "Number of students completing the program",
				"Value": 76.0
			},
			{
				"Description": "Completion Rate",
				"Percentage": 100.0
			},
			{
				"Description": "Average number of students who completed each year",
				"Percentage": 38.0
			}
		]
	}
]

**Comment by stuartasutton** [comment]
In QData, we currently have `demographicEarningsRate` and `demographicEmploymentRate`.  I suggest that we add a new `demongraphicHoldersRate` on `DataProfile`.  The earnings and employment properties have a range of `sdo:QuantitativeValue`. It would be nice to have `sdo:QuantitativeValue` as range of the `demongraphicHoldersRate` property be able to reference a `qData:DemograhicDataTypes`(?) concept scheme that enumerate the concepts of gender, race, age and prior education and their narrower concepts.

**Comment by siuc-nate** [comment]
This has been handled in #941
