### ISSUE TITLE
Enable referencing competencies, occupations, and jobs from a Transfer Value Profile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#737]
Per our 11/3/2020 meeting:

Enable referencing a `ceasn:Competency`, `ceterms:Occupation`, or `ceterms:Job` via `ceterms:transferValueFor` and `ceterms:transfervalueFrom`:

**Add:**
> **Subject:** ceterms:transferValueFor
> **Predicate:** schema:rangeIncludes
> **Object:** ceasn:Competency, ceterms:Occupation, ceterms:Job

**Add:**
> **Subject:** ceterms:transferValueFrom
> **Predicate:** schema:rangeIncludes
> **Object:** ceasn:Competency, ceterms:Occupation, ceterms:Job

**Comment by stuartasutton** [comment]
Looks OK to me.

Stuart

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
