### ISSUE TITLE
Clarify the usage of qdata:percentage

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#738]
I think the [qdata:percentage](https://credreg.net/qdata/terms/percentage) property needs a usage note to clarify whether or not a publisher and/or consumer should multiply its value by 100 to provide a correct percentage.  It is fairly common to store percentage values as numbers between 0 and 1 and compute them as such, but whether or not this is intended with this property is not obvious.

For example, would I communicate `75.6%` like this:
```
"qdata:percentage": 75.6
```
Or like this:
```
"qdata:percentage": 0.756
```

Either way could be published, but depending on the implementation, this could end up getting displayed as `0.756%` or `75.6%` or `7560%` - a rather significant difference.  The intended percentage may not always be as obviously incorrect; consider a smaller number like `1.3%`.  This could be represented as 
```
"qdata:percentage": 1.3
```
Or:
```
"qdata:percentage": 0.013
```
and interpreted as `0.013%` or `1.3%` or `130%`.

So I think we need a usage note that clarifies its intended use, one way or the other. We have a similar case with [ceterms:weight](https://credreg.net/ctdl/terms/weight) where we included just such a note for this very reason:
> "Best practice is to assigned a decimal value weight between 0 and 1 that indicates the strength of the assertion, with 0 being weakest and 1 being strongest."

Since percentages could reasonably go below zero or beyond 100% with this property, it may or may not make sense to follow the same "1 = 100%, 0.5 = 50%, 0.1 = 10%" approach here.

**Comment by stuartasutton** [comment]
There is no problem with providing a comment on usage as you suggest.

**Comment by siuc-nate** [comment]
Proposal:

**Add:**
> **Subject:** qdata:percentage
> **Predicate:** vann:usageNote
> **Object:** "Best practice is to treat the value of this property as a verbatim percentage; for example, a value of 1.5 should be interpreted as 1.5%"

**Comment by siuc-nate** [comment]
This change has been made in pending QData and noted in the history tracking.

**Comment by siuc-nate** [comment]
One additional recommendation, since the definition (which indicates the value should be the quotient - i.e. the result of division without any additional fiddling to make it look like a percentage) conflicts with the usage note:

**Remove:**
> **Subject:** qdata:percentage
> **Predicate:** rdf:comment
> **Object:** "Quotient of two values of the data set."

**Add:**
> **Subject:** qdata:percentage
> **Predicate:** rdf:comment
> **Object:** "Quotient of two values of the data set, expressed as a percentage."

**Comment by siuc-nate** [comment]
This change has been made in pending QData and noted in the history tracking.
