### ISSUE TITLE
Should HoldersProfile have a Name property? All of the other outcome classes do have Name.

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/Schema-Development#740]
ceterms:HoldersProfile doesn't have a property for ceterms:name.
All of the following outcome related classes have the ceterms:name property:

- ceterms:EarningsProfile
- ceterms:EmploymentOutcomProfile
- qdata:DataSetProfile
- qdata:DataSetTimeFrame

Should HoldersProfile have ceterms:name added, if for nothing other than consistency. 
Also qdata:DataProfile also has description, and not name. Where there can be multiple profiles, having a name can be useful in summaries.

**Comment by stuartasutton** [comment]
I see no problem with the `ceterms:HoldersProfile` having a `ceterms:name` property; however, I would not make it required in the policy.

**Comment by siuc-nate** [comment]
Proposal:

**Add:**
> **Subject:** ceterms:name
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:HoldersProfile

Correct?

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
