### ISSUE TITLE
CreditValue was changed to a range of ValueProfile, and the latter only has Value,  not a MinValue and MaxValue

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/Schema-Development#742]
We have use cases where Credit Value can be a range of MinValue and maxValue. The change of the range of CreditValue to ValueProfile will break these existing cases.
Should min and max value be added to ValueProfile?

**Comment by siuc-nate** [comment]
Proposal:

**Add:**
> **Subject:** schema:maxValue
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:ValueProfile

**Add:**
> **Subject:** schema:minValue
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:ValueProfile

**Comment by stuartasutton** [comment]
I have no objection to these additional  property domainIncludes.

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.

**Comment by mparsons-ce** [comment]
We will need to republish documents that are using CreditValue, to convert from QuantitativeValue to ValueProfile
Credentials: 2743
LearningOpportunities: 92
Assessments: 0
I will doing the republishing by Dec. 4, 2020.
