### ISSUE TITLE
TransferValueProfile developmentProcess missing?

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/Schema-Development#748]
According to the [domain model](https://app.diagrams.net/#G1Yg0qKQAQnK8Qev2rWYKQJfO9NvOQUM7_) , [TransferValueProfile](https://credreg.net/ctdl/terms/TransferValueProfile#TransferValueProfile) should have a deveopmentProcess property to link to a ProcessProfile, but it doesn't, and I don't see it in #719 . I don't recall dropping it, and cannot think why we would. Did it just get overlooked?

**Comment by siuc-nate** [comment]
Looks like it was overlooked. I don't see it referenced in the closed github issues about transfer value.

The formal update would be:

**Add:**
> **Subject:** ceterms:developmentProcess
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:TransferValueProfile

**Comment by stuartasutton** [comment]
Looks OK to me.

**Comment by mparsons-ce** [comment]
For developmentProcess

- updated Assistant API
- updated classes in github  https://github.com/CredentialEngine/Registry_Assistant/blob/master/src/RA.Models/Input/TransferValueProfileRequest.cs
- finder import 
- finderDetail page

https://sandbox.credentialengine.org/finder/transfervalue/62/My_Transfer_Value_Profile_Name

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
