### ISSUE TITLE
Consider deprecation of SubjectProfile (and related properties from qData)

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#750]
In qData, consider:  

1. deprecation of [`SubjectProfile`](https://credreg.net/qdata/terms/SubjectProfile)
2. deprecation of [`subjectIncluded`](https://credreg.net/qdata/terms/subjectIncluded); and
3. changing the range of [`subjectExcluded`](https://credreg.net/qdata/terms/subjectExcluded) from [`SubjectProfile`](https://credreg.net/qdata/terms/SubjectProfile) to [`QuantitativeValue`](http://schema.org/QuantitativeValue). 

We have demonstrated proof that [`SubjectProfile`](https://credreg.net/qdata/terms/SubjectProfile) is likely to lead to significant confusion.  That confusion stems from the very real potential for data providers to use multiple instances of the [`SubjectProfile`](https://credreg.net/qdata/terms/SubjectProfile) class and the property [`subjectsInSet`](https://credreg.net/qdata/terms/subjectsInSet) as a means of describing all types of subjects in the data set as opposed to using the more targeted predicates referencing [`QuantitativeValue`](http://schema.org/QuantitativeValue). This change makes [`subjectExcluded`](https://credreg.net/qdata/terms/subjectExcluded) just another property in the more targeted array os "subject" predicates.

The original purpose of the [`SubjectProfile`](https://credreg.net/qdata/terms/SubjectProfile) entity was to fill what Bob perceived as a very significant problem of data providers not identifying potential subjects that had been silently not included in a data set by providing a property and best practice for identifying and quantifying such excluded subjects. But we can easily solve that problem by changing the range of [`subjectExcluded`](https://credreg.net/qdata/terms/subjectExcluded) from [`SubjectProfile`](https://credreg.net/qdata/terms/SubjectProfile) to [`QuantitativeValue`](http://schema.org/QuantitativeValue).

The deprecations of [`subjectIncluded`](https://credreg.net/qdata/terms/subjectIncluded) is no problem because the array of predicates already includes [`subjectsInSet`](https://credreg.net/qdata/terms/subjectsInSet).

CHANGE RANGE:
>Property: [`subjectExcluded`](https://credreg.net/qdata/terms/subjectExcluded)
>Range: _from_ [`SubjectProfile`](https://credreg.net/qdata/terms/SubjectProfile)`]_to_ [`QuantitativeValue`](http://schema.org/QuantitativeValue)

DEPRECATE:
>Class:  [`SubjectProfile`](https://credreg.net/qdata/terms/SubjectProfile)
>Property:  [`subjectIncluded`](https://credreg.net/qdata/terms/subjectIncluded)

**Comment by siuc-nate** [comment]
The URI and definition for the SubjectProfile class may be useful in the future for some other purpose. I would recommend changing the status to unstable and removing the class from the range of any properties, but not deprecating it, in case we find a use for it again later.

**Comment by siuc-nate** [comment]
We will deprecate this and disconnect it from its domains/ranges and, if later we need it, we can un-deprecate it.

**Comment by siuc-nate** [comment]
The following changes have been made in pending QData and noted in the history tracking:
- Deprecated qdata:SubjectProfile
- Deprecated qdata:subjectIncluded
- Changed the range of qdata:subjectExcluded from qdata:SubjectProfile to schema:QuantitativeValue
- Removed the following properties from the domain of qdata:SubjectProfile:
  - ceterms:name
  - ceterms:description
  - qdata:subjectType
  - qdata:subjectValue

Note: qdata:subjectType and qdata:subjectValue no longer have a domain, but have otherwise not been altered.
