### ISSUE TITLE
Create QData property for pass rate

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#751]
QData has a number (6) "rate" properties. To those already defined, we need to add pass rate to [ceterms:HoldersProfile](https://credreg.net/ctdl/terms#HoldersProfile).

**URL:** `qdata:passRate`
**Defintition:** "Rate computed by dividing the number of subjects passing an assessment by the total number taking the assessment."
**Domain:** [qdata:DataProfile](https://credreg.net/qdata/terms/DataProfile)
**Range:** [sdo:QuantitativeValue](http://schema.org/QuantitativeValue)

**Comment by siuc-nate** [comment]
Is this intended to only capture the rate (ie the percentage) or the total taking/total passing as well?

**Comment by siuc-nate** [comment]
Proposal: Add a usage note:
"When data is available, record both the percentage and the number of subjects who passed the assessment."

**Comment by siuc-nate** [comment]
This change has been made in pending QData and noted in the history tracking.
