### ISSUE TITLE
Add ceterms:identifier to ceterms:Place

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#752]
In our ProPath meeting this morning, we encountered the need to be able to identify a Place using some arbitrary framework (such as the [FIPS codes](https://www.nrcs.usda.gov/wps/portal/nrcs/detail/national/home/?cid=nrcs143_013697) or [WIOA numbers](https://apps.illinoisworknet.com/map/Home/) and their equivalents in other states and countries).

The most effective way to solve this would seem to be to add ceterms:identifier to ceterms:Place.

Proposal:
**Add:**
> **Subject:** ceterms:identifier
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Place

**Comment by siuc-nate** [comment]
Note: This _may_ solve the issue we identified in #739; we'll need to look at it

**Comment by stuartasutton** [comment]
Seems reasonable.

**Comment by philbarker** [comment]
looks good to me

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
