### ISSUE TITLE
Change the range of ceterms:jobsObtained from integer to schema:QuantitativeValue

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#754]
Per our 2-9-2020 meeting:

It would be useful to be able to capture both a number and/or a percentage of jobs obtained. 

Proposal:

**Remove:**
> **Subject:** ceterms:jobsObtained
> **Predicate:** schema:rangeIncludes
> **Object:** xsd:integer

**Add:**
> **Subject:** ceterms:jobsObtained
> **Predicate:** schema:rangeIncludes
> **Object:** schema:QuantitativeValue

This would enable data like:
```
{
  "@type": "ceterms:AssociateDegree",
  "ceterms:employmentOutcome": [
    {
      "@type": "ceterms:EmploymentOutcomeProfile",
      "ceterms:jobsObtained": [
        {
          "@type": "schema:QuantitativeValue",
          "qdata:percentage": 88.0,
          "schema:description": { "en": "% of Program Graduates Employed in the Region" }
        }
      ]
    }
  ],
  "ceterms:earnings": [
    {
      "@type": "ceterms:EarningsProfile",
      "ceterms:medianEarnings": 44439,
      "ceterms:postReceiptMonths": 0,
      "ceterms:description": { "en": "Median Earnings of Program Graduates in Region" }
    },
    {
      "@type": "ceterms:EarningsProfile",
      "ceterms:medianEarnings": 49333,
      "ceterms:postReceiptMonths": 60,
      "ceterms:description": { "en": "Median Earnings of Program Graduates in Region" }
    }
  ]
}
```
Based on: https://ksdegreestats.org/ProspectusController?app=prospectus&ficeInstId=001910&programNbr=283

![image](https://user-images.githubusercontent.com/20917206/108537175-895c7500-729a-11eb-876f-9aefbcda48df.png)

**Comment by philbarker** [comment]
That looks reasonable

**Comment by stuartasutton** [comment]
Agreed. Reasonable.

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
