### ISSUE TITLE
Consideration: Consolidate CTDL aggregate data terms

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#756]
In the course of working with aggregate data lately, I have noticed a few things that suggest that our characterization of Earnings data, Holders data, and Employment Outcomes data as semantically distinct entities may not be as accurate as we once thought:
- There are very few properties that separate the [ceterms:EmploymentOutcomeProfile](https://credreg.net/ctdl/terms/EmploymentOutcomeProfile), [ceterms:EarningsProfile](https://credreg.net/ctdl/terms/EarningsProfile), and [ceterms:HoldersProfile](https://credreg.net/ctdl/terms/HoldersProfile) classes
- It produces unnecessarily complex graphs when, [as in ProPath](https://github.com/CredentialEngine/Schema-Development/blob/master/Aggregate%20Performance%20Data%20Examples/Pro%20Path/160%20Driving%20Academy.json), all three properties are used to point to very thin instances of their respective classes which are just indirect wrappers for getting to the **same** [qdata:DataSetProfile](https://credreg.net/qdata/terms/DataSetProfile)
- Cases like [Indiana](https://github.com/CredentialEngine/Schema-Development/blob/master/Aggregate%20Performance%20Data%20Examples/Pro%20Path/Indiana%20-%20BSN%20Pass%20Rates%20-%20Assistant%20API.json) where the data is not held in the Employment Outcome Profile, the Holders Profile, and/or the Earnings Profile, which means that these classes are just an extra layer of indirection
- Cases like [Kansas](https://github.com/CredentialEngine/Schema-Development/issues/754) where the data spread across the profiles is really about the same set of data
- Cases where the data in two or more of these classes is tied together by another property (like region) require repeating that data in each instance of the class (e.g. holders/earnings data for a given set of counties requires repeating the list of counties in both the Holders Profile and the Earnings Profile)
- It is very tedious to have to say, type, diagram, and/or write JSON examples for all three properties/classes when the intent is simply to convey "the aggregate data stuff" in discussions or presentations or meetings or some other context
- We now have QData for going into detail about any of the aggregate data when needed
- QData is also very explicit/specific about what the data is about and doesn't need context like "it is pointed to by a Holders Profile" in order to function properly
- The development of QData means that Employment Outcome Profile, Holders Profile, and Earnings Profile were never thoroughly developed/tested/used anyway since they had remained in an unfinished/prototype state in CTDL right up until the point where we started using them to point to DataSetProfile

As such, I think it is worth consolidating the area of CTDL that discusses aggregate data into a simpler set of terms.  For example, the following would replace ceterms:earnings, ceterms:holders, ceterms:employmentOutcome, ceterms:EarningsProfile, ceterms:HoldersProfile, and ceterms:EmploymentOutcomeProfile:

> **URI:** ceterms:aggregateData
> **Label:** Aggregate Data
> **Definition:** Statistical information about the Resource.
> **Domain:** ceterms:Credential and subclasses
> **Range:** ceterms:AggregateDataProfile

> **URI:** ceterms:AggregateDataProfile
> **Label:** Aggregate Data Profile
> **Definition:** Resource containing summary/statistical employment outcome, earnings, and/or holders information.
> **Usage Note:** For deeper information, use qdata:DataSetProfile.
> **Properties:** ceterms:name, ceterms:description, ceterms:jurisdiction, ceterms:source, ceterms:dateEffective, ceterms:expirationDate, ceterms:jobsObtained, ceterms:numberAwarded, ceterms:demographicInformation, ceterms:highEarnings, ceterms:medianEarnings, ceterms:lowEarnings, ceterms:postReceiptMonths, qdata:relevantDataSet

This isn't a final proposal, as it no doubt needs more thought, but it is intended to solve the above problems.

Additionally, it may make more sense to move the qdata:relevantDataSet property to be a property of Credential directly, since qdata:DataSetProfile contains its own terms for describing date ranges, jurisdiction, source, etc.  This would have the added benefit of allowing qdata:relevantDataSetFor to retain its inverse nature, which has come up in #755.

**Comment by stuartasutton** [comment]
Needs discussion in light of the Namespace Policy. This would be the biggest structural change to the CTDL yet.  Before heading off into this territory, it's best to think about other aspects--e.g., moving from CredentialAlignmentObject to DefinedTermSet etc.

**Comment by jeannekitchens** [comment]
Feb 23, 3021 CTDL Team Meeting Dicussion:

Immediately Implement:
1. Create superclass AggregateDataProfile and include the aggregateData property.  
2. Make the properties of  earnings, holders, and employmentOutcome subproperties of aggregateData.
2. Make EarningsProfile, OutcomeProfile, and EmploymentOutcomeProfile as subclasses of AggregateDataProfile.
3. Include usage notes to EarningsProfile, OutcomeProfile, and EmploymentOutcomeProfile to strongly suggest using AggregateDataProfile. 

Short-term:
1. Consult with TAG and states (i.e., Kansas, Illinois, WA, and NJ) to

**Comment by siuc-nate** [comment]
Changes to make for this release:

Create:
> **URI:** ceterms:aggregateData
> **Label:** Aggregate Data
> **Definition:** Statistical information about the Resource.
> **Domain:** ceterms:Credential and subclasses
> **Range:** ceterms:AggregateDataProfile

> **URI:** ceterms:AggregateDataProfile
> **Label:** Aggregate Data Profile
> **Definition:** Resource containing summary/statistical employment outcome, earnings, and/or holders information.
> **Usage Note:** For deeper information, use qdata:DataSetProfile.
> **Properties:** ceterms:name, ceterms:description, ceterms:jurisdiction, ceterms:source, ceterms:dateEffective, ceterms:expirationDate, ceterms:jobsObtained, ceterms:numberAwarded, ceterms:demographicInformation, ceterms:highEarnings, ceterms:medianEarnings, ceterms:lowEarnings, ceterms:postReceiptMonths, qdata:relevantDataSet

Add:
> **Subject:** ceterms:HoldersProfile, ceterms:EmploymentOutcomeProfile, ceterms:EarningsProfile
> **Predicate:** rdfs:subClassOf
> **Object:** ceterms:AggregateDataProfile

> **Subject:** ceterms:holders, ceterms:employmentOutcome, ceterms:earnings
> **Predicate:** rdfs:subPropertyOf
> **Object:** ceterms:aggregateData

> **Subject:** ceterms:holders, ceterms:employmentOutcome, ceterms:earnings
> **Predicate:** vann:usageNote
> **Object:** "It is strongly recommended to use ceterms:aggregateData instead of this property."

> **Subject:** ceterms:HoldersProfile, ceterms:EmploymentOutcomeProfile, ceterms:EarningsProfile
> **Predicate:** vann:usageNote
> **Object:** "It is strongly recommended to use ceterms:AggregateDataProfile instead of this class."

Not happening in this release:
- Deprecation of ceterms:holders, ceterms:employmentOutcome, or ceterms:earnings
- Deprecation of ceterms:HoldersProfile, ceterms:EmploymentOutcomeProfile, ceterms:EarningsProfile

Correct?

**Comment by siuc-nate** [comment]
One more thing - Are we attaching qdata:relevantDataSet directly to Credential (and making the change described in #755 ) or are we using qdata:relevantDataSet with ceterms:AggregateDataProfile and doing something different with #755?

**Comment by philbarker** [comment]
The change proposal above for this release looks good to me.

I don't think we finished the discussion about #755 for attaching qdata:relevantDataSet directly to Credential.

**Comment by siuc-nate** [comment]
Correct, we didn't finish that discussion.  I think it makes sense to move qdata:relevantDataSet to Credential (instead of making it a property of ceterms:AggregateDataProfile) and to change the range of qdata:relevantDataSetFor to point to Credential (and not, at this time, to AssessmentProfile/LearningOpportunityProfile.

**Comment by philbarker** [comment]
I think it is essential that the ceterms:AggregateDataProfile has a link to the data set of which it is a summary, which implies the  inverse relation should point to it. But let's not have that discussion in the wrong issue.

**Comment by siuc-nate** [comment]
My supposition is that if you have enough data that you need to get into QData, then you probably don't need to create a corresponding AggregateDataProfile at all - a summary may be convenient for some consumers, but for others it just means figuring out which data is redundant and how to avoid displaying the same thing twice.

**Comment by stuartasutton** [comment]
In the [definitions section](https://github.com/CredentialEngine/Schema-Development/issues/756#issuecomment-786042471) above, I see several things that should be changed.

1. `Resource` in the definition of `aggregateData` should be lower cased.
2. The definition of `AggregateDataProfile` has two issues: (a) "...holders information" should be "...holders data"--there is a difference between data and information; and (b) can you bullet proof this definitions should QData ultimately encompass more than just earnings, employment and holders data.
3.  Can we change the ambiguous word "deeper" in the Usage Note for `AggregateDataProfile` to something more description--e.g., "To express more complex data, use `qdata:DataSetProfile`."
4. Change both sentences in the definitions following this pattern: "It is strongly recommended to use `ceterms:aggregateData` instead of this property." to "The use of ceterms:aggregateData instead of this property is strongly recommended."

**Comment by siuc-nate** [comment]
Thanks.

Updated Proposal:

Changes to make for this release:

Create:
> **URI:** ceterms:aggregateData
> **Label:** Aggregate Data
> **Definition:** Statistical information about the resource.
> **Domain:** ceterms:Credential and subclasses
> **Range:** ceterms:AggregateDataProfile

> **URI:** ceterms:AggregateDataProfile
> **Label:** Aggregate Data Profile
> **Definition:** Resource containing summary statistical data.
> **Usage Note:** To express more complex data, use qdata:DataSetProfile.
> **Properties:** ceterms:name, ceterms:description, ceterms:jurisdiction, ceterms:source, ceterms:dateEffective, ceterms:expirationDate, ceterms:jobsObtained, ceterms:numberAwarded, ceterms:demographicInformation, ceterms:highEarnings, ceterms:medianEarnings, ceterms:lowEarnings, ceterms:postReceiptMonths

Add:
> **Subject:** ceterms:HoldersProfile, ceterms:EmploymentOutcomeProfile, ceterms:EarningsProfile
> **Predicate:** rdfs:subClassOf
> **Object:** ceterms:AggregateDataProfile

> **Subject:** ceterms:holders, ceterms:employmentOutcome, ceterms:earnings
> **Predicate:** rdfs:subPropertyOf
> **Object:** ceterms:aggregateData

> **Subject:** ceterms:holders, ceterms:employmentOutcome, ceterms:earnings
> **Predicate:** vann:usageNote
> **Object:** "The Use of ceterms:aggregateData instead of this property is strongly recommended."

> **Subject:** ceterms:HoldersProfile, ceterms:EmploymentOutcomeProfile, ceterms:EarningsProfile
> **Predicate:** vann:usageNote
> **Object:** "The Use of ceterms:AggregateDataProfile instead of this class is strongly recommended."

Not happening in this release:
- Deprecation of ceterms:holders, ceterms:employmentOutcome, or ceterms:earnings
- Deprecation of ceterms:HoldersProfile, ceterms:EmploymentOutcomeProfile, ceterms:EarningsProfile

Still up in the air:
- Whether qdata:relevantDataSet should be a property of ceterms:AggregateDataProfile or a property of ceterms:Credential and its subclasses
- Whether qdata:relevantDataSetFor should have its range appended with ceterms:AggregateDataProfile or completely changed to ceterms:Credential and its subclasses (#755)

**Comment by siuc-nate** [comment]
We need to solve those last two bullet points before I can implement this set of changes, or we need an interim solution.

**Comment by philbarker** [comment]
On the domain of `qdata:relevantDataSet`: 
If there is aggregate data I definitely want to know what data set it comes from. Someone tells me that 99% of their graduates get a job, I want to see all about how that figure was arrived at. So there needs to be provision for a property pointing from the AggregateData to a Dataset.

On `qdata:relevantDataSetFor`
Looking at issue the discussion around #755 especially [Nates comment](https://github.com/CredentialEngine/Schema-Development/issues/755#issuecomment-784283355) of 23 Feb, it doesn't look like there is a strong use case for having the `relevantDataSetFor` property.

Also, the defnition of  [`relevantDataSetFor`](https://credreg.net/qdata/terms/relevantDataSetFor) is quite vague "Data set for the entity being referenced." -- If a I commission a data set, that data set is for me so is it valid to say `<Data> qdata:relevantDataSetFor <Phil> .` That doesn't seem to be how we are using it, and the existing range confirms for me that something different is meant. The domain & range parts of a property is an important part of defining what the property means.

I think if the data set is about a Credential, it is fine to say `<Data> schema:about <Credential> .` You can even have an inverse `<Credential> schema:subjectOf <Data> .` -- which gives the link from a credential directly to data about it. However, that's using `about` in a certain way, it may be preferable to have a specific subproperty of `about`.    Either way, I do not think that this relationship is the inverse of a relationship between AggregateData and the data set from which it was derived. 

Finally, and following from the final points in the last two paras, I think that changing the domain or range of these properties would change their meaning in way that doesn't sit comfortably with the namespace policy (it is a broadening, won't break existing data, so it's not too bad; however, it might break queries).

So, I suggest:
* keep the domain of `qdata:relevantDataSet` as the aggregate data classes only
* Use `about`/`subjectOf` or subproperties of them to point to/from a credential from/to data, _if you need it_.

**Comment by stuartasutton** [comment]
I think Phil's approach here is appropriate.

**Comment by siuc-nate** [comment]
So to clarify, for this release, we will make qdata:relevantDataSet a property of ceterms:AggregateDataProfile, and update the range of qdata:relevantDataSetFor to point to ceterms:AggregateDataProfile? The latter has no URI, so that connection won't work in the registry.

Are we going to add schema:about to qdata:DataSetProfile?

**Comment by siuc-nate** [comment]
Per our 3-9-2021 meeting:

- The qdata:relevantDataSetFor property will have its range changed to ceterms:AggregateDataProfile
- We will add schema:about to QData as a property of qdata:DataSetProfile as described below

Thus, the updated proposal for this release consists of:

**Create:**
> **URI:** ceterms:aggregateData
> **Label:** Aggregate Data
> **Definition:** Statistical information about the resource.
> **Domain:** ceterms:Credential and subclasses
> **Range:** ceterms:AggregateDataProfile

> **URI:** ceterms:AggregateDataProfile
> **Label:** Aggregate Data Profile
> **Definition:** Resource containing summary statistical data.
> **Usage Note:** To express more complex data, use qdata:DataSetProfile.
> **Properties:** ceterms:name, ceterms:description, ceterms:jurisdiction, ceterms:source, ceterms:dateEffective, ceterms:expirationDate, ceterms:jobsObtained, ceterms:numberAwarded, ceterms:demographicInformation, ceterms:highEarnings, ceterms:medianEarnings, ceterms:lowEarnings, ceterms:postReceiptMonths, qdata:relevantDataSet

> **URI:** schema:about (in the QData schema)
> **Label:** About
> **Definition:** Subject matter of the resource.
> **Domain:** qdata:DataSetProfile
> **Range:** ceterms:Credential (and subclasses), ceterms:LearningOpportunityProfile, ceterms:AssessmentProfile

**Add:**
> **Subject:** ceterms:HoldersProfile, ceterms:EmploymentOutcomeProfile, ceterms:EarningsProfile
> **Predicate:** rdfs:subClassOf
> **Object:** ceterms:AggregateDataProfile

> **Subject:** ceterms:holders, ceterms:employmentOutcome, ceterms:earnings
> **Predicate:** rdfs:subPropertyOf
> **Object:** ceterms:aggregateData

> **Subject:** ceterms:holders, ceterms:employmentOutcome, ceterms:earnings
> **Predicate:** vann:usageNote
> **Object:** "The Use of ceterms:aggregateData instead of this property is strongly recommended."

> **Subject:** ceterms:HoldersProfile, ceterms:EmploymentOutcomeProfile, ceterms:EarningsProfile
> **Predicate:** vann:usageNote
> **Object:** "The Use of ceterms:AggregateDataProfile instead of this class is strongly recommended."

> **Subject:** qdata:relevantDataSetFor
> **Predicate:** schema:rangeIncludes
> **Object:** ceterms:AggregateDataProfile

> **Subject:** ceterms:subject
> **Predicate:** rdfs:subPropertyOf
> **Object:** schema:about

**Remove:**
> **Subject:** qdata:relevantDataSetFor
> **Predicate:** schema:rangeIncludes
> **Object:** ceterms:HoldersProfile, ceterms:EmploymentOutcomeProfile, ceterms:EarningsProfile

> **Subject:** ceterms:subject
> **Predicate:** owl:equivalentProperty
> **Object:** schema:about

Not happening in this release:
- Deprecation of ceterms:holders, ceterms:employmentOutcome, or ceterms:earnings
- Deprecation of ceterms:HoldersProfile, ceterms:EmploymentOutcomeProfile, ceterms:EarningsProfile

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.

**Comment by siuc-nate** [comment]
One small addendum: @mparsons-ce identified the need to convey what currency the low/median/high earnings are expressed in. We apparently never added ceterms:currency to ceterms:EarningsProfile, so it got missed when I was merging the properties in earlier posts.

I think we should also extend the domain of ceterms:currency to include ceterms:AggregateDataProfile.

**Add:**
> **Subject:** ceterms:currency
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:AggregateDataProfile

any objections?

**Comment by mparsons-ce** [comment]
@philbarker @stuartasutton 
If adding currency to AggregateDataProfile, should it also be added to EarningsProfile?

**Comment by stuartasutton** [comment]
Well, since we have gotten EarningsProfile sort of half way to deprecation (use AggregateDataProfile instead), should we continue to develop it?

**Comment by philbarker** [comment]
I think the answer to @stuartasutton's question, and hence also @mparsons-ce's is "Nope"

**Comment by siuc-nate** [comment]
Okay, so we add currency to AggregateDataProfile, but not to EarningsProfile, correct?

**Comment by stuartasutton** [comment]
Yes.

**Comment by siuc-nate** [comment]
I have made the changes listed above.

Note that this also includes adding ceterms:aggregateData not only to Credential (as was listed in the earlier post) but also to Assessment Profile and to Learning Opportunity Profile (as this is what was depicted in the diagram and makes sense given that schema:about points to all three).
