### ISSUE TITLE
Update schema: prefix URI because schema.org is moving from http to https

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/Schema-Development#760]
The upcoming version 12 of schema.org completes the process of schema.org moving from http:// URIs to https://.

See issue at https://github.com/schemaorg/schemaorg/pull/2814 discussion at https://github.com/schemaorg/schemaorg/issues/2852#issuecomment-787057322 and penultimate bullet for the changes on the staging site at https://webschemas.org/docs/releases.html#v12.0

We should update our prefix definitions for `schema:` accordingly.

**Comment by siuc-nate** [comment]
Is this something that is ready to go right now? Or is it still in staging?

**Comment by philbarker** [comment]
v12.0 is slated for release on 08-Mar-2021

But schema.org have been running https:// in parallel with http:// for some time [[1](https://schema.org/docs/faq.html#19)] so it should be safe to implement now.

**Comment by siuc-nate** [comment]
Okay, I have updated our contexts.

Thanks, Phil
