### ISSUE TITLE
AudienceType Definition is too narrow

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#761]
The AudienceType definition is too narrow.  We had gone through and changed definitions so not to only reference credentials or in this case credential seekers.  The audience type could be applicable to credentials, learning opps, assessments, pathways.  Do we need to update the definition or is it sufficient?  https://credreg.net/ctdl/terms#audienceType

**Comment by stuartasutton** [comment]
Jeanne, do you mean the definition here: https://purl.org/ctdl/terms/audienceType:

>The type of credential seeker for whom the entity is applicable; select from an existing enumeration of such types.

The range of [ceterms:audienceType](https://purl.org/ctdl/terms/audienceType) is [ceterms:Audience](https://credreg.net/ctdl/terms/Audience) which enumerates the status of persons.

Perhaps a revised description:
>The status of a person for whom the entity is applicable; select from an existing enumeration of such types.

Then add learning opps, assessments, pathways to the domain of [ceterms:audienceType](https://purl.org/ctdl/terms/audienceType)

**Comment by jeannekitchens** [comment]
Current https://credreg.net/ctdl/terms#audienceType definition is only applicable to Credential domains.  Pathways and other classes have audiences.  

Definition: | en-US: The type of credential seeker for whom the entity is applicable; select from an existing enumeration of such types.
-- | --
Usage Note: | en-US: Best practice for developing credential descriptions for the Credential Engine Registry is to use the ceterms:Audience vocabulary.

**Comment by stuartasutton** [comment]
Slight modification of Nate's suggestion:

> The type of audience for whom the entity is applicable or useful; select from an existing enumeration of such types.

**Comment by philbarker** [comment]
My iteration:

> The type of audience for which the entity is intended or useful; select from an existing enumeration of such types.

**Comment by siuc-nate** [comment]
Why not combine them?:
>The type of audience for which the entity is applicable, intended, or useful; select from an existing enumeration of such types.

**Comment by siuc-nate** [comment]
I'll mark this as "ready to implement" unless there are any objections (note that I changed "entity" to "resource" for consistency with our other definitions):

**Remove:**
> **Subject:** ceterms:audienceType
> **Predicate:** rdfs:comment
> **Object:** "The type of credential seeker for whom the entity is applicable; select from an existing enumeration of such types."

**Add:**
> **Subject:** ceterms:audienceType
> **Predicate:** rdfs:comment
> **Object:** "The type of audience for which the resource is applicable, intended, or useful; select from an existing enumeration of such types."

**Comment by stuartasutton** [comment]
The definition is a bit circular using the term it is working to define. Isn't the audience type in this context always a person...perhaps: "The type of person for which the resource is applicable, intended, or useful; select from an existing enumeration of such types."

**Comment by siuc-nate** [comment]
I think we used "audience" because it covers both individuals and groups (and potentially non-humans, but I think I agree that those probably aren't applicable here).  Perhaps:

"The type of person or group for which the resource is applicable, intended, or useful; select from an existing enumeration of such types."

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
