### ISSUE TITLE
IdentifierValue object is overkill for autochthonous identifiers with no scheme 

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/Schema-Development#762]
"autochthonous" = formed or originating in the place where found :)

We need a way of saying that an  identifier comes from the same framework as the thing being described.

The [IdentifierValue](https://purl.org/ctdl/terms/IdentifierValue) class is useful for saying what code is being used as an identifier (the [identifierValueCode](https://credreg.net/ctdl/terms/identifierValueCode)) and what scheme it is drawn from (the [identifierType](https://credreg.net/ctdl/terms/identifierType) / [identifierTypeName](https://credreg.net/ctdl/terms/identifierTypeName)), e.g. 
```
"ceterms:identifier": {  
   "@type": "ceterms:IdentifierValue",
   "ceterms:identifierValueCode": "0-330-25864-8",
   "ceterms:identifierTypeName": "ISBN"
}
```
The code on its own would be meaningless.

In example of describing an Occupation drawn from the [NICE framework](https://gist.github.com/philbarker/858130a2dd2feb6940f7416f73489116) we see
```
"ceterms:identifier":  {
    "@type": "ceterms:IdentifierValue",
    "ceterms:identifierValueCode": "RSK"
}
```
and similar. The implied meaning here is that the identifier comes from the same source as the thing in which it is found (in this case an Occupation framework). We could coin an ad hoc `identifierType` in order to make this meaning explicit (`"ceterms:identifierTypeName": "autochthonous"` anyone?), but a simpler solution already exists in ceasn:

 [ceasn:codedNotation](https://purl.org/ctdlasn/terms/codedNotation): An alphanumeric notation or ID code as defined by the promulgating body to identify this resource.

The similar term in ctdl is less clearly defined, reflecting its use in Alignment Objects:

[ceterms:codedNotation](https://purl.org/ctdl/terms/codedNotation) Set of alpha-numeric symbols that uniquely identifies an item and supports its discovery and use.

I think we should re-align `codedNotation` in ceterms with the term in ceasn, and add Occupation, Job, Task, WorkRole to its domain. We would need not to muddy how it is used in the AlignmentObject, e.g. with a usage note to expand on what is meant by "promulgating body" (possibly defined as "the body that created the framework within which it is used")

**Comment by siuc-nate** [comment]
Interesting.  I am glad we held onto codedNotation, as I doubted we had seen the last of it.

Would it be better to redefine ceterms:codedNotation or to just add ceasn:codedNotation to the classes you listed?  I'm not sure of the ramifications one way or another, or whether there might be some future situation where it would be useful to have both terms on the same class, defined as they presently are.

**Comment by philbarker** [comment]
@siuc-nate I did wonder about just using `ceasn:codedNotation`, but wouldn't it be confusing for data providers to have two variants of codedNotation, especially if they were on the same class? 

My proposal would give us essentially the same term in the two namespaces, `ceasn:codedNotation` for `ceasn:Competency` and `ceterms:codedNotation` for various `ceasn:` classes. I think there may be some benefit in keeping ceasn "clean" so that when you see a `ceasn:codedNotation` out in the wild you know what you're dealling with.  I think that would help with effprts to get people like the W3C VC-Ed group to adopt it. I don't think there is much to lose by adding more direct semantics to the domain of `ceterms:CredentialAlignmentObject` terms as the alignment object is already in the range of so many properties you don't get much by way of semantic meaning just from knowing you've got a `ceterms:CredentialAlignmentObject`.

**Comment by mparsons-ce** [comment]
Currently the publishing API does not require an `IdentifierTypeName` when publishing an `IdentifierValue`. 

Should it? 
**That is when publishing an `IdentifierValue `property to the registry, should both `IdentifierTypeName `and `IdentifierValueCode `be required?**

It would be contrary to Phil's suggestion, however the value of an IdentifierValue over CodedNotation is that by providing the IdentifierTypeName, the context is clear.

**Comment by philbarker** [comment]
@mparsons-ce Not contrary to my suggestion! I'm suggesting that every `ceterms:IdentifierValue` should have one or both of `ceterms:identifierType` and `ceterms:identifierTypeName`, as well as `ceterms:identifierValueCode`, and that we need a different property for when that isn't the case.

**Comment by philbarker** [comment]
@stuartasutton what I am saying is that I don't see much to lose in expanding the domain of **ceterms**:codedNotation because it is currently used on AlignmentObjects and so we don't know (directly from the domain of ceterms:codedNotation) what sort of resource is being described. Currently though **ceasn**:codedNotation is used only on competencies, and has a nice specific meaning within that vocabulary.  I wouldn't want to lose that specificity by fully merging ceasn:codedNotation with the ceterms version, which is what Nate mentioned in the previous post.

**Comment by philbarker** [comment]
Proposal:

- Change the domain of ceterms:codedNotation to include Jobs, Occupation, Task and WorkRole; 
- align its defintion with ceasn:codedNotation
- add usage notes to ceterms:codedNotation and ceterms:identfier to clarify when each should be used.

Add
>**Subject:** ceterms:codedNotation
>**Predicate:** schema:domainIncludes
>**Object:** ceterms:Occupation, ceterms:Job, ceterms:WorkRole, ceterms:Task 

(arguably, codedNotation could have the same domain as ceterms:identifier, but this domain deals with the current issue)

Change
>**Subject:** ceterms:codedNotation
>**Predicate:** rdfs:comment
>**Object:** "Set of alpha-numeric symbols as defined by the body responsible for an item that uniquely identifies that item and supports its discovery and use."

Add
>**Subject:** ceterms:codedNotation
>**Predicate:** vann:usageNote
>**Object:** "For identifiers that come from a recognised identification scheme use the specific property for that identifer type, such as ceterms:opeID, ceterms:ncesID, ceterms:leiCode, etc., or use ceterms:identifier so that the identification schema can be named."

Change
>**Subject:** ceterms:identifier
>**Predicate:** vann:usageNote
>**Object:** "Where a specific property for the originating context or scheme exists, such as ceterms:opeID, ceterms:ncesID, ceterms:leiCode, etc., use that property instead of this one. Where the identifier has no nameable originating context or scheme other than that of the resource being identified, ceterms:codedNotation may be used."

**Comment by siuc-nate** [comment]
I would suggest a tweak to the definition change for consistency with our other definitions:
"Set of alpha-numeric symbols as defined by the body responsible for this resource that uniquely identifies this resource and supports its discovery and use."

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
