### ISSUE TITLE
How do I link jobs to Credentials? (Educational, Licensure)

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/Schema-Development#764]
The Dignity Health job description says:

> Education
> Graduate of an accredited school of nursing; BSN Preferred Graduate of an accredited school of nursing BSN

and 

> Licensure
> AZ RN license or RN License from a Compact State. BLS
> Certification. ACLS certification (in monitored areas).
> Professional certification in area of specialty preferred

How do we represent that some Jobs require Credentials?

**Comment by philbarker** [comment]
As discussed on the call of March 30, 2021: it should be possible to express requirements like this for Jobs and Occupations. We can extend the use of ceterms:requires to make it so. 

Aside: We should also create an example showing how a generic qualification such as "Nursing Degree from accredited provider" can be represented.

Proposal

Add

> **Subject:** ceterms:requires
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Job, ceterms:Occupation

Delete

> **Subject:** ceterms:requires
> **Predicate:** rdfs:comment
> **Object:** "Requirement or set of requirements for this credential, learning opportunity, or assessment."

Add

> **Subject:** ceterms:requires
> **Predicate:** rdfs:comment
> **Object:** "Requirement or set of requirements for this resource."

**Comment by stuartasutton** [comment]
+1 on these changes.

**Comment by siuc-nate** [comment]
Works for me.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
