### ISSUE TITLE
Represent that a generic qualification of some type is required.

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/Schema-Development#766]
Once issue #764 is resolved and we can represent requirements for jobs we should also create an example showing how a generic qualification such as "Nursing Degree from accredited provider" can be represented. This would probably involve a BNode of the required type but no specifics.

**Comment by jeannekitchens** [comment]
The degree super classes are not typically used.  Rather associates, etc.. is used. Certificates, badges, etc are published using their  superclasses.  I don't know that this makes  a difference your suggestion @philbarker.  Just as interesting information, you can see reports of data counts via the Credential Finder.  Go down to Credentials and click on types.  https://credentialfinder.org/reports#registryData

**Comment by stuartasutton** [comment]
Jeanne, just to be clear, I meant that the superclasses could be used where the job, for example, designates a "degree in nursing" which could mean any of the degree subclasses.

**Comment by jeannekitchens** [comment]
+1 @stuartasutton.  That fulfills a very common use case.

**Comment by philbarker** [comment]
yes, though rather than the description property you could use the accreditedBy with a BNode for QAOrganization. 
```
"@graph": [
  {
    "@type": "ceterms:Job",
    "ceterms:requires": [
      {
        "@type": "ceterms:ConditionProfile",
        "ceterms:targetCredential": [ "_:abc..." ]
      }
    ]
  }
  {
    "@id": "_:abc",
    "@type": "ceterms:License",
    "ceterms:accreditedBy":  "_:123"
  },
{
    "@id": "_:123",
    "@type": "ceterms:QACredentialOrganization",
    "ceterms:description":  "Any QA Org."
  },
]
```
The proliferation of BNodes is more convoluted, but the presence of a ceterms:accreditedBy could be machine actionable.

See also https://gist.github.com/philbarker/471c03098e5386dfc3a2f3a4a0c8abbb which has code for a License recognised in the relevant jurisdiction

```
{
  "@context": "https://credreg.net/ctdl/schema/context/json",
  "@graph": [
    {
      "@id": "_:Job_100-1234",
      "@type": "ceterms:Job",
      "ceterms:name": "Acme Job",
      "ceterms:requires": [
        "_:Credential_001"
      ]
    },
    {
      "@id": "_:Credential_001",
      "@type": "ceterms:License",
      "ceterms:name": "License to practise",
      "ceterms:recognizedIn": {
        "@id": "_:Jurisdiction_001",
        "@type": "ceterms:JurisdictionProfile",
        "ceterms:mainJurisdiction": {
          "@type": "ceterms:Place",
          "addressRegion": "NY"
        }
      }
    }
  ]
}

**Comment by siuc-nate** [comment]
It seems like this one is solved. Can it be closed?

**Comment by philbarker** [comment]
I think so. We can re-open if we ever need to.
