### ISSUE TITLE
Should use of QuantitativeValue contents be interpreted consistently or allow exceptions like PassRate

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/Schema-Development#767]
The property PassRate was added to AggregateData. 
https://github.com/CredentialEngine/Schema-Development/issues/751
It includes the usage note:
`When data is available, record both the percentage and the number of subjects who passed the assessment.`

A QuantitativeValue has the flexibility to provide numerical data using any of:
- Value
- Min/MaxValue
- Percentage

The API has edits to only allow one of the three possible numerical properties. 
Decisions:
Should only one numerical value (where min/max is one of the groups) be allowed for QuantiativeValue?

If multiple are allowed, then what combinations?

If multiple are allowed, should a description be required (to explain the numbers - even for PassRate?

**Comment by siuc-nate** [comment]
I don't think we should restrict any of the options - if someone wants to publish all four, what's the problem?

**Comment by mparsons-ce** [comment]
If we are allowing anything, then I would think that a description should be required to explain the meaning of the values.

**Comment by siuc-nate** [comment]
I would be inclined to agree, but in QData, many of the properties that reference the Quantitative Value (e.g. PassRate) already provide an explanation of what the values mean - unless I am misinterpreting what you're getting at.

**Comment by stuartasutton** [comment]
I agree with Nate that we shouldn't limit.  For example, with PassRate, you need the percentage (the rate) and the value being those that passed. While the number of takers can be calculated from those two values, the description could narratively provide the numbers of takers.

**Comment by jeannekitchens** [comment]
This is only a CTDL policy issue.  The description is a Benchmark.  It is not required.

**Comment by siuc-nate** [comment]
Per our 4/13/2021 meeting:

- We will recommend Description in Quantitative Value
- We will allow any combination of value properties to be published
- If we encounter a case/partner that is publishing data that doesn't seem to make sense, we will resolve it with that partner and potentially revisit the policy questions again at that time.

**Comment by jeannekitchens** [comment]
This is being handled via a Quantitative Value Support Class section in the CTDL Handbook.
