### ISSUE TITLE
Extend the domain of ceterms:targetPathway to include ceterms:ConditionProfile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#768]
In order to accommodate use cases like [Fluree](https://drive.google.com/drive/folders/1iR97qPhajCKhH5yoNfEwYN36c4x03wKG) where the requirements for a Credential are very detailed and are better described via a Pathway rather than via a complex tree of Condition Profiles connected via [alternativeCondition](https://credreg.net/ctdl/terms/alternativeCondition), we should **consider and discuss** (to look for potential pitfalls - I have not thought this through completely yet and need to run it by more people) allowing a Condition Profile to reference a Pathway.  This can be accomplished by simply adding Condition Profile to the domain of the existing [Target Pathway](https://credreg.net/ctdl/terms/targetPathway) property.

This would essentially allow the Credential to say that its requirements are to complete the target pathway. This bypasses the need to both create the pathway _and_ embody the pathway in the condition profiles.

Usage:
![image](https://user-images.githubusercontent.com/21346519/113902012-0e411680-9795-11eb-951e-d41de2da2e18.png)

Tentative Proposal:

**Add:**
> **Subject:** ceterms:targetPathway
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:ConditionProfile

**Comment by philbarker** [comment]
I guess this is an aside, and kind of nitpicking, but in the diagram [above](https://github.com/CredentialEngine/Schema-Development/issues/768#issue-852589064) it seems odd to have sourceData pointing to a Credential. A Credential isn't data even though when you resolve the identifier for the Credential you get data about it. If this is the intended usage, it would be better to call the property `source` and remove the reference to "data" in the definition (and I would change its range to rdfs:Resource).

**Comment by stuartasutton** [comment]
+1 to Phil.  Needs discussion.

**Comment by philbarker** [comment]
To the main point, the pathway here looks to me like a combination of courses/assessments/activities etc that are part of a Program, i.e. a learning opportunity. So my questions are how is a program related to a pathway and how do we say that a credential requires successful completion of a pathway/program? From an education point of view these are fairly core things to want to say.  
This is related to issue #730, and the idea that some learning opportunities are only offered as part of a pathway comprised by something bigger while others are that bigger thing, and others again are short and self-contained.

**Comment by siuc-nate** [comment]
**Re: source/sourceData**
Since we already have [ceterms:source](https://credreg.net/ctdl/terms/source), we created [ceterms:sourceData](https://credreg.net/ctdl/terms/sourceData) to be the "structured data" equivalent of `source`. We also didn't want to limit it to just registry expressions of that data (so as to allow things like wikidata), hence the use of xsd:anyURI.  Perhaps a tweak to the range and/or definition is in order, but that is beyond the scope of this thread.

**Re: targetPathway**
Learning Opportunity, by its definition, explicitly covers both programs and courses (and everything in between), and it is probably true to say that in this case the Credential requires completion of a program, and that that program's details are described by the pathway.  

We could express this by having the Credential require a Learning Opportunity which, in turn, embodies the information in the pathway through a connected tree of Condition Profiles leveraging ceterms:alternativeCondition, but that seems overly complex when those same requirements are much more cleanly expressed via the Pathway. The main sticking point there is that the Condition Profile does not have the equivalent of ComponentCondition allowing it to say "x of y are required"; the alternativeCondition property explicitly says in its definition that "any one" of the Condition Profiles it references would satisfy it.  This would be the equivalent of only being able to assert "requiredNumber: 1" in a ComponentCondition.

We could _perhaps_ remedy this by adding ceterms:requiredNumber to ceterms:ConditionProfile and modifying the definition of aleternativeCondition to reference that.  That, I think, would allow Condition Profiles to construct the pathway using a very similar structure and number of entities.  I will model this to be sure when I get some time.

**Comment by philbarker** [comment]
> We could express this by having the Credential require a Learning Opportunity which, in turn, embodies the information in the pathway through a connected tree of Condition Profiles leveraging ceterms:alternativeCondition, but that seems overly complex when those same requirements are much more cleanly expressed via the Pathway. 

Why not link the Learning Opportunity to the Pathway explicitly? Credential requires (completion of) a Learning Opportunity which embodies Pathway directly?

Yes, this is probably equivalent to what you're suggesting, I just want it described in general terms that clarifies the relationship between programs and pathways. I think doing this would help clarify whether `sourceData` pointing to data is problematic.

@stuartasutton is the PathwayComponent to LearningOpportunity relationship similar to the idea of proxy resources in OAI-ORE, and ListItem--item->Resource relationship in schema.org? i.e. is a xyzComponent a representation of some other thing that can be ordered without implying a fixed ordering of the thing itself?

**Comment by stuartasutton** [comment]
It's been a long time since I've looked at OAI-OER...the xyzComponent classes in a Pathway are intended as proxies or surrogates for the entities they represent. Nothing about an instance of the xyzComponent and its pathway context implies anything about ordering of the thing it represents.

**Comment by siuc-nate** [comment]
Okay, so after modeling this, I realized that we would also need to extend the range of ceterms:alternativeCondition to include credentials, assessments, and learning opportunities.  We usually try to avoid having multiple kinds of things in the range of a property, but the alternative (no pun intended) is to confuse the scope of ceterms:requiredNumber while creating a lot of new properties for a very limited edge case, or create a lot of extraneous condition profiles (as in one for each learning opportunity in the pseudo-pathway), so I think this is the least problematic choice. @mparsons-ce what do you think?

Graph-wise, it would look a **lot** like a pathway (which is the intent).  In this partial diagram, the unlabeled curvy arrows along the bottom are all "alternativeCondition" (constrained by requiredNumber as mentioned in my previous post):
![image](https://user-images.githubusercontent.com/21346519/114235885-6f5c1c00-9946-11eb-9450-92490542dfdf.png)

One downside of doing all of this through Condition Profile is that we don't currently have a good way to display it. Condition Profiles can have a lot more stuff in them compared to Pathway Components, so it wouldn't be quite as simple as adapting the existing pathway display (perhaps each one would open in its own modal window when clicked?).  The internal handling for Condition Profiles would probably not be quite as efficient as Pathway Components either, for the same reason.

**Comment by mparsons-ce** [comment]
A pathway has a destination component. There may be more than one internal path to get to the destination component. One of the pathway examples uses a Java path or a C# path to get to the destination component.
The real requirement is the destination component. So I don't see the purpose of adding a target pathway where a target credential (destination component) clearly indicates the requirement.

**Comment by siuc-nate** [comment]
The intent would be to enable using a pathway to describe the requirements for a credential (instead of a branching tree of condition profiles).  The credential would still be the destination.

I suppose it may be a little unnecessary if we just show that the credential is the destination for the pathway on the credential's detail page in the finder - but that is a looser way to communicate the information vs saying, explicitly/semantically, that the credential "requires" the pathway (that leads to itself).

Related - the Condition Profile example I provided above **only** works if there are no places where a Condition Profile has more than one parent, since we don't currently treat Condition Profiles as bnodes in the flat graph (they are structurally embedded in the JSON). The things the Condition Profiles point to can be pointed to by more than one Condition Profile provided they have URIs; that is not a problem. The problem would arise if (in the above picture) "Physical Education" needed to be an alternativeCondition referenced by two or more "parent" Condition Profiles.

**Comment by stuartasutton** [comment]
@philbarker, you ask in your comment above: "So my questions are how is a program related to a pathway and how do we say that a credential requires successful completion of a pathway/program?".  I think the cleanest way of looking at a program  is as an inventory of learning opportunities and other requirements while a related pathway (separate resource) describes a specific path through the program requirements.   Thus a program could have 1..* pathways; e.g., one prescribed by a particular professor and/or many individual student paths...as circumstances/use cases dictate.  

This seems much cleaner than trying to fold the path directly into the program with instances of ConditionProfile.

**Comment by siuc-nate** [comment]
Per our 4-13-2021 meeting:

![image](https://user-images.githubusercontent.com/21346519/114601562-3fb95680-9c5b-11eb-97ad-cdfb5fb06315.png)

**Add:**
> **Subject:** ceterms:targetPathway
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:ConditionProfile

**Comment by stuartasutton** [comment]
I agree with https://github.com/CredentialEngine/Schema-Development/issues/768#issuecomment-818957175 above. Is there a reason that this has been hanging around for nearly a year?

**Comment by stuartasutton** [comment]
If targetPathway's domain is extended to include componentCondition, why should it not also be extended to other classes including Course, Assessment, Learning opportunity, Learning Program to identify individual Pathways in which these resources can be found?

**Comment by siuc-nate** [comment]
The objective with this particular issue was to allow pathways to be used to describe conditions/requirements for earning a credential (hence adding targetPathway to the domain of ConditionProfile).  I don't suppose there is any harm in adding targetPathway to the other classes, but that wasn't the original focus of this issue.

**Comment by stuartasutton** [comment]
I understand https://github.com/CredentialEngine/Schema-Development/issues/768#issuecomment-1059517927, Nate. But while we are at it, why not wrap up the entire package for targetPathway.
