### ISSUE TITLE
Indicate closure of an Organization including credential and QA organizations. 

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#770]
Organizations can have an end of life; they close.  This is not the equivalent of not longer offering a resource.  This issue is to propose a property or concept schem to indicat if an organization exists or had been closed/shut down.  Along with knowing if an organization has shut down, it may be important to know the date this occurs.  Here's a link to schema.org Organization https://schema.org/Organization for research purposes.  

CEDs uses the following properties: Active and Inactive https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=51472.  
CEDS definitions
Active - The organization is active, except for scheduled breaks, holidays, or other temporary interruptions.	
Inactive - The organization is inactive.

**Comment by philbarker** [comment]
Consider also adding dissolutionDate (equivalent to [schema:dissolutionDate](https://schema.org/dissolutionDate)) as a complement to [ceterms:foundingDate](https://credreg.com/ctdl/terms#foundingDate). I expect there will be times when someone wants to know when an organization ceased activity.

**Comment by stuartasutton** [comment]
While I am not suggesting this as being preferred, there is another option that hopefully we will take up soon--action.  `CredentialingAction` is defines as an "[a]ction taken by an agent affecting the status of an object entity.”  We have a discussion document in process: https://docs.google.com/document/d/1yyQV27l_1pW4xgcXqYRitSFeX6mFXeeydHMzyInyzUc/edit#

**Comment by siuc-nate** [comment]
If it's good enough for our purposes to convey that an organization is either operating or isn't (no other kinds of statuses), then we could use dissolutionDate instead of needing a status for organization.  The presence of a value for that property would indicate that the organization is no longer active.

**Comment by jeannekitchens** [comment]
This issue had been handled via https://credreg.net/ctdl/terms#lifeCycleStatusType
https://credreg.net/ctdl/terms#Organization
