### ISSUE TITLE
Correct Typo and Verify Comment Text is Correctly Stated ceasn:weight

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#774]
This is a minor correction we should go ahead and make to https://credreg.net/ctdlasn/terms#weight

The comment needs to change "assigned" to "assign". Also, is it correct that the weights are either a 0 or a 1?  Should it say to use a numeric value rather than a decimal?  The example is not a decimal.  

Best practice is to **assigned** a decimal value weight between 0 and 1 that indicates the strength of the assertion, with 0 being weakest and 1 being strongest.

**Comment by siuc-nate** [comment]
The objective with "between 0 and 1" is to handle values that are percentages or percentage-adjacent while still being able to accommodate non-percentage values (e.g. "[something] has a weight of 0.25" and "this is 1/4th of the material" and "this exam is 25% of your grade" can all be expressed with `0.25` without need of additional notation).

**Comment by siuc-nate** [comment]
This has been fixed.  It's also the same usage note we use with [ceterms:weight](https://credreg.net/ctdl/terms/weight)
