### ISSUE TITLE
Correct Typo 

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#775]
Correct typeo with the https://credreg.net/ctdlasn/terms#skillEmbodied usage note.

Change "referenced' to reference".

Usage Note: | en-US: The skillEmbodied property may **referenced** a defined skill in an ontology such as O*NET or an existing competency defined in a competency framework.

This is a minor correction to go ahead an make.

**Comment by siuc-nate** [comment]
The "typeo" has been fixed.
