### ISSUE TITLE
Consider updating the definitions for ceasn:CompetencyFramework and ceasn:Competency

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#777]
The definitions for [ceterms:CompetencyFramework](https://credreg.net/ctdl/terms/CompetencyFramework) and [ceterms:Competency](https://credreg.net/ctdl/terms/Competency) are more fleshed out than those for [ceasn:CompetencyFramework](https://credreg.net/ctdlasn/terms/CompetencyFramework) and [ceasn:Competency](https://credreg.net/ctdlasn/terms/Competency).  We plan to deprecate the CTDL versions of those classes, but their definitions may be worth using in the CTDL-ASN versions.

ceterms:CompetencyFramework
**Definition:** Entity comprised of a logically related set of competencies.
**Comment:** A competency framework serves a container object for a set of competencies.

ceasn:CompetencyFramework
**Definition:** A description of a competency framework as a whole.

ceterms:Competency
**Definition:** Description of measurable or observable knowledge, skills, and abilities necessary to successful performance of a person in a given context.
**Comment:** Competency is broadly defined to include assertions of academic, professional, occupational, vocational and life goals, outcomes, and standards, however labeled.

ceasn:Competency
**Definition:** Description of knowledge, skills, and/or abilities.

It would also be worth updating the label for ceasn:Competency to just be "Competency" instead of "Competency Statement" since we don't actually say/use "Competency Statement" anywhere in our conversations, presentations, documentation, etc.
**Remove:**
> **Subject:** ceasn:Competency 
> **Predicate:** rdfs:label
> **Object:** Competency Statement

> **Subject:** ceasn:Competency 
> **Predicate:** rdfs:label
> **Object:** Competency

Additionally, **after** we decide which definitions/comments/etc to go with:
**Remove:**
> **Subject:** ceterms:CompetencyFramework
> **Predicate:** vs:term_status
> **Object:** vs:stable

> **Subject:** ceterms:Competency
> **Predicate:** vs:term_status
> **Object:** vs:stable

**Add:**
> **Subject:** ceterms:CompetencyFramework
> **Predicate:** vs:term_status
> **Object:** vs:deprecated

> **Subject:** ceterms:Competency
> **Predicate:** vs:term_status
> **Object:** vs:deprecated

**Comment by siuc-nate** [comment]
Suggested updates:

ceasn:CompetencyFramework
**Definition:** Entity comprised of a logically related set of competencies.
**Comment:** Competency Frameworks may be thought of or referred to as a collection or any other grouping of related competencies, however labeled.

ceasn:Competency
**Definition:** Entity comprised of an academic, professional, occupational, vocational and/or life goal, outcome, or standard, such as knowledge, skill, ability, habit of mind or practice.
**Comment:** Competency is used a broad term that is inclusive of any assertion representing an expectation of what a person should know, value, or be able to do.

**Comment by stuartasutton** [comment]
I suggest updating the revised `ceasn:Competency` definition to add the word "task" to support workforce framework such as the Workforce Framework for Cybersecurity (NICE Framework):

**Updated Definition:** "Entity comprised of an academic, professional, occupational, vocational and/or life goal, outcome, or standard, such as knowledge, skill, ability, task, habit of mind or practice."

**Comment by siuc-nate** [comment]
See #785 for final proposal
