### ISSUE TITLE
Determine the best way to group transfer value data together

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#779]
When a transfer value profile references two or more entities in either its transferValueFrom or transferValueFor properties, we need a way to be able to associate each of those entities with a particular Value Profile in that transfer value profile's transfer value property.

Potential solutions:
1. Additional constraint: Update the definition of transferValueFrom and transferValueFor to indicate that they are always to be treated as a "set" (ie all of them are always considered together) and that any notion of "x or y" must be handled by creating additional transfer value profiles
2. Transfer Value Set: Create a new class/property that enables connecting two or more Transfer Value Profile instances together into a set. In this case, the Transfer Value Profile would serve the purpose of reifying the relationship between the transferValueFrom/For entity and the Value Profile
3. Change the domain of transferValueFrom and transferValueFor properties from Transfer Value Profile to Value Profile. In this case, Value Profile reifies the relationship and the Transfer Value Profile itself handles the notion of "set" (since there would be two or more Value Profiles in its transferValue).
4. Change the range of transferValueFrom/transferValueFor to be Value Profile and add some property to Value Profile that allows it to point out to the entity that would otherwise have been referenced by transferValueFrom/transferValueFor.
5. Add a property (other than transferValueFrom/transferValueFor) to Value Profile that enables tying it to something referenced by the Transfer Value Profile's transferValueFrom/transferValueFor property

**Comment by siuc-nate** [comment]
Actually, I started diagramming option 1 and it occurs to me that this is more or less how it would be done today, and this seems to be a correct and efficient handling of the situation:
- `transferValueFrom` and `transferValueFor` are each considered to embody a complete "set" of entities (that is, everything in the array would be `AND`'d together since any `OR`s would be handled by creating additional Transfer Value Profiles
- The Value Profile attached to the Transfer Value Profile defines the value of the **transfer**, not the value of any individual course/competency/whatever that hangs off of the Transfer Value Profile. We don't want one entity to describe properties of another entity, especially when that other entity already has the appropriate property (ie `creditValue`) to do exactly that
- Taken together, the above mean that the Transfer Value Profile creates a black box effect: Anything "inside" of it transfers for the indicated `transferValue` regardless of what its contents are. Any curiosity about how much each individual resource is worth should be done by looking up that resource rather than trying to embody that resource's value inside of the Transfer Value Profile as some external granular data point (in other words, the only thing that "knows" how many credits a Course is worth is the Course itself; all the Transfer Value Profile "knows" is how many credits are involved in its own `transferValue`).  This seems like a natural way to handle linked data.

I think we were all a little overwhelmed by the many conversations we had that day and over-thought this one just a bit, given the wild variety of solutions proposed.

Here are some diagrams to further illustrate my point:
![image](https://user-images.githubusercontent.com/21346519/124989379-afde3b00-e004-11eb-90f7-ce912dd58ea6.png)
![image](https://user-images.githubusercontent.com/21346519/124989714-0c415a80-e005-11eb-9789-679392a3571d.png)
![image](https://user-images.githubusercontent.com/21346519/124989590-e2883380-e004-11eb-8cc4-df40e0b23d5f.png)

**Comment by siuc-nate** [comment]
Per our 7-13-2021 meeting:
- We should go with the approach in my previous post to group things together based on the transferValueFrom/transferValueFor properties
- The definitions of those properties should be adjusted to explicitly reflect that the values of those arrays are to be logically `AND`'d together as sets

**Comment by jeannekitchens** [comment]
@siuc-nate isn't this diagramming to support GitHub Issue #780 ?  If so, please have one final issue using 780 with the final diagrams.

**Comment by siuc-nate** [comment]
It applies evenly to both issues, but I can merge them.

**Comment by siuc-nate** [comment]
See #780 for continuation of this issue.
