### ISSUE TITLE
Adding competency contextualization through use of ConceptKeyword and ConceptTerm

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#781]
We need to: (1) develop editing system functionality around handling [ceasn:ConceptKeyword](https://credreg.net/ctdlasn/terms#conceptKeyword) for entry of plain literals and literal phrases and [ceasn:ConceptTerm](https://credreg.net/ctdlasn/terms#conceptTerm) for adding terms from concept schemes; and (2) get these functions into our "how-to" documentation for the editor. I am not going to try and sort out here what parts of this are CaSS-related and Registry-related. I leave that to others. I also leave to others how these processes would work with our batch loading functions.

One of the key types of **competency contextualization** is through relationships to concepts covered by the competency. And yet, no emphasis has been placed on data identifying concepts even though both properties have been in the CEASN since inception.  We need to add functionality to the editor that makes this process of adding concepts to a competency efficient, simple, and useful across applications. Here are my ROUGH suggestions:

1.   **[ceasn:ConceptKeyword](https://credreg.net/ctdlasn/terms#conceptKeyword)**: In the concepts entry field in the editor, support form autofill relying on a database of already entered concepts entered by others. 

2. **[ceasn:ConceptTerm](https://credreg.net/ctdlasn/terms#conceptTerm)**: The editor already supports adding a URI-identified concepts through two methods: (a) by searching the registry's concepts (supposedly) in alpha order and optionally filtered to "my own" etc.; and (b) by adding a concept URI located elsewhere. For the latter, consider functionality that accepts a search query and looks for concepts in recognized data stores such as [WikiData](https://www.wikidata.org/wiki/Wikidata:Main_Page), [LoC Authority Headings](https://id.loc.gov/) , (Australia's) [School's Online Thesaurus (SCoT)](http://scot.curriculum.edu.au/) for K-12.

 Perhaps subpart "b" could be part of an array of fee-based data services...

**Comment by jeannekitchens** [comment]
@stuartasutton if this is a CaSS suggestion for an editor improvement, we need to move this card to CaSS.  Does this involve and CTDL or CTDL ASN updates?  If no, let's move it to CaSS with information to specify the update requests.

**Comment by siuc-nate** [comment]
Moved to https://github.com/cassproject/cass-editor/issues/1240
