### ISSUE TITLE
Correction in Handbook: NSF funding

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#786]
In the opening paragraph of [§4 of the Handbook](https://credreg.net/ctdl/handbook#ctdlasnschema) the text says "...was developed by the U.S. National Science Foundation (NSF)". This should be changed to "...was developed under funding from the U.S. National Science Foundation (NSF)."  Otherwise, it sounds like NSF actually created the ASN instead of funding its creation.

**Comment by siuc-nate** [comment]
Fixed.

It might be better to put any other small handbook updates like this in this issue rather than creating new issues for each one.  I'll leave this open for that purpose.

**Comment by stuartasutton** [comment]
Really. Then how can they be efficiently opened/closed rather than in a long list.

**Comment by siuc-nate** [comment]
It comes down to how significant a change is. A bunch of small text changes can be aggregated into one issue so I can take care of them at one time, while something bigger like a new page is more deserving of its own thread.  It doesn't make a big difference either way, but putting something like a small text change on the same level as the other issues in this repo seems like overkill to me. But if it helps you stay organized, it's not a problem.
