### ISSUE TITLE
Create Offering or Resource Instance

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#792]
Per our 9/7/2021 meeting:

In order to handle specific combinations of data that are otherwise aggregated at the ceterms:Course (and potentially ceterms:AssessmentProfile) level, we need some kind of object.  This object should not be another clone of those objects in terms of properties, but should rely on the host/base class for everything that isn't specific to its own instance.  Per our discussion, a class based on [schema:CourseInstance](https://schema.org/CourseInstance) may be too specific(?), but is worth considering.  Failing that, a class loosely based on [schema:Offer](https://schema.org/Offer) may be more appropriate.

Either way, such an object would go beyond the schedule-related properties (as an **alternative** to @philbarker's [proposal for a ScheduleProfile](https://github.com/CredentialEngine/Schema-Development/issues/778#issuecomment-905353544).  The objective of that class is to provide a disaggregation of types of schedules.

**I do not think we need to disaggregate such information. However, if we are going to do it for schedule, we should do it for other things as well, otherwise there is no point in doing it for schedule.**

To that end:
> **URI:** ceterms:Offering (or ceterms:ResourceInstance, or OfferProfile, or InstanceProfile...)
> **Label:** Offering (or Resource Instance)
> **Definition:** Offering (or instance) of a resource.
> **Comment:** Provides a means of describing data specific to a given offering (or instance) of some base resource which provides the majority of the data.
> **Usage Note:** Rather than repeating data, only use the properties in this class when and where their data differs from the data provided by the resource for which this is an offer (or instance).
> **Properties:**
> - Either:
>    - `ceterms:scheduleType` (with single concept scheme which combines frequencies and timings, as I don't think there is a need to create separate schemes for these)
>    - or
>    - `ceterms:scheduleFrequencyType` (with concept scheme, see above proposal)
>    - `ceterms:scheduleTimingType` (with concept scheme, see above proposal)
> - Either: 
>    - `ceterms:address` 
>    - or 
>    - `ceterms:availableAt` (both of which reference `ceterms:Place`, which provides `ceterms:targetContactPoint`)
> - `ceterms:offeredBy` (in case this offering's offeredBy data differs from the base Course/AssessmentProfile)
> - `ceterms:deliveryType` (to disambiguate which delivery method is offered at this location and schedule)
> - `ceterms:deliveryTypeDescription` (ditto)
> - `ceterms:estimatedCost` (in case this offering has a cost that differs from the base Course/AssessmentProfile)
> - `ceterms:commonCosts` (ditto)
> - `ceterms:estimatedDuration` (in case this offering has a duration that differs from the base Course/AssessmentProfile)
> - `ceterms:aggregateData` (in order to provide outcomes data specific to this offering at this location (the use case we discussed) and, if needed, connect to a `qdata:DataSetProfile`)
> - `ceterms:description` (for anything else)

We would also need some kind of `ceterms:hasOffer` or `ceterms:hasInstance` property to point to this object.
> **URI:** ceterms:hasOffering (or ceterms:hasInstance)
> **Label:** Has Offering (or Has Instance)
> **Definition:** Offering (or instance) of this resource.
> **Usage Note:** Only use this property when it is necessary and useful to provide data about specific offerings (or instances) of this resource, such as particular combinations of schedule, location, and delivery.
> **Domain:** ceterms:LearningOpportunityProfile, ceterms:LearningProgram, ceterms:Course, ceterms:AssessmentProfile
> **Range:** ceterms:Offer (or ceterms:ResourceInstance)

Functionally, instances of this class would either:
1. Need to be top-level objects (in order to be referenced by other things, like outcomes data) or 
2. Exist as bnodes in the `@graph` for the host/base resource.

**Note:** If we don't plan to support such a low level of detail in the Registry, **then we still need a solution that can exist at the Course level** to handle the [schedule issue](https://github.com/CredentialEngine/Schema-Development/issues/778) (and I would suggest using the simple scheduleType property for that).

Again, I don't think we need to go into this level of detail **at all**, but it doesn't make sense to only do so for schedule types.

**Comment by philbarker** [comment]
Marked for closure, dealt with under #778 Scheduling Patterns
