### ISSUE TITLE
Determine best approach for handling structural competencies

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#801]
We often encounter cases where competency frameworks are arranged in a hierarchical fashion, but where the upper (sometimes all but the lowest) layers of that hierarchy behave as categories, groups, headers, or other such organizing constructs that are not themselves competencies as we define them.

There are a few ways to tackle these:

---
1. Treat all objects in the hierarchy as instances of ceasn:Competency. 
  - Pros:
    - This is the simplest approach
    - It avoids us needing to make any decisions about whether or not something is a "real" competency
    - If [ceasn:shouldIndex](https://credreg.net/ctdlasn/terms/shouldIndex) is used appropriately, it is possible to tell whether or not a given competency is supposed to be aligned to (which implies whether or not it is a "real" competency)
    - It's relatively straightforward to transpose an indented text hierarchy to an equivalently indented competency hierarchy, making it easier for our partners to use this approach (and to understand the resulting data, which will structurally match the original)
  - Cons:
    - Things which are obviously not competencies will be embodied as such
    - The data can be confusing for consumers
    - It may result in repetition of the same lexical strings when a multi-layered hierarchy has several instances of the same grouping (ie a middle layer that shows up under multiple top layers)

---
2. Use ceasn:competencyCategory on the lower-level competencies to categorize them
  - Pros:
    - This is relatively simple, provided the data itself is relatively simple
  - Cons:
    - It requires us to make semantically-meaningful assertions about the intended structure of a framework
    - [Arguably, this is a misuse of the ceasn:competencyCategory](https://github.com/CredentialEngine/Schema-Development/issues/626), which is meant to enable soft subclassing of the ceasn:Competency class itself, not to "categorize" a competency in the sense that we have been using it
    - This property is supposed to point to a class, rather than use text
    - This approach falls apart if there are multiple layers of categories, as there is no good way to control or indicate the order or hierarchy of such layers
    - This approach falls apart if there are both a non-structural (keyword-esque) category _and_ a hierarchical/structural category, as it is not possible to tell which is which
    - This results in the same category text being included with (and thus displayed alongside) every single competency in that category (meaning if there is a change or error, every single competency must then also be updated)
    - It alters the actual structure of the framework, meaning child competencies get directly assigned to parents they were originally indirect children of, which makes the CTDL-ASN data inconsistent with the original source data
    - It's not easy/intuitive to explain this process to our partners unless the data is very simple

---
3. Create a new class to embody strictly "structural" things (i.e. using hasChild/isChildOf) in a framework
  - Pros:
    - It creates a very clear separation in terms of what is supposed to be what, and how it should be used
    - It can have a different set of properties than a competency does (e.g. using name and description instead of competencyLabel and competencyText)
    - There may be a means of reusing the same category (skos:Concept?) to clearly indicate when multiple instances of such a class are intended to be the same kind of thing under different upper layers (e.g. a middle-ground category like "knowledge" that shows up underneath several parent categories)
    - Depending on how such a class is designed, it may be useful in Concept Schemes and/or Collections
  - Cons:
    - It requires us to make semantically-meaningful assertions about whether or not something in a gray area definitively is or is not a competency
    - It will require significant changes to both our tools (CaSS is not setup to handle such an object as-is) and our documentation (handbook, diagrams, etc.)
    - It is inconsistent with how we've done things thus far, so we'll need to account for what people are expecting
    - We will need to reexamine all of our published frameworks to look for places where it's necessary to apply this change
---
4. Other approaches?

---
I'm open to suggestions for other ways to handle this. @Lomilar @woodkri do you have any suggestions? How do you handle this kind of thing outside of CE?

**Comment by stuartasutton** [comment]
Yes, but the under specificity of the asn:Statement in the context of a competency framework does not leave everyone rudderless since the framework itself is of help. As for many of the "problems" where concept-like nodes are repeated in different places, and competencies show up is different places are problems of a forced hierarchical framing where what we actually have is a graph.  If we were in a place where we could display graphs in an intuitive way, many of these issues become inconsequential. But, we are stuck with forcing graphs into the glass slipper of hierarchies. 

I'm with you, Fritz that we stick with were we are until...

**Comment by siuc-nate** [comment]
Closing this, as it is not needed
