### ISSUE TITLE
WIOA Requires Program's to Meet EEO and Provide Disability Accomodation

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#802]
Nondiscrimination, Equal Opportunity, and Disability Provisions Compliance Assurance
EEO Compliant: Yes
Disability Accomodation: Yes

**Comment by jeannekitchens** [comment]
See issue #806

**Comment by siuc-nate** [comment]
Closing this, as it appears to have been handled via ceterms:membershipCondition per the above post
