### ISSUE TITLE
Audience Level: Add Remedial

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#803]
Remedial training is designed to remediate basic skill deficiencies in reading, writing, speaking, and mathematics of high school graduates and persons achieving the equivalency of a high school diploma in order to prepare them to pursue further postsecondary education or employment.

Developmental, or remedial, education courses are designed to develop the reading, writing or math skills of students who are deemed — usually through standardized tests — underprepared for college-level courses.

https://nces.ed.gov/pubs2004/2004010.pdf

Add Remedial Level to https://credreg.net/ctdl/terms#AudienceLevel

Definition: Intended for people having difficulty learning basic skills.

**Comment by stuartasutton** [comment]
Perhaps:

**RemedialLevel:** Intended for learners who need special training to improve their capability in a particular area or subject.

**Comment by siuc-nate** [comment]
We want to avoid confusion with [Beginner Level](https://credreg.net/ctdl/vocabs/audLevel/BeginnerLevel) ("Intended for novices or those with limited experience."), so perhaps we should lean more into the "basic skill deficiencies" aspect (in other words, remedial helps fill the gaps between where you are now and what some other level, like beginner level, expects).

So maybe something like:
**RemedialLevel** - Intended for learners who need special training to alleviate deficiencies in their current capabilities.

**Comment by jeannekitchens** [comment]
RemedialLevel - Intended for those who are under prepared for learning at a particular level.

**Comment by siuc-nate** [comment]
This has been added in pending CTDL and noted in the history tracking.
