### ISSUE TITLE
Pathway Constraints and Other Related Updates Proposal

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#807]
Experience and further thinking on pathways require the removal of the domain and range of the PathwayComponent subclasses from the terms [ceterms:precedes](https://purl.org/ctdl/terms/precedes) and [ceterms:prerequisite](https://purl.org/ctdl/terms/prerequisite). Appropriate domains/ranges for these properties are, at a minimum, [ceterms:Course](https://purl.org/ctdl/terms/Course) and [ceterms:LearningProgram](https://purl.org/ctdl/terms/LearningProgram).  

The rationale for removing the domain and range from PathwayComponent subclasses is that both properties define conditions directly on an instance of a PathwayComponent subclass when **all such conditioning** must be handled through that PathwayComponent's ceterms:ComponentCondition as the following diagram illustrates:

![Pathway_Columns-2c drawio](https://user-images.githubusercontent.com/2939046/146681910-36713b5e-a6a5-411c-acee-59870ab680e6.png)

The notion of "precedes" is inherent in the structure of the pathway through the hasChild and, additionally, through any progression model used that identifies points in the progression and adds gloss. The notion of "prerequisite" in the pathway is illustrated in the diagram above by the ConditionComponent for the "HTML5 CSS 3" badge component.

Related to #804

**Comment by siuc-nate** [comment]
How does this gel with the current use of precedes, where it basically means "There is no requirement to do "Thing A" before "Thing B", but you typically _would_"?  For example, a course that prepares for an assessment, but which is not required to take the assessment (as seen in [this pathway](https://credentialfinder.org/pathway/4/National_Retail_Federation_Foundation_RISE_Up_Pathway))?

**Comment by stuartasutton** [comment]
Nate, it doesn't affect the actual definition of [ceterms:precedes](https://purl.org/ctdl/terms/precedes) which says "this" is before "that". It simply denotes a sequencing and nothing else. If you want something that precisely states that "[t]here is no requirement to do 'Thing A' before 'Thing B', but you typically would", you need to define a subproperty of [ceterms:precedes](https://purl.org/ctdl/terms/precedes) to do that.

**Comment by siuc-nate** [comment]
The comment on ceterms:precedes was added specifically to indicate the lack of requirement.  However, that is a little bit beside the point - the more important part of my question was to find out how this proposal gels with the NRF pathway I linked to, where precedes is an important part of the glue holding three sets of pathway components together.

**Comment by stuartasutton** [comment]
Summary of proposed updates to enable the model diagram at the start of this issue.

![image](https://user-images.githubusercontent.com/2939046/147982171-efef8dae-99ec-43cb-9dbf-74683bbcc0b8.png)

**ADD:**

**URL:** ceterms:hasPart
**Domain:** ceterms:Pathway
**Range:** ceterms:PathwayComponent (subclasses)
**InverseOf:** ceterms:isPartOf


**URL:** ceterms:isPartOf
**Domain:** ceterms:PathwayComponent (subclasses)
**Range:** ceterms:Pathway
**InverseOf:** ceterms:hasPart

**URL:** ceasn:hasChild
**InverseOf:** ceasn:hasChild

**URL:** ceasn:isChildOf
**InverseOf:** ceasn:hasChild

**URL:** ceterms:precedes
**Domain:** skos:Concept
**Range:** skos:Concept

**URL:** ceterms:prerequisite
**Domain:** ceterms:Course, ceterms:LearningProgram
**Range:** ceterms:Course, ceterms:LearningProgram
 

**REMOVE:**

**URL:** ceasn:hasChild
**Domain:** ceterms:Pathway

**URL:** ceterms:prerequisite
**Domain:** ceterms:PathwayComponent (subclasses)

**Comment by stuartasutton** [comment]
The notion behind the current use of the [ceterms:precedes](https://purl.org/ctdl/terms/precedes) property in this context is not a relationship between two [ceasn:PathwayComponent](https://purl.org/ctdl/terms/PathwayComponent) entities, but a relationship between the [schema:Person](https://schema.org/Person) (learner) and a [ceasn:PathwayComponent](https://purl.org/ctdl/terms/PathwayComponent)--i.e., the learner record of  the person states that the  ceasn:dateAcheived for a the particular component must be less than or equal to (≦)the [ceasn:startDate](https://purl.org/ctdl/terms/startDate) of that subsequent component.

Note: Strained interpretation of [ceasn:startDate](https://purl.org/ctdl/terms/startDate), but the correct notion.

**Comment by siuc-nate** [comment]
I think you are correct, but also overthinking it a bit.  Someone who is building a pathway from resources they may or may not own may want to simply say "you should do X before Y, but don't have to".

**Comment by stuartasutton** [comment]
Nate, that is already handled through the hasChild relationship that were totally left out of the NRF pathway.

**Comment by stuartasutton** [comment]
I agree, hasChild is not the right property. It was inherited from the earlier work group phase with its relationship to the Concentric Sky work. I could accept [ceasn:precedes]([ceterms:precedes](https://purl.org/ctdl/terms/precedes)) instead.

**Comment by siuc-nate** [comment]
Not to nitpick, but the other key thing is the directionality of the property.  Precedes is the only one that goes "backwards" relative to the other properties.  I would strongly suggest a different property that points from the later component to the earlier one.  Perhaps "precededBy" or some variation of ceterms:recommends (which carries a similar "you should do it, but you don't have to" notion).  Consistent directionality makes figuring out the pathway a lot easier (for example, when rendering pathways for the finder, one of the steps is to calculate a fake "precededBy" property based on reversing the "precedes" connections so the rest of the code can handle it properly).

**Comment by stuartasutton** [comment]
Nate, if you look at the document I prepared for pathways, you'll see a
clear recognition of the two directions--one for application of constraints
and the other for the learner/worker journey.  That means that we could
have reciprocal properties, but even that would be wrong in one
direction or the other...application of constraints or journey traveled.

**Comment by philbarker** [comment]
Here's the N Dakota Cyber pathway (just the pathway part, not all the courses) using pathway basic components for the semesters and preceded by to provide the path. I haven't tried and of the proposed ways for representing conditions.

I think it looks good, but one thing that strikes me is that aside from the component condition there is no link between the Semester basic components and the course components, and this is exactly where hasChild would be the right link. 

Sure you can infer that links exist via the component conditions, but if I think it would be useful for tools displaying these pathways to have something that represented nature of the link, in this case the precedBy link from semester to semester is different from the hasChild link from semester to course.

![NorthDakotaCyber-Latest-PW drawio](https://user-images.githubusercontent.com/658047/157438511-bfa477af-69d9-47ff-8dcd-4bb97c958da5.png)

[full version [here](https://drive.google.com/file/d/1yeUJ5hPnwfc9COWQVQWWPd18FVwuYdy6/view?usp=sharing)]

**Comment by stuartasutton** [comment]
@siuc-nate, @jeannekitchens & @philbarker: 

Nate, you are absolutely mistaken when you say that "[t]he conditions provide the useful connective tissue, only needing to fall back on precededBy when no such condition exists." There is obviously something here that I apparently cannot make clear to you. The basic connective tissue of the pathway should be complete even if you had no ComponentConditions (and I'm not implying that you should have none). 

Below is a snippet of my diagram of the National Retail Federation pathway with ConditionComponents. The skeleton of the pathway is the heavy black arrows (all precededBy (used to be hasChild)) and the grey, light dotted arrows and circles are the ComponentCondition information. Simple count rule is all that is needed in the NRF, so there are no Constraint entities. Notice that I could indeed delete all ComponentCondition entities (i.e., every dotted arc and circle) and have the basic skeleton of the Pathway fundamentally in place.

<img width="1185" alt="NRF-Management" src="https://user-images.githubusercontent.com/2939046/157684208-2ff2b0a1-4e20-47c1-89e0-46f0ab3cb4ae.png">

Given Marc's UI/UX, this skeleton could be constructed completely through drag-and-drop before clicking to add any constraints after the skeleton was in place. However, whether the ComponentConditions and Constrain entities are displayed at all is a UI issue and not a data modeling issue.  So, if it turns onto visual spaghetti, that has to be solved via the UI. The information could be derived from ComponentCondition and Constraint entities and displayed in a modal window or as text in the relevant PathwayComponent (i.e., as Concentric Sky handles it). 

This will be on Tuesday's CTDL agenda; so I'd prefer not to go round and round here.

**Comment by siuc-nate** [comment]
I recognize your points, but my pushback would be that the pathway information is not very useful without the conditions, but that it still works fine if you use the conditions to connect the nodes and leave out most (if not all, depending on the pathway) of the precededBy arrows.  If you were to swap the hard arrows with the dotted arrows in your diagram, you would still be able to determine the order of nodes _and_ their requirements, as opposed to just the order of nodes alone.

In a more grounded context: It seems that this approach would require user entry of _both_ all of the conditions _and_ the precededBy arrows. If true, that will add an additional layer of complexity/chance for errors pathway upload and the editor. It may be possible instead to calculate most if not all of those precededBy connections (again, depending on the pathway) based on the conditions, but that still means the computer may guess incorrectly in some edge cases.

Ditto for display: Should precededBy arrows be left out where the conditions make them redundant, so as to keep a cleaner display for the user?

Regarding the UX for the builder: I'm pretty sure it came up that there would always be at least one condition between nodes, so this is probably something we'd need to verify.

**Comment by stuartasutton** [comment]
You are correct, there is not much point in arguing. We both know what the other is saying--we are not talking past each other. Generating the appropriate data using the pathway editor under development supports what I have been saying--(1) first you drag and drop a destination component, then (2) you drag and drop the next component, then (3) procedurally, you generates the link between the two components--that's the precededBy link (the skeleton), then (4) you click on the icon to generate a condition that establishes any constraints on the relationship(s).  

If you want to create an authoring tool that leaves out the precededBy relationships, then go ahead and do it while understanding that the data generated will not interoperate smoothly with systems that more appropriately include the precededBy. However, if precededBy remains in the language, then I am satisfied and we can conclude these comments now.

**Comment by philbarker** [comment]
Seeing `:<=` in the examples, as if `<` can be in a URI, got me to putting down ideas about concept schemes for comparators, I added what I could remember for actions too, though I recall Nate showing a list of array operations. My [ideas are in a Google doc](https://docs.google.com/document/d/1GoR1CcO0LrFIUIKF2b3XCvaj4KEONPvCWo_NBWr0PyM/edit?usp=sharing).

**Comment by stuartasutton** [comment]
See ORDL starting here: [](https://www.w3.org/TR/odrl-vocab/#logicalConstraints)

**Comment by philbarker** [comment]
@stuartasutton thank you for the ODRL link. I have added mappings where I think we can.

**Comment by siuc-nate** [comment]
I have updated [Stuart's comment above](https://github.com/CredentialEngine/Schema-Development/issues/807#issuecomment-1004378147) to reflect the current state of the proposal based on [the powerpoint](https://docs.google.com/presentation/d/1cig_8_7NYnyLNptpJnoHcnmL-1JZyUh82Bj0m057-6A/edit#slide=id.g12e83e89df6_1_22) and on our discussions.

[The vocabularies for constraints](https://docs.google.com/document/d/1GoR1CcO0LrFIUIKF2b3XCvaj4KEONPvCWo_NBWr0PyM/edit) are still TBD.

**Comment by stuartasutton** [comment]
@siuc-nate, a couple of issues with your changes: (1) the ceterms:Rule is actually a new class so I have moved it back up into the list of adds; and (2) the ceterms:hasCondition was misnamed but remains in the Modify Existing Properties section because it is the change that enables the nesting of conditions.

I see you have added ceterms:targetComponentConstraint. I don't think there was an actual decision to do so. I'm not opposed, but would like us to make sure we all understand and have looked at it in greater depth than we did last meeting.

**Comment by siuc-nate** [comment]
I don't recall seeing ceterms:Rule come up in our discussions or presentations - how would it be used?

**Comment by siuc-nate** [comment]
Per our 6-14-2022 meeting:
We'll leave this one open for now so it can be tracked in the schema management system, history tracking, etc.

For the formal proposal itself, see here: https://github.com/CredentialEngine/Schema-Development/blob/master/PathwaysConditionsAndConstraints/proposal.txt

**Comment by siuc-nate** [comment]
Looking at the final proposal, I would advise 3 separate concept schemes, as the concepts have fairly specific uses and don't overlap:
- Comparators
- Array Operations
- Logical Operations

There is zero support for skos collections in any of our code/infrastructure/documentation/etc., and it's likely that such support would not be meaningfully different from just having separate concept schemes, especially given the lack of overlap in the purposes of the concepts in such collections/schemes.

I don't think "and sequence" makes much sense as a logical operation; it seems like sequencing can and should be embodied elsewhere in the pathway structure. What would an example be of this?  I'm also curious what a realistic example of an "only one" constraint would be.

I would also suggest looking at [other logical operations](https://www.techtarget.com/whatis/definition/logic-gate-AND-OR-XOR-NOT-NAND-NOR-and-XNOR), to make sure we don't establish a pattern that would make it difficult to add the others if they were to become relevant.

**Comment by siuc-nate** [comment]
Also: the definitions and ranges for left source and right source don't quite line up. I'll normalize them.

**Comment by stuartasutton** [comment]
I gotta say, Nate. This reopening of discussion drives me crazy...since nothing is ever final, even final for the moment. 

> Looking at the final proposal, I would advise 3 separate concept schemes, as the concepts have fairly specific uses and don't overlap:
> 
> * Comparators
> * Array Operations
> * Logical Operators

I've made my point here. Having 1 constraint concept scheme to look for concepts as opposed to 3 when many will likely already be struggling a bit with the semantics makes far more sense to me. SKOS concept schemes can handle node labels that can break a single concept scheme down into 3 collections.

> 
> There is zero support for skos collections in any of our code/infrastructure/documentation/etc., 

All that means is that we haven't used the skos:Collection functionality, not that we couldn't/shouldn't (but good to know that I count as "zero support"). The Collection functionality is used by many in fairly significant ways within and outside concept schemes. One frequent pattern is demonstrated in the schema encoding for the ODRL turtle [odrl_schema.txt](https://github.com/CredentialEngine/Schema-Development/files/8929609/odrl_schema.txt) where skos:Collection is used to group properties to classes to drive interfaces to the schema.

and it's likely that such support would not be meaningfully different from just having separate concept schemes, especially given the lack of overlap in the purposes of the concepts in such collections/schemes.
> 
> I don't think "and sequence" makes much sense as a logical operation; it seems like sequencing can and should be embodied elsewhere in the pathway structure. What would an example be of this? I'm also curious what a realistic example of an "only one" constraint would be.

Drop them then. They can be added back later.

> 
> I would also suggest looking at [other logical operations](https://www.techtarget.com/whatis/definition/logic-gate-AND-OR-XOR-NOT-NAND-NOR-and-XNOR), to make sure we don't establish a pattern that would make it difficult to add the others if they were to become relevant.

We have looked at others and have kept ours terse.

**Comment by siuc-nate** [comment]
I agree, it's difficult when we have multiple very large proposals that overlap and seem to always be shifting.  But I would rather us sort things out before putting them into the schema rather than afterwards.

I'm not taking issue with the semantic argument regarding skos collections. I'm saying that our systems (schema management, publisher, APIs, search, finder, etc.) have absolutely no way to capture or use a skos:Collection (this is what I meant by "support"; i.e., the software does not support it).  And even if they did, it would end up working the same way as multiple concept schemes work today.  I don't see the point in reinventing functionality for a more complicated solution (having to select from one concept scheme but then only use certain parts of it in certain situations, in a programmatic sense) like that when a perfectly viable, simple solution is available.  If we want to discuss the use of skos collections more broadly, that's fine, but we can't just insert brand new system functionality into a proposal like this.

**Comment by siuc-nate** [comment]
The definitions for and/or/onlyOne/andSequence are too restrictive (applying, explicitly and only, to constraints and conditions). The terms and their URIs should be re-scoped to match, or the definitions should be broadened. This is because the notions of logical and/logical or can apply to a wide variety of things (including our own future plans to use them with condition profiles).

Suggestion (use of lowercase "conditions and constraints" in the definitions is intentional, since that would allow for Condition Profiles or any other notion of "conditions"):
**Label:** And
**Definition:** Relation is satisfied when all of the conditions and constraints are satisfied.
**Usage Note:** When used in a Component Condition, this applies to the combination of all immediately subordinate Component Conditions and Constraints.

**Label:** Or
**Definition:** Relation is satisfied when at least one of the conditions or constraints is satisfied.
**Usage Note:** When used in a Component Condition, this applies to the combination of all immediately subordinate Component Conditions and Constraints.

I'm less certain as to whether the following apply to the combination of immediately subordinate Component Conditions and Constraints (particularly AndSequence, given there is no notion of ordering between the values of two separate properties), but:
**Label:** Only One
**Definition:** Relation is satisfied when exactly one, and not more, of the conditions or constraints is satisfied.
**Usage Note:** When used in a Component Condition, this applies to the combination of all immediately subordinate Component Conditions and Constraints.

(If we keep AndSequence...)
**Label:** And (Sequence)
**Definition:** Relation is satisfied when each of the conditions and constraints are satisfied in the order specified.
**Usage Note:** When used in a Component Condition, this applies to the combination of all immediately subordinate Constraints.

**Comment by stuartasutton** [comment]
@siuc-nate, @jeannekitchens & @philbarker, we'll need to put these changes on the agenda for next Tuesday.

**Comment by siuc-nate** [comment]
Per our 6-21-2022 meeting:
We will embody the concepts above in three separate concept schemes

**Comment by stuartasutton** [comment]
One additional update: 

The hasCondition property needs the phrase "...by which a rule set is satisfied."

**Comment by stuartasutton** [comment]
I thought that had already been done.

**Comment by siuc-nate** [comment]
It had not.

Further changes to make:
- Add ceterms:name to ceterms:Constraint
- Deprecate ceterms:SelectionComponent
- Use "Referenced resource defines a single constraint by which a rule set is satisfied." for the definition of ceterms:hasConstraint

A quick question on "rule set" above: We removed the reference to RuleSet (the class) from the definition for targetComponent. Do we want to add that back (perhaps as "rule set" instead of "RuleSet")?

**Comment by stuartasutton** [comment]
No, the 3rd bullet should be "Referenced resource defines a single
constraint by which a condition is satisfied."

**Comment by siuc-nate** [comment]
Apologies, it looks like I misread and got hasConstraint and hasCondition mixed up.  Currently, in pending, their definitions are:
- hasConstraint: Referenced resource defines a single constraint.
- hasCondition: Resource referenced defines the conditions by which a rule set is satisfied.

Are these correct?

**Comment by siuc-nate** [comment]
From your [message](https://github.com/CredentialEngine/Schema-Development/issues/807#issuecomment-1166354454):
>One additional update:
>The hasCondition property needs the phrase "...by which a rule set is satisfied."

**Comment by stuartasutton** [comment]
The hasCondition property has the domain of nothing but the PathwayComponent subclasses which have nothing to do with the notion "rule set".  I think my earlier message was incomplete. It would be acceptable as: "Resource referenced defines a condition by which this resource is satisfied in full or in part."

**Comment by siuc-nate** [comment]
Also updated:
- Definitions for logicalOperator and comparator
- Added precedes and precededBy to Progression Level

**Comment by siuc-nate** [comment]
The above changes have (finally) been entered into pending CTDL and noted in the history tracking.
