### ISSUE TITLE
Removal of hasChild and the addition of hasPart to Pathway

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#808]
In the review of the pathway specification over the past weeks, we've looked at pathway data in the Finder, e.g., the [Bismarck State College's cybersecurity pathways](https://credentialfinder.org/pathway/5/Bismarck_State_Colleges_Cybersecurity_BAS_pathway_()). If we look at the JSON-LD for Bismarck, we see that the relationship between the pathway and the pathway components is [ceterms:hasPart](https://purl.org/ctdl/terms/hasPart) while the class declaration has [ceasn:isChild](https://purl.org/ctdlasn/terms/hasChild). The Finder is correct. It should be [ceterms:hasPart](https://purl.org/ctdl/terms/hasPart) as illustrated in the diagram below.

![Pathway_Columns-2c drawio](https://user-images.githubusercontent.com/2939046/146683382-9bc28c95-445a-4593-abee-db23d5ea647b.png)

This reserves [ceasn:hasChild](https://purl.org/ctdlasn/terms/hasChild) for defining the relationship between a pathway component and it's children and, as the diagram below illustrates, triggers a [ComponentCondition](https://purl.org/ctdl/terms/ComponentCondition).

**Comment by mparsons-ce** [comment]
@stuartasutton 
I think the  ceasn:isChild property was for where there is a component with a direct relationship to a pathway and is not the destination component.  
I checked back through the github history and found #667 . And specifically the comment where hasPart was to be removed from Pathway. 
https://github.com/CredentialEngine/Schema-Development/issues/667#issuecomment-659674341 

Despite adding the comment, I didn't remove the hasPart property from the Pathway class. The API has step to automatically add all components to the hasPart property when publishing. 
So I can either leave the API as is (with the hasPart property) or remove/disable it for now.

**Comment by stuartasutton** [comment]
Thanks, Mike. This is why I've this issue as a mistake and outlined the correction here. 

:-) we obviously missed switching out "hasPart" since it is in our data...and should stay there.

**Comment by siuc-nate** [comment]
There is no `ceasn:hasPart` property (which means our data is incorrect). Did you mean `ceterms:hasPart`?

**Comment by siuc-nate** [comment]
@stuartasutton In #807 you mention:
>**The notion of "precedes" is inherent in the structure of the pathway through the hasChild** and, additionally, through any progression model used that identifies points in the progression and adds gloss.

If we remove hasChild, does that break the logic/thinking behind #807?

**Comment by stuartasutton** [comment]
Sorry about getting the wrong namespaces in https://github.com/CredentialEngine/Schema-Development/issues/808#issuecomment-1004173493. Using `ceterms:hasPart` is just fine.  Same with `ceasn:hasChild`.

No, it does not break the logic of the model in #807. In fact, the changes are necessary to align with #807--i.e., `hasPart` needs to be added to `Pathway`(as it is in the current data) and `hasChild` should be removed. So, `Pathway` should not have children--but rather it has parts. Only `PathwayComponent` (and its subclasses) can have children.

**Comment by siuc-nate** [comment]
Oh, sorry, I misinterpreted this issue as removing ceasn:hasChild from pathways across the board (ie from all of the pathway components as well).  If all you're proposing is to remove ceasn:hasChild from ceterms:Pathway, then that's fine.  Pathway Components already point back to their Pathway via ceasn:isPartOf, so we don't need a ceasn:hasPart property.  This is exactly the same way that competency frameworks are handled in CTDL-ASN and it works pretty well.

**Comment by stuartasutton** [comment]
I would prefer to have the `hasPart` on `Pathway` even if it is not used in the registry with it declared as the inverse of `isPartOf`.

**Comment by stuartasutton** [comment]
This issue is resolved as part of #807.
