### ISSUE TITLE
Map OSN occupation code references to ceterms:occupationType instead of ceasn:substantiatingOccupation

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#811]
The [ceasn:subtantiatingOccupation](https://purl.org/ctdlasn/terms/substantiatingOccupation) has a range of ceterms:Occupation. The OSN example data for occupation reference SOC codes. We need to either **add** skos:Concept to the range to handle references such as OSN or change the current range from ceterms:Occupation skos:Concept.

**Comment by siuc-nate** [comment]
We get similar input data for competency uploads for CaSS and for our other CTDL types in our bulk upload tool. In all such cases, we convert/map the SOC code to an appropriate occupation reference (generally via credential alignment object in CTDL).  For these cases, we would map the references to the appropriate URI (where available) or to a ceterms:Occupation bnode.

**Comment by stuartasutton** [comment]
Nate, there is a difference between an instance of an actual occupation (ceterms:Occupation) and the concept of a occupation in a classification scheme (skos:Concept). Everything I have seen so far in the wild (e.g., OSN's RSDs) reference occupational classifications via SOC codes etc.  Those "SOC codes" **are not instances** of ceterms:Occupation.

**Comment by siuc-nate** [comment]
The intent is to reference the occupation, not to reference the code, so I think it is correct to use the code to look up the occupation and associate the reference accordingly.

**Comment by stuartasutton** [comment]
@siuc-nate, as for your https://github.com/CredentialEngine/Schema-Development/issues/811#issuecomment-1054480894, we should not be talking about a "poor man's URI" or the means, not the end. As we have discussed before, these two things in the world--an instance of a thing and a classification to which it belongs are not the same. The intention of the reference determines what it is.  It is not our intention that whenever someone creates a _**new**_ ceterms:Occupation complete with URI that what they are creating is a classification. An instance of ceterms:Occupation may exist outside any classification system and absolutely should NOT be treated as faux classification via bNode. An instance of ceterms:Occupation may exist outside any classification may nevertheless be classified in a classification scheme. If all occupation classification systems were to disappear,  the occupations as conceptual things would not disappear...they would just be unclassified.

**Comment by siuc-nate** [comment]
Wouldn't that be covered by the existing ceterms:occupationType property, which already has a domain that includes ceasn:Competency?

It doesn't make sense to say that a competency's existence is justified/substantiated by a code in a classification scheme; it does make sense to say it is justified/substantiated by an occupation.

**Comment by stuartasutton** [comment]
I am not taking issue with either of your statements, Nate. My take from the start of this issue was that the OSN data for ceterms:substantiating data is referencing SOC codes.

**Comment by siuc-nate** [comment]
Then perhaps we are publishing it incorrectly. If instead it should use ceterms:occupationType, then we should update how we're converting the data from their schema to ours.

**Comment by stuartasutton** [comment]
I think you are right, we are publishing it incorrectly. If this is an issue of the OSN spreadsheet mapping, then it should be changed as you suggest. Please go ahead and change this github issue title to something appropriate to changing our mapping. Then, [ceasn:subtantiatingOccupation](https://purl.org/ctdlasn/terms/substantiatingOccupation) remains as is.

**Comment by siuc-nate** [comment]
Sounds good to me.

**Comment by siuc-nate** [comment]
Closing since this one appears to be resolved without any CTDL changes.
