### ISSUE TITLE
Updates for data suppression policy properties

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#814]
Currently, we have https://credreg.net/qdata/terms/dataSuppressionPolicy which has a range of `rdf:langString`.

It would likely be ideal to have Data Set Profiles link to a description of a data suppression policy rather than duplicating the text of that policy across multiple Data Set Profiles.  For this reason, and to make this property work more like other cases where we have a URL/description combo, I propose the following:

- Change the range of `qdata:dataSuppressionPolicy` from `rdf:langString` to `xsd:anyURI`
- Create a new property along the lines of `qdata:dataSuppressionPolicyDescription` with a range of `rdf:langString`

Thoughts?

**Comment by siuc-nate** [comment]
@stuartasutton Thoughts on this?

**Comment by stuartasutton** [comment]
I think they should be left as-is. These policies are unlikely to have dedicated pages to reference which means that the URI would reference some page where one (human.machine) would have to dig around to isolate the policy.

**Comment by jeannekitchens** [comment]
Need to make a decision on moving forward or closing these and revisiting when and if demand arises.

**Comment by philbarker** [comment]
Need to identify all properties that have text values that may be shared by many resource descriptions.

**Comment by jeannekitchens** [comment]
@philbarker @siuc-nate is this something we still need to pursue?  Especially now since we handled a data suppresion related use case?

**Comment by siuc-nate** [comment]
At a higher level, the goal was to reduce duplication of text across DataSetProfiles, not just for suppression, but for various other places where a text description of a policy/method/mechanism/etc is called for.  The justification is not unlike that used for ConditionManifest/CostManifest, but the mechanics will have to be different (if we still want to pursue this) since the structure of QData is more complicated.

**Comment by siuc-nate** [comment]
This was addressed in #941 (and hasn't been a pressing matter in this thread for quite some time)
