### ISSUE TITLE
Update ceasn:sourceDocumentation to support Concepts

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#815]
The property https://credreg.net/ctdlasn/terms/sourceDocumentation could serve the same purpose for Concepts with the following modifications:
- Add skos:Concept to its domain
- Update the definition 
  - from: "Human-readable information resource other than a competency framework from which this competency was generated or derived by humans or machines." 
  - to: "Human-readable information resource other than a competency framework from which this resource was generated or derived by humans or machines." 
  - Possibly striking "other than a competency framework" as well, though that may not be necessary

The motivating factor for this, currently, is to enable including the wikipedia URL in the EMSI data (if we document them as concepts).

**Comment by philbarker** [comment]
I thought the purpose of sourceDocumentation was for when something like an instruction manual had been used to derive competences. In this case the source document would be the job ad from which the competence was inferred. I think EMSI use wikipedia as a reference for what has been derived from other docs, so not a source more of a target.

I'd suggest subjectWebpage as a better match for including a URL for a reference giving more information about a competence. [Better still, at least for machine readability, sameAs pointing to the dbpedia or wikidata id, but that would take some computation to work out.]

**Comment by philbarker** [comment]
For the EMSI use case, `ceterms:subjectWebpage` works.

For other potential use cases:

Add skos:Concept, skos:ConceptScheme, ctdlasn:CompetencyFramework to domain of https://credreg.net/ctdlasn/terms/sourceDocumentation

Update the definition
from: "Human-readable information resource other than a competency framework from which this competency was generated or derived by humans or machines."
to: "Human-readable information resource other than a competency framework from which this resource was generated or identified by humans or machines."
comment: "The intended use case for this is when documentation is analyzed in order to find and describe entities such as competencies and concepts."

**Comment by siuc-nate** [comment]
Proposal:

Add:
> **Subject:** ceterms:subjectWebpage
> **Predicate:** schema:domainIncludes
> **Object:** skos:Concept

> **Subject:** skos:Concept, skos:ConceptScheme, ctdlasn:CompetencyFramework
> **Predicate:** schema:domainIncludes
> **Object:** ceasn:sourceDocumentation

Update:
> **Subject:** ceasn:sourceDocumentation
> **Predicate:** rdfs:comment
> **Remove Object:** "Human-readable information resource other than a competency framework from which this competency was generated or derived by humans or machines."
> **Add Object:** "Human-readable information resource other than a competency framework from which this resource was generated or identified by humans or machines."

Add: 
> **Subject:** ceasn:sourceDocumentation
> **Predicate:** dct:description
> **Object:** "The intended use case for this is when documentation is analyzed in order to find and describe entities such as competencies and concepts."

@philbarker Is subjectWebpage meant to be added to any other classes?

**Comment by siuc-nate** [comment]
The above changes have been made in pending CTDL/CTDL-ASN and noted in the history tracking.

I will close this thread pending @philbarker's approval.

**Comment by philbarker** [comment]
That looks good to me.
