### ISSUE TITLE
Missing dates in term history data

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#817]
Today, I was back into the terms history serializations to determine when the [ceasn:tableOfContents](https://purl.org/ctdlasn/terms/tableOfContents)  property was added in teh serializations data. Since it has had no changes, there is no creation date. However, once the first change is registered, the date of creation appears (or I think that is the date of creation). 

* See `tableOfContext` property history that shows no creation date: [https://credreg.net/ctdlasn/termhistory/ceasn/tableOfContents/turtle](https://credreg.net/ctdlasn/termhistory/ceasn/tableOfContents/turtle)
* See `competencyLabel` property history that shows date of creation, but no dates on the subsequent changes: [https://credreg.net/ctdlasn/termhistory/ceasn/competencyLabel/turtle](https://credreg.net/ctdlasn/termhistory/ceasn/competencyLabel/turtle)

In sum, we should be able to see: 

1. the creation date of the property (published regardless of stable or unstable) should be in the serializations even where there has been no changes made. Being able to pinpoint when a term entered the vocabulary is an important part of history; and
2. the date of each change commitment. I understand that if they click on the "View History" that they are taken to the release date, but that is insufficient for pinpointing a specific change date in a history with multiple changes. That change date should be in each rdf:Statement.

**Comment by siuc-nate** [comment]
This property was part of CTDL-ASN from the very beginning, so it pre-dated any of our change tracking stuff, or the schema management system itself. We don't have dates for those terms.

**Comment by stuartasutton** [comment]
I understand, I am just wanting to make sure we do have them with anything new.

**Comment by siuc-nate** [comment]
Can this be closed?

**Comment by stuartasutton** [comment]
It can be closed if you can verify the any new changes are being accurately captured with date of change.
