### ISSUE TITLE
Program Services

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#818]
Learning Programs can offer services such as: Childcare Services, Disabled Student Services, Career Counseling Service, Job Placement Services, Public Transportation Services.  

These types of services are offered through WIOA programs when funding is available. 

These types of services can be offered by secondary and postsecondary education institutions.

Special programs can receive funding to provide these types of services.

These services are identified with the Texas Use Cases ([deck](https://docs.google.com/presentation/d/1SF0zihOfgjwSqAl5-aGJJi0CLl2ZSqxg/edit?usp=sharing&ouid=100765403558718637226&rtpof=true&sd=true)) and ([google sheet TX use case tracking](https://docs.google.com/spreadsheets/d/1us-JEOP5dHk3vAt7QRA5oNhBsZnzUUFhN6SNPUxmvPI/edit#gid=1743788980))

**Comment by siuc-nate** [comment]
We encountered this waaay back in the early stages of developing for ProPath (back when we were going to give it its own schema).  I had documented the services I found (in the data we were working with at the time) in [the spreadsheet we were using at the time](https://docs.google.com/spreadsheets/d/1L213QzmTtOWdmAHeFopPMsrOv-Tj5kw5H6FCPCvmZO8/edit#gid=1547473779). The plan there may be a useful starting point for the plan here.  It consisted of the following:

1. A Support Profile class (defined as "Entity that describes the nature of support available for a resource.") with these properties:
  - Name
  - Description
  - Subject Webpage
  - Available At
  - Offered By
  - Support Type
2. A Support Type concept scheme with these concepts:
![image](https://user-images.githubusercontent.com/21346519/158205107-6a23a0f5-db0e-4f80-9dbe-c0b6515615d8.png)

We might also want to look at Financial Assistance Profile to see if any of the support stuff should be covered there instead.  The Support Profile I had in mind here was largely for the kinds of support in the concept scheme.

**Comment by philbarker** [comment]
> Learning Programs can offer services such as:...

I would prefer to say that Organizations offer services that may be associated with a LearningProgram. This keeps **Learning**Programs as a set of Courses etc, i.e. a resource, not something with agency to offer / organize / provide things (which other definitions of Program may allow). It affects the modelling, but we could say:
`(Organization) --[offersService]-> (Support) --[eligibleProgram]-> (LearningProgram)`
and/or
`(LearningProgram) --[coveredBy]-> (Support) --[offeredBy]->(Organization)`

**Comment by stuartasutton** [comment]
Very odd, I am getting an error from gighub that I "cannot commit at this
time" when I try to respond to Phil's comment.

**Comment by siuc-nate** [comment]
See #872
