### ISSUE TITLE
Add ceterms:postReceiptMonths to qdata:DataProfile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#821]
In order to enable QData to capture data like that described by this document and the last few columns in this sheet:
https://docs.google.com/document/d/1i4Sm0uMKBpKYp16zy7AC9wm9YcPFPnFdCPXeYTVJOSE/edit
https://docs.google.com/spreadsheets/d/1UaBUM4e9YBxphbvdqMSawUPb94DqVf5chSFOPOOx0mc/edit#gid=0

We should add qdata:DataProfile to the domain of ceterms:postReceiptMonths

Example:
https://github.com/CredentialEngine/Schema-Development/blob/master/Aggregate%20Performance%20Data%20Examples/Indiana/ROI%20Example%201.json

**Comment by siuc-nate** [comment]
I have spent some time reviewing the data that kicked off this issue and I'm not entirely sure that I completely understand it. We should discuss it before moving forward with this change.

**Comment by jeannekitchens** [comment]
This issue was resolved while working with the Indiana team.
