### ISSUE TITLE
Issues with CTDL use of rdfs:range

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#822]
There are identified issues with the use of rdfs:range in CTDL that need examination and clarification so we can make sure we are on the right path going forward.  This matters both internally and externally.

The rdfs:range predicate is used to indicate that the values of a particular property are instances of a designated class(i.e., it defines the range of the property). While this appears straight forward, it's a bit complex.

Can a datatype be used as a range? The definition appears to cut against using datatypes as a range; but datatypes as a range are seen in practice (and instruction).

<img width="350" alt="range" src="https://user-images.githubusercontent.com/2939046/160638678-a27bf02c-0f6d-4a97-9de9-a277c6b5b576.png">

This is one of the question raised in #812 for xsd:anyURI.

A second issue stemming from the use of datatypes as range is how they are interpreted. For example, if we have a property with the range of rdfs:Resource, what gets returned in instance data should be a resource description. If I have a range of xsd:anyURI, is it treated simple as a literal or is it resolved (i.e., returning a resource description)?

A third issue with range that we have with CTDL is how best to handle ranges for concepts and concept schemes. CTDL has variously used the ceterms:CredentialAlignmentObject for this purpose (ugh), and skos:Concept/ConceptScheme. Also now in the mix outside CTDL is sdo:DefinedTerm/DefinedTermSet. 

So, we need to have a conversation to first get rdfs:range right and ONLY then, as what the Credential Engine should do or not do.

**Comment by siuc-nate** [comment]
For what it's worth, we technically use https://schema.org/rangeIncludes rather than `rdfs:range` in our schema. This was [a change you had us make quite a while back](https://github.com/CredentialEngine/Schema-Development/issues/500). I'm not sure how that impacts your points here.

**Comment by stuartasutton** [comment]
Yes, that is correct, it 'softens' the semantics (i.e., no inferences to be made). It does not change the trust of the issue here and that is for us all to be absolutely clear first amongst ourselves and then as reflected through out schemas and data.

**Comment by jeannekitchens** [comment]
@stuartasutton please layout any additional information needed to determine if there is or isn't any updates needed to any of the Ranges with CTDL terms.

**Comment by stuartasutton** [comment]
Jeanne, with the exception of any impact on the existing applications, I do not think there is "any additional information" needed in determining:

1. our use of "xsd:anyURI" as opposed to "rdfs:Resource; and
2. which is the preferred rdfs:range when reference concepts and concept schemes (ceterms:CredentialAlingmentObject, skos:Concept/ConceptScheme, sdo:DefinedTerm/DefinedTermSet.

Do we settle on solutions to both and shift course going forward or do we stay the course with either or both.

**Comment by philbarker** [comment]
18 Oct meeting:
- Change xsd:anyURI to rdfs:Resource by default
- Some cases there may be a more specific correct value, such as skos:Concept, sdo:WebPage...
- Can use sdo:WebPage and sdo:URL for text that should be rendered as a link (but no data sent)
- Need to check code base in case this breaks anything

**Comment by siuc-nate** [comment]
Archiving this to reduce clutter, but I think it may still be a viable issue.
