### ISSUE TITLE
Error in ctdlasn schema / context regarding subclass

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/Schema-Development#826]
In http://credreg.net/ctdlasn/schema/context/json
line 1419:
```
   "rdfs:subclassOf": {
      "@type": "@id"
    },
```

Should be [`rdfs:subClassOf:`](https://www.w3.org/TR/rdf-schema/#ch_subclassof)

Urgent action please, as this might be causing problems with import into DESM.

**Comment by siuc-nate** [comment]
It looked like this was right in all but one spot in the code. I have updated the site. It should be fixed now.

**Comment by jeannekitchens** [comment]
Thank you @siuc-nate !  Please take a look to be sure all three schemas are correct now.

**Comment by philbarker** [comment]
Looks good to me.  Thank you @siuc-nate
