### ISSUE TITLE
License Proposed Definition Update

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#827]
This proposed change is to meet use case requirements via the IMS Global CLR project.  Related IMS GitHub issue https://github.com/IMSGlobal/openbadges-specification/pull/364#issuecomment-1105453906 and use case. 

https://credreg.net/ctdl/terms#License -  broaden the definition from  "Credential awarded by a government agency that constitutes legal authority to do a specific job and/or utilize a specific item, system or infrastructure and are typically earned through some combination of degree or certificate attainment, certifications, assessments, work experience, and/or fees, and are time-limited and must be renewed periodically." 

to 

"Credential awarded by a government agency or other authorized organization that constitutes legal authority to do a specific job and/or utilize a specific item, system or infrastructure and are typically earned through some combination of degree or certificate attainment, certifications, assessments, work experience, and/or fees, and are time-limited and must be renewed periodically."

**Comment by siuc-nate** [comment]
We could simplify this by focusing on the core of what makes a license different from other credentials:
"Official permission for that which would otherwise be illegal."

**Comment by jeannekitchens** [comment]
This is from the IMS Global CLR workgroup Phillip Long The topic came up in the CLRv2 meeting that CTDL apparently doesn’t have a license type that is other than one issued by a government entity (local, state, of federal). Yet many examples exist of professional associations that issue licenses -e.g.., were given for things like welding, in some states auto repair that rely on a professional association license instead of anything state issued, and healthcare. Others were offered in the context of Canadian licensing. We voted in the CLRv2 meeting today to harmonize with the CTDL names for issued credentials, but this omission caused Joshua Marks and a few others to suggest we hold off on that. In the end we voted to harmonize anyway, and open a conversation with CE to add this ‘missing’ license type.

**Comment by siuc-nate** [comment]
Worth considering: https://www.merriam-webster.com/dictionary/license
Definition 2a is similar to my above proposal: "a permission granted by competent authority to engage in a business or occupation or in an activity otherwise unlawful"

**Comment by jeannekitchens** [comment]
License Definition change: "Credential awarded by a government or other authorized organization that constitutes legal authority to do a specific job and/or utilize a specific item, system or infrastructure and are typically earned through some combination of degree or certificate attainment, certifications, assessments, work experience, and/or fees, and are time-limited and must be renewed periodically."

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
