### ISSUE TITLE
Add ceterms:lifeCycleStatusType to ceterms:Collection

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#828]
This is something we were going to do per the diagrams/our presentations related to #806 but that doesn't actually appear as part of the changes in that issue, so it seems we made another oversight.

Proposal:
**Add:**
> **Subject:** ceterms:lifeCycleStatusType
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Collection

**Comment by jeannekitchens** [comment]
Also, I thought we added https://credreg.net/ctdlasn/terms#PublicationStatus to Competency.

**Comment by siuc-nate** [comment]
I'm not seeing that specified anywhere.

**Comment by stuartasutton** [comment]
I don't recall any discussion regarding adding [PublicationStatus](https://credreg.net/ctdlasn/terms#PublicationStatus) to Competency. It exists on [CompetencyFramework](https://purl.org/ctdlasn/terms/CompetencyFramework). What's the use case for it on Competency?

**Comment by jeannekitchens** [comment]
NICE competency statements that are no longer applicable.  Same for WGU, SNHU any organization that manages collections outside the constraints of a framework, eventually, the lifecycle of a competency ends.

**Comment by jeannekitchens** [comment]
Final Proposal:
Add:

Subject: ceterms:lifeCycleStatusType
Predicate: schema:domainIncludes
Object: ceterms:Collection

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
