### ISSUE TITLE
Progression Model and Progression Level Need All Properties, 

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#829]
@siuc-nate See the Progression Model and Progression Level tab of the CaSS mapping sheet and [CaSS GitHub issue #1116](https://github.com/cassproject/cass-editor/issues/1116) https://docs.google.com/spreadsheets/d/1dM5D113yQP23GxsHmck4EI89S8yhRatVkZ3sOPaRN-U/edit#gid=99163956

- https://credreg.net/ctdlasn/terms#ProgressionLevel
- [asn:ProgressionModel](https://credreg.net/ctdlasn/terms/ProgressionModel).

There's no need to wait to do this.  We're using Progression Models with pathways and it's confusing currently with no properties showing with either of the above classes. This has nothing to do with the current task group work so it will not be included with the terms proposal.  

@mparsons-ce verify this is already fully supported with the API.  

@stuartasutton see the CaSS mapping sheet tabs and confirm all properties are complete and none of the rows should be removed.  I copied and pasted all Concept properties to Progression Model and I pasted all Concept Properties to Progression Level.  The CTDL handbook was updated by you to include information about Progression Models in the pathways section.  https://credreg.net/ctdl/handbook#progressionmodel.  However both terms are in the ASN namespace so it would be very helpful to have a Progression Model example that is competency-relevant in the Competency Framework section, just as we have a [Collection section with a diagram specific to Competencies](https://credreg.net/ctdl/handbook#ctdlasncollection).

**Comment by mparsons-ce** [comment]
Notes
All concept schemes published to date have **PublisherName** as a single value.
https://credentialengineregistry.org/graph/ce-14de89f3-4ae2-4247-8000-776d8047800a
![image](https://user-images.githubusercontent.com/58825866/167720458-5a35fce7-6808-4b08-b4ef-05ee8cd795af.png)


**Source** is currently defined as a string, not a list.
![image](https://user-images.githubusercontent.com/58825866/167720370-d397bc47-c412-4717-b84d-1e7baee7ae61.png)

**notation**
This currently defined as a single string.
For all cases of the property CodedNotation, a single value was used. Where defined as a list, it was reverted to a string based on codedNotation being a type of identifier. 
It sounds like notation would have a similar rational. 
I don't think it has been used. So could change to a list if that is the decision.

Depending on the decision on these, all concept schemes will have to be republished.

**Comment by jeannekitchens** [comment]
@siuc-nate use the CaSS/CTDL mapping sheet https://docs.google.com/spreadsheets/d/1dM5D113yQP23GxsHmck4EI89S8yhRatVkZ3sOPaRN-U/edit#gid=589991464

**Comment by siuc-nate** [comment]
Per the spreadsheet:
Proposal:

Add asn:ProgressionModel to the domain of the following properties:
- ceterms:ctid
- ceasn:description
- ceasn:inLanguage
- ceasn:name
- ceasn:hasTopConcept
- ceasn:publisher
- ceasn:publisherName
- ceasn:conceptTerm
- ceasn:creator
- ceasn:dateCopyrighted
- ceasn:dateCreated
- ceasn:dateModified
- ceasn:conceptKeyword
- ceasn:license
- ceasn:publicationStatusType
- ceasn:rights
- ceasn:rightsHolder
- ceasn:source

Add asn:ProgressionLevel to the domain of the following properties:
- asn:hasProgressionModel
- skos:prefLabel
- skos:inScheme
- skos:definition
- skos:notation
- skos:note
- skos:topConceptOf
- skos:broader
- skos:narrower


**However**, there are some problems:
- The spreadsheet indicates that Progression Model should have asn:hasProgressionLevel.  This doesn't seem correct. That property is used to point to a progression level from a pathway component.  
  - It's also disjoint from how concept schemes work.  
- The spreadsheet indicates that Progression model uses ceasn:hasTopConcept. We shouldn't mix hasTopConcept with hasProgressionLevel. What is the equivalent for Concept Scheme? The inconsistency here will be an annoyance for implementers.
- The spreadsheet indicates that Progression Level should have asn:hasProgressionModel.  Again, this is not the intended function of hasProgressionModel. It's also redundant with skos:inScheme (which the spreadsheet indicates is _also_ a property of Progression Level)
- The spreadsheet is missing ceterms:ctid as a property of Progression Level

We need to look at this more holistically. If we're still taking the approach that a Progression Model/Level are sufficiently identical to Concept Scheme/Concept to have so much overlap in their properties, then I suggest the following:
- Do not use hasProgressionModel/hasProgressionLevel with Progression Level and Progression Model, respectively
- Follow the same pattern used with Concept Scheme/Concept to determine the Progression Levels for a Progression Model (essentially just lookup all of the items with a skos:inScheme that references the scheme/model you're interested in - if this works for Concept Schemes, it will work for Progression Models)
- Add ceterms:ctid to Progression Level

**Comment by siuc-nate** [comment]
Properties with the domain of Progression Model (subclass of skos:ConceptScheme):
- ceasn:conceptKeyword
- ceasn:conceptTerm
- ceasn:creator
- ceasn:dateCopyrighted
- ceasn:dateCreated
- ceasn:dateModified
- ceasn:description
- ceasn:inLanguage
- ceasn:license
- ceasn:name
- ceasn:publicationStatusType
- ceasn:publisher
- ceasn:publisherName
- ceasn:rights
- ceasn:rightsHolder
- ceasn:source
- ceterms:ctid
- skos:hasTopConcept

Properties with the domain of Progression Level (subclass of skos:Concept):
- ceterms:ctid
- skos:broader
- skos:definition
- skos:inScheme (subproperty: ceasn:inProgressionModel)
- skos:narrower
- skos:notation
- skos:note
- skos:prefLabel
- skos:topConceptOf

**Comment by siuc-nate** [comment]
Note: I have updated the [CaSS spreadsheet](https://docs.google.com/spreadsheets/d/1dM5D113yQP23GxsHmck4EI89S8yhRatVkZ3sOPaRN-U/edit#gid=99163956) to match the above list

**Comment by siuc-nate** [comment]
The above changes have been made in pending CTDL/CTDL-ASN and noted in the history tracking.
