### ISSUE TITLE
Add ceterms:supersededBy to Organization classes

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#830]
To accommodate cases where organizations [merge](https://docs.google.com/document/d/1mcVe5V_JvaINgFMvOrHrX6IYdFSwPPkswHnDPEl5Ll4/edit#), are replaced, dissolved, etc., but their credentials, assessments, learning opportunities, etc. are maintained by other organizations, we should add ceterms:supersededBy and ceterms:supersedes to the Organization classes.

Usage: When an organization closes, but its credentials go on under a new owner...
- Set the Organization's status to lifeCycle:Ceased
- Add a reference to the new owner(s) to the Organization via ceterms:supersededBy

This can also be mirrored on the other side:
- Add a reference to the closed organization to the surviving organization(s) via ceterms:supersedes

Proposal:
**Add:**
> **Subject:** ceterms:supersededBy
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Organization, ceterms:CredentialOrganization, ceterms:QACredentialOrganization, ceterms:AssessmentProfile, ceterms:Course, ceterms:LearningOpportunityProfile,ceterms:LearningProgram, ceterms:TransferValueProfile

> **Subject:** ceterms:supersedes
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Organization, ceterms:CredentialOrganization, ceterms:QACredentialOrganization, ceterms:AssessmentProfile, ceterms:Course, ceterms:LearningOpportunityProfile,ceterms:LearningProgram, ceterms:TransferValueProfile

**Comment by stuartasutton** [comment]
mergedInto and supersededBy are different notions/actions.

**Comment by siuc-nate** [comment]
Maybe to humans, but from the perspective of tracking resources, they are just two distinct organizations/records/CTIDs/etc. where one should be used instead of the other because one has, for all intents and purposes, replaced the other.  The fact that it's a result of a merger is irrelevant.  We can capture that in the description of the closed organization if need be.

**Comment by jeannekitchens** [comment]
We just met with several representatives from the Minnesota College System and State of Minnesota.  They completely agree it would be very useful to include supercededBy with Organization and want this information published with the five colleges being merged into one new college.   This is practical and helpful. It will be part of the data to show a direct link to the college that superceded those that closed.  We need to implement this.  It does not have to wait for the pathways release. See the related merger scenario notes here https://docs.google.com/document/d/1mcVe5V_JvaINgFMvOrHrX6IYdFSwPPkswHnDPEl5Ll4/edit#.

**Comment by jeannekitchens** [comment]
Final proposal to be implemented:
Add:

Subject: ceterms:supersededBy
Predicate: schema:domainIncludes
Object: ceterms:Organization, ceterms:CredentialOrganization, ceterms:QACredentialOrganization, ceterms:AssessmentProfile, ceterms:Course, ceterms:LearningOpportunityProfile,ceterms:LearningProgram, ceterms:TransferValueProfile

Subject: ceterms:supersedes
Predicate: schema:domainIncludes
Object: ceterms:Organization, ceterms:CredentialOrganization, ceterms:QACredentialOrganization, ceterms:AssessmentProfile, ceterms:Course, ceterms:LearningOpportunityProfile,ceterms:LearningProgram, ceterms:TransferValueProfile

**Comment by siuc-nate** [comment]
Just a note - I assume this proposal is to add those classes to both the domain **and** the range of those two properties. Otherwise it doesn't make any sense. I am currently adding it to the schema as such.

**Comment by siuc-nate** [comment]
The following changes have been made in pending CTDL and noted in the history tracking:

**Add:**
> **Subject:** ceterms:supersededBy
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Organization, ceterms:CredentialOrganization, ceterms:QACredentialOrganization, ceterms:AssessmentProfile, ceterms:Course, ceterms:LearningOpportunityProfile,ceterms:LearningProgram, ceterms:TransferValueProfile

> **Subject:** ceterms:supersedes
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Organization, ceterms:CredentialOrganization, ceterms:QACredentialOrganization, ceterms:AssessmentProfile, ceterms:Course, ceterms:LearningOpportunityProfile,ceterms:LearningProgram, ceterms:TransferValueProfile

> **Subject:** ceterms:supersededBy
> **Predicate:** schema:rangeIncludes
> **Object:** ceterms:Organization, ceterms:CredentialOrganization, ceterms:QACredentialOrganization, ceterms:AssessmentProfile, ceterms:Course, ceterms:LearningOpportunityProfile,ceterms:LearningProgram, ceterms:TransferValueProfile

> **Subject:** ceterms:supersedes
> **Predicate:** schema:rangeIncludes
> **Object:** ceterms:Organization, ceterms:CredentialOrganization, ceterms:QACredentialOrganization, ceterms:AssessmentProfile, ceterms:Course, ceterms:LearningOpportunityProfile,ceterms:LearningProgram, ceterms:TransferValueProfile
