### ISSUE TITLE
Use of constraints for requirements on award of credential

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/Schema-Development#832]
Explore how the Constraint class can be used outside of pathways to describe more complex conditions such as for the award of credentials.

Related: 

- issue #768 
- [modeling ND Cyber framework](https://github.com/CredentialEngine/Schema-Development/issues/807#issuecomment-1062858585)

**Comment by siuc-nate** [comment]
Seems like this would be covered by #848
