### ISSUE TITLE
Need Non Credit Property or Concept

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#834]
We need to support use cases where Learning Opportunities, Learning Programs, Courses, Assessments, and some Credential types are "non credit."  For example a Badge or Certificate may be Non Credit.  

Draft Definition: Non Credit -  Carrying or conferring no official academic credit towards a program or a credential.

Possible Solutions:
1. Add "NonCredit" as concept to https://credreg.net/ctdl/terms#CreditUnit.
2. Update the Domains for https://credreg.net/ctdl/terms#creditUnitType to include the above Classes.  This allows use cases where the value of the credit unit is not needed, rather the type of credit unit or non credit is needed.  Also, update the definition to "The type of**, or absence of,**  credit associated with the credit awarded or required.

This is a State of Florida use case but is also a use case applicable to all types of learning opps and many types of credentials. CTDL needs to support the use cases where there is a need to identify the CreditUnitType and it's value and/or use cases where whether the Learning Opp, Assessment or Credential is Non Credit or a type of credit, e.g., Continuing Education Unit.

**Comment by jeannekitchens** [comment]
No..  just because there's no credit information in no way means you can discern if it is non credit.  It has to be explicit.  For example, every public college has non-credit courses explicitly identified because they in a way get around enrollment requirements and other barriers that students face when enrolling in academic credit programs where credits are the requirement to earn/confer a degree or diploma. Those course can and should be identified as NonCredit.

**Comment by philbarker** [comment]
CreditUnit seems like the wrong concept scheme. It's for the unit that something is measured. If something has no weight you don't use a unit of "weightless" to weigh it in, you say it weighs 0 in any unit. So if something is not credit bearing why not set the value of the credit to zero?
```
...
  "ceterms:creditValue" : { 
     "@type": "ceterms:ValueProfile";
     "schema:value": 0
   }
... 
```

**Comment by stuartasutton** [comment]
+1 on [Phil's comment](https://github.com/CredentialEngine/Schema-Development/issues/834#issuecomment-1171020780)

**Comment by stuartasutton** [comment]
But also +1 on [Jeanne's comment](https://github.com/CredentialEngine/Schema-Development/issues/834#issuecomment-1170501248). Many institutions make provision for non-credit courses that do not count toward total required credits (i.e., non-credit). So, while Phil's treatment of creditValue makes sense, that does not change the fact that the credit status of the course is non-credit.

**Comment by jeannekitchens** [comment]
All, we simply need to support a use case where the publisher can identify a course or program as non credit..  I believe the existing concept scheme works. My main point is that we should not force the declaring of a value when it is just as important to know something is only non credit or something is only professional development credit.  Taking the extra step of adding the value is also great but you can have one without the other.  We're completely missing the 1st part, simply identifying the thing with a credit type.   I agree they can, in addition, add a value of zero but that does not definitively communicate that the reason for the zero is it's noncredit.  We should not be tethering the concept scheme to the requirement that to use it you have to have a value.

**Comment by siuc-nate** [comment]
Using the Credit Unit concept scheme seems like the most logical place for this (+1 to using 0 for the value as well). We might consider adding the creditValue property to ScheduledOffering to facilitate indicating offerings of a Course where some give credit and some do not but they are otherwise identical.

**Comment by jeannekitchens** [comment]
Yes @siuc-nate there's no need to have another concept scheme.  All, this is for a very large publishing project.  We need to have a final definition, and per my 1st post directly support the simple need to support use cases for identifying the creditUnitType directly with the above listed domains rather than the only supported use case being identifying value.

**Comment by philbarker** [comment]
I don't see how saying that something as creditValue of 0 is different to saying it is non-credit bearing, and you can already do it, no need to wait for an update to CTDL.

I'll stand aside, but I have reservations about using creditUnitType directly on those classes.  We packaged the information about credit awarded into a ValueProfile for good reasons, e.g. to avoid ambiguity when a course may award credit in different units (e.g. University of Edinburgh MOOC courses do not bear credit that count to a degree, but do bear credit towards micro-credentials).

**Comment by siuc-nate** [comment]
I'm certainly also okay with just using 0 and not doing anything with the concept scheme. 0 is 0 regardless of the unit of measurement, so it is a little redundant to specify both.

If we did create a new concept, it would still be done via creditValue -> ValueProfile -> creditUnitType (unless I missed something)

**Comment by siuc-nate** [comment]
Proposal:
Create creditUnit:NonCredit concept
> **URI:** creditUnit:NonCredit
> **Label:** Non-Credit
> **Definition:** Carrying or conferring no official academic credit towards a program or a credential.
> **In Scheme:** ceterms:CreditUnit

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
