### ISSUE TITLE
CredentialStatus and LifeCycleStatus Concept: Teach Out

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#835]
Need to add a new concept, TeachOut, to CredentialStatus and LifeCycleStatus.  It needs to be on both CredentialStatus and LifeCycleStatus because the institution may remain open but program is no longer accessible to students either at a specific location or no longer accessible at all.

This is for a State of Florida use case. 

References:
1. [SACS COC pages 65 and 66](https://sacscoc.org/app/uploads/2019/08/SubstantiveChange.pdf)
2.[ Wikipedia Teach Out](https://en.wikipedia.org/wiki/Teach-out#cite_note-FOOTNOTECongressional_Research_Service2019Summary-1)
3.[ Federal Student Aid Teach [](Out Process](https://studentaid.gov/help-center/answers/article/teach-out-plan))
4. [Higher Learning Commission's Requirements for Teach Out Agreement](https://www.hlcommission.org/Policies/teach-out-arrangements.html)

TeachOut definition: Arrangement by which an educational institution provides its current students with the opportunity to complete their course of study when the program, institution or location offering access closes.

**Comment by siuc-nate** [comment]
Either a course is active or it's not; the details ("teach out") are not part of its life cycle.  This sounds like something that should just go in the description, as I can't imagine this being a common use case at all.

If _anything_, I think this would be a concept under ScheduleFrequency (alongside "Irregular", "OnDemand", "OpenEntryExit", etc.).

It also doesn't make sense as a descriptor for a credential, since it is entirely to do with the status of the program that leads to that credential.

**Comment by jeannekitchens** [comment]
@siuc-nate that's not true and why there's other statuses not just active or deprecated. It would not be part of a description.

**Comment by siuc-nate** [comment]
My point is, that minor detail of how the course is offered is not describing an aspect of its life cycle. The rest of my previous post has my alternative suggestions.

**Comment by philbarker** [comment]
+1 to adding TeachOut. It's very common in multi-year programs and addresses a period in the lifecycle of a Program that would otherwise be ambiguous.

**Comment by stuartasutton** [comment]
I am with Jeanne and Phil.

**Comment by siuc-nate** [comment]
Life Cycle Status is used for more than just learning opportunities. If we're going to put teach out in there, we should try to broaden it to something that could make sense for other types of resource. Something along the lines of "not active for new participants" or "active only for those already participating" with a more generically-applicable label/URI than "teach out"

**Comment by stuartasutton** [comment]
Nate, that misses the point. Apparently, "teach-out" is a term of art and should therefore not be generalized. Jeanne, your definition is is aligned with the Wikipedia definition ("A teach-out or teachout is an arrangement by which an educational institution provides its current students with the opportunity to complete their course of study when the institution closes.) which references as source the Congressional Research Service. I am not familiar with the notion, but wonder whether "institutional closing" is too narrow. Are there other circumstances, perhaps only temporary, where the terms would be applicable?

**Comment by siuc-nate** [comment]
>should therefore not be generalized

Then I would point to my alternative suggestion above.

**Comment by siuc-nate** [comment]
I would also note that using schedule frequency covers the use case Jeanne highlighted, whereas using life cycle would not:
>no longer accessible to students at a specific location

ceterms:offerFrequencyType is already a property of ceterms:ScheduledOffering, allowing for a course to be offered normally at one location and offered teach-out style at another.

**Comment by siuc-nate** [comment]
Create two concepts:
**URI:** lifeCycle:Ceasing
**Label:** Ceasing
**Description:** Resource is no longer active, current, ongoing, offered, operational, or available, except for participants who are already engaged with it.

**URI:** lifeCycle:TeachOut
**Label:** Teach Out
**Description:** Arrangement by which an educational institution provides its current students with the opportunity to complete their course of study when the program, institution or location offering access closes.
**Broader:** lifeCycle:Ceasing

**Comment by jeannekitchens** [comment]
CredentialStatus has to have TeachOut.

**Comment by siuc-nate** [comment]
With what definition?

**Comment by siuc-nate** [comment]
Does something like "Arrangement by which an educational institution provides its current students with the opportunity to complete the credential when the program, institution or location offering access closes." work?

**Comment by philbarker** [comment]
Slight niggle about the definition referencing completing a credential, which might not necessarily be the case, but I could live with that.

**Comment by siuc-nate** [comment]
I am still opposed to the term, but since we're adding it, it needs a definition. I presume we would want to use a definition that is specific to Credentials rather than repeating the definition for the lifeCycle:TeachOut status, so I made an attempt. The term doesn't make any logical sense to me, though, so I'm probably not the best person to be defining it.

**Comment by siuc-nate** [comment]
I have updated [this post](https://github.com/CredentialEngine/Schema-Development/issues/835#issuecomment-1175308346) with the proposed definition above.

These changes have been made in pending CTDL and noted in the history tracking.

**Comment by philbarker** [comment]
Ah, OK, I had missed that the definition was just for teachOut in  CredentialStatus. Good work @siuc-nate
