### ISSUE TITLE
Alignment properties used by schema terms

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#838]
I did some fiddling with javascript using the 3 schemas' JSON-LD encodings and came up with this, per our meeting the other day where we wanted these lists:

https://github.com/CredentialEngine/Schema-Development/blob/master/Discussions/Alignment%20properties%20used%20by%20terms.json

These are the properties that connect one term to another used in our schema currently, along with the terms that use those properties.

**Comment by siuc-nate** [comment]
See also #699

**Comment by philbarker** [comment]
Thanks, I guess that is manageable. I think the skos terms we want are `skos:broadMatch` and `skos:narrowMatch` (matches to concepts in other ConceptSchemes, not relationships within the same scheme).

**Comment by siuc-nate** [comment]
Updated listings (I wasn't sure which would be easiest to work with):
- [Compact, with the subjects and their objects, grouped by predicate](https://github.com/CredentialEngine/Schema-Development/blob/master/Discussions/AlignmentPropertiesV2Compact.json)
- [Triples, grouped by predicate](https://github.com/CredentialEngine/Schema-Development/blob/master/Discussions/AlignmentPropertiesV2Grouped.json)
- [A big flat list of triples](https://github.com/CredentialEngine/Schema-Development/blob/master/Discussions/AlignmentPropertiesV2Graph.json)

**Comment by siuc-nate** [comment]
I have also added the above listing to a spreadsheet here:
https://docs.google.com/spreadsheets/d/1jazCSPbWlKoc3OJcGSvii3lohNtd2pRdz5c3UmwjnCY/edit#gid=0

There is a second tab on the spreadsheet that lists the terms that come from other namespaces and are used as-is.

**Comment by jeannekitchens** [comment]
@philbarker @siuc-nate what exactly is the open item here?  Thanks!

**Comment by siuc-nate** [comment]
I think Phil was using this for research on something, but I don't recall the details.

**Comment by philbarker** [comment]
There is no open issue. I needed a list to check how we had dealt with issues relating to the [namespace policy for borrowed terms](https://credreg.net/page/namespacepolicy#borrowedterms).
