### ISSUE TITLE
Consider normalizing how concept URIs are published

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#839]
While putting together [this issue](https://github.com/CredentialEngine/CredentialRegistry/issues/570), I noticed there are inconsistencies in how our registry records record concept URIs.

The problem seems to be a lack of normalization in terms of how URIs for concepts get (or don't get) expanded out into full URIs.  For example, I see data in the registry using `credentialStat:Active`, with [this credential](https://credentialengineregistry.org/resources/ce-91d5eb73-f136-4510-91ad-1d4290307240), but I also see data using `http://purl.org/ctdlasn/vocabs/publicationStatus/Published` like [this framework](https://credentialengineregistry.org/resources/ce-14de89f3-4ae2-4247-8000-776d8047800a) (the shorthand would be `publicationStatus:Published`).

My instinct is to say that we should always publish full URIs, using the credreg domain (instead of purl) so that full URIs will be consistently available in the records, which means that it won't matter so much whether a URI points to a concept from CTDL or to a concept someone published to the registry or to a concept somewhere else on the internet - it will always just be a full URI.

However, there are a few problems causing my thinking on this to go around in circles:
- The JSON-LD expansion/compaction rules would suggest that our compact URIs should expand to purl URIs, not credreg URIs (at least in most cases)
- If we ever needed to change the credreg domain to something else, we would wish we had used the purl URIs
- But the purl URIs also require an extra step of requesting data to figure out that they come from the credreg domain, so using the compact URIs instead keeps this simple/abstracts it away while keeping the benefits of the JSON-LD context file if we ever needed to change the domains of the namespaces (which probably negates the need to use a purl URI in the first place, come to think of it)
- But using the compact URIs leads to the inconsistency I noticed today

So I'm a bit stumped on how to move forward.  But I do think that, at a minimum, we should publish using either the compact URIs or the expanded URIs, but not a mix of both as noted in my second paragraph above.  I would probably lean towards the compact URIs, because they allow us to leverage the JSON-LD context file - but we would need to do it across the board.

I'm open to suggestions/ideas.

**Comment by philbarker** [comment]
> My instinct is to say that we should always publish full URIs, using the credreg domain (instead of purl)
...
> The JSON-LD expansion/compaction rules would suggest that our compact URIs should expand to purl URIs, not credreg URIs (at least in most cases)

It has to be the purl URL (expanded or not) because that is the identifier of the term. The credreg URI is a URL to which browsers are _redirected_  when the identifier is resolved. Ideally it would be a HTTP 303 "See Other" redirect to show that you were getting redirected to something other than the concept itself, but actually it's a 301 Moved.

I think that compact URIs which expand to PURLs are fine. FWIW, there is no reason for applications to be routinely resolving and downloading the term & concept definitions, the definitions should be cached.

**Comment by jeannekitchens** [comment]
The Credential Registry team had suggestions for handling this on the Registry side.  @siuc-nate created a Registry issue.  We'll discuss it further with Registry team next week. https://github.com/CredentialEngine/CredentialRegistry/issues/593

**Comment by siuc-nate** [comment]
This has been resolved in https://github.com/CredentialEngine/CredentialRegistry/issues/593
