### ISSUE TITLE
ceterms:dateEffective definition needs to be corrected. 

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#840]
https://credreg.net/ctdl/terms#dateEffective 

Current definition: Effective date of the content of a credential, assessment or learning opportunity.
Proposed definition: Effective date of the resource's content.

**Comment by stuartasutton** [comment]
Revised definition looks good; however, “this resource” as opposed to “the resource”.

**Comment by philbarker** [comment]
Looks good

**Comment by siuc-nate** [comment]
This change:
**Removal:**
> **Subject:** ceterms:dateEffective
> **Predicate:** rdfs:comment
> **Object:** "Effective date of the content of a credential, assessment or learning opportunity."

**Addition:**
> **Subject:** ceterms:dateEffective
> **Predicate:** rdfs:comment
> **Object:** "Effective date of this resource's content."

Has been made in pending CTDL and noted in the history tracking.
