### ISSUE TITLE
Add alternateName to the Learning Opportunity, Learning Program and Course Domains

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#844]
Currently https://credreg.net/ctdl/terms#alternateName domains are limited to Credential and Credential subclasses.  The Community College Growth Engine Fund (CCGEF) needs to collect the alternate names for programs from community colleges.  This is a viable use case applicable to colleges.  Minimally, need https://credreg.net/ctdl/terms#alternateName domains to include https://credreg.net/ctdl/terms#LearningProgram.  Are there any downsides to including https://credreg.net/ctdl/terms#LearningOpportunityProfile and https://credreg.net/ctdl/terms#Course?   I do not know of any downsides.  We have several colleges publishing now so need this change minimally to add domain of Learning Program ASAP.

**Comment by stuartasutton** [comment]
No nate, codedNotation would not work. What is being addressed here isn't a coded anything; it is an actual alternative name. 

I see no reason not to include it on ceterms:AssessmentProfile.

**Comment by siuc-nate** [comment]
Most likely - I would just like to see a few examples, as we do for everything else.

**Comment by jeannekitchens** [comment]
@siuc-nate here's the Guiding Questions used with micro-pathway designers and college faculty members.  They use the guide to fill in our bulk upload and publish, and note that the abbreviation is required.  https://docs.google.com/document/d/1qtiAi_kOADhR0QRwz5ggp1gOpZCWXev9/edit#

Please don't type in the above guide. It's shared with the CCGEF team and is a clean version.

**Comment by siuc-nate** [comment]
I see the abbreviation there for the "micro pathway", but I don't see one for the other items. Am I missing it?

**Comment by jeannekitchens** [comment]
With this example, we only need the abbreviation for the Learning Program, in this case the Micro-pathway.  I don't have an example for the other but there's no harm in adding them and if we don't do it now, we'll have to spend time doing it later.  Main thing is it's needed for Learning Program.

**Comment by philbarker** [comment]
I see no problem with extending alternateName to those classes. There could be a problem if it is used for identifiers / codedNotation, but there could also be a problem if identifiers / codedNotation are used for alternateNames,

**Comment by siuc-nate** [comment]
So we need to add ceterms:alternateName to the following classes, right?:
- ceterms:LearningOpportunityProfile
- ceterms:Course
- ceterms:LearningProgram
- ceterms:Assessment

Any others?

**Comment by siuc-nate** [comment]
This change:

**Addition:**
> **Subject:** ceterms:alternateName
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:AggregateDataProfile ceterms:AssessmentComponent ceterms:AssessmentProfile ceterms:BasicComponent ceterms:CocurricularComponent ceterms:Collection ceterms:CollectionMember ceterms:CompetencyComponent ceterms:ComponentCondition ceterms:ConditionManifest ceterms:ConditionProfile ceterms:Constraint ceterms:ContactPoint ceterms:CostManifest ceterms:CostProfile ceterms:Course ceterms:CourseComponent ceterms:CredentialComponent ceterms:ExtracurricularComponent ceterms:FinancialAssistanceProfile ceterms:GeoCoordinates ceterms:HoldersProfile ceterms:Job ceterms:JobComponent ceterms:LearningOpportunityProfile ceterms:LearningProgram ceterms:Occupation ceterms:Pathway ceterms:PathwaySet ceterms:Place ceterms:PostalAddress ceterms:ScheduledOffering ceterms:Task ceterms:TransferIntermediary ceterms:TransferValueProfile ceterms:WorkExperienceComponent ceterms:WorkRole 

Has been made in pending CTDL and noted in the history tracking.

**Comment by mparsons-ce** [comment]
re: ceterms:HoldersProfile
Isn't this functionally obsolete? Or along with EarningsProfile and EmploymentOutcome, has been replaced by AggregateDataProfile.
We had removed the latter from the Registry API and finder years ago.
So is some designation needed somewhere (other than the Usage note on credreg)?
Otherwise EarningsProfile and EmploymentOutcome should be added to this wish list.

**Comment by siuc-nate** [comment]
We don't use those profiles anymore, but we never formally deprecated them in the schema.  Perhaps we should.

**Comment by mparsons-ce** [comment]
Also
- qdata:DataSetProfile
- qdata:DataSetTimeFrame

**Comment by stuartasutton** [comment]
Nate is there is a way to tell whether these terms were functionally deprecated prior to the CTDL going public? I would think that anything we got rid of before the first instance of CTDL was made public need not be tracked as formally deprecated.

**Comment by stuartasutton** [comment]
What? https://github.com/CredentialEngine/Schema-Development/issues/844#issuecomment-1254009846

**Comment by siuc-nate** [comment]
>qdata:DataSetProfile
>qdata:DataSetTimeFrame

Good catch, I added these. Something seems to be a bit fiddly with cross-schema connections in the schema management system. It may be related to the recent caching updates, but it might also be the way those terms are configured in QData.  I'd have to dig into it a little deeper to be sure.

>Nate is there is a way to tell whether these terms were functionally deprecated prior to the CTDL going public? I would think that anything we got rid of before the first instance of CTDL was made public need not be tracked as formally deprecated.

I'm pretty sure we launched CTDL with those three classes, though they saw little if any use, at least that we're aware of.
