### ISSUE TITLE
Tweak isNonCredit Definition and Update Domains

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#845]
Tweak the isNonCredit definition and update domains:

From: Resource carries or confers no official academic credit towards a program or a credential.
To: Resource carries or confers no official academic credit according to the provider of the resource.

- isNonCredit supported [Badge](https://credreg.net/ctdl/terms/Badge) Recognition designed to be displayed as a marker of accomplishment, activity, achievement, skill, interest, association, or identity.
- isNotCredit supported  [Digital Badge](https://credreg.net/ctdl/terms/DigitalBadge) Badge offered in digital form.
- isNotCredit supported  [Open Badge](https://credreg.net/ctdl/terms/OpenBadge) Visual symbol containing verifiable claims in accordance with the Open Badges specification and delivered digitally.
- isNonCredit supported  [Certificate](https://credreg.net/ctdl/terms/Certificate) Credential that designates requisite knowledge and skills of an occupation, profession, or academic program.
- isNonCredit supported  [Apprenticeship Certificate](https://credreg.net/ctdl/terms/ApprenticeshipCertificate) Credential earned through work-based learning and earn-and-learn models that meet standards and are applicable to industry trades and professions.
- isNonCredit supported  [Journeyman Certificate](https://credreg.net/ctdl/terms/JourneymanCertificate) Credential awarded to skilled workers on successful completion of an apprenticeship in industry trades and professions.
- isNonCredit supported  [Master Certificate](https://credreg.net/ctdl/terms/MasterCertificate) Credential awarded upon demonstration through apprenticeship of the highest level of skills and performance in industry trades and professions.
- isNonCredit supported  [Certificate of Completion](https://credreg.net/ctdl/terms/CertificateOfCompletion) Credential that acknowledges completion of an assignment, training or other activity.  A record of the activity may or may not exist, and the credential may or may not be designed as preparation for another resource such as a credential, assessment, or learning opportunity.
- isNonCredit supported  [Certification](https://credreg.net/ctdl/terms/Certification) Time-limited, revocable, renewable credential awarded by an authoritative body for demonstrating the knowledge, skills, and abilities to perform specific tasks or an occupation.  Certifications can typically be revoked if not renewed, for a violation of a code of ethics (if applicable) or proven incompetence after due process. Description of revocation criteria for a specific Certification should be defined using Revocation Profile.
- isNonCredit supported  [License](https://credreg.net/ctdl/terms/License) Credential awarded by a government agency or other authorized organization that constitutes legal authority to do a specific job and/or utilize a specific item, system or infrastructure and are typically earned through some combination of degree or certificate attainment, certifications, assessments, work experience, and/or fees, and are time-limited and must be renewed periodically.
- isNonCredit supported  [Micro-Credential](https://credreg.net/ctdl/terms/MicroCredential) Credential that addresses a subset of field-specific knowledge, skills, or competencies; often developmental with relationships to other micro-credentials and field credentials.
- isNonCredit supported [Diploma](https://credreg.net/ctdl/terms/Diploma) Credential awarded by educational institutions for successful completion of a course of study or its equivalent.

**Comment by siuc-nate** [comment]
While I object to this change, as it does not make any sense at all to me, I have made it in pending CTDL and noted it in the history tracking:

**Addition:**
> **Subject:** ceterms:isNonCredit
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Badge ceterms:DigitalBadge ceterms:OpenBadge ceterms:Certificate ceterms:ApprenticeshipCertificate ceterms:JourneymanCertificate ceterms:MasterCertificate ceterms:CertificateOfCompletion ceterms:Certification ceterms:License ceterms:MicroCredential ceterms:Diploma
