### ISSUE TITLE
Updates to align multiple properties and correct issues including: ceterms:corequisite, ceterms:prerequisite, ceterms:entryCondition, ceterms:coPrerequisite, ceterms:requires

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#846]
Currently, [ceterms:prerequisite](https://purl.org/ctdl/terms/prerequisite) has no domains or ranges and should include both [ceterms:Course](https://purl.org/ctdl/terms/Course) and [ceterms:LearningOpportunity](https://purl.org/ctdl/terms/LearningOpportunity).

**Comment by siuc-nate** [comment]
This is intertwined with #771 and #831. We should look at these terms more holistically, I think, and determine the best course of action.

**Comment by stuartasutton** [comment]
That's OK, but it should be done ASAP since we are working on LearningProgram etc involving Course.

**Comment by siuc-nate** [comment]
Regarding the above, I have some objections:
- As we discussed, I do not think it makes sense to have redundant means of indicating a course as a prerequisite.
  - The entire ceterms:prerequisite property could be dropped and no functionality would be lost, as all of it could be accommodated via ceterms:entryCondition.
  - If it is necessary to retain the "term of art" (the word "prerequisite" independent of its definition), then leave that word in the definition for entryCondition, drop the prerequisite property entirely. This would simplify the usage of the term and negate the need for the complicated usage notes that are proposed as additions to the other terms.
  - It creates unnecessary complexity for publishers of the data
  - It creates unnecessary complexity for consumers of the data
  - All of these costs, for what **tangible** benefit?

- The addition of a comment (dcterms:description) to ceterms:requires: 
  - It does not follow the established patterns we use in the rest of the schema, and 
  - It is redundant with the subproperty indications provided by the other terms. 
  - It introduces a maintenance concern if those relationships change, or if properties are added/removed.
  - In our meeting, the justification for this was that people might not read the schema to be aware of these terms. I don't think that is sufficient justification, as it has never been a problem with any other sub/superproperty set in our schema. 

- The addition of a usage note to ceterms:requires:
  - Properties should describe themselves, and not be used to describe other properties (that should be the responsibility of those properties).
  - This addition is redundant with the definitions/comments on those other properties.
  - This addition leaves out ceterms:coPrerequisite and ceterms:corequisite, which are equally important as ceterms:prerequisite and ceterms:entryCondition.
  - It introduces a maintenance concern if those relationships change, or if properties are added/removed.
  - Describing these distinctions should be something that goes in the handbook, where the nuances can be fleshed out and examples given. Trying to shoehorn subtle differentiations between four properties into a usage note for a fifth property is the wrong approach.

**Comment by philbarker** [comment]
@siuc-nate that looks like what we discussed on Tuesday. Thanks

**Comment by stuartasutton** [comment]
Phil, can you clarify your https://github.com/CredentialEngine/Schema-Development/issues/846#issuecomment-1262056145 above. Are you referring to Nate's https://github.com/CredentialEngine/Schema-Development/issues/846#issuecomment-1261426973 or Nate's https://github.com/CredentialEngine/Schema-Development/issues/846#issuecomment-1261436959. It makes a big difference.

**Comment by philbarker** [comment]
I was referring to both, Stuart: the changes look like what we agreed, and Nate's objections look like those we considered.

**Comment by stuartasutton** [comment]
I may be confused because Nate first gives us the outcome and then objects in his second post. Have the objections been put to rest or not?Sent from my iPhoneOn Oct 1, 2022, at 4:18 AM, Phil Barker ***@***.***> wrote:﻿
I was referring to both, Stuart: the changes look like what we agreed, and Nate's objections look like those we considered.

**Comment by siuc-nate** [comment]
They have not, but I wanted to list the changes, as they stand currently, in their own post so that my objections don't get interwoven with them and lead to confusion - at least, that was what I was trying to do.

**Comment by stuartasutton** [comment]
In order not to have to return to [ceterms:prerequisite](https://purl.org/ctdl/terms/prerequisite) immediately after these discussions are concluded, we need to also consider the addition of [ceterms:ConditionProfile](https://purl.org/ctdl/terms/ConditionProfile) to its range. This proposal stems from earlier discussions (at Phil's suggestion) that aspects  of the model for [ceterms:PathwayComponent](https://purl.org/ctdl/terms/PathwayComponent)s conditions and constraints are also applicable to [ceterms:Course](https://purl.org/ctdl/terms/Course) and [ceterms:LearningOpportunity](https://purl.org/ctdl/terms/LearningOpportunity) through [ceterms:ConditionProfile](https://purl.org/ctdl/terms/ConditionProfile):

1. [ceterms:hasConstraint](https://purl.org/ctdl/terms/hasConstraint)  
2. [ceterms:logicalOperator](https://purl.org/ctdl/terms/logicalOperator)
3. [ceterms:Constraint](https://purl.org/ctdl/terms/Constraint) 

The Hutchison Welding Technology prerequisites for course EN101: English Composition II illustrate the need:

>Prerequisites: EN101 English Composition IA with a grade of C or higher, or EN101H English Comp IA with a grade of C or higher, or EN100 English Comp IB with a grade of C or higher.

Slight tweaks to the definitions of affected properties are likely necessary.

**Comment by jeannekitchens** [comment]
The final proposal was updated today based on a discussion of the comments https://github.com/CredentialEngine/Schema-Development/issues/846#issuecomment-1261426973

**Comment by siuc-nate** [comment]
The changes from [this post](https://github.com/CredentialEngine/Schema-Development/issues/846#issuecomment-1261426973) have been made in pending CTDL and noted in the history tracking.
