### ISSUE TITLE
Add a domain of ceterms:Course to ceterms:assesses  

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#849]
Currently, [ceterms:Course](https://purl.org/ctdl/terms/Course) has a [ceterms:teaches](https://purl.org/ctdl/terms/reaches) property, but not a [ceterms:assesses](https://purl.org/ctdl/terms/assesses) property. Most courses that teach a competency also assess whether that competency has been achieved. So, [ceterms:assesses](https://purl.org/ctdl/terms/assesses) needs to have [ceterms:Course](https://purl.org/ctdl/terms/Course) added as a domain.

To avoid duplication of the range, perhaps creating a new ceterms:teachesAndAssess property is in order.

**Comment by siuc-nate** [comment]
Would it make more sense to extend the definition of ceterms:teaches to indicate that the competency is likely also assessed? I am hard-pressed to think of a case where something would teach a competency but _not_ assess it in some way.

**Comment by siuc-nate** [comment]
Separating this issue from #851:

Proposal:
**Add:**
> **Subject:** ceterms:assesses
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:LearningOpportunityProfile, ceterms:LearningProgram, ceterms:Course

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
