### ISSUE TITLE
Add LearningProgram to the domain of degreeConcentrations property

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#850]
Currently, [ceterms:degreeConcentration](https://purl.org/ctdl/terms/degreeConcentration) only lists credentials as domain. Concentrations, while transcriptable on credentials, are really more critical to the description of learning programs (and related classes). 

Add 
> [ceterms:LearningProgram](https://purl.org/ctdl/terms/LearningProgram), [ceterms:LearningOpportunity](https://purl.org/ctdl/terms/LearningOpportunity) and [ceterms:LearningOpportunityProfile](https://purl.org/ctdl/terms/LearningOpportunityProfile) to the [ceterms:degreeConcentration](https://purl.org/ctdl/terms/degreeConcentration) property.

**Comment by siuc-nate** [comment]
Per our 2022-11-29 meeting:
- This will just be degreeConcentration for now
- We will determine the range of degreeConcentration in a separate issue

**Add:**
> **Subject:** ceterms:degreeConcentration
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:LearningProgram, ceterms:LearningOpportunityProfile

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
