### ISSUE TITLE
Create a new teachesAndAssesses property to the ceterms:Course class

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#851]
Currently, [ceterms:Course](https://purl.org/ctdl/terms/Course) is the domain of the [ceterms:teaches](https://purl.org/ctdl/terms/teaches) property. However, most courses [ceterms:assesses](https://purl.org/ctdl/terms/assess) the competencies that they teach (even where there is a post-course required for assessment by a certifying body). 

Proposal: 
1. Extend the domain of [ceterms:Course](https://purl.org/ctdl/terms/Course) to include [ceterms:assesses](https://purl.org/ctdl/terms/assesses); 
2. Consider the creation of a new ceterms:teachesAndAssesses so all of the following are covered where the resource:
* both teaches and assesses;
* only teaches;
* only assesses.

**Comment by philbarker** [comment]
Depending on how much detail is required, another approach might be worth considering. Most courses do have one or more assessment component, and it's often important to students and accrediting bodies to how each learning objective is assessed. That is, what is assessed by exam, what is assessed through continual assessment / teacher observation, what is assessed through coursework/essays/set tasks etc; furthermore, it matters whether the assessment is diagnostic, formative or summative. Given this just saying that a course includes an element of assessment of such-and-such competence seems minimal. I would suggest using the targetAssessment property to link Assessments to the Course, and attaching assesses properties to that. If you want to keep targetAssessment for external summative assessments, then a new property includesAssessment would do.

We might also consider whether teachesAndAssesses is better expressed as hasLearningObjective (read: should teach and asses).

**Comment by stuartasutton** [comment]
Interesting, Phil. I think your opening phrase is key for me: "Depending on how much detail is required." So, any of your suggestions work "depending"; although I am not enamored with hasLearningObjective particularly when teaches is available. Maybe best to just add assesses and leave it at that.

**Comment by siuc-nate** [comment]
Just keep in mind the hurdles some of that would incur for both publishers and consumers of data.  We have trouble getting some really basic info from some publishers, so while it might make semantic sense to have all that in the schema, that also means we'd need to implement ways of publishing, handling, searching, displaying, etc. that which might never actually get used because the source data detail (and/or the will to provide it) just isn't there.

**Comment by siuc-nate** [comment]
More to the point: I think ceterms:teachesAndAssesses makes sense, but it's a little clunky (albeit very clear).  ceterms:hasLearningObjective is a little more ambiguous (which can be useful in its own way) but flows better.  I don't have a strong preference (or an alternative suggestion) at the moment.  I think it's something that might see enough use to be worthwhile, and makes sense from a publishing perspective, but at the same time, I'm reluctant to agree with having yet another search route to get from some starting point to a competency, as that has a multiplicative effect on the way queries need to be written to handle all possible routes.  

Still, I think this is worth discussing.  Also, would this inevitably wind up getting added to credential as well?

**Comment by stuartasutton** [comment]
We have sort of conflated two different issues (my fault!): (1) ceterms:assesses having an additional domain of ceterms:Course; and (2) a new property asserting that something both teaches and assesses. After thinking about it a bit, we could take Phil's suggestion of a hasLearningObjective and define it as a super property with the existing ceterms:teaches and ceterms:assesses as subproperties makes sense

**Comment by siuc-nate** [comment]
How does this interact with #847 ?

**Comment by siuc-nate** [comment]
Archiving this, as it hasn't seen demand in a few years. Also, I think if we solve #847, we can just use teaches and assesses with that solution instead of needing an additional property here.
