### ISSUE TITLE
Alternatives to the whether conditions/constraints on courses are off LearningProgram or Course

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#853]
@@@
![Learning Program Relationships (2022-11-01)](https://user-images.githubusercontent.com/2939046/199305218-ee25ba41-c5c3-4d1a-83e6-756dde4c9aa9.png)

**Comment by siuc-nate** [comment]
I think I'm with Phil on this one.

**Comment by stuartasutton** [comment]
I have no problem with it either. As for programs that are parts of programs, I (think I) respectfully disagree.  How do you deal with the notion of "concentrations" with a program?

**Comment by siuc-nate** [comment]
What exactly do the connections look like when describing a concentration? Is it just a particular subset of courses within a program that are exclusive to that concentration (with prerequisites and other courses being shared among the concentrations)?  If that's the case, a program starts to look an awful lot like a pathway.  Perhaps a collection could be used here?

Actually, do different concentrations lead to different credentials, or to the same credential with some additional object that conveys "this person had this concentration"?  If the latter is the case, then is there any actual value in capturing which courses go with which concentration?

**Comment by stuartasutton** [comment]
>"Is it just a particular subset of courses within a program that are exclusive to that concentration (with prerequisites and other courses being shared among the concentrations)?"

No, the overall program leading to a degree has an array of courses that are sliced and diced across a set of concentrations although nothing precludes some courses being unique to a particular concentration.

>"If that's the case, a program starts to look an awful lot like a pathway."

Absolutely not a Pathway. The key distinguishing characteristic of a Pathway is mission--sequencing over time.  With the exception of course prerequisites (that we've solidly determined aren't pathways) there is absolutely no sequencing necessary to express a program or a program within a program (a concentration).

>"Actually, do different concentrations lead to different credentials, or to the same credential with some additional object that conveys "this person had this concentration"?"

It is the SAME credential. Sometimes, the credential certificate may state a concentration, but most do not.

>"Actually, do different concentrations lead to different credentials, or to the same credential with some additional object that conveys "this person had this concentration"? If the latter is the case, then is there any actual value in capturing which courses go with which concentration?"

There absolutely is a reason to capture this per-concentration course information--it's how students in a concentration plan their program and the basis of my assertion that concentrations can be effectively represented as programs within a program.

**Comment by siuc-nate** [comment]
>No, the overall program leading to a degree has an array of courses that are sliced and diced across a set of concentrations although nothing precludes some courses being unique to a particular concentration.

This sounds like what I was trying to say/ask with that, though perhaps my perception had more overlap between courses (e.g. general education stuff).

>It is the SAME credential. Sometimes, the credential certificate may state a concentration, but most do not.

One credential, with multiple tracks to earn it, then. It's hard to fend off the pathway analogies, but I'll try.

>There absolutely is a reason to capture this per-concentration course information--it's how students in a concentration plan their program and the basis of my assertion that concentrations can be effectively represented as programs within a program.

I am inclined to agree.  It's more specific than using a Collection, and has the convenience of already having been implemented in the schema.  It also works for cases where there are offramp and other related credentials that are part of a program, but not the main goal of that program.  We should probably throw that against all of the use cases/examples we've identified just to make sure it covers all of the bases.

**Comment by siuc-nate** [comment]
This came up in our Kansas meeting:
- Would it be a valid use case of a LearningProgram (as part of another LearningProgram) to be a listing of general education courses that get referenced from a variety of other Learning Programs? (I would think so)
- Would it be a valid use case of a LearningProgram (as part of another LearningProgram) to be a listing of a handful (say two or three) courses where the student must decide between those courses (e.g. pick one of two welding courses to fulfill x requirement), or is that level of detail strictly the responsibility of the pathway?

**Comment by jeannekitchens** [comment]
It is definitely a valid use case for multiple courses to be required or optional for many programs.  This is well established.  

The requirements for progressing through a Pathway are not the same as the requirements to enroll into a program. Didn't we discuss this at length in multiple meetings and that is why Condition Profile will be updated to support constraints?

**Comment by siuc-nate** [comment]
Per our meeting on 2023-01-17:
The Learning Program should be a simple inventory of what all is involved in the program; the conditions for earning a Credential should hang off of the Credential itself.

**Comment by siuc-nate** [comment]
Is there anything else to discuss with this one?

**Comment by philbarker** [comment]
I think we are done discussing it here, we seemed to reach consensus on the main point. We can close it as an issue, but still reference the conversation in ongoing work on Programs.
