### ISSUE TITLE
Duplication of Certification subClassOf Credential

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/Schema-Development#854]
On https://credreg.com/ctdl/terms/Certification#Certification

![image](https://user-images.githubusercontent.com/658047/199529396-4f5c9eb7-bbbf-4692-83a6-9b57d1aadd72.png)

and in [data view:](https://credreg.com/ctdl/terms/Certification/json?releaseID=20220930)

![image](https://user-images.githubusercontent.com/658047/199529614-3fc9c7b4-87b3-43db-a595-bfc1b91b7e9d.png)

**Comment by siuc-nate** [comment]
Will fix this when I get a chance

**Comment by siuc-nate** [comment]
Fixed
