### ISSUE TITLE
Add an esteemIndicator property to both the CredentialOrganization and LearningProgram (et al)

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#855]
One indirect indicator of the quality of education available through a particular [ceterms:CredentialOrganization](https://purl.org/ctdl/terms/CredentialOrganization) or specific "department" of an institution are publicly recognized indicators of esteem such as the formal recognition of the faculty (individually or in sum) such as: (a) the number of Nobel Prizes or MacArthur Fellows awarded faculty or graduates over time, and (b) faculty honored through National Academies membership, etc.. 

See examples: University of Washington, Facts: FY 2018 https://www.washington.edu/research/wp-content/uploads/2019/02/Fact-Sheet-FY2018.pdf). 

This proposal for a new esteemIndicator property picks up on a name-drop by Phil regarding how this attribute is characterized in the UK.

>**URI:** ceterms:esteemIndicator
**Label:** esteem indicator
**Definition:** The high regard in which the CredentialOrganization, its component units or its faculty are publicly held.
**Comment:** Examples of such recognition range from the number of Nobel Prizes, MacArthur Fellows  (Genius Awards) awarded to faculty honors through National Academies and Societies. 
**Domain:** ceterms:CredentialOrganization, ceterms:LearningProgram (et al)
**Range:**  rdfs:Literal/rdf:langString

**Comment by philbarker** [comment]
I think the definition should begin "Evidence of ...." or similar (-- it's an indicator, not the esteem itself)

**Comment by stuartasutton** [comment]
Makes sense, Phil.

**Comment by siuc-nate** [comment]
Is it meant to be a reference to the evidence itself (ie rdfs:Resource) or merely an rdf:langString claiming such evidence/esteem/etc exists?

**Comment by stuartasutton** [comment]
This ranges from a simple assertion of aggregate awards (e.g., 20 Nobel Prizes) to brief statements of specific awards (see for example the Nobel listings at chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.washington.edu/research/wp-content/uploads/2019/02/Fact-Sheet-FY2018.pdf).

**Comment by stuartasutton** [comment]
The esteemIndicator property should not be confused with the the much broader in scope notableAlumni (#857).

**Comment by stuartasutton** [comment]
Nothing precludes a skos:ConceptScheme; but it is also likely that the scope of those indicators is likely quite broad.

**Comment by siuc-nate** [comment]
@stuartasutton @philbarker I think this one just comes down to deciding on what the range should be.  I would lean towards skos:Concept (a bnode can be used if necessary), but I'm not knowledgeable enough about this particular topic to be 100% certain of that.

**Comment by philbarker** [comment]
Downside of using a skos:Concept is that some of the data will only be available wordy format, e.g. in total the Institute has been home to winners of 6 Nobel prizes in Sciences and 3 Fields Medals and a Perkins Medal, currently 2 Nobel Laureates are on the Faculty, while alumni and former researchers have won...  -- there's a lot there to unpack into different concepts without worrying about how to represent multiples.

**Comment by stuartasutton** [comment]
+1 on Phil’s comment.

**Comment by stuartasutton** [comment]
As for https://github.com/CredentialEngine/Schema-Development/issues/855#issuecomment-1340042777, the answer is no.  I meant the specific classes LearningProgram and CredentialOrgaization. Shouldn't have included "et al".

**Comment by siuc-nate** [comment]
Why not also ceterms:Organization and ceterms:QACredentialOrganization? Both of those could receive various kinds of awards.

**Comment by siuc-nate** [comment]
Archiving this, as it hasn't seen demand in a few years.
