### ISSUE TITLE
Include a notableAlumni property on CredentialOrganization

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#857]
Add a ceterms:notableAlumni property to ceterms:CredentialOrganization. This proposal settles on using "notable" (as does Google) as opposed "distinguished"--Wharton School of the University of Pennsylvania might list Donald Trump as "notable" but might get some pushback with characterizing him as "distinguished". So, in this usage, the term "notable" should not necessarily be equated with "distinguished" (maybe worthy of a comment).  

>**URI:** ceterms:notableAlumni
**Label:** notable alumni
**Definition:** Noteworthy alumnus of the institution.
**Domain:** ceterms:CredentialOrganization
**Range:** rdfs:Literal (rdf:langString)

**Comment by siuc-nate** [comment]
It depends on what definitions they use for "notable" and "distinguished", but if "notable" covers all the bases then that works for me.

Would this effectively just be an array of names, or would there be any other data points we need to capture here?

**Comment by stuartasutton** [comment]
I think an array of names. Obviously, google in listing the 'notables' includes an image...worth some discussion whether this best points to a Person class...

**Comment by siuc-nate** [comment]
Or, we could get the best of both worlds:
- Make the range of the property in the original post be ceterms:CredentialPerson, but disallow use of that property in the Registry
- Continue disallowing the use of ceterms:CredentialPerson in the Registry, as we do today
- Create a second property, something like "ceterms:notableAlumniListing" whose value is an xsd:anyURI (pending resolution of #822) referencing a webpage describing such alumni

That keeps the registry free of personal info while still giving the schema the capability to go into detail about the alumni in question.

**Comment by siuc-nate** [comment]
Archiving this, as it hasn't seen demand in a few years.
