### ISSUE TITLE
Add a facultyToStudent ratio property to DataProfile and to AggregateDataProfile

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#859]
For many students, the faculty-to-student ratio is important because it potentially signals the level of individual attention a student may expect from faculty and the potential level of student participation in course-related discourse. Different CredentialOrganizations have significantly different  ratios (e.g., Stanford: 5 students to 1 faculty member (5:1); and San Francisco State University: 21 students to 1 faculty member (21:1).  This ratio data fits in two different places in CTDL depending on the source of the data—both are reflected in the Domain below.  

Ratios may also be applicable for colleges, schools, and departments within a CredentialOrganization—i.e., there may be an institution-wide ratio as well as individual rations for sub-units of the CredentialOrganization.

>**URI:** qdata:facultyToStudentRatio
**Label:** faculty-to-student ratio
**Definition:** Ratio of the number of teaching faculty to the number of students.
**Comment:** What constitutes "teaching faculty" is up to the CredentialOrganization to determine and may include anyone with a significant, direct instructional role in interactions with students in learning activities.
**Domain:** qdata:DataProfile [distribution file], ceterms:AggregateDataProfile [bespoke local]
**Range:** rdfs:Literal (rdf:langString)

**Comment by siuc-nate** [comment]
I looked briefly and was a little surprised that there wasn't an xsd:ratio or schema:ratio data type, at least not that I could find.  Perhaps there's a math schema out there that would be suitable, but I couldn't find one. So I would think either xsd:string or rdf:langString makes sense as a value here.

**Comment by philbarker** [comment]
As far as maths is concerned, ratios are just integers divided one by the other. So if you want a maths way of saying there are 21 students per instructor, you will find `"21"^^xsd:decimal` works. Or, if you prefer to give the facultyToStudent ratio literally `"0.047619047619"^^xsd:decimal`

**Comment by siuc-nate** [comment]
Does that assume it's always an x:1 ratio? I would think it would be preferable to store whole numbers, as it avoids the need for calculation and makes it easier to other ratios like 7:3 or 2:5.

**Comment by philbarker** [comment]
No, except in special cases maths does not assume the denominator is always one :) 

I was just explaining why you probably won't find a specific data type for ratios.  So it has to be a string or a numeric format, and assuming it's not always an x:1 ratio means you need to use xsd:decimal or xsd:long or similar.

**Comment by siuc-nate** [comment]
I'd rather stick to xsd:string, since I don't think we'd be doing any operations on the data and using a string lets us store/report the data vebatim.  If we did need to use something like xsd:decimal, then perhaps it would be best to advise using something like `21.1` to indicate "21:1" since that at least avoids the need for any kind of calculation (though it would lead to a problem if we ever needed to handle a ratio where one or both of the numbers in that ratio had decimal points).

**Comment by siuc-nate** [comment]
Per our 2022-11-29 meeting:

Proposal:

Create:
> **URI:** qdata:facultyToStudentRatio
> **Label:** Faculty-to-Student Ratio
> **Definition:** Ratio of the number of teaching faculty to the number of students.
> **Comment:** What constitutes "teaching faculty" is determined by the Organization and may include anyone with a significant, direct instructional role in interactions with students in learning activities.
> **Usage Note:** The expression of the ratio should feature the number of faculty first, followed by the number of students, e.g., "1:10" to mean "one faculty per ten students".
> **Domain:** qdata:DataProfile, ceterms:AggregateDataProfile
> **Range:** xsd:string

@stuartasutton I did tweak a few things here and added a usage note. Please verify that this proposal works for you. Thanks.

**Comment by siuc-nate** [comment]
The above changes have been made in pending QData and noted in the history tracking.

I will close this thread pending @stuartasutton 's approval.
