### ISSUE TITLE
Update qdata:relevantDataSetFor to include missing ranges

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#860]
The [qdata:relevantDataSetFor](https://credreg.net/qdata/terms/relevantDataSetFor) only has a range of [ceterms:AggregateDataProfile](https://purl.org/ctdl/terms/AggregateDataProfile)  when it should also have as range [ceterms:HoldersProfile](https://purl.org/ctdl/terms/HoldersProfile), [ceterms:EarningsProfile](https://purl.org/ctdl/terms/EarningsProfile) and [EmploymentOutcomeProfile](https://purl.org/ctdl/terms/EmploymentOutcomeProfile)—see domain model below.

![qData Domain Model--Holder, Earnings   Employment drawio](https://user-images.githubusercontent.com/2939046/200142374-db201f1f-f216-4e73-b67b-97566cb9600f.png)

The [qdata:relevantDataSet](https://credreg.net/qdata/terms/relevantDataSet) has correct domains and ranges.

**Comment by siuc-nate** [comment]
Per [my response](https://github.com/CredentialEngine/Schema-Development/issues/861#issuecomment-1305814503) in #861, I would recommend deprecating those three profiles instead.  Otherwise, this makes sense.

**Comment by stuartasutton** [comment]
My comments on #861 remain the same. The AggregateDataProfile class is there for you to push everything through it for the Registry; but, don't push that result on the rest of the world. The model is OK as it stands.

**Comment by jeannekitchens** [comment]
@philbarker @siuc-nate @mparsons-ce we need to work on this issue.

**Comment by philbarker** [comment]
I would add the three classes to the range as Stuart suggested. I see no benefit to deprecating those classes.

**Comment by siuc-nate** [comment]
Per our 2023-09-26 meeting:
- We will add the three classes to the range of the property in CTDL
- We will continue to **not** use those classes in the Registry (instead using AggregateDataProfile)

**Comment by siuc-nate** [comment]
These changes have been made in pending QData and noted in the history tracking.
