### ISSUE TITLE
Update usage notes for EarningsProfile, EmploymentOutcomeProfile and HoldersProfile

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Schema-Development#861]
The usage notes for the following three properties are not appropriate for the CTDL description language. If you want to force everyone to use [ceterms:AggregateDataProfile](https://purl.org/ctdl/terms/ceterms:AggregateDataProfile) instead of, or in addition to, these more precise classes, then why did we create them in the first place. Usage notes as framed here ARE appropriate for an application profile (e.g., the Registry) that is limiting the available options...but not appropriate for a description language.

It would be OK to restate the usage notes to point out that a more general means is available through [ceterms:AggregateDataProfile](https://purl.org/ctdl/terms/ceterms:AggregateDataProfile) should they not need this level of precision to meet their needs.

**Earnings Profile**

>**URI:** [ceterms:EarningsProfile](https://purl.org/ctdl/terms/EarningsProfile)
**Definition:** Entity that describes earning and related statistical information for a given credential.
**Usage Note:** The use of [ceterms:AggregateDataProfile](https://purl.org/ctdl/terms/ceterms:AggregateDataProfile) instead of this class is strongly recommended.

**Employment Outcome Profile**

>**URI:** [ceterms:EmploymentOutcomeProfile](https://purl.org/ctdl/terms/EmploymentOutcomeProfile)
**Definition:** Entity that describes employment outcomes and related statistical information for a given credential.
**Usage Note:** The use of [ceterms:AggregateDataProfile](https://purl.org/ctdl/terms/ceterms:AggregateDataProfile) instead of this class is strongly recommended.

**Holders Profile**

>**URI:** [ceterms:HoldersProfile](https://purl.org/ctdl/terms/HoldersProfile)
**Definition:** Entity describing the count and related statistical information of holders of a given credential.
**Usage Note:** The use of [ceterms:AggregateDataProfile](https://purl.org/ctdl/terms/ceterms:AggregateDataProfile) instead of this class is strongly recommended.

This issue is related to #860.

**Comment by siuc-nate** [comment]
>The usage notes for the following three properties are not appropriate for the CTDL description language.

They were intended to be temporary (see below)

>If you want to force everyone to use [ceterms:AggregateDataProfile](https://purl.org/ctdl/terms/ceterms:AggregateDataProfile) instead of, or in addition to, these more precise classes, then why did we create them in the first place.

AggregateDataProfile didn't exist when they were created.  It was created as [a way to simplify capturing that kind of data](https://github.com/CredentialEngine/Schema-Development/issues/756), along with a raft of QData-related changes.

>Usage notes as framed here ARE appropriate for an application profile (e.g., the Registry) that is limiting the available options...but not appropriate for a description language.

We very nearly deprecated them, but [according to this post](https://github.com/CredentialEngine/Schema-Development/issues/756#issuecomment-784457132), the next step was to "Consult with TAG and states (i.e., Kansas, Illinois, WA, and NJ) to determine any other tweaks and whether or not the following should be deprecated EarningsProfile, OutcomeProfile, and EmploymentOutcomeProfile."

@jeannekitchens Did such consultation ever happen? If not, is it still relevant? We've been using AggregateDataProfile for some time now and haven't seen any demand for the three more specific profiles.

I would recommend deprecating those three profiles instead.

**Comment by stuartasutton** [comment]
@siuc-nate, do what you will; but, throwing away precision for simplicity is a pretty lame reason.

**Comment by siuc-nate** [comment]
I don't think we lose any precision in this case, given how AggregateDataProfile was setup.  Complexity where simplicity will do is also not a great approach.

**Comment by jeannekitchens** [comment]
@siuc-nate either raise this for discussion or, if it's not going to be implemented, close it.  Thank you.

**Comment by siuc-nate** [comment]
My recommendation is still to deprecate HoldersProfile, EmploymentOutcomeProfile, and EarningsProfile, since their functionality has been combined into AggregateDataProfile.

**Comment by philbarker** [comment]
@siuc-nate is every adopter of CTDL going to go the same route as the Registry and use not distinguish between the two types of profile?

**Comment by siuc-nate** [comment]
I would hope so. I don't see the value in splitting those particular pieces of data up into 3 separate classes (especially considering they all then have to have boilerplate properties like name, description, etc, that mean those three classes really only exist for a handful of unique properties that all also exist in AggregateDataProfile anyway).

**Comment by philbarker** [comment]
I can see a lot of people wanting to know what type of data was being provided and being told it is a "Resource containing summary statistical data" doesn't do that.

**Comment by siuc-nate** [comment]
This hasn't been a pressing matter for quite some time.  See also #941
