### ISSUE TITLE
Potential new concept scheme for Associate Degree Credentials 

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#862]
CTDL / CTDL ASN currently only provide a way to link to concept schemes/concepts that aren't CTDL vocabularies to competency frameworks/competencies and collections of competencies. Is there a reason for this?  Seems to me we should be able to use a property e.g, hasConceptScheme with credentials, learning opps, etc...

For the state of Texas, we have an issue to resolve in a timely manner.

From the State of Texas, this is only applicable to Community College degree programs.   They have to be able to query on this. 

In their system,  it’s called “degree type”.  

- "Academic Associate Degree" (concept) defined as: An academic associate is designed for transfer to a baccalaureate degree. 
- "Applied Associate Degree" (concept) defined as: An applied associate is designed for immediate employment. Another term for applied associate is 'technical associate'. 

A primary reason for distinguishing between these types is that outcome measures differ. A key measure for academic associates is whether graduates are found enrolled in a 4-year institution following graduation, while a key measure for applied associates is whether graduates are found employed following graduation.

Looking through our concept schemes, I don't see a place to add this.  We have a credential type concept scheme but it's for pathways. Or, could we put it there but only allow selecting those two concepts from the scheme for credentials?

Identifier Value https://credreg.net/ctdl/terms#IdentifierValue could potentially work for this but it wouldn't include the definitions so only people who know what this means would find this data useful.  They are queuing up thousands of credentials to publish now.

**Comment by philbarker** [comment]
Also note that we have Bachelor Degree, but not all the flavours of BSc/BS, BEd, BA, LLB, BD, MA (Scot/Cantab/Oxon) -- yes that last one is a Bachelors degree by our definition.

Options are 

- Add more specific types of credential under the credential type hierarchy, continuing as we started, as used by OB v3.
- Extend the domain of [ceterms:classification](https://purl.org/ctdl/terms/classification) to all types of credential and use a skos concept scheme.

 [definitely not a Identifier Value because this is showing membership of a grouping of things not identifying an individual]

**Comment by stuartasutton** [comment]
I think I have been clear as to where I'd go with this in terms of class and not some concept in a concept scheme. I do not think that that means that all fringe characterizations need to be accommodated.

**Comment by jeannekitchens** [comment]
I think it would be problematic to consider applied and academic as credential classes as it's very likely that other states, and countries, would not use that terminology with the degree names.  In this case, I do not believe, but I have an email in to Texas to verify, that degrees are conferred as, for example, an Applied Associates Degree in French.  Rather it's an attribute necessary in reporting and other systems.  I've looked at Texas community college websites and associates degrees are just associates degrees, they're not applied or academic on public web pages.

**Comment by stuartasutton** [comment]
Jeanne, good. We may learn more from Texas. But, if they are actual degrees, we do have an actual parallel in CTDL with the Academic and Professional Doctorates as subclasses of Doctorate?

**Comment by stuartasutton** [comment]
Also, while this may seem like a particular/fringe case, it is not. As Jeanne notes in her opening test above, one characteristics of this bifurcation at the associates level is the transferability of the degree. Many/most community colleges differentiate between credentials that are transferable and those that are not. This is tangentially related to the "non-transcriptability" issue raised separately.

**Comment by siuc-nate** [comment]
We have contacts at a number of other states.  We should find out what, if anything, they do here, and find an approach that works across states.  We would not want 50 slightly-different approaches all merged together in CTDL (which would defeat the purpose of CTDL - comparability of the data).

I would suggest adding ceterms:classification to the existing Credential classes, and allowing publishers to pick the CTDL credential type that most closely matches their data (again for comparability) and then express any highly specific subtyping via custom concepts associated via the classification property.

**Comment by siuc-nate** [comment]
@jeannekitchens If this is just something Texas needs for query purposes, and they need it right now, then they should use specific keywords. That's supported right now with the current implementation and wouldn't be much different query-wise vs looking for a concept (regardless of property).

**Comment by jeannekitchens** [comment]
From State of Texas:

In general, there are three types of associate degrees:
 
Associate of Arts (A.A.) – academic (transfer) associate
Associate of Science (A.S.) – academic (transfer) associate
Associate of Applied Science (A.A.S) – applied (technical) associate
 
Applied associate degrees—also called technical associate degrees—are typically found in technical/science/health areas. I would not expect to find an applied associate degree in the field of French. However, in the field of Environmental Science and Technology, institutions could offer academic or applied associate degrees. An example of this is found on Austin Community College's website.
 
[Environmental Science and Technology | Austin Community College District (austincc.edu)](https://www.austincc.edu/academic-and-career-programs/areas-of-study/science-engineering-and-math/environmental-science-and-technology)
 
ACC offers three associate degrees in Environmental Science and Technology (one academic and two applied):
 
Associate of Science, Environmental Studies
Associate of Applied Science, Conservation Science and Wildlife Management
Associate of Applied Science, Environmental Technology
 
In the area of Drama, ACC offers an academic associate and two applied associates ([Drama | Austin Community College District (austincc.edu)](https://www.austincc.edu/academic-and-career-programs/areas-of-study/arts-digital-media-and-communications/drama)):
 
Associate of Arts, Drama
Associate of Applied Science, Technical Theater - Makeup Artistry and Costume Technology Specialization
Associate of Applied Science, Technical Theater - Scenic Construction, Lighting, and Media Technology Specialization
 
Note that "Applied" is a part of the award name for applied associate degrees (i.e., A.A.S., as opposed to A.S., or A.A.). Academic associate programs will include more general education courses than applied associate programs, where the focus is on courses within the field, so that the student can immediately find work upon graduation. In general, in Texas, when a student with an academic associate degree transfers to a four-year institution, the receiving institution is required by state statute to accept the general education requirements as complete. If a student transfers with an applied associate, however, the student will likely be required to take additional general education coursework.
 
Here is an example from a community college in New York. Note that associate degrees are separated into the three types (A.A.S., A.S., A.A):
 
[Academic Programs – BMCC (cuny.edu)](https://www.bmcc.cuny.edu/academics/programs/)

CEDS Definitions https://ceds.ed.gov/CEDSElementDetails.aspx?TermxTopicId=57607 
IPEDS Definitions https://nces.ed.gov/ipeds/use-the-data/survey-components-glossary/7#:~:text=An%20award%20that%20requires%20completion%20of%20an%20organized%20program%20of,requirements%20of%20a%20master's%20degree. 
U.S Dept. of Education Definitions 
NCES Definitions https://nces.ed.gov/programs/raceindicators/glossary.asp#:~:text=Associate's%20degree%20A%20degree%20granted,cooperative%20or%20work%2Dstudy%20program. 
[US Dept of Ed (2008) ](https://www2.ed.gov/about/offices/list/ous/international/usnei/us/associate.doc)An associate degree can be defined as “An award that requires completion of an organized program of study of at least 2 but less than 4 years of full-time academic study or more than 60, but less than 120 semester credit hours” (NCES).  Unlike certificate and diploma programs, the associate degree is a recognized higher education degree.  Most associate degrees earned in academic programs are Associate of Arts (AA) or Science (AS) degrees.  Associate degrees earned in professional, technical or terminal programs are frequently called Associate of Applied Science (AAS) degrees, but will sometimes carry the name of the program of study in the title.

**Comment by siuc-nate** [comment]
I don't think we want to end up having a separate credential type for every combination of degree level and subject (that's what those properties are for).

**Comment by jeannekitchens** [comment]
There are numerous website that cover the difference between Associate of Arts (A.A.) and Associate of Science (A.S.).  They are all in agreement, both are general transfer degrees with the difference being the focus of study and thereby course requirements. 

Associate of Arts (A.A.) - College/university award for students typically completing the first one to two years of post secondary school education intended to focus study on social science, humanities or liberal arts. 
Associate of Science (A.S.) - College/university award for students typically completing the first one to two years of post secondary school education intended to focus study on math and science. 

https://www.ccccurriculum.net/degrees/
https://www.saintleo.edu/about/stories/blog/aa-vs-as-degree-similarities-and-differences
https://helenacollege.edu/student_support_center/advising/aa_as_dif.aspx
https://www.stanly.edu/future-students/educational-offerings/associate-arts/associate-degrees-arts-or-science-how-they-work
https://www.dmacc.edu/advising/Pages/understandingdegrees.aspx
https://www.fnu.edu/associate-science-vs-associate-arts-degree-difference/
https://www.gcu.edu/blog/gcu-experience/associate-arts-vs-associate-science
and it goes on and on...

**Comment by siuc-nate** [comment]
Are there any other "Associate of _____" to account for?
Does this also apply to the other degree levels (e.g. "Bachelor of Arts", "Bachelor of Science", etc)?
What is the point of the audience level and subject properties (and other such properties) if we're just going to combine everything into `@type`?

**Comment by philbarker** [comment]
>Are there any other "Associate of _____" to account for?

For the US, Wikipedia [says](https://en.wikipedia.org/wiki/Associate_degree#United_States) that "The two most commonly awarded associate degrees are the Associate of Arts (sometimes Associate in Arts) (AA) and Associate of Science (sometimes Associate in Science) (AS) degrees" and that 
"Common associate-level degree titles include:

- Associate of Arts (AA)
- Associate of Science (AS)
- Associate of Applied Arts (AAA)
- Associate of Applied Science (AAS) "

The reference for both is Education USA. US Department of Education. ([doc](https://www2.ed.gov/about/offices/list/ous/international/usnei/us/associate.doc))

> Does this also apply to the other degree levels (e.g. "Bachelor of Arts", "Bachelor of Science", etc)?

There is a lot more variety in Bachelor level degrees: BSc, BA are the most common, but  also BEng (Engineering), BD (divinity), LLB (law), MB (medicine) ChB (surgery) BArch (Architecture) and a plethora of "let's just put the subject in the degree title" like BScIT (IT), BEcon / BScEcon.

> What is the point of the audience level and subject properties (and other such properties) if we're just going to combine everything into @type?

Consider that Archaeology [at Boston is a BA](https://www.bu.edu/archaeology/academics/undergraduate-program/ba-in-archaeology/), but  [at Wisconsin is a BS](http://catalog.uwlax.edu/undergraduate/archaeology/major-archaeological-studies-bs/).
Consider the [BA in Chemistry offered by ASU](https://asuonline.asu.edu/online-degree-programs/undergraduate/ba-chemistry/)
Consider that at about the same level as an associates degree, there are eight different types of award in Scotland, depending on context and length of study.

**Comment by jeannekitchens** [comment]
Can we either have a proposal or two, or more, for pros and cons.  Currently,  the Credential Types concept scheme is only for Credential Pathway Components.

**Comment by siuc-nate** [comment]
I think we need to get a more comprehensive listing of what all of these kinds of degrees are that we want to capture, and then work out the best way to atomize them into parts that we can then compare to the schema to see where the gaps are.  These institutions wrap a lot of attributes into the name/type/etc of the degree itself, but our schema is designed to put a lot of that data into other properties besides `@type`.

We want our schema to be a collection of lego bricks out of which any of these things can be constructed (as this will lend itself to scaling and expansion in the future); we do not want our schema to be a collection of completed lego sets that have nearly identical bricks in slightly different configurations, as that will not scale well at all.

We have two or three other threads on other suggested types of credentials that need similar atomization and comparison against each other and against the contents of this thread.  I will create a spreadsheet to try to find a starting point.

**Comment by stuartasutton** [comment]
![Credential Ontology](https://user-images.githubusercontent.com/2939046/207373782-1edd785c-1e7f-4e1f-b66c-7a22a1303a90.png)

**Comment by siuc-nate** [comment]
There are a number of usage notes that say "Use the name property to capture local variations on what this class covers."

Name alone is probably not enough.  I would suggest at least "name" and "subject", or broadening it to just say "Use the other properties to capture local variations on what this class covers"

**Comment by philbarker** [comment]
I think the usage note is there to capture a particular issue with the folk who have a degree called "Bachelor of Chemistry" or some such. We want to tell them that that is the name not the type. We've got to hope they would put the subject as Chemistry without any further guidance.

**Comment by siuc-nate** [comment]
I forgot to mention it here, but the updates listed in the google doc above have been made in CTDL and noted in the history tracking.

**Comment by mparsons-ce** [comment]
@jeannekitchens @siuc-nate 
Does this mean the Assistant API, etc. can now be updated to handle the new types?

**Comment by jeannekitchens** [comment]
@mparsons-ce I believe so using the most current list in the proposal that include Specialist Degree https://docs.google.com/document/d/1bn4N-8WLaN3dKyQuGpx7U0oRz-sQMQfbkWefTD67rdw/edit#heading=h.h96iw8k2hcnv

**Comment by siuc-nate** [comment]
@mparsons-ce Right, sounds good to me.
