### ISSUE TITLE
Enable referencing lists of entities in a Pathway

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/Schema-Development#871]
Per our 2023-03-28 meeting:

- It is overly cumbersome to create a Competency Component for every Competency when there are many Competencies that need to be explicitly listed in a Pathway (when for whatever reason it is not sufficient to simply rely on the links in the linked data to do so)
- There may be cases where it is useful to reference a pre-existing (or reusable) list of entities such as Competencies, Courses, etc. (e.g. general education courses)
- The functionality to reference an external pathway technically already exists in the schema, but is not reflected in our implementations

In terms of the schema, I believe there may be a two-part solution to this:
- Create a class of component intended to reference an **existing, external** list of objects (e.g. Collection, Competency Framework (which is a subclass of Collection)) so that its members do not need to be reenumerated (and maintained if the source ever changes) in a Component
- One of these two options:
  - Create a class of component which **itself** provides the list of entities, and is likely unique to a given Pathway, or
  - Update the implementation of the existing ___Component classes to make their `proxyFor` properties multi-value

For the first part, I suggest a new class and property:
> **URI:** ceterms:CollectionComponent
> **Label:** Collection Component
> **Definition:** Resource that is a proxy for the entities contained in or referenced by an external Collection, Framework, or other such list, or for the list itself.
> **Usage Note:** Completion or satisfaction of this Component entails completion or satisfaction of all members of the referenced list, unless otherwise indicated by Constraints, or other relevant information.
> **Properties:** asn:hasProgressionLevel, ceasn:hasChild, ceasn:isChildOf, ceterms:alternateName, ceterms:componentDesignation, ceterms:ctid, ceterms:description, ceterms:hasCondition, ceterms:identifier, ceterms:isDestinationComponentOf, ceterms:isPartOf, ceterms:name, ceterms:precededBy, ceterms:precedes, ceterms:proxyFor, ceterms:sourceData, ceterms:subjectWebpage

For the second part, I suggest either making the existing proxyFor property in the ___Component classes (including Collection Component) be multi-value (though we would need to figure out what all of the ramifications of that would be), **or** creating a generic class where proxyFor is multi-value:
> **URI:** ceterms:MultiComponent
> **Label:** Multi Component
> **Definition:** Resource that is a proxy for multiple entities.
> **Usage Note:** Completion or satisfaction of this Component entails completion or satisfaction of all entities for which this Component is a proxy, unless otherwise indicated by Constraints, or other relevant information.
> **Properties:** asn:hasProgressionLevel, ceasn:hasChild, ceasn:isChildOf, ceterms:alternateName, ceterms:componentDesignation, ceterms:ctid, ceterms:description, ceterms:hasCondition, ceterms:identifier, ceterms:isDestinationComponentOf, ceterms:isPartOf, ceterms:name, ceterms:precededBy, ceterms:precedes, ceterms:proxyFor, ceterms:sourceData, ceterms:subjectWebpage

Important: If we go the "every proxyFor is multi-value" route, then it would probably be more appropriate to create a **requiredProxies** property along with adding similar usage notes(?) where appropriate.  There would be a lot of potential for unintended consequences, many of which we may not run into for a while.

Lastly, the notion of referencing a PathwayComponent from an external Pathway is already supported in the schema, but our implementations don't allow for this. We should need to make sure our implementations enable this functionality, so that a Pathway for something common to multiple other Pathways (such as general education courses) can be reused in those other Pathways.

An example of all of this in action is shown below:
![image](https://user-images.githubusercontent.com/21346519/228318607-441cab28-d35b-4035-adc8-c8ac5d592fad.png)

**Comment by siuc-nate** [comment]
One other thing we need to explore:
>(when for whatever reason it is not sufficient to simply rely on the links in the linked data to do so)

What exactly would these cases be, and why is linked data as-is not sufficient to meet them? Is this just a UI problem (e.g. things could be floated up in the display) or is this actually something that requires a CTDL change?  Every time data is created, it also needs to be maintained, and creates different alternatives for search queries that searchers have to be aware of, etc.

**Comment by siuc-nate** [comment]
@philbarker Would like to get your thoughts on this as well

**Comment by philbarker** [comment]
@siuc-nate @jeannekitchens Have you considered a fix on the other side of the problem: if there are many competencies that need to be referenced, create a [ceasn:Competency](https://credreg.net/ctdlasn/terms/Competency) that is [ceasn:comprisedOf](https://credreg.net/ctdlasn/terms/comprisedOf) the many competencies that need to be referenced? The semantics are different form Collection. Collection is just a bag of competencies that are possibly related by no other fact than being in the same collection, whereas comprisedOf indicates that the main competency includes whatever the sub-competencies specify.

I am kind of nervous about changing something so fundamental in Pathways as the components from which they are built. What would be the interpretation of component conditions and constraints if one of the a single components references a Collection or or is a proxy for multiple things?

**Comment by siuc-nate** [comment]
>Have you considered a fix on the other side of the problem...

We don't currently have tooling that enables creation of free-floating Competencies outside of a Competency Framework or a Collection, so I don't think that would work from an implementation standpoint.  Also we haven't really defined whether or not RSDs are permitted to "contain" other RSDs or not. I don't think that has come up.  Also what about ceasn:hasChild? That seems like the more natural property rather than ceasn:comprisedOf.

>I am kind of nervous about changing something so fundamental in Pathways as the components from which they are built.

the consensus seems to be that we do not want to make ceterms:proxyFor be a multi-value property for all of the other components (we will instead create MultiComponent with a multi-value proxyFor).  CollectionComponent/MultiComponent would be treated as black boxes, so 
```
(X Component)-[hasCondition]->(ComponentCondition requiredNumber: 1)-[targetComponent]->(CollectionComponent)
```
Would work the same as it would if the thing on the end were any other kind of component (so no "peering into" the contents of the collection to pick one of its members; the entire thing/all of its members are required).  

An earlier version of this proposal had an additional property, `ceterms:requiredMembers`, which was intended to allow a CollectionComponent/MultiComponent to provide a full list and then require x items from it, but we thought that might get too confusing.  I am open to reexploring that, but I think the goal is to simplify the representation of a flat list of items, not to accidentally build a nested pathway inside of a component.

**Comment by siuc-nate** [comment]
Per our 2023-9-15 meeting:

CollectionComponent and MultiComponent as shown in the first post have been added to pending CTDL and noted in the history tracking.
