### ISSUE TITLE
Need targetJob property

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#873]
Need a ceterms:targetJob property with a range that includes Credential and Credential subclasses, Learning Opportunity and Learning Program minimally.

**Comment by siuc-nate** [comment]
I take it from the context of the meeting that led to this that what you would want is a way to get from a Credential to a Job via a Condition Profile as we do with other top-level classes, e.g.:

> **URI:** ceterms:targetJob
> **Label:** Target Job
> **Definition:** Job that is the focus of a resource.
> **Domain:** ceterms:ConditionProfile
> **Range:** ceterms:Job

That would enable a path like
`Credential > isRequiredFor > ConditionProfile > targetJob > Job`

**Comment by philbarker** [comment]
Job seems very specific as opposed to Occupation. Is the use case about in-house training?

**Comment by jeannekitchens** [comment]
It could be Job or Occupation.  It's best to add it to both.

**Comment by jeannekitchens** [comment]
GitHub Issue #884 covers targetJob, targetOccupation, and targetTask.
