### ISSUE TITLE
Add ceterms:enrollmentRate to https://credreg.net/qdata/terms/DataProfile, https://credreg.net/qdata/terms/DataSetProfile and / or https://credreg.net/ctdl/terms/AggregateDataProfile

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#876]
Enrollment rate refers to the percentage of eligible individuals who register for a particular ceterms:LearningOpportunity, ceterms:LearningProgram, ceterms:Course, ceterms:Credential, or ceterms:Assessment Profile.  

This property needs to be explicit.  Enrollment rates are a widely used metric in education and are available for many countries around the world. 

This is also to support Equity Council use cases explictely called out in the final Council's report to be released in June 

Many international organizations such as UNESCO, the World Bank, and OECD, collect and publish enrollment rate data for various levels of education, allowing for cross-country comparisons and global monitoring of education trends.

UNESCO Institute for Statistics: They provide data on enrollment rates for pre-primary, primary, secondary, and tertiary education levels for many countries around the world. Their data can be accessed on their website: http://uis.unesco.org/.

World Bank Education Data: The World Bank also provides data on enrollment rates for various levels of education, including primary, secondary, and tertiary education. Their data can be accessed on their website: https://data.worldbank.org/topic/education.

OECD Education at a Glance: The OECD provides a range of education statistics, including enrollment rates for pre-primary, primary, secondary, and tertiary education. Their data can be accessed on their website: https://www.oecd.org/education/education-at-a-glance/.

National Center for Education Statistics (NCES): This is the primary source of education data in the United States and is part of the U.S. Department of Education. The NCES provides data on enrollment rates for pre-primary, primary, secondary, and postsecondary education levels, including vocational and technical education. Their data can be accessed on their website: https://nces.ed.gov/.

College Board: The College Board provides data on college enrollment rates in the United States, including enrollment rates by state, race/ethnicity, and socioeconomic status. Their data can be accessed on their website: https://research.collegeboard.org/programs/trends-college-pricing.

Integrated Postsecondary Education Data System (IPEDS): This is a national database of information on colleges and universities in the United States, maintained by the National Center for Education Statistics. The IPEDS provides data on college enrollment rates, including enrollment by race/ethnicity, gender, and field of study. Their data can be accessed on their website: https://nces.ed.gov/ipeds/use-the-data/enrollment-data.

U.S. Census Bureau: The U.S. Census Bureau provides data on educational attainment and enrollment rates for the U.S. population as a whole, including enrollment rates by age group and region. Their data can be accessed on their website: https://www.census.gov/topics/education.html.

**Comment by philbarker** [comment]
@jeannekitchens are you sure about the definition?

> Enrollment rate refers to the percentage of eligible individuals who register for a particular ceterms:LearningOpportunity,

I don't think a definition with "a particular ceterms:LearningOpportunity" works. For most LearningOpportunities the number of people eligible is going to be in the millions, the number enrolling in any particular L.Op. is not likely to be above a thousand and will normally be much less, so the percentage will always be ~0%.

The examples you give are all sector-wide, aggregated over many LearningOpportunities, not for a particular LearningOpportunity.

I don't know how we could handle sector-wide stats in Credential Engine. What entities do we have that are sector wide? We define some audience sectors, but do these align with the ones for which there are stats--i.e. how do we combine Audience classifications with Jurisdiction?

**Comment by philbarker** [comment]
I Still don't get it. The examples Jeanne points to don't seem relevant to individual offerings such as CTDL deals with.

**Comment by siuc-nate** [comment]
Enrollment Rate can now be described in #941
