### ISSUE TITLE
Need to add ceterms:persistanceRate to  https://credreg.net/qdata/terms/DataProfile and/or https://credreg.net/qdata/terms/DataSetProfile and / or https://credreg.net/ctdl/terms/AggregateDataProfile

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#877]
We need to have an explicit property for persistanceRate.  This is an Equity Council use case.  This is common data available globally. 

ceterms:persistanceRate - The percentage of students who continue or return for subsequent years in a particular educational program or institution.

Persistence rate, also known as retention rate, is a measure of the percentage of students who continue their enrollment or return for subsequent years in a particular educational program or institution. It is an important indicator of the effectiveness of educational programs and institutions in supporting student success and degree completion.

Persistence rates are recognized as an important metric in education and are used globally to assess student progress and institutional effectiveness. However, the availability and accuracy of persistence rate data may vary across countries, as not all countries have the same level of data collection and reporting infrastructure.

Persistence rate is a more globally recognized term, as it is used by international organizations such as the Organization for Economic Cooperation and Development (OECD) to assess educational outcomes across countries. The term persistence rate is also used by many countries in their own education systems and national statistical agencies.

For example, the European Union's Eurostat database uses the term persistence rate to measure the percentage of students who continue their studies in higher education from one academic year to the next. The Australian government's Department of Education, Skills and Employment also uses the term persistence rate to report on the percentage of students who continue their studies in higher education from one year to the next.

While retention rate is more commonly used in the United States, persistence rate is a more universally recognized term and is used by many countries and international organizations to measure student persistence and progress in education.

Here are some examples of sources that use the term retention rate in the United States:

National Center for Education Statistics (NCES): The NCES uses the term retention rate to refer to the percentage of first-time, full-time undergraduate students who return to the same institution for their second year of enrollment. Their data can be accessed on their website: https://nces.ed.gov/collegenavigator/.

College Board: The College Board uses the term retention rate to refer to the percentage of first-time, full-time students who return to the same institution for their second year of enrollment. Their data can be accessed on their website: https://research.collegeboard.org/programs/trends-college-pricing.

Chronicle of Higher Education: The Chronicle of Higher Education uses the term retention rate to refer to the percentage of first-time, full-time students who return to the same institution for their second year of enrollment. Their data can be accessed on their website: https://www.chronicle.com/interactives/20190419-Retention.

However, it is important to note that while the term retention rate is more commonly used in the United States, persistence rate is also used by some institutions and organizations in the United States and other countries.

**Comment by philbarker** [comment]
We use retention rate in the UK for the % who stay at an institution, progression rate for the % who progress through a pathway (so students who re-take a year are retained but don't progress) and completion rate for the % who complete a program of study (also sometimes called graduation rate I think). Of the three, completion/graduation rate would be the easiest to cover in CTDL as a property of a LearningOpportunity or Credential. Persistence/retention/progression depend on the stage of study,  so we would need a combination of a Program or Pathway and a progression model.

**Comment by siuc-nate** [comment]
This was handled in #941
