### ISSUE TITLE
Add properties for student debt alongside wages to https://credreg.net/qdata/terms/DataProfile and/or https://credreg.net/qdata/terms/DataSetProfile and / or https://credreg.net/ctdl/terms/AggregateDataProfile

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#879]
This is an Equity Council use case to publish the debt of graduates analyzed alongside wages. 

Here's some globally utilized student debt/aggregate outcome statistics:

1. Average debt at graduation - the average amount of student loan debt held by students upon graduating from an institution or program. This is often calculated separately for undergraduate and graduate programs.
2. 3. Loan default rates - the percentage of borrowers who are unable to repay their student loans within a certain timeframe and enter default status.
4. 5. Loan repayment rates - the percentage of borrowers who have made progress in repaying their student loans, usually measured by the percentage of borrowers who have made payments on their loans for a certain number of months after entering repayment.
6. 7. Total student loan debt - the total amount of outstanding student loan debt held by borrowers in a certain country or region.

Sources Include:

1. In the United States, the National Center for Education Statistics (NCES) and the Federal Student Aid office within the U.S. Department of Education collect and publish data on student debt and other higher education outcomes. https://nces.ed.gov/
2. States/Provinces. See Texas definitions below. 
3. The Organization for Economic Cooperation and Development (OECD) collects data on student debt and other higher education outcomes for its member countries and publishes reports and analyses of the data. https://www.oecd.org/education/
4. The United Nations Educational, Scientific and Cultural Organization (UNESCO) also collects and publishes data on higher education outcomes, including student debt, for countries around the world. https://data.uis.unesco.org/
5. The World Bank also collects and publishes data on higher education outcomes and student debt for countries around the world. https://datatopics.worldbank.org/education/

United State College Scorecard Glossary of Outcome Data
https://collegescorecard.ed.gov/data/glossary/

State of Texas Definitions for Sudent Loan/Debt Statistics:
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Loan_Amount | Average loan amount at graduation. |   | Average loan amount is calculated by averaging each student’s loan debt, accumulated at all Texas institutions up to the time of receiving an applicable degree, based on the student’s highest degree earned. Only students with debt are included. Each student's loan debt includes all loans reported in the THECB financial aid database (FADS) report by any institution for that student in the last 15 years. Parent loans are excluded. Data are available for programs with at least 5 graduates with loans. Source: THECB CBM001, CBM009, Financial Aid Database System (FADS)
-- | -- | -- | --
Loan_Percent | Percent of graduates with loans. |   | The percentage of graduates who accumulated student loan debt at the time of award as reported on the THECB FADS reports by any institution in the last 15 years. Parent loans are excluded. Source: THECB FADS Report
Loan_to_First_Wage_Ratio | Loan as a percentage of first year wages. |   | The median of individual student loan debt as a percentage of first year wages. Individual must have student loan debt at time of award and wages in first year following award. Each student's loan debt includes all student loans reported in the THECB financial aid database (FADS) report by any institution for that student in the last 15 years. Parent loans are excluded. First year wages are based wage data reported to the Texas Workforce Commission (TWC). Source: THECB CBM009, FADS Report, TWC UI wage records

</body>
</html>

**Comment by philbarker** [comment]
I think debt is important, not a niche case. Especially globally. 

It is kind of a consequence of fees Vs funding options, and the funding options depend on student circumstances in varied way. For example an English student of Computer Science at HW is going to graduate with a much higher debt than a Scots student, because the Scottish government pays the tuition fees directly to the university.

Is that the sort of thing that [subjectType](https://credreg.net/qdata/terms/subjectType) deals with?

BTW, there is no `schema:percentage` property.

**Comment by philbarker** [comment]
@siuc-nate OK, got you. Let's start with debt as generic and then think about how to describe whose debt is being measured, how and when.  I think there are common ways of defining the how and when (though maybe that's my European view of how these things are done) I would look to something like OECD for those.

**Comment by siuc-nate** [comment]
Per our 7/10/2023 meeting:
Example data: https://sandbox.credentialengine.org/finder/credential/50787
Example descriptions (currently done via qdata:holdersInSet):
- Percent of graduates with loans
- Average loan amount at graduation
- Loan debt as a percent of wages
- Loan to first wage ratio
- Average time to finish a degree

**Comment by philbarker** [comment]
Text descriptions will do for a first pass, it'll give an indication to prospective students. Go for it.

It won't be sufficient for serious analytics, for that you need identifiers for common methodologies for measuring all the variables -- but that would probably need a task group to sort out, if we need to and feel able to.

BTW @siuc-nate the example data [above](https://github.com/CredentialEngine/Schema-Development/issues/879#issuecomment-1530290873) shows `schema:percentage": 0.5`: that should be `qdata:percentage": 50`

**Comment by siuc-nate** [comment]
@jeannekitchens @philbarker Can you both confirm that the plan, then, is to move forward with the proposal [from this post](https://github.com/CredentialEngine/Schema-Development/issues/879#issuecomment-1530290873)?

> **URI:** qdata:dataPoint
> **Label:** Data Point
> **Description:** A piece of information for which there is no more specific property.
> **Domain:** qdata:DataProfile
> **Range:** schema:QuantitativeValue

**Comment by philbarker** [comment]
Confirmed.

**Comment by jeannekitchens** [comment]
There needs to be a property or concept for student debt or studen loan debt.  With data set profile, users e.g., state governments can include a description that is based on the way they calculate student loan debt but publishers and consumers need to know that the date they're publishing or getting is about student loan debt. If the final proposal is only to add Data Point, I don't believe this addresses the use case.

**Comment by siuc-nate** [comment]
Do we have enough data from enough states to know how they measure it (see example above - measured as a loan in absolute dollars, measured as debt (ie minus any grants/payments/etc), measured as a percentage of wages, whether there is a time component involved (e.g. first year's wages, debt over 10 years, etc).  There is a lot of potential variation and if we want data that speaks a common language that all states can share/compare among each other, we'll need to come up with what the common denominator should be.

**Comment by jeannekitchens** [comment]
There can be multiple types of calculations for student debt, the main point it to know the data is about student debt.  They use the description to describe how they do the calculation with the data set profile and they also do this with the data set.  We don't need to document the calculations, rather the type of data.

**Comment by siuc-nate** [comment]
Would this be something specific to student loans, or debt in general? Also, are there any issues with using the term "student" as opposed to "learner" or one of the other more generic terms like that?  I guess what I'm asking is, how broadly/narrowly should we scope such a property?

**Comment by jeannekitchens** [comment]
It's only relevant to students accumulating debt to cover costs for learning and debt is via loans.

**Comment by philbarker** [comment]
This is where putting all data in an AggregateDataProfile fails. The clearest solution is to have a StudentDebtProfile class so that rdfs:type can do its job of telling data consumers what type of thing the data is about no matter what property points to it (e.g. it could be referenced from outside the registry using a non-CTDL property). Next best would be a dataSetType property pointing to concepts such as StudentDebtProfile.

**Comment by siuc-nate** [comment]
For context, Phil, we're looking at adding a property to DataProfile with a range of either QuantitativeValue or MonetaryAmount, so that would work the same way as all the other properties on DataProfile in QData.  AggregateDataProfile isn't in play here and the contextual information is provided by QData classes higher up the hierarchy.

**Comment by philbarker** [comment]
@siuc-nate sorry, sometimes it's hard to keep track of these long-running issues, especially times like now when several are in play at the same time. I got mislead by the issue title :-}

**Comment by siuc-nate** [comment]
This was handled in #941
