### ISSUE TITLE
Add ceterms:TimeToEmployment to Add properties for student debt alongside wages to https://credreg.net/qdata/terms/DataProfile and/or https://credreg.net/qdata/terms/DataSetProfile and / or https://credreg.net/ctdl/terms/AggregateDataProfile

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#880]
This is an Equity Council use case to provide the average length of time to intial job placement. 

Time to Employment or Time to Placement - Aggregate data that measures the average length of time it takes for individuals to secure employment after completing an education or training program.

Here are some examples of organizations that collect and publish time-to-employment statistics in the United States, along with their URLs:

National Student Clearinghouse - This organization collects data on the postsecondary enrollment and completion of students in the United States, and also publishes statistics on time-to-employment for college graduates. (https://nscresearchcenter.org/signature-initiatives/completion-time-employment/)

Texas Higher Education Coordinating Board - This state agency collects data on the employment outcomes of graduates from Texas public higher education institutions, including the percentage of graduates who are employed or pursuing further education six months after graduation. (http://www.txhighereddata.org/Interactive/GradRates.cfm)

California Community Colleges Chancellor's Office - This organization collects data on the employment outcomes of graduates from California's community college system, including the percentage of graduates who are employed or enrolled in further education six months after graduation. (https://scorecard.cccco.edu/scorecardrates.aspx)

Here are some examples of organizations that collect and publish time-to-employment statistics globally:

Eurostat - This statistical office of the European Union collects and publishes data on the employment outcomes of graduates from higher education institutions in EU member states, including the time it takes for graduates to find their first job. (https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Tertiary_education_graduates_-_employment_statistics)

Australian Government Department of Education, Skills and Employment - This department collects and publishes data on the employment outcomes of graduates from Australian higher education institutions, including the median time it takes for graduates to find full-time employment. (https://www.qilt.edu.au/employability)

Canadian Association of Career Educators and Employers - This association collects data on the employment outcomes of graduates from Canadian post-secondary institutions, including the percentage of graduates who find employment within six months of graduation. (https://ceric.ca/career-development-resources/career-planning-resources/statistics-on-grad-employment/)

**Comment by siuc-nate** [comment]
Do any of these work?:
- https://credreg.net/qdata/terms/meetEmploymentCriteria + https://credreg.net/qdata/terms/employmentDefinition
- https://credreg.net/qdata/terms/workTimeThreshold
- https://credreg.net/qdata/terms/earningsThreshold

**Comment by philbarker** [comment]
I do not understand the proposal, I cannot parse the title:
"Add ceterms:TimeToEmployment to Add properties for student debt alongside wages to https://credreg.net/qdata/terms/DataProfile and/or https://credreg.net/qdata/terms/DataSetProfile and / or https://credreg.net/ctdl/terms/AggregateDataProfile"

Is that two proposals merged?

At least in the UK, it's the employment rate after some time (6 months) that is the stat gathered, as in Texas, which I think is what the properties Nate 

Also, half those links don't work.

**Comment by siuc-nate** [comment]
I think the way we had handled time gaps in one of our other cases was to use the existing date properties with [dataSetTimePeriod](https://credreg.net/qdata/terms/dataSetTimePeriod)/[dataSetTimeFrame](https://credreg.net/qdata/terms/DataSetTimeFrame).  We would want to be consistent here as well.

**Comment by siuc-nate** [comment]
See changes in #941
