### ISSUE TITLE
Add Advisor to Student Ratio to to https://credreg.net/qdata/terms/DataProfile and/or https://credreg.net/qdata/terms/DataSetProfile and / or https://credreg.net/ctdl/terms/AggregateDataProfile

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#881]
This is an Equity Council use case to provide the adviosry to student ratio. Advisors could be faculty or some other personnel with or related to the credential organization.

Advisor-to-Student Ratio - Measure of the number of students that an academic advisor is responsible for. It is typically calculated by dividing the total number of students enrolled in a program or institution by the number of academic advisors available to support them.

Examples in the United States:

The National Center for Education Statistics (NCES) collects data on the student-to-faculty ratio, which can be used as a proxy for the advisor-to-student ratio in many cases. Data can be found on the NCES website: https://nces.ed.gov/

The American Association of Collegiate Registrars and Admissions Officers (AACRAO) collects and publishes data on enrollment management trends, including advising and support services. Data can be found on the AACRAO website: https://www.aacrao.org/

Examples globally:

The Organisation for Economic Co-operation and Development (OECD) collects and publishes data on education, including data on the student-to-teacher ratio. Data can be found on the OECD website: https://www.oecd.org/

The United Nations Educational, Scientific and Cultural Organization (UNESCO) collects and publishes data on education, including data on the student-to-teacher ratio. Data can be found on the UNESCO website: https://en.unesco.org/

Regenerate response

**Comment by siuc-nate** [comment]
Is this covered by https://credreg.net/qdata/terms/facultyToStudentRatio ?

**Comment by philbarker** [comment]
I think Nate is on the right track.

It's not worth us trying to be more specific than "teaching faculty". Given all the different definitions of "faculty", "staff", "teaching staff", "academic staff", "teaching assistants/fellows" and so on, this is notoriously difficult to compare. Stanford might have twice the "faculty" that some community college has, but if they spend more of their time doing research will that matter to a student?

Stuart's suggestions for Program included something similar. Would the QData property be applicable there?

**Comment by siuc-nate** [comment]
This can be expressed as a percentage (and possibly other ways) in an Observation now. See #941
