### ISSUE TITLE
Add Transfer Credit Acceptance Rate to https://credreg.net/qdata/terms/DataProfile and/or https://credreg.net/qdata/terms/DataSetProfile and / or https://credreg.net/ctdl/terms/AggregateDataProfile 

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#882]
This is an Equity Council use case to provide the number of transfer credits that were accepted and applied by a subsequent provider.  

The number of transfer credits that were accepted and applied is a commonly reported statistic in higher education institutions in the United States, but it may not be as widely reported or standardized globally. However, there are organizations that collect and report data on transfer credits and articulation agreements between institutions.

Label: Transfer Credit Acceptance Rate

Definition: Transfer Credit Acceptance Rate is a measure of the percentage of transfer credit hours that are accepted by an institution and applied toward a student's degree program.

Examples in the United States:

The National Student Clearinghouse Research Center collects and publishes data on transfer and mobility trends in higher education, including transfer credit acceptance rates. Data can be found on their website: https://nscresearchcenter.org/

The College Board collects and publishes data on college admissions and enrollment, including transfer credit policies and practices. Data can be found on their website: https://research.collegeboard.org/

Examples globally:

The European Commission collects and publishes data on the European Credit Transfer and Accumulation System (ECTS), which is used to facilitate the transfer of credits between higher education institutions in the European Union. Data can be found on the European Commission website: https://ec.europa.eu/education/resources-and-tools/european-credit-transfer-and-accumulation-system-ects_en

The UNESCO Global Education Monitoring Report collects and publishes data on international education, including transfer credit policies and practices. Data can be found on the UNESCO website: https://en.unesco.org/

Regenerate response

**Comment by siuc-nate** [comment]
Is this collected at the organization level, the course level, the course instance level, etc.?

**Comment by philbarker** [comment]
Can you provide more specific links? None of the one you give mention acceptance rate.

I am a little worried about how this would be interpreted in a TransferValueProfile. If we have

<> a TransferValueProfile ;  
  transferValue 100 ; 
  acceptanceRate 0.5 ; 
  transferValueFor <someCredential> ;
  transferValueFrom <someProgram> .

does that mean that 200 credits came from the Program but only 100 go to the Credential, or that 100 came from the Program and only 50 go to the Credential.

Can we clarify what we mean by transferValue by saying more clearly that it is the value that counts towards the destination/target--which is what I at least understood it to be.

If we do that, does it matter for the TransferValueProfile what value the owners of the Program put on it?

**Comment by siuc-nate** [comment]
My understanding is that this would actually be an update to QData - that is, collected statistics about the transfer acceptance rate (presumably for a given program/credential) that would be part of the DataSetProfile for that.

**Comment by philbarker** [comment]
Ah, yes, sorry, I had forgotten the issue title by the time I go to writing my comment.

If it is in QData maybe I have completely misunderstood what it is about? Is it % of people applying to have their credits accepted?

**Comment by siuc-nate** [comment]
It looks like it's meant to be "the number of transfer credits that were accepted and applied" (presumably vs the total number that were requested).

**Comment by siuc-nate** [comment]
See #941
