### ISSUE TITLE
Pathway Class Updates

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#890]
Add the following properties to https://credreg.net/ctdl/terms#Pathway.  This is necessary to support functionality requirements.

- https://credreg.net/ctdl/terms#lifeCycleStatusType
- https://credreg.net/ctdl/terms#latestVersion
- https://credreg.net/ctdl/terms#nextVersion
- https://credreg.net/ctdl/terms#previousVersion
- https://credreg.net/ctdl/terms#versionIdentifier

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
