### ISSUE TITLE
Placeholder - Need to support Collection Component Class

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#891]
@siuc-nate @sedula27 @mparsons-ce this issue was dicussed back when we did the pathway builder pilot. We have clear uses cases for needing ot be able to aggregate components into a Collection Componet. I could not find the issue for this.  Let's get this documented and resolved.

**Comment by siuc-nate** [comment]
The issue I think you were looking for is #871.
