### ISSUE TITLE
Rubric Domain Model and Terms Proposal.

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#892]
This replaces closed issue #530.  Also see the [CTDL Rubric Github Repository](https://github.com/CredentialEngine/Schema-Development/tree/master/Rubrics) for more information. 

[Draft CTDL Rubric Terms Proposal](https://docs.google.com/document/d/15ZXhI4jC-u5NKcuc4yRPz4SzjNoTAaf725HZHsB2_gY/edit)

![CTDL Rubric Domain Model 21-Aug-2023 drawio](https://github.com/CredentialEngine/Schema-Development/assets/20917206/cb29ef57-0c2d-4683-8e74-1d05c3ca858e)

![CTDL Rubric-Simplified drawio](https://github.com/CredentialEngine/Schema-Development/assets/20917206/20dd5c3a-bd51-4ea0-82bf-d0a41dca3ced)

**Comment by siuc-nate** [comment]
Terms proposal, based on https://docs.google.com/document/d/15ZXhI4jC-u5NKcuc4yRPz4SzjNoTAaf725HZHsB2_gY/edit

**rdfs:Class Changes**
---

**Create rdfs:Class - ceasn:CriterionLevel**
> **Term Status -** vs:unstable
> **Label -** "Criterion Level"
> **Definition -** "An individual component or specific element within a criterion that defines a particular aspect or standard for evaluation."

**Create rdfs:Class - ceasn:Rubric**
> **Term Status -** vs:unstable
> **Label -** "Rubric"
> **Definition -** "A structured and systematic evaluation tool used to assess performance, quality, and/or criteria."
> **Equivalent Class -** asn:Rubric

**Create rdfs:Class - ceasn:RubricCriterion**
> **Term Status -** vs:unstable
> **Label -** "Rubric Criterion"
> **Definition -** "Resource providing explicit criteria for ensuring specific and measurable evaluation."
> **Equivalent Class -** asn:RubricCriterion

**Create rdfs:Class - ceasn:RubricLevel**
> **Term Status -** vs:unstable
> **Label -** "Rubric Level"
> **Definition -** "Level or quality indicator used with Rubric Criteria."

**rdf:Property Changes**
---

**Create rdf:Property - ceasn:benchmarkLabel**
> **Term Status -** vs:unstable
> **Label -** "Benchmark Label"
> **Definition -** "Label for the level achieved as defined by the Rubric Criterion."
> **Domain Includes -** ceasn:CriterionLevel
> **Range Includes -** rdf:langString

**Create rdf:Property - ceasn:benchmarkText**
> **Term Status -** vs:unstable
> **Label -** "Benchmark Text"
> **Definition -** "Description of the level achieved as defined by the Rubric Criterion."
> **Domain Includes -** ceasn:CriterionLevel
> **Range Includes -** rdf:langString

**Create rdf:Property - ceasn:evaluatorType**
> **Term Status -** vs:unstable
> **Label -** "Evaluator Type"
> **Definition -** "Type of evaluator; select from an existing enumeration of such types."
> **Domain Includes -** ceasn:Rubric
> **Range Includes -** skos:Concept
> **Target Concept Scheme -** ceasn:EvaluatorCategory

**Create rdf:Property - ceasn:feedback**
> **Term Status -** vs:unstable
> **Label -** "Feedback"
> **Definition -** "Predefined feedback text for the benefit of the subject being evaluated."
> **Comment -** "This may include guidance and suggestions for improvement or development."
> **Domain Includes -** ceasn:CriterionLevel
> **Range Includes -** rdf:langString

**Create rdf:Property - ceasn:hasCriterionCategory**
> **Term Status -** vs:unstable
> **Label -** "Has Criterion Category"
> **Definition -** "Indicates a Concept for clustering logical sets of Rubric Criteria."
> **Domain Includes -** ceasn:RubricCriterion
> **Range Includes -** skos:Concept

**Create rdf:Property - ceasn:hasCriterionCategorySet**
> **Term Status -** vs:unstable
> **Label -** "Has Criterion Category Set"
> **Definition -** "Indicates the Concept Scheme for clustering logical sets of Rubric Criteria."
> **Domain Includes -** ceasn:Rubric
> **Range Includes -** skos:ConceptScheme

**Create rdf:Property - ceasn:hasCriterionLevel**
> **Term Status -** vs:unstable
> **Label -** "Has Criterion Level"
> **Definition -** "Criterion Level for this resource."
> **Domain Includes -** ceasn:RubricCriterion, ceasn:RubricLevel
> **Range Includes -** ceasn:CriterionLevel

**Create rdf:Property - ceasn:hasRubricCriterion**
> **Term Status -** vs:unstable
> **Label -** "Has Rubric Criterion"
> **Definition -** "Explicit criterion for ensuring specific and measurable evaluation."
> **Domain Includes -** ceasn:Rubric
> **Range Includes -** ceasn:RubricCriterion
> **Subproperty Of -** asn:hasCriterion

**Create rdf:Property - ceasn:hasRubricLevel**
> **Term Status -** vs:unstable
> **Label -** "Has Rubric Level"
> **Definition -** "Resource describing a level or quality indicator used with Rubric Criteria."
> **Domain Includes -** ceasn:Rubric
> **Range Includes -** ceasn:RubricLevel

**Create rdf:Property - ceasn:hasScope**
> **Term Status -** vs:unstable
> **Label -** "Has Scope"
> **Definition -** "Description of what the rubric's creator intended to assess or evaluate."
> **Equivalent Property -** asn:hasScope

**Create rdf:Property - ceasn:isBinaryEvaluation**
> **Term Status -** vs:unstable
> **Label -** "Is Binary Evaluation"
> **Definition -** "Indicates whether the criterion level is evaluated as having been met or not."
> **Usage Note -** "A value of true does not mean the subject of evaluation has met this criterion level; it means that the criterion level itself only permits a binary evaluation such as "pass/fail", "checked/unchecked", "yes/no", and so on."
> **Domain Includes -** ceasn:CriterionLevel
> **Range Includes -** xsd:boolean

**Create rdf:Property - ceterms:hasRubric**
> **Term Status -** vs:unstable
> **Label -** "Has Rubric"
> **Definition -** "Rubric related to this resource."
> **Domain Includes -** ceterms:AssessmentProfile, ceasn:CompetencyFramework, ceterms:Job, ceterms:LearningOpportunityProfile, ceterms:Course, ceterms:LearningProgram, ceterms:ApprenticeshipCertificate, ceterms:AssociateDegree, ceterms:AssociateOfAppliedArtsDegree, ceterms:AssociateOfAppliedScienceDegree, ceterms:AssociateOfArtsDegree, ceterms:AssociateOfScienceDegree, ceterms:BachelorDegree, ceterms:BachelorOfArtsDegree, ceterms:BachelorOfScienceDegree, ceterms:Badge, ceterms:Certificate, ceterms:CertificateOfCompletion, ceterms:Certification, ceterms:Credential, ceterms:Degree, ceterms:DigitalBadge, ceterms:Diploma, ceterms:DoctoralDegree, ceterms:GeneralEducationDevelopment, ceterms:JourneymanCertificate, ceterms:License, ceterms:MasterCertificate, ceterms:MasterDegree, ceterms:MasterOfArtsDegree, ceterms:MasterOfScienceDegree, ceterms:MicroCredential, ceterms:OpenBadge, ceterms:ProfessionalDoctorate, ceterms:QualityAssuranceCredential, ceterms:ResearchDoctorate, ceterms:SecondarySchoolDiploma, ceterms:SpecialistDegree
> **Range Includes -** ceasn:Rubric

**Create rdf:Property - qdata:maxPercentage**
> **Term Status -** vs:unstable
> **Label -** "Max Percentage"
> **Definition -** "The upper percentage of some characteristic or property."
> **Usage Note -** "Best practice is to treat the value of this property as a verbatim percentage; for example, a value of 1.5 should be interpreted as 1.5%"
> **Domain Includes -** ceasn:CriterionLevel
> **Range Includes -** xsd:float

**Create rdf:Property - qdata:minPercentage**
> **Term Status -** vs:unstable
> **Label -** "Min Percentage"
> **Definition -** "The lower percentage of some characteristic or property."
> **Usage Note -** "Best practice is to treat the value of this property as a verbatim percentage; for example, a value of 1.5 should be interpreted as 1.5%"
> **Domain Includes -** ceasn:CriterionLevel
> **Range Includes -** xsd:float

**Modify rdf:Property - asn:hasProgressionLevel**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - asn:hasProgressionModel**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:altCodedNotation**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:codedNotation**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:codedNotation**
> **Add schema:domainIncludes -** ceasn:RubricCriterion

**Modify rdf:Property - ceasn:codedNotation**
> **Add schema:domainIncludes -** ceasn:RubricLevel

**Modify rdf:Property - ceasn:codedNotation**
> **Add schema:domainIncludes -** ceasn:CriterionLevel

**Modify rdf:Property - ceasn:conceptKeyword**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:creator**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:dateCopyrighted**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:dateCreated**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:dateModified**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:dateValidFrom**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:dateValidFrom**
> **Remove rdfs:comment -** "Beginning date of validity of this competency framework."
> **Add dct:description -** "Beginning date of validity of this resource."
> **Remove vann:usageNote -** "Where the competency document is valid for a given period of time, use both the dateValidFrom and dateValidUntil properties."
> **Add vann:usageNote -** "Where the resource is valid for a given period of time, use both the dateValidFrom and dateValidUntil properties."

**Modify rdf:Property - ceasn:dateValidUntil**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:dateValidUntil**
> **Remove rdfs:comment -** "End date of validity of this competency framework."
> **Add rdfs:comment -** "End date of validity of this resource."
> **Remove vann:usageNote -** "Where the competency document is valid for a given period of time, use both the dateValidFrom and dateValidUntil properties."
> **Add vann:usageNote -** "Where the resource is valid for a given period of time, use both the dateValidFrom and dateValidUntil properties."

**Modify rdf:Property - ceasn:derivedFrom**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:description**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:description**
> **Add schema:domainIncludes -** ceasn:RubricCriterion

**Modify rdf:Property - ceasn:educationLevelType**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:inLanguage**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:license**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:listID**
> **Add schema:domainIncludes -** ceasn:RubricCriterion

**Modify rdf:Property - ceasn:listID**
> **Add schema:domainIncludes -** ceasn:RubricLevel

**Modify rdf:Property - ceasn:listID**
> **Add schema:domainIncludes -** ceasn:CriterionLevel

**Modify rdf:Property - ceasn:name**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:name**
> **Add schema:domainIncludes -** ceasn:RubricCriterion

**Modify rdf:Property - ceasn:publicationStatusType**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:publicationStatusType**
> **Remove rdfs:comment -** "The publication status of the of this resource."
> **Add rdfs:comment -** "The publication status of the resource."

**Modify rdf:Property - ceasn:publisher**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:publisherName**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:rights**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceasn:weight**
> **Add schema:domainIncludes -** ceasn:RubricCriterion

**Modify rdf:Property - ceterms:ctid**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceterms:industryType**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceterms:instructionalProgramType**
> **Add schema:domainIncludes -** ceasn:Rubric

**Modify rdf:Property - ceterms:occupationType**
> **Add schema:domainIncludes -** ceasn:Rubric

**skos:ConceptScheme Changes**
---

**Create skos:ConceptScheme - ceasn:EvaluatorCategory**
> **Term Status -** vs:unstable
> **Label -** "Evaluator Category"
> **Definition -** "Category of agents that perform evaluation."

**skos:Concept Changes**
---

**Create skos:Concept - evalCat:Authority**
> **Term Status -** vs:unstable
> **In Scheme -** ceasn:EvaluatorCategory
> **Preferred Label -** "Authority"
> **Definition -** "Evaluator is an agent with authority over the person,  group, or thing being evaluated in the relevant context."
> **Comment -** "Examples include teachers, supervisors, managers, or others with positions over the person or group being evaluated."

**Create skos:Concept - evalCat:Automated**
> **Term Status -** vs:unstable
> **In Scheme -** ceasn:EvaluatorCategory
> **Preferred Label -** "Automated"
> **Definition -** "Evaluator is an automated agent or process."

**Create skos:Concept - evalCat:External**
> **Term Status -** vs:unstable
> **In Scheme -** ceasn:EvaluatorCategory
> **Preferred Label -** "External"
> **Definition -** "Evaluator is an agent who is outside the context of the person, group, or thing being evaluated."
> **Comment -** "Evaluator is typically independent of the person, group, or thing being evaluated."

**Create skos:Concept - evalCat:Peer**
> **Term Status -** vs:unstable
> **In Scheme -** ceasn:EvaluatorCategory
> **Preferred Label -** "External"
> **Definition -** "Evaluator is one or more peers of the person, group, or thing being evaluated."
> **Comment -** "Peers may be people taking the same course or in similar job roles."

**Create skos:Concept - evalCat:Self**
> **Term Status -** vs:unstable
> **In Scheme -** ceasn:EvaluatorCategory
> **Preferred Label -** "Self"
> **Definition -** "Evaluator is the person or group being evaluated."

**Comment by philbarker** [comment]
Noting that the schema:isBasedOn alignments to asn terms are not included, presumably because there is no way of adding them yet.

**Comment by philbarker** [comment]
@siuc-nate @jeannekitchens 
Comparing to Domain model diagram I find these differences (which may be intentional changes missed from the domain model diagram or errors in the proposal doc):
 - [ ] ceterms:Task add domain of ceasn:hasRubric (was in term proposal doc)
 - [ ] ceterms:lifecycleStatusType add domain ceasn:Rubric (I have added this to term proposal doc)
 - [ ] ceterms:hasProgressionLevel add domain ceasn:RubricCriterion (I have added this to term proposal doc)
 - [ ] ceterms:hasProgressionLevel add domain ceasn:CriterionLevel (I have added this to term proposal doc) (should this RubricLevel as well / instead)
 - [ ] diagram shows nested criterionLevels (i.e. CriterionLevel in domain of hasCriterionLevel: did we decide against that? -- I haven't changed the terms proposal doc)

**Comment by philbarker** [comment]
Q for @siuc-nate qdata:maxPercentage  usage note says: "Best practice is to treat the value of this property as a verbatim percentage; for example, a value of 1.5 should be interpreted as 1.5%" but the code examples (e.g. [Moodle](https://github.com/CredentialEngine/Schema-Development/blob/master/Rubrics/Examples/Blackboard_Essay_Evaluation.json) have
```
"qdata:percentage": 1.0
```
for 100%. Assuming best practice for qdata:percentage and qdata:maxPercentage should be the same, where's the error?

**Comment by philbarker** [comment]
Error in EvalCat
- [ ]  evalCat:Peer has label External, should be Peer

**Comment by siuc-nate** [comment]
> schema:isBasedOn

Will address this when I get a chance to update the schema manager to support it.

> qdata:minPercentage/qdata:maxPercentage

Agree all of the percentage properties should work the same way. We just need to fix the examples.

> Other properties

Fixed (will update the proposal post above soon). Note that we also decided to use asn:hasProgressionLevel with ceasn:RubricLevel and ceasn:RubricCriterion instead of with ceasn:CriterionLevel.

> Which classes should have ceterms:ctid

- ceasn:Rubric
- ceasn:RubricCriterion

**Comment by siuc-nate** [comment]
To clean up some things, I split out the changes by schema, and regenerated the change data in [this post](https://github.com/CredentialEngine/Schema-Development/issues/892#issuecomment-1710691870) and in [this turtle file](https://github.com/CredentialEngine/Schema-Development/blob/master/Rubrics/FinalProposal.txt)

**Comment by siuc-nate** [comment]
These changes have been made in the pending schemas and noted in the history tracking.

**Comment by siuc-nate** [comment]
Per our 2023-10-17 meeting:
We have decided to drop ceasn:isBinaryEvaluation entirely, as it appears it may not be necessary after all. If needed, we can explore bringing it back.  Since the property is unstable, it won't be kept as a deprecated property.
