### ISSUE TITLE
Add Owns, OwnedBy to Occupation, Work Role and Task

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#896]
Add Owns, OwnedBy to Occupation, Work Role and Task
https://docs.google.com/spreadsheets/d/1seHwgPp0q8jYxyB11G_fsa2wgc0sQMA6Yd6s_Yw0n9w/edit#gid=610336704

**Comment by philbarker** [comment]
Assuming this is:
> Add Occupation, Work Role and Task to domainIncludes of ownedBy
> Add Occupation, Work Role and Task to rangeIncludes of owns

What does it mean to have legal title over these things? Who owns the occupation of Computer Programmer? I think [ceterms:offers](https://credreg.net/ctdl/terms#offers) makes more sense, but even that is more appropriate to Job than Occupation.

**Comment by jeannekitchens** [comment]
ceterms:offers [](https://credreg.net/ctdl/terms/offers) - Resource offered or conferred by the organization or person.
cterms:owns[](https://credreg.net/ctdl/terms/owns)  - Resource over which the organization or person claims legal title.
ceasn:publisher[](https://credreg.net/ctdlasn/terms/publisher)  - An agent responsible for making this resource available.

Colleges and other organizations could identify occupations that are not jobs that they own or offer. They're the publisher.  The owns defintion gets in the way of using that term.  Publisher looks to be the best suited.

**Comment by philbarker** [comment]
@jeannekitchens I can only make sense of this if you're talking about owns/publishes the data in the registry, not the Occupation being described. Am I missing something?

**Comment by jeannekitchens** [comment]
The organization taking responsiblity for the occupation being described not who publishes it.  For organizations like a military branch that organizes data as both occupations and jobs, owns and offers is fine.  Maybe this is just being overthought.  Since occupations aren't offered, make it owned.

**Comment by philbarker** [comment]
Perhaps we are over-thinking it, but I think our distinction between Occupation and Job is that a Job is associated with a single Organization whereas an Occupation was shared across several. So, if there is a single Organization owning it, it is a Job not an Occupation.

Or put it another way, having an "organization taking responsiblity for the [thing] being described" sounds a lot like the [thing] matches our definition of [Job](https://credreg.net/ctdl/terms/Job): Set of responsibilities based on work roles within an occupation as **defined by an employer** (my emphasis)

**Comment by siuc-nate** [comment]
How about https://credreg.net/ctdl/terms/assertedBy ? Does that get around the problem?

**Comment by philbarker** [comment]
Yes, I think `assertedBy` would work for me. Some Organization(s) is(/are) saying that this is an Occupation.

There is more than one military. If we end up with assertions like `<USArmy> ceterms:owns <Soldier>` then we might have a problem with internationalization. I know the occupations in question are likely more finely defined, but if they are specific to one employer then they meet our definition for Job not Occupation. I think the problem might be that we dropped Specialization at some point thinking that were wasn't space for it between Occupation and Job. This may be that space.

**Comment by siuc-nate** [comment]
Proposal:

**Add:**
> **Subject:** ceterms:assertedBy
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Occupation

**Comment by siuc-nate** [comment]
The above changes have been made in pending CTDL and noted in the history tracking.
