### ISSUE TITLE
Add IsMemberOf to Occupation and Add Occupation to HasMember

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#897]
Add IsMemberOf to Occupation and Add Occupation to HasMember
https://docs.google.com/spreadsheets/d/1seHwgPp0q8jYxyB11G_fsa2wgc0sQMA6Yd6s_Yw0n9w/edit#gid=610336704

**Comment by siuc-nate** [comment]
Isn't this already accommodated by the Support Service class itself? It has description and subjectWebpage properties, and can be used in a high-level/summary sense (like those pair-properties on organization).

**Comment by jeannekitchens** [comment]
This is very similar to the Transfer Value Description and Web Page properties.  We have a Transfer Value Class but we also support simple description and URL about transfer value.  Yes, we clearly have a Support Services Class but we  simply need a way to describe them in general directly on the organization.

**Comment by jeannekitchens** [comment]
@siuc-nate ?  I think this comment is meant for another issue.  This issue also need to add credential, and assessement to Collection.  We have a collection of credentials published.

**Comment by siuc-nate** [comment]
@philbarker This issue is to enable collections of Occupations. Are there any issues with this?

**Comment by philbarker** [comment]
@siuc-nate I no issue in having a collection of anything, the issue I mentioned elsewhere is in how those collections might get (mis)used in data.

**Comment by siuc-nate** [comment]
Proposal:

**Add:**
> **Subject:** ceterms:hasMember
> **Predicate:** schema:rangeIncludes
> **Object:** ceterms:Occupation

> **Subject:** ceterms:isMemberOf
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Occupation

**Comment by siuc-nate** [comment]
The above changes have been made in pending CTDL and noted in the history tracking.
