### ISSUE TITLE
Add Environmental Hazard Type to Occupation

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#898]
Add Environmental Hazard Type to Occupation
https://docs.google.com/spreadsheets/d/1seHwgPp0q8jYxyB11G_fsa2wgc0sQMA6Yd6s_Yw0n9w/edit#gid=610336704

**Comment by philbarker** [comment]
OK

**Comment by siuc-nate** [comment]
What about related properties from the CCTG?:
- ceterms:performanceLevelType
- ceterms:physicalCapabilityType
- ceterms:sensoryCapabilityType (I see we have #901 for that)

**Comment by jeannekitchens** [comment]
@siuc-nate yes,  per the Work Classes Mapping Occupation also needs: 1. performanceLevelType, physicalCapabilityType, and sensoryCapabilityType https://docs.google.com/spreadsheets/d/1seHwgPp0q8jYxyB11G_fsa2wgc0sQMA6Yd6s_Yw0n9w/edit#gid=610336704

**Comment by siuc-nate** [comment]
Proposal:

**Addition:**
> **Subject:** ceterms:performanceLevelType, ceterms:physicalCapabilityType, ceterms:sensoryCapabilityType
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Occupation

**Comment by siuc-nate** [comment]
The above changes have been made in pending CTDL and noted in the history tracking.
