### ISSUE TITLE
Add hasTask to Job and Occupation

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#899]
Add hasTask to Job and Occupation
https://docs.google.com/spreadsheets/d/1seHwgPp0q8jYxyB11G_fsa2wgc0sQMA6Yd6s_Yw0n9w/edit#gid=610336704

**Comment by philbarker** [comment]
OK

**Comment by siuc-nate** [comment]
ceterms:Job already has ceterms:hasTask, so:

**Addition:**
> **Subject:** ceterms:hasTask
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Occupation

**Comment by siuc-nate** [comment]
The above change has been made in pending CTDL and noted in the history tracking.
