### ISSUE TITLE
Add hasWorkRole to Job and Occupation

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#900]
Add hasWorkRole to Job and Occupation
https://docs.google.com/spreadsheets/d/1seHwgPp0q8jYxyB11G_fsa2wgc0sQMA6Yd6s_Yw0n9w/edit#gid=610336704

**Comment by philbarker** [comment]
OK

**Comment by siuc-nate** [comment]
Is this meant to be something else? Occupation and Job both already have the ceterms:hasWorkRole property.

**Comment by jeannekitchens** [comment]
It must have been missed on our mapping sheet and then corrected and I forgot to remove this after the correction.  Closing this issue.
