### ISSUE TITLE
Missing domains?

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/Schema-Development#906]
@siuc-nate is there a reason why the following don't have Domains 
ceterms:affiliatedAgent 
ceterms:spatialCoverage
ceterms:temporalCoverage
ceterms:isSimilarTo
ceterms:endTime
ceterms:startTime

**Comment by siuc-nate** [comment]
- ceterms:affiliatedAgent
  - According to its [term history](https://credreg.net/ctdl/termhistory/ceterms/affiliatedAgent/json), it was removed from Task Profile back in 2020.  Task Profile was dropped (not deprecated, as it was unstable) in [this issue/comment](https://github.com/CredentialEngine/Schema-Development/issues/694#issuecomment-651992745) to avoid confusion with ceterms:Task. Its definition was updated back when we replaced a bunch of references to specific domains with "resource" and the definition used to reference "task being described", so it was probably _only_ associated with Task Profile, so when that class went away, it had nowhere else to belong.

- ceterms:spatialCoverage
- ceterms:temporalCoverage
  - These are both meant to be domainless superclasses for other properties, according to their comments and according to [the issue that spawned those properties](https://github.com/CredentialEngine/Schema-Development/issues/27#issuecomment-245908985).

- ceterms:isSimilarTo
  - Same idea as the two above according to [this issue/comment](https://github.com/CredentialEngine/Schema-Development/issues/210#issuecomment-261712672)

- ceterms:startTime
- ceterms:endTime
  - These were originally associated with some classes, but were effectively replaced by ceterms:startDate and ceterms:endDate in [this issue](https://github.com/CredentialEngine/Schema-Development/issues/373) (which notes that they would have no domain afterwards). See also [this issue](https://github.com/CredentialEngine/Schema-Development/issues/369).

**Comment by philbarker** [comment]
Thanks @siuc-nate , no big deal. 

I was experimenting with [a SHACL file to validate the CTDL schema exports](https://gist.github.com/philbarker/b726f7cfeba1bafe8c7060dbea876d2f) and these were stopping me from putting in a rule that all properties must have `sdo:domainIncludes`. 

If those validation rules ever prove useful, and we do want that rule, we could use sdo:domainIncludes rdfs:Resource 

I'll close this issue now. Hopefully one of us will remember it is here if we ever need to refer to it.
