### ISSUE TITLE
Add version properties to Transfer Value Profile

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#911]
We have a real-world use case.  ACE publishing transfer values with start and end dates.  Any transfer value recommendation can have multiple and even several versions.  They must be able to not only show a start and end date but link them so it is clear and explicit in the data what the current version is and prior versions.  Below is a real example that's in our sandbox for the purpose of  showing how the versions relate.  ACE is publishing now and want to implement this now. 

- https://credreg.net/ctdl/terms#latestVersion - Latest version of the resource.
- https://credreg.net/ctdl/terms#nextVersion - Version of the resource that immediately follows this version.
- https://credreg.net/ctdl/terms#previousVersion - Version of the resource that immediately precedes this version. 
- https://credreg.net/ctdl/terms#versionIdentifier - Alphanumeric identifier of the version of the resource that is unique within the organizational context of its owner.

CFTA-0017: Money and Banking: Start Date:2017-10-01 and End Date:2021-05-31 -  CTID:ce-ebef0682-c654-4d31-a948-5405c64da137
**latest version** = CTID:ce-ebef0682-c654-4d31-a948-5405c64da137 
**previous version** = CTID:ce-a0aa48ea-dfe5-4181-864a-211b9a99dc17 

CFTA-0017: Money and Banking: Start Date:2011-10-01 and End Date:2014-08-31  CTID:ce-a0aa48ea-dfe5-4181-864a-211b9a99dc17 
**next version** = CTID:ce-ebef0682-c654-4d31-a948-5405c64da137
**previous version** =  CTID:ce-eb70657d-0468-4195-b517-584168d69434

CFTA-0017: Money and Banking:Start Date:2004-01-01 and End Date:2011-09-30 - CTID:ce-eb70657d-0468-4195-b517-584168d69434
**next version** = CTID:ce-a0aa48ea-dfe5-4181-864a-211b9a99dc17
**previous version** = CTID:ce-8827b569-c9a5-42f3-a6f4-af157d9cc28f   

CFTA-0017: Money and Banking: Start Date:1987-01-01 and End Date:2003-12-31 - CTID:ce-8827b569-c9a5-42f3-a6f4-af157d9cc28f
**next version** = CTID:ce-eb70657d-0468-4195-b517-584168d69434

**Comment by siuc-nate** [comment]
Proposal:
**Add:**
> **Subject:** ceterms:latestVersion, ceterms:nextVersion, ceterms:previousVersion, ceterms:versionIdentifier
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:TransferValueProfile

**Comment by siuc-nate** [comment]
The above change has been made in pending CTDL and noted in the history tracking.
