### ISSUE TITLE
Add all Organization classes to the range of schema:about

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#912]
State agencies and other organizations provide aggregate outcome data for schools not just for credentials and programs. This website https://www.schev.edu/students/applying-for-college/colleges-universities  is aggregate outcome data about the schools not specific credentials or programs.  This is not uncommon.  The agency needs to be able to publish this data about the schools.

Add https://credreg.net/qdata/terms#about to domains:
1. https://credreg.net/ctdl/terms#Organization
2. https://credreg.net/ctdl/terms#CredentialOrganization
3. https://credreg.net/ctdl/terms#QACredentialOrganization

**Comment by siuc-nate** [comment]
Proposal:
**Add:**
> **Subject:** schema:about
> **Predicate:** schema:rangeIncludes
> **Object:** ceterms:Organization, ceterms:CredentialOrganization, ceterms:QACredentialOrganization

**Comment by siuc-nate** [comment]
The above change has been made in pending QData and noted in the history tracking.
