### ISSUE TITLE
Add all of the Action classes to the domain of ceterms:name

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#913]
We're working on supporting publishing some of the action classes now focused on use cases for QA organizations issuing QA credentials to objects, e.g., courses, organizations, credential, etc... It is a problem to not have a name of the QA action.  There would be no information for any systems or users to have a clue as to what the data is about and would force all users to open every resource.

All Action Class domains need to be added to the Range https://credreg.net/ctdl/terms#name

1. https://credreg.net/ctdl/terms/AccreditAction
2. https://credreg.net/ctdl/terms/AdvancedStandingAction
3. https://credreg.net/ctdl/terms/ApproveAction
4. https://credreg.net/ctdl/terms/CredentialingAction
5. https://credreg.net/ctdl/terms/OfferAction
6. https://credreg.net/ctdl/terms/RecognizeAction
7. https://credreg.net/ctdl/terms/RegulateAction
8. https://credreg.net/ctdl/terms/RenewAction
9. https://credreg.net/ctdl/terms/RevokeAction
10. https://credreg.net/ctdl/terms/RightsAction
11. https://credreg.net/ctdl/terms/WorkforceDemandAction

**Comment by siuc-nate** [comment]
Proposal:
**Add:**
> **Subject:** ceterms:name
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:AccreditAction, ceterms:AdvancedStandingAction, ceterms:ApproveAction, ceterms:CredentialingAction, ceterms:OfferAction, ceterms:RecognizeAction, ceterms:RegulateAction, ceterms:RenewAction, ceterms:RevokeAction, ceterms:RightsAction, ceterms:WorkforceDemandAction

**Comment by siuc-nate** [comment]
The above change has been made in pending CTDL and noted in the history tracking.
