### ISSUE TITLE
Certificates Task Group Proposal

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#914]
**[[Draft CTDL Terms Proposal  V 3.1, January 12, 2024](https://docs.google.com/document/d/1GdTnh_qv2TsL2jwTTLky2FchWhLjEEau2m7MTuiwmbo/edit?usp=sharing)]**

The proposal needs to consider the information provided by partners via issue #836.

**Domain Model, January 12, [2024)**
![CertificateDraftDomainModelV3 1_12_Jan_2023 drawio](https://github.com/CredentialEngine/Schema-Development/assets/20917206/fbb178b7-bfc3-4f81-a5d5-13c2d86b551b)

**Comment by siuc-nate** [comment]
Per the draft document https://docs.google.com/document/d/1GdTnh_qv2TsL2jwTTLky2FchWhLjEEau2m7MTuiwmbo/edit

I ran into some open questions while preparing this (and I have attempted to resolve them in the proposal below):
1. The sheet indicates we are changing "Master Certificate" to "Master Trade Certificate". Is this purely a label change, or are we actually deprecating ceterms:MasterCertificate and creating ceterms:MasterTradeCertificate? The latter is implied by that URI being in the proposal document, but this seems unnecessary to me. (I have treated this as a label change)
2. The domain changes for ceterms:registeredBy and ceterms:isRegisteredApprenticeship in the proposal document only show those properties being added to the 3 existing apprenticeship classes (pending the decision on MasterCertificate above).  Should it also be added to ceterms:PreApprenticeshipCertificate and/or ceterms:WorkBasedLearningCertificate? (I have included both properties with all 5 classes)
3. Should ceterms:isRegisteredApprenticeship also be added to ceterms:LearningOpportunityProfile, ceterms:LearningProgram, and ceterms:Course? (I have included it with those classes as well)
4. Should "Secondary Certificate" be "Secondary Education Certificate"? That meaning would be clearer, and many of the other certificates in that section include "education" in their name. (I have gone with "Secondary Education Certificate")
5. "Post-Masters Certificate" should be "Post-Master Certificate" given that we use "Master Degree" and "Master Trade Certificate" (no "s" on the end) elsewhere. (I have used Post-Master Certificate)

Make the following modifications to the following existing Classes:
---
> **URI:** ceterms:Certificate
> **Remove:** rdfs:comment "Credential that designates requisite knowledge and skills of an occupation, profession, or academic program."
> **Add:** rdfs:comment "Credential which designates participation in, completion of, or demonstration of requisite knowledge and skills for a formal academic or training program, an occupation, or non-formal learning."
> **Add:** dct:description "Distinct from degrees of higher education and typically non-renewable. For degrees of higher education use and appropriate type from the Degree hierarchy."

> **URI:** ceterms:CertificateOfCompletion
> **Add:** owl:subClassOf ceterms:Certificate

> **URI:** ceterms:ApprenticeshipCertificate
> **Remove:** rdfs:comment "Credential earned through work-based learning and earn-and-learn models that meet standards and are applicable to industry trades and professions."
> **Add:** rdfs:comment "Credential awarded at the Apprentice level for successful completion of an apprenticeship program in industry trades and professions."
> **Add:** owl:subclassOf ceterms:WorkBasedLearningCertificate

> **URI:** ceterms:JourneymanCertificate
> **Remove:** rdfs:comment "Credential awarded to skilled workers on successful completion of an apprenticeship in industry trades and professions."
> **Add:** rdfs:comment "Credential awarded at the Journeyman level for successful completion of an apprenticeship program in industry trades and professions."
> **Add:** owl:subclassOf ceterms:WorkBasedLearningCertificate

> **URI:** ceterms:MasterCertificate
> **Remove:** rdfs:label "Master Certificate"
> **Add:** rdfs:label "Master Trade Certificate"
> **Remove:** rdfs:comment "Credential awarded upon demonstration through apprenticeship of the highest level of skills and performance in industry trades and professions."
> **Add:** rdfs:comment "Credential awarded at the Master level for demonstration of the highest level of skills and performance in industry trades and professions."
> **Add:** owl:subclassOf ceterms:WorkBasedLearningCertificate


Create each of the following Classes:
---
> **URI:** ceterms:CertificateOfParticipation
> **Label:**  Certificate of Participation
> **Definition:**  Credential that acknowledges attendance and/or engagement in an activity.
> **Comment:**  These certificates do not imply completion, or mastery of specific skills, or that a grade has been awarded, but recognize the individual's active participation with an activity . A record of the activity may or may not exist, and the credential may or may not be designed as preparation for another resource such as a credential, assessment, or learning opportunity.
> **Subclass Of:**  ceterms:Certificate

> **URI:** ceterms:ProfessionalCertificate
> **Label:**  Professional Certificate
> **Definition:**  Credential awarded for demonstrating competencies in a profession or particular occupational field, including job readiness.
> **Comment:**  These certificates validate competency in tasks, tools, software, or procedures within a particular industry and are often awarded by training centers, career and technical education, industry organizations, or businesses.
> **Subclass Of:**  ceterms:Certificate

> **URI:** ceterms:ProficiencyCertificate
> **Label:**  Proficiency Certificate
> **Definition:**  Credential awarded after assessment of skills in a specific area defined by a recognized body of experts, without regard for how the skills were learned. 
> **Comment:**  Examples of specific areas include language, typing, music, and dance.
> **Subclass Of:**  ceterms:Certificate

> **URI:** ceterms:WorkBasedLearningCertificate
> **Label:**  Work-Based Learning Certificate
> **Definition:**  Credential awarded for work-based learning and earn-and-learn models that meet standards and are applicable to industry, trades, occupations, and professions.
> **Comment:**  Work-based learning includes many types of skills training that are occupation specific including, but not limited to apprenticeship.
> **Subclass Of:**  ceterms:Certificate

> **URI:** ceterms:PreApprenticeshipCertificate
> **Label:**  Pre-Apprenticeship Certificate
> **Definition:**  Credential awarded to indicate readiness for an apprentice-level program.
> **Subclass Of:**  ceterms:WorkBasedLearningCertificate

> **URI:** ceterms:AcademicCertificate
> **Label:**  Academic Certificate
> **Definition:**  Credential awarded for successful completion of a formal education program, demonstrating requisite knowledge and skills.
> **Comment:**  Formal education programs include academic, career, technical programs with defined completion requirements and often require approvals by provincial or federal government. 
> **Subclass Of:**  ceterms:Certificate

> **URI:** ceterms:SecondaryEducationCertificate
> **Label:**  Secondary Education Certificate
> **Definition:**  Credential for successful completion of a formal secondary-level education program that is less than a diploma and does not indicate completion of secondary education graduation requirements. 
> **Usage Note:**  Use Diploma or General Education Development to indicate completion of secondary education graduation requirements.
> **Subclass Of:**  ceterms:AcademicCertificate

> **URI:** ceterms:BasicTechnicalCertificate
> **Label:**  Basic Technical Certificate
> **Definition:**  Credential awarded at a postsecondary level for successful completion of a formal education program that is completed within one semester, demonstrating competencies within a specific occupational area, indicating job readiness. 
> **Comment:**  Typically equivalent to a United States IPEDS level 1a that specifies postsecondary certificates of less than 300 clock hours, or less than 9 semester or trimester credit hours, or less than 13 quarter credit hours and UNESCO ISCED 2011 Levels 3 or 4. 
> **Subclass Of:**  ceterms:AcademicCertificate

> **URI:** ceterms:TechnicalLevel1Certificate
> **Label:**  Technical Level 1 Certificate
> **Definition:**  Credential award at a postsecondary level for successful completion of a formal education program that is more than one semester and less than 1 year, demonstrating competencies within a specific subject area or an occupational area indicating job readiness.
> **Comment:**  Can lead to a Technical Certificate Level 2 or a degree. Equivalent to a United States IPEDS Award Level 1b that specifies postsecondary certificates of 300-899 clock hours, or 9-29 semester or trimester credit hours, or 13-44 quarter credit hours and UNESCO ISCED 2011 Level 4.
> **Subclass Of:**  ceterms:AcademicCertificate

> **URI:** ceterms:TechnicalLevel2Certificate
> **Label:**  Technical Level 2 Certificate
> **Definition:**  Credential award at a postsecondary level for successful completion of a formal education program that is at least 1 year but less than 2 years, demonstrating competencies within a specific subject area or in an occupational area indicating job readiness.
> **Comment:**  Can lead to a degree. Equivalent to a United States IPEDS Award Level 2 that specifies postsecondary certificates of at least 900 but less than 1,800 clock hours, or at least 30 but less than 60 semester or trimester credit hours, or at least 45 but less than 90 quarter credit hours and UNESCO ISCED 2011 Level 4.
> **Subclass Of:**  ceterms:AcademicCertificate

> **URI:** ceterms:TechnicalLevel3Certificate
> **Label:**  Technical Level 3 Certificate
> **Definition:**  Credential award at a postsecondary level for successful completion of a formal education program that is at least 2 years but less than 4 years, demonstrating competencies within specific occupational areas indicating job readiness.
> **Comment:**  Can lead to a degree. Equivalent to a United States IPEDS Award Level 4 that specifies certificates of 1,800 or more clock hours, or 60 or more semester or trimester credit hours, or 90 or more quarter credit hours and UNESCO ISCED 2011 Level 5.
> **Subclass Of:**  ceterms:AcademicCertificate

> **URI:** ceterms:GeneralEducationLevel1Certificate
> **Label:**  General Education Level 1 Certificate
> **Definition:**  Credential award at a postsecondary level for successful completion of general education courses that cover a broad range of foundational academic skills and takes less than 1 year.
> **Comment:**  Can lead to a General Education Certificate Level 2 or a degree. Equivalent to a United States IPEDS Award Level 1b that specifies postsecondary certificates of 300-899 clock hours, or 9-29 semester or trimester credit hours, or 13-44 quarter credit hours and UNESCO ISCED 2011 Level 4. 
> **Usage Note:**  If the competencies are related to a specific subject area or occupational area use the Technical Level 1 or use a Higher Education Certificate.
> **Subclass Of:**  ceterms:AcademicCertificate

> **URI:** ceterms:GeneralEducationLevel2Certificate
> **Label:**  General Education Level 2 Certificate
> **Definition:**  Credential award at a postsecondary level for successful completion of general education courses that takes at least 1 year that cover a broad range of foundational academic skills and takes less than 2 years to complete.
> **Comment:**  Can lead to a degree. Equivalent to a United States IPEDS Award Level 2 that specifies postsecondary certificates of at least 900 but less than 1,800 clock hours, or at least 30 but less than 60 semester or trimester credit hours, or at least 45 but less than 90 quarter credit hours and UNESCO ISCED 2011 Level 4. 
> **Usage Note:**  If the competencies are related to a specific subject area or occupational area use the Technical Level 2 or use a Higher Education Certificate.
> **Subclass Of:**  ceterms:AcademicCertificate

> **URI:** ceterms:HigherEducationLevel1Certificate
> **Label:**  Higher Education Level 1 Certificate
> **Definition:**  Credential awarded at the postsecondary level for successful completion of a formal higher education program that takes about one year in a specific subject.
> **Comment:**  Typically equivalent to 60 ECTS Credits at Level 5 in the European Qualifications Framework or UNESCO ISCED 2011 Level 5.
> **Subclass Of:**  ceterms:AcademicCertificate

> **URI:** ceterms:HigherEducationLevel2Certificate
> **Label:**  Higher Education Level 2 Certificate
> **Definition:**  Credential awarded at the postsecondary level for successful completion of a formal higher education program that takes about two years in a specific subject.
> **Comment:**  Typically equivalent to 120 ECTS Credits at Level 5 in the European Qualifications Framework and the Short Cycle in the Qualifications Framework of the European Higher Education Area, or UNESCO ISCED 2011 Level 5.
> **Subclass Of:**  ceterms:AcademicCertificate

> **URI:** ceterms:PostBaccalaureateCertificate
> **Label:**  Post-Baccalaureate Certificate
> **Definition:**  Credential award that requires completion of an organized program of study at a level beyond that of a bachelor's degree, which is designed for persons who have completed a baccalaureate degree but does not meet the requirements of a master's degree.
> **Comment:**  This may include certificates that are for specialties within an occupational field or occupational program of study. Equivalent to a United States IPEDS Award Level 6 and UNESCO ISCED 2011 Level 7.
> **Subclass Of:**  ceterms:AcademicCertificate

> **URI:** ceterms:PostMasterCertificate
> **Label:**  Post-Master Certificate
> **Definition:**  Credential award that requires completion of an organized program of study beyond that of a master's degree, which is designed for persons who have completed a master’s degree but does not meet the requirements of a doctor’s degree. 
> **Comment:**  This may include certificates that are for specialties within an occupational field or occupational program of study and can include post-doctoral first professional certificates such as healthcare and law. Equivalent to a United States IPEDS Award Level 7 or 17, 18, and 19, and UNESCO ISCED 2011 Level 8.
> **Subclass Of:**  ceterms:AcademicCertificate


Make the following modifications to the following existing Properties:
---
> **URI:** ceterms:registeredBy
> **Add:** schema:domainIncludes ceterms:WorkBasedLearningCertificate, ceterms:PreApprenticeshipCertificate, ceterms:ApprenticeshipCertificate, ceterms:JourneymanCertificate, ceterms:MasterCertificate

Add each of the above newly-created Certificate subclasses to the domain of each of the following Properties:
---
ceterms:accreditedBy ceterms:accreditedIn ceterms:administrationProcess ceterms:advancedStandingFrom ceterms:aggregateData ceterms:alternateName ceterms:appealProcess ceterms:approvedBy ceterms:approvedIn ceterms:assessmentDeliveryType ceterms:audienceLevelType ceterms:audienceType ceterms:availabilityListing ceterms:availableAt ceterms:availableOnlineAt ceterms:broadAlignment ceterms:commonConditions ceterms:commonCosts ceterms:complaintProcess ceterms:coPrerequisite ceterms:copyrightHolder ceterms:corequisite ceterms:credentialId ceterms:credentialStatusType ceterms:ctid ceterms:dateEffective ceterms:description ceterms:developmentProcess ceterms:earnings ceterms:employmentOutcome ceterms:estimatedCost ceterms:estimatedDuration ceterms:exactAlignment ceterms:expirationDate ceterms:financialAssistance ceterms:hasPart ceterms:hasProxy ceterms:hasRubric ceterms:hasSupportService ceterms:holders ceterms:identifier ceterms:image ceterms:industryType ceterms:inLanguage ceterms:instructionalProgramType ceterms:isAdvancedStandingFor ceterms:isicV4 ceterms:isNonCredit ceterms:isPartOf ceterms:isPreparationFor ceterms:isRecommendedFor ceterms:isRequiredFor ceterms:jurisdiction ceterms:keyword ceterms:latestVersion ceterms:learningDeliveryType ceterms:maintenanceProcess ceterms:majorAlignment ceterms:minorAlignment ceterms:naics ceterms:name ceterms:narrowAlignment ceterms:nextVersion ceterms:occupationType ceterms:offeredBy ceterms:offeredIn ceterms:ownedBy ceterms:preparationFrom ceterms:previousVersion ceterms:processStandards ceterms:processStandardsDescription ceterms:recognizedBy ceterms:recognizedIn ceterms:recommends ceterms:region ceterms:regulatedBy ceterms:regulatedIn ceterms:relatedAction ceterms:renewal ceterms:renewalFrequency ceterms:renewedBy ceterms:renewedIn ceterms:requires ceterms:reviewProcess ceterms:revocation ceterms:revocationProcess ceterms:revokedBy ceterms:revokedIn ceterms:sameAs ceterms:subject ceterms:subjectWebpage ceterms:supersededBy ceterms:supersedes ceterms:targetPathway ceterms:usesVerificationService ceterms:versionIdentifier

Add each of the above newly-created Certificate subclasses to the range of each of the following Properties:
---
ceasn:substantiatingCredential ceterms:accredits ceterms:advancedStandingFrom ceterms:approves ceterms:broadAlignment ceterms:credentialType ceterms:exactAlignment ceterms:hasPart ceterms:instrument ceterms:isAdvancedStandingFor ceterms:isPartOf ceterms:isPreparationFor ceterms:isRecommendedFor ceterms:isRequiredFor ceterms:latestVersion ceterms:majorAlignment ceterms:minorAlignment ceterms:narrowAlignment ceterms:nextVersion ceterms:object ceterms:offers ceterms:owns ceterms:preparationFrom ceterms:previousVersion ceterms:qualityAssuranceTargetType ceterms:recognizes ceterms:recommends ceterms:regulates ceterms:renews ceterms:requires ceterms:revokes ceterms:supersededBy ceterms:supersedes ceterms:supportServiceFor ceterms:targetCredential ceterms:transferValueFor ceterms:transferValueFrom schema:about

Add ceterms:RegistrationAction to the domain of each of the following Properties:
---
ceterms:actingAgent ceterms:actionStatusType ceterms:ctid ceterms:description ceterms:endDate ceterms:evidenceOfAction ceterms:instrument ceterms:name ceterms:object ceterms:participant ceterms:startDate

Add ceterms:RegistrationAction to the range of each of the following Properties:
---
ceterms:credentialingAction ceterms:relatedAction

Create each of the following Properties:
---
> **URI:** ceterms:isRegisteredApprenticeship
> **Label:**  Is Registered Apprenticeship
> **Definition:**  The resource is registered with a governmental agency or other authorized organization because it has been vetted, approved and validated to meet specific criteria.
> **Domain:**  ceterms:WorkBasedLearningCertificate, ceterms:PreApprenticeshipCertificate, ceterms:ApprenticeshipCertificate, ceterms:JourneymanCertificate, ceterms:MasterCertificate, ceterms:LearningOpportunityProfile, ceterms:LearningProgram, ceterms:Course
> **Range:**  xsd:boolean

**Comment by siuc-nate** [comment]
The above changes have been made in pending CTDL and noted in the history tracking. I'm about 90% sure I got everything (this update is enormous when you expand it all out into the individual changes to be made), so getting other sets of eyes on it is going to be really important.

**Comment by jeannekitchens** [comment]
@siuc-nate excellent. We'll need to do a walk through in pending to be sure all of the updates were made.  Thanks for getting this done!

**Comment by philbarker** [comment]
First pass through, just the classes found mostly trivial errors and the ISCED Level changes (assuming these are agreed). 
 
- [ ] typo carried over from google doc, near the end of the comment for Certificate, `and` for `an`: "... use an*d* appropriate type from the Degree hierarchy. "
- [ ] typo carried over from google doc, in middle of the comment for CertificateOfParticipation there is an extra space before the period: "...with an activity . A record of the activity may..."
- [ ] I think the last work of the comment should be plural: apprenticeships.
- [ ] Label for ceterms:ApprenticeshipCertificate should be changed to "Apprentice Certificate"
- [ ] Label for [ceterms:MasterCertificate should be changed to "Master Trade Certificate"
- [ ] remove " and UNESCO ISCED 2011 Levels 3 or 4" from comment for ceterms:BasicTechnicalCertificate
- [ ] remove " and UNESCO ISCED 2011 Level 4" from comment for ceterms:TechnicalLevel1Certificate
- [ ] ditto ceterms:TechnicalLevel2Certificate
- [ ] ditto ceterms:GernalEducationLevel1Certificate
- [ ] ditto ceterms:GernalEducationLevel2Certificate
- [ ] remove " and UNESCO ISCED 2011 Level 5" from comment for ceterms:TechnicalLevel3Certificate
- [ ] ditto ceterms:HigherEducationLevel1Certificate
- [ ] ditto ceterms:HigherEducationLevel2Certificate
- [ ] remove " and UNESCO ISCED 2011 Level 7" from comment for ceterms:PostBaccalaureateCertificate
- [ ] remove " and UNESCO ISCED 2011 Level 8" from comment for ceterms:PostMasterCertificate
- [ ] There is a character encoding problem near end of  defintion of ceterms:PostMasterCertificate : "... master�s degree ...  doctor�s degree"

**Comment by siuc-nate** [comment]
>There is a character encoding problem near end of defintion of ceterms:PostMasterCertificate : "... master�s degree ... doctor�s degree"

Smart quotes/fancy apostrophes/etc strike again.  

Good catches Phil, thanks for going through all of that.  I'll remove the UNESCO stuff once that's finalized.

It also looks like some of the dct:descriptions might not have made it into the history tracking - I'm looking into it.

**Comment by siuc-nate** [comment]
Looks like there was a bug in the script I used to help generate the change tracking that swapped vann:usageNote and dct:description around. I have corrected it in the history tracking. The schema data is tracked separately, so it wouldn't've been affected.
