### ISSUE TITLE
Need a property for Catalog webpage. 

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#915]
Course catalogs are a standard for postsecondary institutions.  With the Course class https://credreg.net/ctdl/terms#Course, the option for idenification of the catalog web page is handled with https://credreg.net/ctdl/terms#subjectWebpage.

A ceterms:catalog property is needed to use with Course and should be added to other classes where a catalog is the source of information.  E.g., Collection of courses, the URL for the Collection would be ceterms:catalog.

**Comment by jeannekitchens** [comment]
Major use case: As a publisher of course information I need to include a URL with each course. However, the courses are listed in a catalog.  They are not listed on a webpage where the course is described. The course is described in a catalog.  

This use case is course specfic because every accredited postsecondary insitution in the U.S. has a course catalog.  However should the Domains be broader to allow for any type of a catalog?  The Domains Includes considers going broader.

We need to resolve this issue and implement it.

Proposal:
 New Property: ceterms:catalogWebpage
 Definition: A webpage hosting the listing of this resource within a catalog or inventory.
 Domains Include: Course, Learning Opportunity Profile, Learning Program, Rubric, Credential and its subclasses, Collection, Job, Occupation, Work Role Task, Assessment Profile, Transfer Value Profile. 
 In Range Of: [xsd:anyURI](http://www.w3.org/2001/XMLSchema#anyURI)

**Comment by philbarker** [comment]
Looks fine, but web page might be limiting: some catalogs spread over several pages, or the entire site might be a catalog, or it might be an mobile app or some other technology rather than on the web.

I would prefer 
New Property: ceterms:inCatalog
Definition: An inventory or listing of resources that includes this resource.
Domains Include: Course, Learning Opportunity Profile, Learning Program, Rubric, Credential and its subclasses, Collection, Job, Occupation, Work Role Task, Assessment Profile, Transfer Value Profile.
Range Includes: schema:CreativeWork

**Comment by jeannekitchens** [comment]
@siuc-nate please review Phil's input. I'm good with @philbarker proposal for ceterms:inCatalog.

**Comment by mparsons-ce** [comment]
If there is a course catalog and every course is in the catalog, then publishing the catalog property with thousands of courses would seem excessive. Instead  the organization could have appropriate property?

**Comment by jeannekitchens** [comment]
@mparsons-ce the purpose of the URL is a link to find all of the courses.  However, we are currently working on publishing all courses.  Once we have the course AI-assistant publishing going in 2024 expect large quantities of courses.

**Comment by jeannekitchens** [comment]
Finalize this:

New Property: ceterms:inCatalog
Definition: An inventory or listing of resources that includes this resource.
Domains Include: Course, Learning Opportunity Profile, Learning Program, Rubric, Credential and its subclasses, Collection, Job, Occupation, Work Role Task, Assessment Profile, Transfer Value Profile.
Range Includes: schema:CreativeWork or xsd:anyURI

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
