### ISSUE TITLE
Need ceterms:transferValueFrom range to include TransferValue Profile

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#917]
**Major use case:** As a credentialing organization I need to indicate with my Transfer Value Profile that my organization accepts the transfer value recommendation provided by American Council on Education. 

**E.g., WGU example, WGU wants to indicate that they explicitly accept a TV from Ivey Tech and the recommendation for a McDonalds course TV recommendation issued by ACE.**

I know I can use a reference to the ACE course, exam or apprenticeship recommendation but the linking of this acceptance needs to be direct and not dependent on the 3rd parties course that ACE has recommmened transfer credit for.  I need to either directly indicate that the TVP published by ACE as a credit recommendation is ceterms:transferValueFrom the ACE published TV as ceterms:transferValueFor my course and or degree

Otherwise...

I need a way to be explicit with the data and directly link to it as a targetTransferValueProfile.

Currently, ACE is currently in process of publishing over 10,000 TVPs to the Registry [https://credentialfinder.org/search?searchType=transfervalue&filteritemtext=American%20Council%20on%20Education:%20Owns%203432%20Transfer%20Value%20Profiles(s)&filterparameters={%22n%22:%22organizationroles%22,%22aid%22:1314,%22rid%22:[6,7]}](https://credentialfinder.org/search?searchType=transfervalue&filteritemtext=American%20Council%20on%20Education:%20Owns%203432%20Transfer%20Value%20Profiles(s)&filterparameters=%7B%22n%22:%22organizationroles%22,%22aid%22:1314,%22rid%22:%5B6,7%5D%7D). They issue transfer value recommmendations for courses, exams and apprenticeships. They are NOT going to publish those courses exams and apprenticeships for their customers. They are identifying the courses, exams and apprenticeships as blank nodes/references along with their owners (as blank nodes / references).

Further, ACE is not going to initially track the CTIDS of their customers course, exams, or apprenticeships.

The diagram is the second tab and it's editable by CE and Phil. https://drive.google.com/file/d/1u3SaDBpcwpmtaCWfJdiqFJb9Tg2twewS/view?usp=sharing

![image](https://github.com/CredentialEngine/Schema-Development/assets/20917206/7ffc76a5-0234-44ed-b890-4c5a5d285a4a)

**Comment by siuc-nate** [comment]
This is already covered by the existing design:
1. To indicate that an organization recognizes a Transfer Value Profile, use ceterms:recognizes. [This is why we enabled ceterms:recognizes to point to Transfer Value Profile](https://github.com/CredentialEngine/Schema-Development/issues/683).
2. To indicate that one Transfer Value Profile was created based on another Transfer Value Profile, use ceasn:derivedFrom. [This was explicitly covered in the changes from the 2020 Transfer Value Profile Task Group](https://github.com/CredentialEngine/Schema-Development/issues/719)

**Comment by siuc-nate** [comment]
![image](https://github.com/CredentialEngine/Schema-Development/assets/21346519/164671d7-1796-438e-9c58-04f1aea11da0)

**Comment by jeannekitchens** [comment]
**Use the existing ceterms:derivedFrom for this use case.** 

https://credreg.net/ctdlasn/terms#derivedFrom
<html>
<body>

Definition: | en-US: A version of the entity being referenced that has been modified in meaning through editing, extension or refinement.
-- | --



</body>
</html>

**Comment by siuc-nate** [comment]
Just to verify - @jeannekitchens @philbarker Are we all on board with the change in the previous post (repeated below)?:

> **Subject**: ceasn:derivedFrom
> **Remove rdfs:comment** "A version of the entity being referenced that has been modified in meaning through editing, extension or refinement."
> **Add rdfs:comment** "The entity being described has been modified, extended or refined from the referenced resource."

**Comment by philbarker** [comment]
Doesn't `ceterms: receivesTransferValueFrom` proposed in #916 also solve for this use case? It would allow the courses in your diagram above point directly to the ACE transfer value profile, which is simpler and more direct that adding an intermediate TVP.

**Comment by siuc-nate** [comment]
I think we determined that the use case is already handled, yes - we just wanted to tweak the definition for ceasn:derivedFrom (see my previous post).

**Comment by philbarker** [comment]
Noting that we seem to have determined two different ways to handle the use case, but yes that update seems like an improvement.

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL-ASN and noted in the history tracking
