### ISSUE TITLE
Action Classes Need  URL to a Verification Profile/verificationDirectory

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#919]
Major Use Case: As a Quality Assurance Organization, I issue ceterms:AccreditAction, or RecognizeAction, or RegulateAction, or Approve Action, I need to include the URL to the directory where the evidence of that action is maintained.  

Action classes have property to point to https://credreg.net/ctdl/terms#evidenceOfAction.

[ceterms:evidenceOfAction](https://credreg.net/ctdl/terms/evidenceOfAction)
Definition: Entity that proves that the action occurred or that the action continues to be valid.
Comment: The evidence verifies the information in the action and is particular to it. It is not a directory of such evidentiary entities or a description of how such verifications might generically be characterized.

The issue here is that the comment states, " It is not a directory of such evidentiary entities or a description of how such verifications might generically be characterized." This means the intent of this URL is to the verified "digital" instance of the action.

Solution: If the intent is misundersood, remove the comment. If the above use case requires another solution, we need https://credreg.net/ctdl/terms#verificationDirectory to be expanded.

https://credreg.net/ctdl/terms#verificationDirectory
Current Definition: Directory of credential holders and their current statuses.
Revised: Directory of credential holders or action instances and their current status. 
Domain Includes: ceterms:VerificationServiceProfile and the Action Classes. Range: [xsd:anyURI](http://www.w3.org/2001/XMLSchema#anyURI)

**Comment by philbarker** [comment]
> I need to include the URL to the directory where the evidence of that action is maintained.

Is the directory "particular to" the  "information in the action" or is it directory of information about many actions?

My reading is that the comment was intended to rule out indicating a directory where there is information about many actions in one directory—which seems reasonable. If there is a directory containing several pieces of **evidence about the same action**, it seems reasonable to point to the directory and we should clarify the comment.

Otherwise I guess we might need a property that says "Here's information about a few hundred actions, we'll leave you to figure out which is one relevant".

**Comment by jeannekitchens** [comment]
@philbarker the directory is particular to the action and contains the evidence of numerous actions.  

See:
1. https://qualitymatters.org/reviews-certifications/qm-certified-courses
2. https://qualitymatters.org/qm-membership/faqs/qm-certified-programs

These are two verification directories, each contains verifications of specific types of QA issuances.  The https://credreg.net/ctdl/terms#verificationDirectory is for pointing to a directory so the user does have to find the related instance in the directory.  Like a course catalog, directories do not necssarily have a URL directly to an instance nor do they use redirects etc.. If there is a verified instance the publisher uses the evidenceofAction.  

If the intent of evidenceOfAction is to point to the verification of the instance then we get the best of both worlds.  For example, Quality Matters issues widgets to the organization receiving the QA and when opened, it provides the evidence of the action/instance.  There's also a directory.

**Comment by siuc-nate** [comment]
I would characterize @jeannekitchens 's links as being "particular to the QA Credential with evidence for multiple Actions" rather than simultaneously being specific to one action and many actions.

I suggest using whatever property comes out of #915. It's just a catalog of Actions which this Action is in, so "inCatalog" (the current proposal) makes sense.

**Comment by jeannekitchens** [comment]
Final proposal - Updated the comment for  https://credreg.net/ctdl/terms#evidenceOfAction as follows:

Comment: The evidence verifies the information in the action and is particular to it. It is not a collection relating to several unrelated actions or a description of how such verifications might generically be characterized. It may comprise more than one evidentiary entity relating to the same action.

**Comment by siuc-nate** [comment]
Proposal: 
**Remove:**
> **Subject:** ceterms:evidenceOfAction 
> **Predicate:** dct:description 
> **Object:** The evidence verifies the information in the action and is particular to it. It is not a directory of such evidentiary entities or a description of how such verifications might generically be characterized.

**Add:**
> **Subject:** ceterms:evidenceOfAction 
> **Predicate:** dct:description 
> **Object:** The evidence verifies the information in the action and is particular to it. It is not a collection relating to several unrelated actions or a description of how such verifications might generically be characterized. It may comprise more than one evidentiary entity relating to the same action.

**Comment by siuc-nate** [comment]
The above change has been made in pending CTDL and noted in the history tracking.
