### ISSUE TITLE
Target Occupation and Target Job Domain Needs to be Expanded

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#921]
Major use case: As an education and training provider, I offer credentials and related opportunities to prepare for specific career fields or jobs. As a learner, I need to enroll in a program and earn a credential that makes me hireable for a specific occupation or job.  

https://credreg.net/ctdl/terms#targetJob and https://credreg.net/ctdl/terms/targetOccupation need to be expanded to include:
1. All credential types https://credreg.net/page/typeslist#ceterms_Credential
2. https://credreg.net/ctdl/terms/LearningOpportunityProfile
3. https://credreg.net/ctdl/terms/LearningProgram
4. https://credreg.net/ctdl/terms/Course
5. https://credreg.net/ctdl/terms/AssessmentProfile 

Many credentials, LOs, LPs, Courses, and APs are for the purpose of preparing for specific occupations or jobs. It is not sufficient to only identify Occupation Types.  Occuption Types are used for many other purposes including CIP/SOC crosswalks. 

From Rutgers University EERC State Noncredit Data Taxonomy https://docs.google.com/spreadsheets/d/1svFLdfsOEusIy9c3oZUgROJvHMsHqDau/edit#gid=257574632 (do not type in this Google Sheet) “Noncredit occupational training is geared toward individuals seeking to gain or improve job skills leading to initial or better employment. These courses are most often available through an open registration process, do not follow a typical semester schedule, and are paid for by individuals through either their own resources or through third-party funding for which they are eligible.”

**Comment by philbarker** [comment]
I think this is a step in the right direction. Classifying Learning Opps, Programs, Courses and Assessments as Occupations using occupationType was one of those short cuts that confuses two related entities; saying that the LO, program, course or assessment, targets an Occupation (which may have an Occupation Type) is more correct.

So while I know the proposal isn't to stop using occupationType on occupation-related entity types, and I know we can't deprecate its use, anything that provides a better way of specifying the occupation-relevance of these types of resource seems like the right direction. My only question is, whether the effect on search & query of having an additional path to check is too burdensome?

**Comment by siuc-nate** [comment]
CTDL currently supports
```
Job -[requires]-> Credential
```

I think, rather than a generic "target" property, it would make more sense to use:
```
Credential -[isRequiredFor]-> Job
Credential -[isRecommendedFor] -> Job
```
Both of which are already supported (as are other properties that go through condition profile, ie advanced standing, preparation, etc)

**Comment by philbarker** [comment]
@siuc-nate, any suggestions for Occupation?
For Job  [that](https://github.com/CredentialEngine/Schema-Development/issues/921#issuecomment-1904502264) might make good sense, but I suspect Occupation is the more important use case. Job's are quite specific so I think there will be far fewer credentials that target jobs than target occupations. Compare "Do this certificate if you want to be a welder" to "Do this Certificate if you want to work as a fabricator-level-1 at Bob's Welding".

**Comment by siuc-nate** [comment]
We also have the same connections available for Occupation via ceterms:targetOccupation
```
Credential -[isRequiredFor]-> Occupation
Credential -[isRecommendedFor]-> Occupation
Learning Program -[isRequiredFor]-> Occupation
Course -[isRequiredFor]-> Occupation
Assessment Profile -[isRequiredFor]-> Occupation
```

**Comment by siuc-nate** [comment]
Closing this, as it is already handled.
