### ISSUE TITLE
Broaden definition for ceterms:availabilityListing

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#923]
Change the current definition for https://credreg.net/ctdl/terms/availabilityListing#availabilityListing: Listing of online and/or physical locations where a credential can be pursued.

To:  Listing of online and/or physical locations where a credential, assessment, or learning opportunity can be pursued.

This will put the defintion in alignment with:

- https://credreg.net/ctdl/terms/availableAt
- https://credreg.net/ctdl/terms/availableOnlineAt

**Comment by philbarker** [comment]
Need also to accommodate Organization from domain:

Listing of online and/or physical locations where a resource can be found or pursued.

**Comment by siuc-nate** [comment]
Proposal:
**Modify:**
> **Subject:** ceterms:availabilityListing
> **Remove Definition:** Listing of online and/or physical locations where a credential can be pursued.
> **Add Definition:** Listing of online and/or physical locations where a resource can be found or pursued.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
