### ISSUE TITLE
Correct Typo with ceterms:subjectWebpage

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#925]
Update the comment to be clearer. The "not be assumed" part of the sentence need to be removed or be rewritten. 

Subject Webpage](https://credreg.net/ctdl/terms/subjectWebpage

Comment: The web page being referenced describes the entity. The value of subjectWebpage is an authoritative location for information about the subject but should not be assumed to be a persistent identifier of the subject.

**Comment by siuc-nate** [comment]
The typo was already fixed, unless I'm missing something. What's on the page matches what's in your post.

Or do you mean we should rewrite the whole thing?

**Comment by siuc-nate** [comment]
Closing this, as it was already corrected.
