### ISSUE TITLE
Property to include a Course Catalog URL to an Organization

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#929]
A college partner, Houston Community College (HCC), has requested to be able to publish a link to their course catalog from Credential Organization.

**Comment by siuc-nate** [comment]
Something like this (borrowing from [ceterms:inCatalog](https://credreg.net/ctdl/terms/inCatalog) for consistency)?:

> **URI:** ceterms:hasCatalog
> **Label:** Has Catalog
> **Definition:** An inventory or listing of resources maintained by this Organization
> **Domain:** ceterms:Organization, ceterms:CredentialOrganization, ceterms:QACredentialOrganization
> **Range:** xsd:anyURI

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
