### ISSUE TITLE
ceterms:versionIdentifier Need to include Domain of Competency Framework and Competency

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/Schema-Development#933]
The NICE Cybersecurity Framework is being versioned as well as the competencies.   Just as other resources can have versions 

add https://credreg.net/ctdlasn/terms#CompetencyFramework to domain and range of 
https://credreg.net/ctdl/terms#versionIdentifier 

https://www.nist.gov/itl/applied-cybersecurity/nice/nice-framework-resource-center/nice-framework-current-versions 

The usage note for https://credreg.net/ctdl/terms#versionIdentifier needs to be removed.

Related to https://github.com/CredentialEngine/Schema-Development/issues/788 

Related to this ,add https://credreg.net/ctdlasn/terms#CompetencyFramework to domain and range of 

https://credreg.net/ctdl/terms/latestVersion
https://credreg.net/ctdl/terms/nextVersion
https://credreg.net/ctdl/terms#previousVersion

**Comment by jeannekitchens** [comment]
Also need to add the above to Collection https://credreg.net/ctdl/terms#Collection.

**Comment by siuc-nate** [comment]
Updated proposal per today's meeting:

**Add:**
> **Subject:** ceterms:versionIdentifier
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Collection, ceasn:CompetencyFramework

> **Subject:** ceterms:latestVersion
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Collection, ceasn:CompetencyFramework

> **Subject:** ceterms:nextVersion
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Collection, ceasn:CompetencyFramework

> **Subject:** ceterms:previousVersion
> **Predicate:** schema:domainIncludes
> **Object:** ceterms:Collection, ceasn:CompetencyFramework

**Comment by siuc-nate** [comment]
See also [#788](https://github.com/CredentialEngine/Schema-Development/issues/788#issuecomment-2113037682)

**Comment by siuc-nate** [comment]
This appears to be ready to implement. @philbarker Do you have anything to add?

**Comment by philbarker** [comment]
@siuc-nate agree: nothing to add.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
